.TH "_DIACTIONFORMATA" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_DIACTIONFORMATA
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "DWORD \fBdwSize\fP"
.br
.ti -1c
.RI "DWORD \fBdwActionSize\fP"
.br
.ti -1c
.RI "DWORD \fBdwDataSize\fP"
.br
.ti -1c
.RI "DWORD \fBdwNumActions\fP"
.br
.ti -1c
.RI "\fBLPDIACTIONA\fP \fBrgoAction\fP"
.br
.ti -1c
.RI "GUID \fBguidActionMap\fP"
.br
.ti -1c
.RI "DWORD \fBdwGenre\fP"
.br
.ti -1c
.RI "DWORD \fBdwBufferSize\fP"
.br
.ti -1c
.RI "LONG \fBlAxisMin\fP"
.br
.ti -1c
.RI "LONG \fBlAxisMax\fP"
.br
.ti -1c
.RI "HINSTANCE \fBhInstString\fP"
.br
.ti -1c
.RI "FILETIME \fBftTimeStamp\fP"
.br
.ti -1c
.RI "DWORD \fBdwCRC\fP"
.br
.ti -1c
.RI "CHAR \fBtszActionMap\fP [MAX_PATH]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
