.TH "_DICONFIGUREDEVICESPARAMSA" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_DICONFIGUREDEVICESPARAMSA
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "DWORD \fBdwSize\fP"
.br
.ti -1c
.RI "DWORD \fBdwcUsers\fP"
.br
.ti -1c
.RI "LPSTR \fBlptszUserNames\fP"
.br
.ti -1c
.RI "DWORD \fBdwcFormats\fP"
.br
.ti -1c
.RI "\fBLPDIACTIONFORMATA\fP \fBlprgFormats\fP"
.br
.ti -1c
.RI "HWND \fBhwnd\fP"
.br
.ti -1c
.RI "\fBDICOLORSET\fP \fBdics\fP"
.br
.ti -1c
.RI "LPUNKNOWN \fBlpUnkDDSTarget\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
