.TH "_DIDATAFORMAT" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_DIDATAFORMAT
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "DWORD \fBdwSize\fP"
.br
.ti -1c
.RI "DWORD \fBdwObjSize\fP"
.br
.ti -1c
.RI "DWORD \fBdwFlags\fP"
.br
.ti -1c
.RI "DWORD \fBdwDataSize\fP"
.br
.ti -1c
.RI "DWORD \fBdwNumObjs\fP"
.br
.ti -1c
.RI "\fBLPDIOBJECTDATAFORMAT\fP \fBrgodf\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
