.TH "_DIDEVICEIMAGEINFOW" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_DIDEVICEIMAGEINFOW
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "WCHAR \fBtszImagePath\fP [MAX_PATH]"
.br
.ti -1c
.RI "DWORD \fBdwFlags\fP"
.br
.ti -1c
.RI "DWORD \fBdwViewID\fP"
.br
.ti -1c
.RI "RECT \fBrcOverlay\fP"
.br
.ti -1c
.RI "DWORD \fBdwObjID\fP"
.br
.ti -1c
.RI "DWORD \fBdwcValidPts\fP"
.br
.ti -1c
.RI "POINT \fBrgptCalloutLine\fP [5]"
.br
.ti -1c
.RI "RECT \fBrcCalloutRect\fP"
.br
.ti -1c
.RI "DWORD \fBdwTextAlign\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
