.TH "_GLFWlibraryWGL" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GLFWlibraryWGL
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "HINSTANCE \fBinstance\fP"
.br
.ti -1c
.RI "PFN_wglCreateContext \fBCreateContext\fP"
.br
.ti -1c
.RI "PFN_wglDeleteContext \fBDeleteContext\fP"
.br
.ti -1c
.RI "PFN_wglGetProcAddress \fBGetProcAddress\fP"
.br
.ti -1c
.RI "PFN_wglGetCurrentDC \fBGetCurrentDC\fP"
.br
.ti -1c
.RI "PFN_wglGetCurrentContext \fBGetCurrentContext\fP"
.br
.ti -1c
.RI "PFN_wglMakeCurrent \fBMakeCurrent\fP"
.br
.ti -1c
.RI "PFN_wglShareLists \fBShareLists\fP"
.br
.ti -1c
.RI "PFNWGLSWAPINTERVALEXTPROC \fBSwapIntervalEXT\fP"
.br
.ti -1c
.RI "PFNWGLGETPIXELFORMATATTRIBIVARBPROC \fBGetPixelFormatAttribivARB\fP"
.br
.ti -1c
.RI "PFNWGLGETEXTENSIONSSTRINGEXTPROC \fBGetExtensionsStringEXT\fP"
.br
.ti -1c
.RI "PFNWGLGETEXTENSIONSSTRINGARBPROC \fBGetExtensionsStringARB\fP"
.br
.ti -1c
.RI "PFNWGLCREATECONTEXTATTRIBSARBPROC \fBCreateContextAttribsARB\fP"
.br
.ti -1c
.RI "GLFWbool \fBEXT_swap_control\fP"
.br
.ti -1c
.RI "GLFWbool \fBEXT_colorspace\fP"
.br
.ti -1c
.RI "GLFWbool \fBARB_multisample\fP"
.br
.ti -1c
.RI "GLFWbool \fBARB_framebuffer_sRGB\fP"
.br
.ti -1c
.RI "GLFWbool \fBEXT_framebuffer_sRGB\fP"
.br
.ti -1c
.RI "GLFWbool \fBARB_pixel_format\fP"
.br
.ti -1c
.RI "GLFWbool \fBARB_create_context\fP"
.br
.ti -1c
.RI "GLFWbool \fBARB_create_context_profile\fP"
.br
.ti -1c
.RI "GLFWbool \fBEXT_create_context_es2_profile\fP"
.br
.ti -1c
.RI "GLFWbool \fBARB_create_context_robustness\fP"
.br
.ti -1c
.RI "GLFWbool \fBARB_create_context_no_error\fP"
.br
.ti -1c
.RI "GLFWbool \fBARB_context_flush_control\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
