.TH "_GLFWlibraryX11" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GLFWlibraryX11
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Display * \fBdisplay\fP"
.br
.ti -1c
.RI "int \fBscreen\fP"
.br
.ti -1c
.RI "Window \fBroot\fP"
.br
.ti -1c
.RI "float \fBcontentScaleX\fP"
.br
.ti -1c
.RI "float \fBcontentScaleY\fP"
.br
.ti -1c
.RI "Window \fBhelperWindowHandle\fP"
.br
.ti -1c
.RI "Cursor \fBhiddenCursorHandle\fP"
.br
.ti -1c
.RI "XContext \fBcontext\fP"
.br
.ti -1c
.RI "XIM \fBim\fP"
.br
.ti -1c
.RI "int \fBerrorCode\fP"
.br
.ti -1c
.RI "char * \fBprimarySelectionString\fP"
.br
.ti -1c
.RI "char * \fBclipboardString\fP"
.br
.ti -1c
.RI "char \fBkeyName\fP [5]"
.br
.ti -1c
.RI "short int \fBkeycodes\fP [256]"
.br
.ti -1c
.RI "short int \fBscancodes\fP [GLFW_KEY_LAST+1]"
.br
.ti -1c
.RI "double \fBrestoreCursorPosX\fP"
.br
.ti -1c
.RI "double \fBrestoreCursorPosY\fP"
.br
.ti -1c
.RI "\fB_GLFWwindow\fP * \fBdisabledCursorWindow\fP"
.br
.ti -1c
.RI "Atom \fBNET_SUPPORTED\fP"
.br
.ti -1c
.RI "Atom \fBNET_SUPPORTING_WM_CHECK\fP"
.br
.ti -1c
.RI "Atom \fBWM_PROTOCOLS\fP"
.br
.ti -1c
.RI "Atom \fBWM_STATE\fP"
.br
.ti -1c
.RI "Atom \fBWM_DELETE_WINDOW\fP"
.br
.ti -1c
.RI "Atom \fBNET_WM_NAME\fP"
.br
.ti -1c
.RI "Atom \fBNET_WM_ICON_NAME\fP"
.br
.ti -1c
.RI "Atom \fBNET_WM_ICON\fP"
.br
.ti -1c
.RI "Atom \fBNET_WM_PID\fP"
.br
.ti -1c
.RI "Atom \fBNET_WM_PING\fP"
.br
.ti -1c
.RI "Atom \fBNET_WM_WINDOW_TYPE\fP"
.br
.ti -1c
.RI "Atom \fBNET_WM_WINDOW_TYPE_NORMAL\fP"
.br
.ti -1c
.RI "Atom \fBNET_WM_STATE\fP"
.br
.ti -1c
.RI "Atom \fBNET_WM_STATE_ABOVE\fP"
.br
.ti -1c
.RI "Atom \fBNET_WM_STATE_FULLSCREEN\fP"
.br
.ti -1c
.RI "Atom \fBNET_WM_STATE_MAXIMIZED_VERT\fP"
.br
.ti -1c
.RI "Atom \fBNET_WM_STATE_MAXIMIZED_HORZ\fP"
.br
.ti -1c
.RI "Atom \fBNET_WM_STATE_DEMANDS_ATTENTION\fP"
.br
.ti -1c
.RI "Atom \fBNET_WM_BYPASS_COMPOSITOR\fP"
.br
.ti -1c
.RI "Atom \fBNET_WM_FULLSCREEN_MONITORS\fP"
.br
.ti -1c
.RI "Atom \fBNET_WM_WINDOW_OPACITY\fP"
.br
.ti -1c
.RI "Atom \fBNET_WM_CM_Sx\fP"
.br
.ti -1c
.RI "Atom \fBNET_WORKAREA\fP"
.br
.ti -1c
.RI "Atom \fBNET_CURRENT_DESKTOP\fP"
.br
.ti -1c
.RI "Atom \fBNET_ACTIVE_WINDOW\fP"
.br
.ti -1c
.RI "Atom \fBNET_FRAME_EXTENTS\fP"
.br
.ti -1c
.RI "Atom \fBNET_REQUEST_FRAME_EXTENTS\fP"
.br
.ti -1c
.RI "Atom \fBMOTIF_WM_HINTS\fP"
.br
.ti -1c
.RI "Atom \fBXdndAware\fP"
.br
.ti -1c
.RI "Atom \fBXdndEnter\fP"
.br
.ti -1c
.RI "Atom \fBXdndPosition\fP"
.br
.ti -1c
.RI "Atom \fBXdndStatus\fP"
.br
.ti -1c
.RI "Atom \fBXdndActionCopy\fP"
.br
.ti -1c
.RI "Atom \fBXdndDrop\fP"
.br
.ti -1c
.RI "Atom \fBXdndFinished\fP"
.br
.ti -1c
.RI "Atom \fBXdndSelection\fP"
.br
.ti -1c
.RI "Atom \fBXdndTypeList\fP"
.br
.ti -1c
.RI "Atom \fBtext_uri_list\fP"
.br
.ti -1c
.RI "Atom \fBTARGETS\fP"
.br
.ti -1c
.RI "Atom \fBMULTIPLE\fP"
.br
.ti -1c
.RI "Atom \fBINCR\fP"
.br
.ti -1c
.RI "Atom \fBCLIPBOARD\fP"
.br
.ti -1c
.RI "Atom \fBPRIMARY\fP"
.br
.ti -1c
.RI "Atom \fBCLIPBOARD_MANAGER\fP"
.br
.ti -1c
.RI "Atom \fBSAVE_TARGETS\fP"
.br
.ti -1c
.RI "Atom \fBNULL_\fP"
.br
.ti -1c
.RI "Atom \fBUTF8_STRING\fP"
.br
.ti -1c
.RI "Atom \fBCOMPOUND_STRING\fP"
.br
.ti -1c
.RI "Atom \fBATOM_PAIR\fP"
.br
.ti -1c
.RI "Atom \fBGLFW_SELECTION\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   GLFWbool \fBavailable\fP"
.br
.ti -1c
.RI "   void * \fBhandle\fP"
.br
.ti -1c
.RI "   int \fBeventBase\fP"
.br
.ti -1c
.RI "   int \fBerrorBase\fP"
.br
.ti -1c
.RI "   int \fBmajor\fP"
.br
.ti -1c
.RI "   int \fBminor\fP"
.br
.ti -1c
.RI "   GLFWbool \fBgammaBroken\fP"
.br
.ti -1c
.RI "   GLFWbool \fBmonitorBroken\fP"
.br
.ti -1c
.RI "   PFN_XRRAllocGamma \fBAllocGamma\fP"
.br
.ti -1c
.RI "   PFN_XRRFreeCrtcInfo \fBFreeCrtcInfo\fP"
.br
.ti -1c
.RI "   PFN_XRRFreeGamma \fBFreeGamma\fP"
.br
.ti -1c
.RI "   PFN_XRRFreeOutputInfo \fBFreeOutputInfo\fP"
.br
.ti -1c
.RI "   PFN_XRRFreeScreenResources \fBFreeScreenResources\fP"
.br
.ti -1c
.RI "   PFN_XRRGetCrtcGamma \fBGetCrtcGamma\fP"
.br
.ti -1c
.RI "   PFN_XRRGetCrtcGammaSize \fBGetCrtcGammaSize\fP"
.br
.ti -1c
.RI "   PFN_XRRGetCrtcInfo \fBGetCrtcInfo\fP"
.br
.ti -1c
.RI "   PFN_XRRGetOutputInfo \fBGetOutputInfo\fP"
.br
.ti -1c
.RI "   PFN_XRRGetOutputPrimary \fBGetOutputPrimary\fP"
.br
.ti -1c
.RI "   PFN_XRRGetScreenResourcesCurrent \fBGetScreenResourcesCurrent\fP"
.br
.ti -1c
.RI "   PFN_XRRQueryExtension \fBQueryExtension\fP"
.br
.ti -1c
.RI "   PFN_XRRQueryVersion \fBQueryVersion\fP"
.br
.ti -1c
.RI "   PFN_XRRSelectInput \fBSelectInput\fP"
.br
.ti -1c
.RI "   PFN_XRRSetCrtcConfig \fBSetCrtcConfig\fP"
.br
.ti -1c
.RI "   PFN_XRRSetCrtcGamma \fBSetCrtcGamma\fP"
.br
.ti -1c
.RI "   PFN_XRRUpdateConfiguration \fBUpdateConfiguration\fP"
.br
.ti -1c
.RI "} \fBrandr\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   GLFWbool \fBavailable\fP"
.br
.ti -1c
.RI "   GLFWbool \fBdetectable\fP"
.br
.ti -1c
.RI "   int \fBmajorOpcode\fP"
.br
.ti -1c
.RI "   int \fBeventBase\fP"
.br
.ti -1c
.RI "   int \fBerrorBase\fP"
.br
.ti -1c
.RI "   int \fBmajor\fP"
.br
.ti -1c
.RI "   int \fBminor\fP"
.br
.ti -1c
.RI "   unsigned int \fBgroup\fP"
.br
.ti -1c
.RI "} \fBxkb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int \fBcount\fP"
.br
.ti -1c
.RI "   int \fBtimeout\fP"
.br
.ti -1c
.RI "   int \fBinterval\fP"
.br
.ti -1c
.RI "   int \fBblanking\fP"
.br
.ti -1c
.RI "   int \fBexposure\fP"
.br
.ti -1c
.RI "} \fBsaver\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int \fBversion\fP"
.br
.ti -1c
.RI "   Window \fBsource\fP"
.br
.ti -1c
.RI "   Atom \fBformat\fP"
.br
.ti -1c
.RI "} \fBxdnd\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   void * \fBhandle\fP"
.br
.ti -1c
.RI "   PFN_XcursorImageCreate \fBImageCreate\fP"
.br
.ti -1c
.RI "   PFN_XcursorImageDestroy \fBImageDestroy\fP"
.br
.ti -1c
.RI "   PFN_XcursorImageLoadCursor \fBImageLoadCursor\fP"
.br
.ti -1c
.RI "} \fBxcursor\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   GLFWbool \fBavailable\fP"
.br
.ti -1c
.RI "   void * \fBhandle\fP"
.br
.ti -1c
.RI "   int \fBmajor\fP"
.br
.ti -1c
.RI "   int \fBminor\fP"
.br
.ti -1c
.RI "   PFN_XineramaIsActive \fBIsActive\fP"
.br
.ti -1c
.RI "   PFN_XineramaQueryExtension \fBQueryExtension\fP"
.br
.ti -1c
.RI "   PFN_XineramaQueryScreens \fBQueryScreens\fP"
.br
.ti -1c
.RI "} \fBxinerama\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   void * \fBhandle\fP"
.br
.ti -1c
.RI "   PFN_XGetXCBConnection \fBGetXCBConnection\fP"
.br
.ti -1c
.RI "} \fBx11xcb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   GLFWbool \fBavailable\fP"
.br
.ti -1c
.RI "   void * \fBhandle\fP"
.br
.ti -1c
.RI "   int \fBeventBase\fP"
.br
.ti -1c
.RI "   int \fBerrorBase\fP"
.br
.ti -1c
.RI "   PFN_XF86VidModeQueryExtension \fBQueryExtension\fP"
.br
.ti -1c
.RI "   PFN_XF86VidModeGetGammaRamp \fBGetGammaRamp\fP"
.br
.ti -1c
.RI "   PFN_XF86VidModeSetGammaRamp \fBSetGammaRamp\fP"
.br
.ti -1c
.RI "   PFN_XF86VidModeGetGammaRampSize \fBGetGammaRampSize\fP"
.br
.ti -1c
.RI "} \fBvidmode\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   GLFWbool \fBavailable\fP"
.br
.ti -1c
.RI "   void * \fBhandle\fP"
.br
.ti -1c
.RI "   int \fBmajorOpcode\fP"
.br
.ti -1c
.RI "   int \fBeventBase\fP"
.br
.ti -1c
.RI "   int \fBerrorBase\fP"
.br
.ti -1c
.RI "   int \fBmajor\fP"
.br
.ti -1c
.RI "   int \fBminor\fP"
.br
.ti -1c
.RI "   PFN_XIQueryVersion \fBQueryVersion\fP"
.br
.ti -1c
.RI "   PFN_XISelectEvents \fBSelectEvents\fP"
.br
.ti -1c
.RI "} \fBxi\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   GLFWbool \fBavailable\fP"
.br
.ti -1c
.RI "   void * \fBhandle\fP"
.br
.ti -1c
.RI "   int \fBmajor\fP"
.br
.ti -1c
.RI "   int \fBminor\fP"
.br
.ti -1c
.RI "   int \fBeventBase\fP"
.br
.ti -1c
.RI "   int \fBerrorBase\fP"
.br
.ti -1c
.RI "   PFN_XRenderQueryExtension \fBQueryExtension\fP"
.br
.ti -1c
.RI "   PFN_XRenderQueryVersion \fBQueryVersion\fP"
.br
.ti -1c
.RI "   PFN_XRenderFindVisualFormat \fBFindVisualFormat\fP"
.br
.ti -1c
.RI "} \fBxrender\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
