.TH "_GLFWerror" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GLFWerror
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB_GLFWerror\fP * \fBnext\fP"
.br
.ti -1c
.RI "int \fBcode\fP"
.br
.ti -1c
.RI "char \fBdescription\fP [_GLFW_MESSAGE_SIZE]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
