.TH "_GLFWcontextWGL" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GLFWcontextWGL
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "HDC \fBdc\fP"
.br
.ti -1c
.RI "HGLRC \fBhandle\fP"
.br
.ti -1c
.RI "int \fBinterval\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
