.TH "_GLFWcontext" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GLFWcontext
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBclient\fP"
.br
.ti -1c
.RI "int \fBsource\fP"
.br
.ti -1c
.RI "int \fBmajor\fP"
.br
.ti -1c
.RI "int \fBminor\fP"
.br
.ti -1c
.RI "int \fBrevision\fP"
.br
.ti -1c
.RI "GLFWbool \fBforward\fP"
.br
.ti -1c
.RI "GLFWbool \fBdebug\fP"
.br
.ti -1c
.RI "GLFWbool \fBnoerror\fP"
.br
.ti -1c
.RI "int \fBprofile\fP"
.br
.ti -1c
.RI "int \fBrobustness\fP"
.br
.ti -1c
.RI "int \fBrelease\fP"
.br
.ti -1c
.RI "PFNGLGETSTRINGIPROC \fBGetStringi\fP"
.br
.ti -1c
.RI "PFNGLGETINTEGERVPROC \fBGetIntegerv\fP"
.br
.ti -1c
.RI "PFNGLGETSTRINGPROC \fBGetString\fP"
.br
.ti -1c
.RI "_GLFWmakecontextcurrentfun \fBmakeCurrent\fP"
.br
.ti -1c
.RI "_GLFWswapbuffersfun \fBswapBuffers\fP"
.br
.ti -1c
.RI "_GLFWswapintervalfun \fBswapInterval\fP"
.br
.ti -1c
.RI "_GLFWextensionsupportedfun \fBextensionSupported\fP"
.br
.ti -1c
.RI "_GLFWgetprocaddressfun \fBgetProcAddress\fP"
.br
.ti -1c
.RI "_GLFWdestroycontextfun \fBdestroy\fP"
.br
.ti -1c
.RI "\fB_GLFW_PLATFORM_CONTEXT_STATE\fP"
.br
.ti -1c
.RI "\fB_GLFW_EGL_CONTEXT_STATE\fP"
.br
.ti -1c
.RI "\fB_GLFW_OSMESA_CONTEXT_STATE\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
