.TH "_GLFWwindowNS" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GLFWwindowNS
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "id \fBobject\fP"
.br
.ti -1c
.RI "id \fBdelegate\fP"
.br
.ti -1c
.RI "id \fBview\fP"
.br
.ti -1c
.RI "id \fBlayer\fP"
.br
.ti -1c
.RI "GLFWbool \fBmaximized\fP"
.br
.ti -1c
.RI "GLFWbool \fBretina\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "int \fBfbWidth\fP"
.br
.ti -1c
.RI "int \fBfbHeight\fP"
.br
.ti -1c
.RI "float \fBxscale\fP"
.br
.ti -1c
.RI "float \fByscale\fP"
.br
.ti -1c
.RI "double \fBcursorWarpDeltaX\fP"
.br
.ti -1c
.RI "double \fBcursorWarpDeltaY\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
