.TH "_GLFWcursor" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GLFWcursor
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB_GLFWcursor\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fB_GLFW_PLATFORM_CURSOR_STATE\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
