.TH "_GLFWwndconfig" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GLFWwndconfig
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "const char * \fBtitle\fP"
.br
.ti -1c
.RI "GLFWbool \fBresizable\fP"
.br
.ti -1c
.RI "GLFWbool \fBvisible\fP"
.br
.ti -1c
.RI "GLFWbool \fBdecorated\fP"
.br
.ti -1c
.RI "GLFWbool \fBfocused\fP"
.br
.ti -1c
.RI "GLFWbool \fBautoIconify\fP"
.br
.ti -1c
.RI "GLFWbool \fBfloating\fP"
.br
.ti -1c
.RI "GLFWbool \fBmaximized\fP"
.br
.ti -1c
.RI "GLFWbool \fBcenterCursor\fP"
.br
.ti -1c
.RI "GLFWbool \fBfocusOnShow\fP"
.br
.ti -1c
.RI "GLFWbool \fBscaleToMonitor\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   GLFWbool \fBretina\fP"
.br
.ti -1c
.RI "   char \fBframeName\fP [256]"
.br
.ti -1c
.RI "} \fBns\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   char \fBclassName\fP [256]"
.br
.ti -1c
.RI "   char \fBinstanceName\fP [256]"
.br
.ti -1c
.RI "} \fBx11\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
