.TH "_GLFWfbconfig" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GLFWfbconfig
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBredBits\fP"
.br
.ti -1c
.RI "int \fBgreenBits\fP"
.br
.ti -1c
.RI "int \fBblueBits\fP"
.br
.ti -1c
.RI "int \fBalphaBits\fP"
.br
.ti -1c
.RI "int \fBdepthBits\fP"
.br
.ti -1c
.RI "int \fBstencilBits\fP"
.br
.ti -1c
.RI "int \fBaccumRedBits\fP"
.br
.ti -1c
.RI "int \fBaccumGreenBits\fP"
.br
.ti -1c
.RI "int \fBaccumBlueBits\fP"
.br
.ti -1c
.RI "int \fBaccumAlphaBits\fP"
.br
.ti -1c
.RI "int \fBauxBuffers\fP"
.br
.ti -1c
.RI "GLFWbool \fBstereo\fP"
.br
.ti -1c
.RI "int \fBsamples\fP"
.br
.ti -1c
.RI "GLFWbool \fBsRGB\fP"
.br
.ti -1c
.RI "GLFWbool \fBdoublebuffer\fP"
.br
.ti -1c
.RI "GLFWbool \fBtransparent\fP"
.br
.ti -1c
.RI "uintptr_t \fBhandle\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
