.TH "_GLFWjoystick" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GLFWjoystick
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GLFWbool \fBpresent\fP"
.br
.ti -1c
.RI "float * \fBaxes\fP"
.br
.ti -1c
.RI "int \fBaxisCount\fP"
.br
.ti -1c
.RI "unsigned char * \fBbuttons\fP"
.br
.ti -1c
.RI "int \fBbuttonCount\fP"
.br
.ti -1c
.RI "unsigned char * \fBhats\fP"
.br
.ti -1c
.RI "int \fBhatCount\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "void * \fBuserPointer\fP"
.br
.ti -1c
.RI "char \fBguid\fP [33]"
.br
.ti -1c
.RI "\fB_GLFWmapping\fP * \fBmapping\fP"
.br
.ti -1c
.RI "\fB_GLFW_PLATFORM_JOYSTICK_STATE\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
