.TH "_GLFWctxconfig" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GLFWctxconfig
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBclient\fP"
.br
.ti -1c
.RI "int \fBsource\fP"
.br
.ti -1c
.RI "int \fBmajor\fP"
.br
.ti -1c
.RI "int \fBminor\fP"
.br
.ti -1c
.RI "GLFWbool \fBforward\fP"
.br
.ti -1c
.RI "GLFWbool \fBdebug\fP"
.br
.ti -1c
.RI "GLFWbool \fBnoerror\fP"
.br
.ti -1c
.RI "int \fBprofile\fP"
.br
.ti -1c
.RI "int \fBrobustness\fP"
.br
.ti -1c
.RI "int \fBrelease\fP"
.br
.ti -1c
.RI "\fB_GLFWwindow\fP * \fBshare\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   GLFWbool \fBoffline\fP"
.br
.ti -1c
.RI "} \fBnsgl\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
