.TH "_GLFWjoystickWin32" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GLFWjoystickWin32
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB_GLFWjoyobjectWin32\fP * \fBobjects\fP"
.br
.ti -1c
.RI "int \fBobjectCount\fP"
.br
.ti -1c
.RI "IDirectInputDevice8W * \fBdevice\fP"
.br
.ti -1c
.RI "DWORD \fBindex\fP"
.br
.ti -1c
.RI "GUID \fBguid\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
