.TH "_GLFWwindowWin32" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GLFWwindowWin32
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "HWND \fBhandle\fP"
.br
.ti -1c
.RI "HICON \fBbigIcon\fP"
.br
.ti -1c
.RI "HICON \fBsmallIcon\fP"
.br
.ti -1c
.RI "GLFWbool \fBcursorTracked\fP"
.br
.ti -1c
.RI "GLFWbool \fBframeAction\fP"
.br
.ti -1c
.RI "GLFWbool \fBiconified\fP"
.br
.ti -1c
.RI "GLFWbool \fBmaximized\fP"
.br
.ti -1c
.RI "GLFWbool \fBtransparent\fP"
.br
.ti -1c
.RI "GLFWbool \fBscaleToMonitor\fP"
.br
.ti -1c
.RI "int \fBlastCursorPosX\fP"
.br
.ti -1c
.RI "int \fBlastCursorPosY\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
