.TH "_GLFWlibraryNS" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GLFWlibraryNS
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "CGEventSourceRef \fBeventSource\fP"
.br
.ti -1c
.RI "id \fBdelegate\fP"
.br
.ti -1c
.RI "GLFWbool \fBfinishedLaunching\fP"
.br
.ti -1c
.RI "GLFWbool \fBcursorHidden\fP"
.br
.ti -1c
.RI "TISInputSourceRef \fBinputSource\fP"
.br
.ti -1c
.RI "IOHIDManagerRef \fBhidManager\fP"
.br
.ti -1c
.RI "id \fBunicodeData\fP"
.br
.ti -1c
.RI "id \fBhelper\fP"
.br
.ti -1c
.RI "id \fBkeyUpMonitor\fP"
.br
.ti -1c
.RI "id \fBnibObjects\fP"
.br
.ti -1c
.RI "char \fBkeyName\fP [64]"
.br
.ti -1c
.RI "short int \fBkeycodes\fP [256]"
.br
.ti -1c
.RI "short int \fBscancodes\fP [GLFW_KEY_LAST+1]"
.br
.ti -1c
.RI "char * \fBclipboardString\fP"
.br
.ti -1c
.RI "CGPoint \fBcascadePoint\fP"
.br
.ti -1c
.RI "double \fBrestoreCursorPosX\fP"
.br
.ti -1c
.RI "double \fBrestoreCursorPosY\fP"
.br
.ti -1c
.RI "\fB_GLFWwindow\fP * \fBdisabledCursorWindow\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   CFBundleRef \fBbundle\fP"
.br
.ti -1c
.RI "   PFN_TISCopyCurrentKeyboardLayoutInputSource \fBCopyCurrentKeyboardLayoutInputSource\fP"
.br
.ti -1c
.RI "   PFN_TISGetInputSourceProperty \fBGetInputSourceProperty\fP"
.br
.ti -1c
.RI "   PFN_LMGetKbdType \fBGetKbdType\fP"
.br
.ti -1c
.RI "   CFStringRef \fBkPropertyUnicodeKeyLayoutData\fP"
.br
.ti -1c
.RI "} \fBtis\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
