.TH "_GLFWwindow" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GLFWwindow
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fB_GLFWwindow\fP * \fBnext\fP"
.br
.ti -1c
.RI "GLFWbool \fBresizable\fP"
.br
.ti -1c
.RI "GLFWbool \fBdecorated\fP"
.br
.ti -1c
.RI "GLFWbool \fBautoIconify\fP"
.br
.ti -1c
.RI "GLFWbool \fBfloating\fP"
.br
.ti -1c
.RI "GLFWbool \fBfocusOnShow\fP"
.br
.ti -1c
.RI "GLFWbool \fBshouldClose\fP"
.br
.ti -1c
.RI "void * \fBuserPointer\fP"
.br
.ti -1c
.RI "\fBGLFWvidmode\fP \fBvideoMode\fP"
.br
.ti -1c
.RI "\fB_GLFWmonitor\fP * \fBmonitor\fP"
.br
.ti -1c
.RI "\fB_GLFWcursor\fP * \fBcursor\fP"
.br
.ti -1c
.RI "int \fBminwidth\fP"
.br
.ti -1c
.RI "int \fBminheight\fP"
.br
.ti -1c
.RI "int \fBmaxwidth\fP"
.br
.ti -1c
.RI "int \fBmaxheight\fP"
.br
.ti -1c
.RI "int \fBnumer\fP"
.br
.ti -1c
.RI "int \fBdenom\fP"
.br
.ti -1c
.RI "GLFWbool \fBstickyKeys\fP"
.br
.ti -1c
.RI "GLFWbool \fBstickyMouseButtons\fP"
.br
.ti -1c
.RI "GLFWbool \fBlockKeyMods\fP"
.br
.ti -1c
.RI "int \fBcursorMode\fP"
.br
.ti -1c
.RI "char \fBmouseButtons\fP [GLFW_MOUSE_BUTTON_LAST+1]"
.br
.ti -1c
.RI "char \fBkeys\fP [GLFW_KEY_LAST+1]"
.br
.ti -1c
.RI "double \fBvirtualCursorPosX\fP"
.br
.ti -1c
.RI "double \fBvirtualCursorPosY\fP"
.br
.ti -1c
.RI "GLFWbool \fBrawMouseMotion\fP"
.br
.ti -1c
.RI "\fB_GLFWcontext\fP \fBcontext\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBGLFWwindowposfun\fP \fBpos\fP"
.br
.ti -1c
.RI "   \fBGLFWwindowsizefun\fP \fBsize\fP"
.br
.ti -1c
.RI "   \fBGLFWwindowclosefun\fP \fBclose\fP"
.br
.ti -1c
.RI "   \fBGLFWwindowrefreshfun\fP \fBrefresh\fP"
.br
.ti -1c
.RI "   \fBGLFWwindowfocusfun\fP \fBfocus\fP"
.br
.ti -1c
.RI "   \fBGLFWwindowiconifyfun\fP \fBiconify\fP"
.br
.ti -1c
.RI "   \fBGLFWwindowmaximizefun\fP \fBmaximize\fP"
.br
.ti -1c
.RI "   \fBGLFWframebuffersizefun\fP \fBfbsize\fP"
.br
.ti -1c
.RI "   \fBGLFWwindowcontentscalefun\fP \fBscale\fP"
.br
.ti -1c
.RI "   \fBGLFWmousebuttonfun\fP \fBmouseButton\fP"
.br
.ti -1c
.RI "   \fBGLFWcursorposfun\fP \fBcursorPos\fP"
.br
.ti -1c
.RI "   \fBGLFWcursorenterfun\fP \fBcursorEnter\fP"
.br
.ti -1c
.RI "   \fBGLFWscrollfun\fP \fBscroll\fP"
.br
.ti -1c
.RI "   \fBGLFWkeyfun\fP \fBkey\fP"
.br
.ti -1c
.RI "   \fBGLFWcharfun\fP \fBcharacter\fP"
.br
.ti -1c
.RI "   \fBGLFWcharmodsfun\fP \fBcharmods\fP"
.br
.ti -1c
.RI "   \fBGLFWdropfun\fP \fBdrop\fP"
.br
.ti -1c
.RI "} \fBcallbacks\fP"
.br
.ti -1c
.RI "\fB_GLFW_PLATFORM_WINDOW_STATE\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
