.TH "_GLFWmonitorWin32" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GLFWmonitorWin32
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "HMONITOR \fBhandle\fP"
.br
.ti -1c
.RI "WCHAR \fBadapterName\fP [32]"
.br
.ti -1c
.RI "WCHAR \fBdisplayName\fP [32]"
.br
.ti -1c
.RI "char \fBpublicAdapterName\fP [32]"
.br
.ti -1c
.RI "char \fBpublicDisplayName\fP [32]"
.br
.ti -1c
.RI "GLFWbool \fBmodesPruned\fP"
.br
.ti -1c
.RI "GLFWbool \fBmodeChanged\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
