.TH "_GLFWjoystickLinux" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GLFWjoystickLinux
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBfd\fP"
.br
.ti -1c
.RI "char \fBpath\fP [PATH_MAX]"
.br
.ti -1c
.RI "int \fBkeyMap\fP [KEY_CNT \- BTN_MISC]"
.br
.ti -1c
.RI "int \fBabsMap\fP [ABS_CNT]"
.br
.ti -1c
.RI "struct input_absinfo \fBabsInfo\fP [ABS_CNT]"
.br
.ti -1c
.RI "int \fBhats\fP [4][2]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
