.TH "_GLFWcursorWayland" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GLFWcursorWayland
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBwl_cursor\fP * \fBcursor\fP"
.br
.ti -1c
.RI "struct \fBwl_cursor\fP * \fBcursorHiDPI\fP"
.br
.ti -1c
.RI "struct wl_buffer * \fBbuffer\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "int \fBxhot\fP"
.br
.ti -1c
.RI "int \fByhot\fP"
.br
.ti -1c
.RI "int \fBcurrentImage\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
