.TH "_GLFWwindowX11" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GLFWwindowX11
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Colormap \fBcolormap\fP"
.br
.ti -1c
.RI "Window \fBhandle\fP"
.br
.ti -1c
.RI "XIC \fBic\fP"
.br
.ti -1c
.RI "GLFWbool \fBoverrideRedirect\fP"
.br
.ti -1c
.RI "GLFWbool \fBiconified\fP"
.br
.ti -1c
.RI "GLFWbool \fBmaximized\fP"
.br
.ti -1c
.RI "GLFWbool \fBtransparent\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "int \fBxpos\fP"
.br
.ti -1c
.RI "int \fBypos\fP"
.br
.ti -1c
.RI "int \fBlastCursorPosX\fP"
.br
.ti -1c
.RI "int \fBlastCursorPosY\fP"
.br
.ti -1c
.RI "int \fBwarpCursorPosX\fP"
.br
.ti -1c
.RI "int \fBwarpCursorPosY\fP"
.br
.ti -1c
.RI "Time \fBlastKeyTime\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
