.TH "_GLFWlibraryGLX" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GLFWlibraryGLX
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBmajor\fP"
.br
.ti -1c
.RI "int \fBminor\fP"
.br
.ti -1c
.RI "int \fBeventBase\fP"
.br
.ti -1c
.RI "int \fBerrorBase\fP"
.br
.ti -1c
.RI "void * \fBhandle\fP"
.br
.ti -1c
.RI "PFNGLXGETFBCONFIGSPROC \fBGetFBConfigs\fP"
.br
.ti -1c
.RI "PFNGLXGETFBCONFIGATTRIBPROC \fBGetFBConfigAttrib\fP"
.br
.ti -1c
.RI "PFNGLXGETCLIENTSTRINGPROC \fBGetClientString\fP"
.br
.ti -1c
.RI "PFNGLXQUERYEXTENSIONPROC \fBQueryExtension\fP"
.br
.ti -1c
.RI "PFNGLXQUERYVERSIONPROC \fBQueryVersion\fP"
.br
.ti -1c
.RI "PFNGLXDESTROYCONTEXTPROC \fBDestroyContext\fP"
.br
.ti -1c
.RI "PFNGLXMAKECURRENTPROC \fBMakeCurrent\fP"
.br
.ti -1c
.RI "PFNGLXSWAPBUFFERSPROC \fBSwapBuffers\fP"
.br
.ti -1c
.RI "PFNGLXQUERYEXTENSIONSSTRINGPROC \fBQueryExtensionsString\fP"
.br
.ti -1c
.RI "PFNGLXCREATENEWCONTEXTPROC \fBCreateNewContext\fP"
.br
.ti -1c
.RI "PFNGLXGETVISUALFROMFBCONFIGPROC \fBGetVisualFromFBConfig\fP"
.br
.ti -1c
.RI "PFNGLXCREATEWINDOWPROC \fBCreateWindow\fP"
.br
.ti -1c
.RI "PFNGLXDESTROYWINDOWPROC \fBDestroyWindow\fP"
.br
.ti -1c
.RI "PFNGLXGETPROCADDRESSPROC \fBGetProcAddress\fP"
.br
.ti -1c
.RI "PFNGLXGETPROCADDRESSPROC \fBGetProcAddressARB\fP"
.br
.ti -1c
.RI "PFNGLXSWAPINTERVALSGIPROC \fBSwapIntervalSGI\fP"
.br
.ti -1c
.RI "PFNGLXSWAPINTERVALEXTPROC \fBSwapIntervalEXT\fP"
.br
.ti -1c
.RI "PFNGLXSWAPINTERVALMESAPROC \fBSwapIntervalMESA\fP"
.br
.ti -1c
.RI "PFNGLXCREATECONTEXTATTRIBSARBPROC \fBCreateContextAttribsARB\fP"
.br
.ti -1c
.RI "GLFWbool \fBSGI_swap_control\fP"
.br
.ti -1c
.RI "GLFWbool \fBEXT_swap_control\fP"
.br
.ti -1c
.RI "GLFWbool \fBMESA_swap_control\fP"
.br
.ti -1c
.RI "GLFWbool \fBARB_multisample\fP"
.br
.ti -1c
.RI "GLFWbool \fBARB_framebuffer_sRGB\fP"
.br
.ti -1c
.RI "GLFWbool \fBEXT_framebuffer_sRGB\fP"
.br
.ti -1c
.RI "GLFWbool \fBARB_create_context\fP"
.br
.ti -1c
.RI "GLFWbool \fBARB_create_context_profile\fP"
.br
.ti -1c
.RI "GLFWbool \fBARB_create_context_robustness\fP"
.br
.ti -1c
.RI "GLFWbool \fBEXT_create_context_es2_profile\fP"
.br
.ti -1c
.RI "GLFWbool \fBARB_create_context_no_error\fP"
.br
.ti -1c
.RI "GLFWbool \fBARB_context_flush_control\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
