.TH "_GLFWlibraryEGL" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GLFWlibraryEGL
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "EGLDisplay \fBdisplay\fP"
.br
.ti -1c
.RI "EGLint \fBmajor\fP"
.br
.ti -1c
.RI "EGLint \fBminor\fP"
.br
.ti -1c
.RI "GLFWbool \fBprefix\fP"
.br
.ti -1c
.RI "GLFWbool \fBKHR_create_context\fP"
.br
.ti -1c
.RI "GLFWbool \fBKHR_create_context_no_error\fP"
.br
.ti -1c
.RI "GLFWbool \fBKHR_gl_colorspace\fP"
.br
.ti -1c
.RI "GLFWbool \fBKHR_get_all_proc_addresses\fP"
.br
.ti -1c
.RI "GLFWbool \fBKHR_context_flush_control\fP"
.br
.ti -1c
.RI "void * \fBhandle\fP"
.br
.ti -1c
.RI "PFN_eglGetConfigAttrib \fBGetConfigAttrib\fP"
.br
.ti -1c
.RI "PFN_eglGetConfigs \fBGetConfigs\fP"
.br
.ti -1c
.RI "PFN_eglGetDisplay \fBGetDisplay\fP"
.br
.ti -1c
.RI "PFN_eglGetError \fBGetError\fP"
.br
.ti -1c
.RI "PFN_eglInitialize \fBInitialize\fP"
.br
.ti -1c
.RI "PFN_eglTerminate \fBTerminate\fP"
.br
.ti -1c
.RI "PFN_eglBindAPI \fBBindAPI\fP"
.br
.ti -1c
.RI "PFN_eglCreateContext \fBCreateContext\fP"
.br
.ti -1c
.RI "PFN_eglDestroySurface \fBDestroySurface\fP"
.br
.ti -1c
.RI "PFN_eglDestroyContext \fBDestroyContext\fP"
.br
.ti -1c
.RI "PFN_eglCreateWindowSurface \fBCreateWindowSurface\fP"
.br
.ti -1c
.RI "PFN_eglMakeCurrent \fBMakeCurrent\fP"
.br
.ti -1c
.RI "PFN_eglSwapBuffers \fBSwapBuffers\fP"
.br
.ti -1c
.RI "PFN_eglSwapInterval \fBSwapInterval\fP"
.br
.ti -1c
.RI "PFN_eglQueryString \fBQueryString\fP"
.br
.ti -1c
.RI "PFN_eglGetProcAddress \fBGetProcAddress\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
