.TH "_XINPUT_GAMEPAD" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_XINPUT_GAMEPAD
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "WORD \fBwButtons\fP"
.br
.ti -1c
.RI "BYTE \fBbLeftTrigger\fP"
.br
.ti -1c
.RI "BYTE \fBbRightTrigger\fP"
.br
.ti -1c
.RI "SHORT \fBsThumbLX\fP"
.br
.ti -1c
.RI "SHORT \fBsThumbLY\fP"
.br
.ti -1c
.RI "SHORT \fBsThumbRX\fP"
.br
.ti -1c
.RI "SHORT \fBsThumbRY\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
