.TH "align_spec" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
align_spec
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBbasic_format_specs< Char >\fP, \fBbasic_format_specs< char_type >\fP, \fBbasic_format_specs< Context::char_type >\fP, and \fBbasic_format_specs< ParseContext::char_type >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "FMT_CONSTEXPR unsigned \fBwidth\fP () const"
.br
.ti -1c
.RI "FMT_CONSTEXPR wchar_t \fBfill\fP () const"
.br
.ti -1c
.RI "FMT_CONSTEXPR alignment \fBalign\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBwidth_\fP"
.br
.ti -1c
.RI "wchar_t \fBfill_\fP"
.br
.ti -1c
.RI "alignment \fBalign_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
