.TH "back_insert_range< Container >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
back_insert_range< Container >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBoutput_range< std::back_insert_iterator< Container > >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef Container::value_type \fBvalue_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBback_insert_range\fP (Container &c)"
.br
.ti -1c
.RI "\fBback_insert_range\fP (typename base::iterator it)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
