.TH "basic_format_context< OutputIt, Char >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
basic_format_context< OutputIt, Char >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBinternal::context_base< OutputIt, basic_format_context< OutputIt, Char >, Char >\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBformatter_type\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef Char \fBchar_type\fP"
.br
.ti -1c
.RI "typedef OutputIt \fBiterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbasic_format_context\fP (OutputIt out, \fBbasic_string_view\fP< \fBchar_type\fP > format_str, \fBbasic_format_args\fP< \fBbasic_format_context\fP > ctx_args, \fBinternal::locale_ref\fP loc=\fBinternal::locale_ref\fP())"
.br
.ti -1c
.RI "\fBformat_arg\fP \fBnext_arg\fP ()"
.br
.ti -1c
.RI "\fBformat_arg\fP \fBget_arg\fP (unsigned arg_id)"
.br
.ti -1c
.RI "\fBformat_arg\fP \fBget_arg\fP (\fBbasic_string_view\fP< \fBchar_type\fP > name)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename OutputIt, typename Char > typedef Char \fBbasic_format_context\fP< OutputIt, Char >::\fBchar_type\fP"
The character type for the output\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename OutputIt, typename Char > \fBbasic_format_context\fP< OutputIt, Char >::\fBbasic_format_context\fP (OutputIt out, \fBbasic_string_view\fP< \fBchar_type\fP > format_str, \fBbasic_format_args\fP< \fBbasic_format_context\fP< OutputIt, Char > > ctx_args, \fBinternal::locale_ref\fP loc = \fC\fBinternal::locale_ref\fP()\fP)\fC [inline]\fP"
Constructs a \fC\fBbasic_format_context\fP\fP object\&. References to the arguments are stored in the object so make sure they have appropriate lifetimes\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
