.TH "basic_format_arg< Context >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
basic_format_arg< Context >
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBhandle\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "FMT_EXPLICIT \fBoperator bool\fP () const FMT_NOEXCEPT"
.br
.ti -1c
.RI "internal::type \fBtype\fP () const"
.br
.ti -1c
.RI "bool \fBis_integral\fP () const"
.br
.ti -1c
.RI "bool \fBis_arithmetic\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBbasic_format_args< Context >\fP"
.br
.ti -1c
.RI "class \fBinternal::arg_map< Context >\fP"
.br
.ti -1c
.RI "template<typename ContextType , typename T > FMT_CONSTEXPR \fBbasic_format_arg\fP< ContextType > \fBinternal::make_arg\fP (const T &value)"
.br
.ti -1c
.RI "template<typename Visitor , typename Ctx > FMT_CONSTEXPR \fBinternal::result_of\fP< Visitor(int)>::type \fBvisit_format_arg\fP (Visitor &&vis, const \fBbasic_format_arg\fP< Ctx > &arg)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
