.TH "basic_format_arg< Context >::handle" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
basic_format_arg< Context >::handle
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBhandle\fP (\fBinternal::custom_value\fP< Context > custom)"
.br
.ti -1c
.RI "void \fBformat\fP (Context &ctx) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
