.TH "basic_writer< Range >::int_writer< Int, Spec >::hex_writer" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
basic_writer< Range >::int_writer< Int, Spec >::hex_writer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename It > void \fBoperator()\fP (It &&it) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int_writer & \fBself\fP"
.br
.ti -1c
.RI "int \fBnum_digits\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
