.TH "Typhoon/ThirdParty/glm/glm/gtx/bit.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/gtx/bit.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./gtc/bitfield\&.hpp'\fP
.br
\fC#include 'bit\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genIUType > GLM_FUNC_DECL genIUType \fBglm::highestBitValue\fP (genIUType Value)"
.br
.ti -1c
.RI "template<typename genIUType > GLM_FUNC_DECL genIUType \fBglm::lowestBitValue\fP (genIUType Value)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec< L, T, Q > \fBglm::highestBitValue\fP (vec< L, T, Q > const &value)"
.br
.ti -1c
.RI "template<typename genIUType > GLM_DEPRECATED GLM_FUNC_DECL genIUType \fBglm::powerOfTwoAbove\fP (genIUType Value)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_DEPRECATED GLM_FUNC_DECL vec< L, T, Q > \fBglm::powerOfTwoAbove\fP (vec< L, T, Q > const &value)"
.br
.ti -1c
.RI "template<typename genIUType > GLM_DEPRECATED GLM_FUNC_DECL genIUType \fBglm::powerOfTwoBelow\fP (genIUType Value)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_DEPRECATED GLM_FUNC_DECL vec< L, T, Q > \fBglm::powerOfTwoBelow\fP (vec< L, T, Q > const &value)"
.br
.ti -1c
.RI "template<typename genIUType > GLM_DEPRECATED GLM_FUNC_DECL genIUType \fBglm::powerOfTwoNearest\fP (genIUType Value)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_DEPRECATED GLM_FUNC_DECL vec< L, T, Q > \fBglm::powerOfTwoNearest\fP (vec< L, T, Q > const &value)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTX_bit\fP
.PP
\fBSee also:\fP
.RS 4
\fBCore features\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
