.TH "Catch::BenchmarkLooper" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::BenchmarkLooper
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBenchmarkLooper\fP (\fBStringRef\fP name)"
.br
.ti -1c
.RI "\fBoperator bool\fP ()"
.br
.ti -1c
.RI "void \fBincrement\fP ()"
.br
.ti -1c
.RI "void \fBreportStart\fP ()"
.br
.ti -1c
.RI "auto \fBneedsMoreIterations\fP () \-> bool"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
