.TH "Catch::Generators::ChunkGenerator< T >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Generators::ChunkGenerator< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCatch::Generators::IGenerator< std::vector< T > >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChunkGenerator\fP (size_t size, \fBGeneratorWrapper\fP< T > generator)"
.br
.ti -1c
.RI "std::vector< T > const  & \fBget\fP () const override"
.br
.ti -1c
.RI "bool \fBnext\fP () override"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
