.TH "Catch::Generators::IGenerator< T >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Generators::IGenerator< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCatch::Generators::GeneratorUntypedBase\fP\&.
.PP
Inherited by \fBCatch::Generators::FilterGenerator< T, Predicate >\fP, \fBCatch::Generators::FixedValuesGenerator< T >\fP, \fBCatch::Generators::Generators< T >\fP, \fBCatch::Generators::MapGenerator< T, U, Func >\fP, \fBCatch::Generators::RangeGenerator< T >\fP, \fBCatch::Generators::RepeatGenerator< T >\fP, \fBCatch::Generators::SingleValueGenerator< T >\fP, and \fBCatch::Generators::TakeGenerator< T >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBtype\fP = T"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual T const  & \fBget\fP () const =0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
