.TH "Catch::Matchers::Impl::MatcherUntypedBase" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Matchers::Impl::MatcherUntypedBase
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCatch::Matchers::Impl::MatcherBase< T >\fP, \fBCatch::Matchers::Impl::MatcherBase< ArgT >\fP, \fBCatch::Matchers::Impl::MatcherBase< double >\fP, \fBCatch::Matchers::Impl::MatcherBase< std::string >\fP, and \fBCatch::Matchers::Impl::MatcherBase< std::vector< T > >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMatcherUntypedBase\fP (\fBMatcherUntypedBase\fP const &)=default"
.br
.ti -1c
.RI "\fBMatcherUntypedBase\fP & \fBoperator=\fP (\fBMatcherUntypedBase\fP const &)=delete"
.br
.ti -1c
.RI "std::string \fBtoString\fP () const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual std::string \fBdescribe\fP () const =0"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fBm_cachedToString\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
