.TH "Catch::Timer" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Timer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBstart\fP ()"
.br
.ti -1c
.RI "auto \fBgetElapsedNanoseconds\fP () const \-> uint64_t"
.br
.ti -1c
.RI "auto \fBgetElapsedMicroseconds\fP () const \-> uint64_t"
.br
.ti -1c
.RI "auto \fBgetElapsedMilliseconds\fP () const \-> unsigned int"
.br
.ti -1c
.RI "auto \fBgetElapsedSeconds\fP () const \-> double"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
