.TH "Catch::SourceLineInfo" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::SourceLineInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSourceLineInfo\fP (char const *_file, std::size_t _line) noexcept"
.br
.ti -1c
.RI "\fBSourceLineInfo\fP (\fBSourceLineInfo\fP const &other)=default"
.br
.ti -1c
.RI "\fBSourceLineInfo\fP & \fBoperator=\fP (\fBSourceLineInfo\fP const &)=default"
.br
.ti -1c
.RI "\fBSourceLineInfo\fP (\fBSourceLineInfo\fP &&) noexcept=default"
.br
.ti -1c
.RI "\fBSourceLineInfo\fP & \fBoperator=\fP (\fBSourceLineInfo\fP &&) noexcept=default"
.br
.ti -1c
.RI "bool \fBempty\fP () const noexcept"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBSourceLineInfo\fP const &other) const noexcept"
.br
.ti -1c
.RI "bool \fBoperator<\fP (\fBSourceLineInfo\fP const &other) const noexcept"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char const  * \fBfile\fP"
.br
.ti -1c
.RI "std::size_t \fBline\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
