.TH "Catch::SectionInfo" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::SectionInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSectionInfo\fP (\fBSourceLineInfo\fP const &_lineInfo, std::string const &_name)"
.br
.ti -1c
.RI "\fBSectionInfo\fP (\fBSourceLineInfo\fP const &_lineInfo, std::string const &_name, std::string const &)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "std::string \fBdescription\fP"
.br
.ti -1c
.RI "\fBSourceLineInfo\fP \fBlineInfo\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
