.TH "Catch::WarnAbout" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::WarnAbout
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBWhat\fP { \fBNothing\fP = 0x00, \fBNoAssertions\fP = 0x01, \fBNoTests\fP = 0x02 }"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
