.TH "Catch::pluralise" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::pluralise
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpluralise\fP (std::size_t count, std::string const &label)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::size_t \fBm_count\fP"
.br
.ti -1c
.RI "std::string \fBm_label\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, \fBpluralise\fP const &pluraliser)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
