.TH "Catch::ReusableStringStream" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::ReusableStringStream
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "auto \fBstr\fP () const \-> std::string"
.br
.ti -1c
.RI "template<typename T > auto \fBoperator<<\fP (T const &value) \-> \fBReusableStringStream\fP &"
.br
.ti -1c
.RI "auto \fBget\fP () \-> std::ostream &"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
