.TH "Catch::ITransientExpression" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::ITransientExpression
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCatch::BinaryExpr< LhsT, RhsT >\fP, \fBCatch::MatchExpr< ArgT, MatcherT >\fP, and \fBCatch::UnaryExpr< LhsT >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "auto \fBisBinaryExpression\fP () const \-> bool"
.br
.ti -1c
.RI "auto \fBgetResult\fP () const \-> bool"
.br
.ti -1c
.RI "virtual void \fBstreamReconstructedExpression\fP (std::ostream &os) const =0"
.br
.ti -1c
.RI "\fBITransientExpression\fP (bool isBinaryExpression, bool result)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBm_isBinaryExpression\fP"
.br
.ti -1c
.RI "bool \fBm_result\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
