.TH "Catch::Matchers::Impl::MatchNotOf< ArgT >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Matchers::Impl::MatchNotOf< ArgT >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCatch::Matchers::Impl::MatcherBase< ArgT >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMatchNotOf\fP (\fBMatcherBase\fP< ArgT > const &underlyingMatcher)"
.br
.ti -1c
.RI "bool \fBmatch\fP (ArgT const &arg) const override"
.br
.ti -1c
.RI "std::string \fBdescribe\fP () const override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMatcherBase\fP< ArgT > const  & \fBm_underlyingMatcher\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
