.TH "Catch::Matchers::Vector::EqualsMatcher< T >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Matchers::Vector::EqualsMatcher< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCatch::Matchers::Impl::MatcherBase< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEqualsMatcher\fP (std::vector< T > const &comparator)"
.br
.ti -1c
.RI "bool \fBmatch\fP (std::vector< T > const &v) const override"
.br
.ti -1c
.RI "std::string \fBdescribe\fP () const override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< T > const  & \fBm_comparator\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
