.TH "Catch::TestInvokerAsMethod< C >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::TestInvokerAsMethod< C >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCatch::ITestInvoker\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestInvokerAsMethod\fP (void(C::*testAsMethod)()) noexcept"
.br
.ti -1c
.RI "void \fBinvoke\fP () const override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
