.TH "Catch::AssertionHandler" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::AssertionHandler
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAssertionHandler\fP (\fBStringRef\fP const &macroName, \fBSourceLineInfo\fP const &lineInfo, \fBStringRef\fP capturedExpression, ResultDisposition::Flags resultDisposition)"
.br
.ti -1c
.RI "template<typename T > void \fBhandleExpr\fP (\fBExprLhs\fP< T > const &expr)"
.br
.ti -1c
.RI "void \fBhandleExpr\fP (\fBITransientExpression\fP const &expr)"
.br
.ti -1c
.RI "void \fBhandleMessage\fP (ResultWas::OfType resultType, \fBStringRef\fP const &message)"
.br
.ti -1c
.RI "void \fBhandleExceptionThrownAsExpected\fP ()"
.br
.ti -1c
.RI "void \fBhandleUnexpectedExceptionNotThrown\fP ()"
.br
.ti -1c
.RI "void \fBhandleExceptionNotThrownAsExpected\fP ()"
.br
.ti -1c
.RI "void \fBhandleThrowingCallSkipped\fP ()"
.br
.ti -1c
.RI "void \fBhandleUnexpectedInflightException\fP ()"
.br
.ti -1c
.RI "void \fBcomplete\fP ()"
.br
.ti -1c
.RI "void \fBsetCompleted\fP ()"
.br
.ti -1c
.RI "auto \fBallowThrows\fP () const \-> bool"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
