.TH "Catch::Matchers::StdString::RegexMatcher" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Matchers::StdString::RegexMatcher
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCatch::Matchers::Impl::MatcherBase< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRegexMatcher\fP (std::string regex, CaseSensitive::Choice caseSensitivity)"
.br
.ti -1c
.RI "bool \fBmatch\fP (std::string const &matchee) const override"
.br
.ti -1c
.RI "std::string \fBdescribe\fP () const override"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
