.TH "Catch::Generators::GeneratorUntypedBase" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Generators::GeneratorUntypedBase
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCatch::Generators::IGenerator< T >\fP, \fBCatch::Generators::IGenerator< Float >\fP, \fBCatch::Generators::IGenerator< Integer >\fP, and \fBCatch::Generators::IGenerator< std::vector< T > >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBnext\fP ()=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
