.TH "Catch::IMutableRegistryHub" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::IMutableRegistryHub
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBregisterReporter\fP (std::string const &name, IReporterFactoryPtr const &factory)=0"
.br
.ti -1c
.RI "virtual void \fBregisterListener\fP (IReporterFactoryPtr const &factory)=0"
.br
.ti -1c
.RI "virtual void \fBregisterTest\fP (\fBTestCase\fP const &testInfo)=0"
.br
.ti -1c
.RI "virtual void \fBregisterTranslator\fP (const \fBIExceptionTranslator\fP *translator)=0"
.br
.ti -1c
.RI "virtual void \fBregisterTagAlias\fP (std::string const &alias, std::string const &tag, \fBSourceLineInfo\fP const &lineInfo)=0"
.br
.ti -1c
.RI "virtual void \fBregisterStartupException\fP () noexcept=0"
.br
.ti -1c
.RI "virtual \fBIMutableEnumValuesRegistry\fP & \fBgetMutableEnumValuesRegistry\fP ()=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
