.TH "Catch::Matchers::Generic::PredicateMatcher< T >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Matchers::Generic::PredicateMatcher< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCatch::Matchers::Impl::MatcherBase< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPredicateMatcher\fP (std::function< bool(T const &)> const &elem, std::string const &descr)"
.br
.ti -1c
.RI "bool \fBmatch\fP (T const &item) const override"
.br
.ti -1c
.RI "std::string \fBdescribe\fP () const override"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
