.TH "Catch::Generators::GeneratorWrapper< T >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Generators::GeneratorWrapper< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGeneratorWrapper\fP (std::unique_ptr< \fBIGenerator\fP< T >> generator)"
.br
.ti -1c
.RI "T const  & \fBget\fP () const"
.br
.ti -1c
.RI "bool \fBnext\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
