.TH "Catch::ResultWas" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::ResultWas
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBOfType\fP { \fBUnknown\fP = -1, \fBOk\fP = 0, \fBInfo\fP = 1, \fBWarning\fP = 2, \fBFailureBit\fP = 0x10, \fBExpressionFailed\fP = FailureBit | 1, \fBExplicitFailure\fP = FailureBit | 2, \fBException\fP = 0x100 | FailureBit, \fBThrewException\fP = Exception | 1, \fBDidntThrowException\fP = Exception | 2, \fBFatalErrorCondition\fP = 0x200 | FailureBit }"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
