.TH "Catch::LazyExpression" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::LazyExpression
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLazyExpression\fP (bool isNegated)"
.br
.ti -1c
.RI "\fBLazyExpression\fP (\fBLazyExpression\fP const &other)"
.br
.ti -1c
.RI "\fBLazyExpression\fP & \fBoperator=\fP (\fBLazyExpression\fP const &)=delete"
.br
.ti -1c
.RI "\fBoperator bool\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBAssertionHandler\fP"
.br
.ti -1c
.RI "struct \fBAssertionStats\fP"
.br
.ti -1c
.RI "class \fBRunContext\fP"
.br
.ti -1c
.RI "auto \fBoperator<<\fP (std::ostream &os, \fBLazyExpression\fP const &lazyExpr) \-> std::ostream &"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
