.TH "Catch::Totals" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Totals
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTotals\fP \fBoperator \-\fP (\fBTotals\fP const &other) const"
.br
.ti -1c
.RI "\fBTotals\fP & \fBoperator+=\fP (\fBTotals\fP const &other)"
.br
.ti -1c
.RI "\fBTotals\fP \fBdelta\fP (\fBTotals\fP const &prevTotals) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBerror\fP = 0"
.br
.ti -1c
.RI "\fBCounts\fP \fBassertions\fP"
.br
.ti -1c
.RI "\fBCounts\fP \fBtestCases\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
