.TH "Catch::TestCase" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::TestCase
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCatch::TestCaseInfo\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestCase\fP (\fBITestInvoker\fP *testCase, \fBTestCaseInfo\fP &&info)"
.br
.ti -1c
.RI "\fBTestCase\fP \fBwithName\fP (std::string const &_newName) const"
.br
.ti -1c
.RI "void \fBinvoke\fP () const"
.br
.ti -1c
.RI "\fBTestCaseInfo\fP const  & \fBgetTestCaseInfo\fP () const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBTestCase\fP const &other) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (\fBTestCase\fP const &other) const"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
