.TH "Catch::Matchers::StdString::StringMatcherBase" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Matchers::StdString::StringMatcherBase
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCatch::Matchers::Impl::MatcherBase< T >\fP\&.
.PP
Inherited by \fBCatch::Matchers::StdString::ContainsMatcher\fP, \fBCatch::Matchers::StdString::EndsWithMatcher\fP, \fBCatch::Matchers::StdString::EqualsMatcher\fP, and \fBCatch::Matchers::StdString::StartsWithMatcher\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStringMatcherBase\fP (std::string const &operation, \fBCasedString\fP const &comparator)"
.br
.ti -1c
.RI "std::string \fBdescribe\fP () const override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCasedString\fP \fBm_comparator\fP"
.br
.ti -1c
.RI "std::string \fBm_operation\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
