.TH "Catch::Counts" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Counts
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCounts\fP \fBoperator \-\fP (\fBCounts\fP const &other) const"
.br
.ti -1c
.RI "\fBCounts\fP & \fBoperator+=\fP (\fBCounts\fP const &other)"
.br
.ti -1c
.RI "std::size_t \fBtotal\fP () const"
.br
.ti -1c
.RI "bool \fBallPassed\fP () const"
.br
.ti -1c
.RI "bool \fBallOk\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::size_t \fBpassed\fP = 0"
.br
.ti -1c
.RI "std::size_t \fBfailed\fP = 0"
.br
.ti -1c
.RI "std::size_t \fBfailedButOk\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
