.TH "Catch::ScopedMessage" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::ScopedMessage
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScopedMessage\fP (\fBMessageBuilder\fP const &builder)"
.br
.ti -1c
.RI "\fBScopedMessage\fP (\fBScopedMessage\fP &duplicate)=delete"
.br
.ti -1c
.RI "\fBScopedMessage\fP (\fBScopedMessage\fP &&old)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMessageInfo\fP \fBm_info\fP"
.br
.ti -1c
.RI "bool \fBm_moved\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
