.TH "Catch::Matchers::StdString::CasedString" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Matchers::StdString::CasedString
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCasedString\fP (std::string const &str, CaseSensitive::Choice caseSensitivity)"
.br
.ti -1c
.RI "std::string \fBadjustString\fP (std::string const &str) const"
.br
.ti -1c
.RI "std::string \fBcaseSensitivitySuffix\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "CaseSensitive::Choice \fBm_caseSensitivity\fP"
.br
.ti -1c
.RI "std::string \fBm_str\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
