.TH "Catch::IResultCapture" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::IResultCapture
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBsectionStarted\fP (\fBSectionInfo\fP const &sectionInfo, \fBCounts\fP &assertions)=0"
.br
.ti -1c
.RI "virtual void \fBsectionEnded\fP (\fBSectionEndInfo\fP const &endInfo)=0"
.br
.ti -1c
.RI "virtual void \fBsectionEndedEarly\fP (\fBSectionEndInfo\fP const &endInfo)=0"
.br
.ti -1c
.RI "virtual auto \fBacquireGeneratorTracker\fP (\fBSourceLineInfo\fP const &lineInfo) \-> \fBIGeneratorTracker\fP &=0"
.br
.ti -1c
.RI "virtual void \fBbenchmarkStarting\fP (BenchmarkInfo const &info)=0"
.br
.ti -1c
.RI "virtual void \fBbenchmarkEnded\fP (BenchmarkStats const &stats)=0"
.br
.ti -1c
.RI "virtual void \fBpushScopedMessage\fP (\fBMessageInfo\fP const &message)=0"
.br
.ti -1c
.RI "virtual void \fBpopScopedMessage\fP (\fBMessageInfo\fP const &message)=0"
.br
.ti -1c
.RI "virtual void \fBemplaceUnscopedMessage\fP (\fBMessageBuilder\fP const &builder)=0"
.br
.ti -1c
.RI "virtual void \fBhandleFatalErrorCondition\fP (\fBStringRef\fP message)=0"
.br
.ti -1c
.RI "virtual void \fBhandleExpr\fP (\fBAssertionInfo\fP const &info, \fBITransientExpression\fP const &expr, \fBAssertionReaction\fP &reaction)=0"
.br
.ti -1c
.RI "virtual void \fBhandleMessage\fP (\fBAssertionInfo\fP const &info, ResultWas::OfType resultType, \fBStringRef\fP const &message, \fBAssertionReaction\fP &reaction)=0"
.br
.ti -1c
.RI "virtual void \fBhandleUnexpectedExceptionNotThrown\fP (\fBAssertionInfo\fP const &info, \fBAssertionReaction\fP &reaction)=0"
.br
.ti -1c
.RI "virtual void \fBhandleUnexpectedInflightException\fP (\fBAssertionInfo\fP const &info, std::string const &message, \fBAssertionReaction\fP &reaction)=0"
.br
.ti -1c
.RI "virtual void \fBhandleIncomplete\fP (\fBAssertionInfo\fP const &info)=0"
.br
.ti -1c
.RI "virtual void \fBhandleNonExpr\fP (\fBAssertionInfo\fP const &info, ResultWas::OfType resultType, \fBAssertionReaction\fP &reaction)=0"
.br
.ti -1c
.RI "virtual bool \fBlastAssertionPassed\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBassertionPassed\fP ()=0"
.br
.ti -1c
.RI "virtual std::string \fBgetCurrentTestName\fP () const =0"
.br
.ti -1c
.RI "virtual const AssertionResult * \fBgetLastResult\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBexceptionEarlyReported\fP ()=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
