.TH "Typhoon/ThirdParty/glm/glm/gtx/color_encoding.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/gtx/color_encoding.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./detail/setup\&.hpp'\fP
.br
\fC#include '\&.\&./detail/qualifier\&.hpp'\fP
.br
\fC#include '\&.\&./vec3\&.hpp'\fP
.br
\fC#include <limits>\fP
.br
\fC#include 'color_encoding\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 3, T, Q > \fBglm::convertLinearSRGBToD65XYZ\fP (vec< 3, T, Q > const &ColorLinearSRGB)"
.br
.RI "Convert a linear sRGB color to D65 YUV\&. "
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 3, T, Q > \fBglm::convertLinearSRGBToD50XYZ\fP (vec< 3, T, Q > const &ColorLinearSRGB)"
.br
.RI "Convert a linear sRGB color to D50 YUV\&. "
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 3, T, Q > \fBglm::convertD65XYZToLinearSRGB\fP (vec< 3, T, Q > const &ColorD65XYZ)"
.br
.RI "Convert a D65 YUV color to linear sRGB\&. "
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 3, T, Q > \fBglm::convertD65XYZToD50XYZ\fP (vec< 3, T, Q > const &ColorD65XYZ)"
.br
.RI "Convert a D65 YUV color to D50 YUV\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTX_color_encoding\fP
.PP
\fBSee also:\fP
.RS 4
\fBCore features\fP (dependence) 
.PP
\fBGLM_GTX_color_encoding\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
