.TH "Typhoon/ThirdParty/glm/glm/gtx/color_space_YCoCg.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/gtx/color_space_YCoCg.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./glm\&.hpp'\fP
.br
\fC#include 'color_space_YCoCg\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 3, T, Q > \fBglm::rgb2YCoCg\fP (vec< 3, T, Q > const &rgbColor)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 3, T, Q > \fBglm::YCoCg2rgb\fP (vec< 3, T, Q > const &YCoCgColor)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 3, T, Q > \fBglm::rgb2YCoCgR\fP (vec< 3, T, Q > const &rgbColor)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 3, T, Q > \fBglm::YCoCgR2rgb\fP (vec< 3, T, Q > const &YCoCgColor)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTX_color_space_YCoCg\fP
.PP
\fBSee also:\fP
.RS 4
\fBCore features\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
