.TH "Typhoon/ThirdParty/glm/glm/gtx/color_space.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/gtx/color_space.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./glm\&.hpp'\fP
.br
\fC#include 'color_space\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 3, T, Q > \fBglm::rgbColor\fP (vec< 3, T, Q > const &hsvValue)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 3, T, Q > \fBglm::hsvColor\fP (vec< 3, T, Q > const &rgbValue)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL mat< 4, 4, T, defaultp > \fBglm::saturation\fP (T const s)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 3, T, Q > \fBglm::saturation\fP (T const s, vec< 3, T, Q > const &color)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 4, T, Q > \fBglm::saturation\fP (T const s, vec< 4, T, Q > const &color)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL T \fBglm::luminosity\fP (vec< 3, T, Q > const &color)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTX_color_space\fP
.PP
\fBSee also:\fP
.RS 4
\fBCore features\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
