.TH "Typhoon/ThirdParty/glm/glm/gtx/common.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/gtx/common.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./vec2\&.hpp'\fP
.br
\fC#include '\&.\&./vec3\&.hpp'\fP
.br
\fC#include '\&.\&./vec4\&.hpp'\fP
.br
\fC#include '\&.\&./gtc/vec1\&.hpp'\fP
.br
\fC#include 'common\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType::bool_type \fBglm::isdenormal\fP (genType const &x)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec< L, T, Q > \fBglm::fmod\fP (vec< L, T, Q > const &v)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec< L, bool, Q > \fBglm::openBounded\fP (vec< L, T, Q > const &Value, vec< L, T, Q > const &Min, vec< L, T, Q > const &Max)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec< L, bool, Q > \fBglm::closeBounded\fP (vec< L, T, Q > const &Value, vec< L, T, Q > const &Min, vec< L, T, Q > const &Max)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTX_common\fP
.PP
\fBSee also:\fP
.RS 4
\fBCore features\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
