.TH "core_matrix" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core_matrix
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, double, defaultp > \fBglm::dmat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, double, defaultp > \fBglm::dmat2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, double, defaultp > \fBglm::dmat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, double, defaultp > \fBglm::dmat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, double, defaultp > \fBglm::dmat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, double, defaultp > \fBglm::dmat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, double, defaultp > \fBglm::dmat3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, double, defaultp > \fBglm::dmat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, double, defaultp > \fBglm::dmat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, double, defaultp > \fBglm::dmat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, double, defaultp > \fBglm::dmat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, double, defaultp > \fBglm::dmat4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, float, defaultp > \fBglm::mat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 2, float, defaultp > \fBglm::mat2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 3, float, defaultp > \fBglm::mat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 2, 4, float, defaultp > \fBglm::mat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, float, defaultp > \fBglm::mat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 3, float, defaultp > \fBglm::mat3\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, float, defaultp > \fBglm::mat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 2, float, defaultp > \fBglm::mat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, float, defaultp > \fBglm::mat4x3\fP"
.br
.in -1c
.in +1c
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, float, defaultp > \fBglm::mat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 4, float, defaultp > \fBglm::mat4\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Matrix types of with C columns and R rows where C and R are values between 2 to 4 included\&. These types have exhaustive sets of operators\&. 
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBmat\fP< 2, 2, \fBf64\fP, defaultp > \fBglm::dmat2\fP"
2 columns of 2 components matrix of double-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef \fBmat\fP< 2, 2, double, defaultp > \fBglm::dmat2x2\fP"
2 columns of 2 components matrix of double-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef \fBmat\fP< 2, 3, double, defaultp > \fBglm::dmat2x3\fP"
2 columns of 3 components matrix of double-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef \fBmat\fP< 2, 4, double, defaultp > \fBglm::dmat2x4\fP"
2 columns of 4 components matrix of double-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef \fBmat\fP< 3, 3, \fBf64\fP, defaultp > \fBglm::dmat3\fP"
3 columns of 3 components matrix of double-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef \fBmat\fP< 3, 2, double, defaultp > \fBglm::dmat3x2\fP"
3 columns of 2 components matrix of double-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef \fBmat\fP< 3, 3, double, defaultp > \fBglm::dmat3x3\fP"
3 columns of 3 components matrix of double-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef \fBmat\fP< 3, 4, double, defaultp > \fBglm::dmat3x4\fP"
3 columns of 4 components matrix of double-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef \fBmat\fP< 4, 4, \fBf64\fP, defaultp > \fBglm::dmat4\fP"
4 columns of 4 components matrix of double-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef \fBmat\fP< 4, 2, double, defaultp > \fBglm::dmat4x2\fP"
4 columns of 2 components matrix of double-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef \fBmat\fP< 4, 3, double, defaultp > \fBglm::dmat4x3\fP"
4 columns of 3 components matrix of double-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef \fBmat\fP< 4, 4, double, defaultp > \fBglm::dmat4x4\fP"
4 columns of 4 components matrix of double-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef \fBmat\fP< 2, 2, \fBf32\fP, defaultp > \fBglm::mat2\fP"
2 columns of 2 components matrix of single-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef \fBmat\fP< 2, 2, \fBf32\fP, defaultp > \fBglm::mat2x2\fP"
2 columns of 2 components matrix of single-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef \fBmat\fP< 2, 3, \fBf32\fP, defaultp > \fBglm::mat2x3\fP"
2 columns of 3 components matrix of single-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef \fBmat\fP< 2, 4, \fBf32\fP, defaultp > \fBglm::mat2x4\fP"
2 columns of 4 components matrix of single-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef \fBmat\fP< 3, 3, \fBf32\fP, defaultp > \fBglm::mat3\fP"
3 columns of 3 components matrix of single-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef \fBmat\fP< 3, 3, \fBf32\fP, defaultp > \fBglm::mat3x3\fP"
3 columns of 3 components matrix of single-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef \fBmat\fP< 3, 4, \fBf32\fP, defaultp > \fBglm::mat3x4\fP"
3 columns of 4 components matrix of single-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef \fBmat\fP< 4, 4, \fBf32\fP, defaultp > \fBglm::mat4\fP"
4 columns of 4 components matrix of single-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef \fBmat\fP< 4, 2, \fBf32\fP, defaultp > \fBglm::mat4x2\fP"
4 columns of 2 components matrix of single-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef \fBmat\fP< 4, 3, \fBf32\fP, defaultp > \fBglm::mat4x3\fP"
4 columns of 3 components matrix of single-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef \fBmat\fP< 4, 4, \fBf32\fP, defaultp > \fBglm::mat4x4\fP"
4 columns of 4 components matrix of single-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
