.TH "core_vector" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core_vector
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBvec\fP< 2, bool, defaultp > \fBglm::bvec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, bool, defaultp > \fBglm::bvec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, bool, defaultp > \fBglm::bvec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, double, defaultp > \fBglm::dvec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, double, defaultp > \fBglm::dvec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, double, defaultp > \fBglm::dvec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, float, defaultp > \fBglm::vec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, float, defaultp > \fBglm::vec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, float, defaultp > \fBglm::vec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, int, defaultp > \fBglm::ivec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, int, defaultp > \fBglm::ivec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, int, defaultp > \fBglm::ivec4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, unsigned int, defaultp > \fBglm::uvec2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, unsigned int, defaultp > \fBglm::uvec3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, unsigned int, defaultp > \fBglm::uvec4\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Vector types of two to four components with an exhaustive set of operators\&. 
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBvec\fP< 2, bool, defaultp > \fBglm::bvec2\fP"
2 components vector of boolean\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.RE
.PP

.SS "typedef \fBvec\fP< 3, bool, defaultp > \fBglm::bvec3\fP"
3 components vector of boolean\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.RE
.PP

.SS "typedef \fBvec\fP< 4, bool, defaultp > \fBglm::bvec4\fP"
4 components vector of boolean\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.RE
.PP

.SS "typedef \fBvec\fP< 2, \fBf64\fP, defaultp > \fBglm::dvec2\fP"
2 components vector of double-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.RE
.PP

.SS "typedef \fBvec\fP< 3, \fBf64\fP, defaultp > \fBglm::dvec3\fP"
3 components vector of double-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.RE
.PP

.SS "typedef \fBvec\fP< 4, \fBf64\fP, defaultp > \fBglm::dvec4\fP"
4 components vector of double-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.RE
.PP

.SS "typedef \fBvec\fP< 2, \fBi32\fP, defaultp > \fBglm::ivec2\fP"
2 components vector of signed integer numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.RE
.PP

.SS "typedef \fBvec\fP< 3, \fBi32\fP, defaultp > \fBglm::ivec3\fP"
3 components vector of signed integer numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.RE
.PP

.SS "typedef \fBvec\fP< 4, \fBi32\fP, defaultp > \fBglm::ivec4\fP"
4 components vector of signed integer numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.RE
.PP

.SS "typedef \fBvec\fP< 2, \fBu32\fP, defaultp > \fBglm::uvec2\fP"
2 components vector of unsigned integer numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.RE
.PP

.SS "typedef \fBvec\fP< 3, \fBu32\fP, defaultp > \fBglm::uvec3\fP"
3 components vector of unsigned integer numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.RE
.PP

.SS "typedef \fBvec\fP< 4, \fBu32\fP, defaultp > \fBglm::uvec4\fP"
4 components vector of unsigned integer numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.RE
.PP

.SS "typedef \fBvec\fP< 2, float, defaultp > \fBglm::vec2\fP"
2 components vector of single-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.RE
.PP

.SS "typedef \fBvec\fP< 3, float, defaultp > \fBglm::vec3\fP"
3 components vector of single-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.RE
.PP

.SS "typedef \fBvec\fP< 4, float, defaultp > \fBglm::vec4\fP"
4 components vector of single-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
