.TH "core" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core \- Features that implement in C++ the GLSL specification as closely as possible\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBCommon functions\fP"
.br
.ti -1c
.RI "\fBExponential functions\fP"
.br
.ti -1c
.RI "\fBGeometric functions\fP"
.br
.ti -1c
.RI "\fBVector types\fP"
.br
.ti -1c
.RI "\fBVector types with precision qualifiers\fP"
.br
.RI "Vector types with precision qualifiers which may result in various precision in term of ULPs\&. "
.ti -1c
.RI "\fBMatrix types\fP"
.br
.ti -1c
.RI "\fBMatrix types with precision qualifiers\fP"
.br
.RI "Matrix types with precision qualifiers which may result in various precision in term of ULPs\&. "
.ti -1c
.RI "\fBInteger functions\fP"
.br
.ti -1c
.RI "\fBMatrix functions\fP"
.br
.ti -1c
.RI "\fBFloating\-Point Pack and Unpack Functions\fP"
.br
.ti -1c
.RI "\fBAngle and Trigonometry Functions\fP"
.br
.ti -1c
.RI "\fBVector Relational Functions\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBmat\fP< 3, 2, float, defaultp > \fBglm::mat3x2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Features that implement in C++ the GLSL specification as closely as possible\&. 

The GLM core consists of C++ types that mirror GLSL types and C++ functions that mirror the GLSL functions\&.
.PP
The best documentation for GLM Core is the current GLSL specification, \fCversion 4\&.2 (pdf file)\fP\&.
.PP
GLM core functionalities require <\fBglm/glm\&.hpp\fP> to be included to be used\&. 
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBmat\fP< 3, 2, \fBf32\fP, defaultp > \fBglm::mat3x2\fP"
3 columns of 2 components matrix of single-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
