.TH "core_format_specs" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core_format_specs
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBbasic_format_specs< Char >\fP, \fBbasic_format_specs< char_type >\fP, \fBbasic_format_specs< Context::char_type >\fP, and \fBbasic_format_specs< ParseContext::char_type >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "FMT_CONSTEXPR bool \fBhas\fP (unsigned f) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBprecision\fP"
.br
.ti -1c
.RI "uint_least8_t \fBflags\fP"
.br
.ti -1c
.RI "char \fBtype\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
