.TH "deprecated" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 

.IP "\fBMember \fBGLFWcharmodsfun\fP )(GLFWwindow *, unsigned int, int)\fP" 1c
Scheduled for removal in version 4\&.0\&. 
.IP "\fBMember \fBglfwSetCharModsCallback\fP (GLFWwindow *window, GLFWcharmodsfun callback)\fP" 1c
Scheduled for removal in version 4\&.0\&.
.PP

