.TH "DIDEVICEOBJECTINSTANCEA" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DIDEVICEOBJECTINSTANCEA
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "DWORD \fBdwSize\fP"
.br
.ti -1c
.RI "GUID \fBguidType\fP"
.br
.ti -1c
.RI "DWORD \fBdwOfs\fP"
.br
.ti -1c
.RI "DWORD \fBdwType\fP"
.br
.ti -1c
.RI "DWORD \fBdwFlags\fP"
.br
.ti -1c
.RI "CHAR \fBtszName\fP [MAX_PATH]"
.br
.ti -1c
.RI "DWORD \fBdwFFMaxForce\fP"
.br
.ti -1c
.RI "DWORD \fBdwFFForceResolution\fP"
.br
.ti -1c
.RI "WORD \fBwCollectionNumber\fP"
.br
.ti -1c
.RI "WORD \fBwDesignatorIndex\fP"
.br
.ti -1c
.RI "WORD \fBwUsagePage\fP"
.br
.ti -1c
.RI "WORD \fBwUsage\fP"
.br
.ti -1c
.RI "DWORD \fBdwDimension\fP"
.br
.ti -1c
.RI "WORD \fBwExponent\fP"
.br
.ti -1c
.RI "WORD \fBwReserved\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
