.TH "DIDEVCAPS" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DIDEVCAPS
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "DWORD \fBdwSize\fP"
.br
.ti -1c
.RI "DWORD \fBdwFlags\fP"
.br
.ti -1c
.RI "DWORD \fBdwDevType\fP"
.br
.ti -1c
.RI "DWORD \fBdwAxes\fP"
.br
.ti -1c
.RI "DWORD \fBdwButtons\fP"
.br
.ti -1c
.RI "DWORD \fBdwPOVs\fP"
.br
.ti -1c
.RI "DWORD \fBdwFFSamplePeriod\fP"
.br
.ti -1c
.RI "DWORD \fBdwFFMinTimeResolution\fP"
.br
.ti -1c
.RI "DWORD \fBdwFirmwareRevision\fP"
.br
.ti -1c
.RI "DWORD \fBdwHardwareRevision\fP"
.br
.ti -1c
.RI "DWORD \fBdwFFDriverVersion\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
