.TH "DIDEVICEOBJECTDATA_DX3" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DIDEVICEOBJECTDATA_DX3
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "DWORD \fBdwOfs\fP"
.br
.ti -1c
.RI "DWORD \fBdwData\fP"
.br
.ti -1c
.RI "DWORD \fBdwTimeStamp\fP"
.br
.ti -1c
.RI "DWORD \fBdwSequence\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
