.TH "DIENVELOPE" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DIENVELOPE
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "DWORD \fBdwSize\fP"
.br
.ti -1c
.RI "DWORD \fBdwAttackLevel\fP"
.br
.ti -1c
.RI "DWORD \fBdwAttackTime\fP"
.br
.ti -1c
.RI "DWORD \fBdwFadeLevel\fP"
.br
.ti -1c
.RI "DWORD \fBdwFadeTime\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
