.TH "DIJOYSTATE2" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DIJOYSTATE2
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "LONG \fBlX\fP"
.br
.ti -1c
.RI "LONG \fBlY\fP"
.br
.ti -1c
.RI "LONG \fBlZ\fP"
.br
.ti -1c
.RI "LONG \fBlRx\fP"
.br
.ti -1c
.RI "LONG \fBlRy\fP"
.br
.ti -1c
.RI "LONG \fBlRz\fP"
.br
.ti -1c
.RI "LONG \fBrglSlider\fP [2]"
.br
.ti -1c
.RI "DWORD \fBrgdwPOV\fP [4]"
.br
.ti -1c
.RI "BYTE \fBrgbButtons\fP [128]"
.br
.ti -1c
.RI "LONG \fBlVX\fP"
.br
.ti -1c
.RI "LONG \fBlVY\fP"
.br
.ti -1c
.RI "LONG \fBlVZ\fP"
.br
.ti -1c
.RI "LONG \fBlVRx\fP"
.br
.ti -1c
.RI "LONG \fBlVRy\fP"
.br
.ti -1c
.RI "LONG \fBlVRz\fP"
.br
.ti -1c
.RI "LONG \fBrglVSlider\fP [2]"
.br
.ti -1c
.RI "LONG \fBlAX\fP"
.br
.ti -1c
.RI "LONG \fBlAY\fP"
.br
.ti -1c
.RI "LONG \fBlAZ\fP"
.br
.ti -1c
.RI "LONG \fBlARx\fP"
.br
.ti -1c
.RI "LONG \fBlARy\fP"
.br
.ti -1c
.RI "LONG \fBlARz\fP"
.br
.ti -1c
.RI "LONG \fBrglASlider\fP [2]"
.br
.ti -1c
.RI "LONG \fBlFX\fP"
.br
.ti -1c
.RI "LONG \fBlFY\fP"
.br
.ti -1c
.RI "LONG \fBlFZ\fP"
.br
.ti -1c
.RI "LONG \fBlFRx\fP"
.br
.ti -1c
.RI "LONG \fBlFRy\fP"
.br
.ti -1c
.RI "LONG \fBlFRz\fP"
.br
.ti -1c
.RI "LONG \fBrglFSlider\fP [2]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
