.TH "DIMOUSESTATE2" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DIMOUSESTATE2
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "LONG \fBlX\fP"
.br
.ti -1c
.RI "LONG \fBlY\fP"
.br
.ti -1c
.RI "LONG \fBlZ\fP"
.br
.ti -1c
.RI "BYTE \fBrgbButtons\fP [8]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
