.TH "DIPROPRANGE" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DIPROPRANGE
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDIPROPHEADER\fP \fBdiph\fP"
.br
.ti -1c
.RI "LONG \fBlMin\fP"
.br
.ti -1c
.RI "LONG \fBlMax\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
