.TH "DIPROPCPOINTS" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DIPROPCPOINTS
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDIPROPHEADER\fP \fBdiph\fP"
.br
.ti -1c
.RI "DWORD \fBdwCPointsNum\fP"
.br
.ti -1c
.RI "\fBCPOINT\fP \fBcp\fP [MAXCPOINTSNUM]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
