.TH "Typhoon/ThirdParty/glm/glm/gtx/easing.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/gtx/easing.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./glm\&.hpp'\fP
.br
\fC#include '\&.\&./gtc/constants\&.hpp'\fP
.br
\fC#include '\&.\&./detail/qualifier\&.hpp'\fP
.br
\fC#include 'easing\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::linearInterpolation\fP (genType const &a)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::quadraticEaseIn\fP (genType const &a)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::quadraticEaseOut\fP (genType const &a)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::quadraticEaseInOut\fP (genType const &a)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::cubicEaseIn\fP (genType const &a)"
.br
.RI "Modelled after the cubic y = x^3\&. "
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::cubicEaseOut\fP (genType const &a)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::cubicEaseInOut\fP (genType const &a)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::quarticEaseIn\fP (genType const &a)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::quarticEaseOut\fP (genType const &a)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::quarticEaseInOut\fP (genType const &a)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::quinticEaseIn\fP (genType const &a)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::quinticEaseOut\fP (genType const &a)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::quinticEaseInOut\fP (genType const &a)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::sineEaseIn\fP (genType const &a)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::sineEaseOut\fP (genType const &a)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::sineEaseInOut\fP (genType const &a)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::circularEaseIn\fP (genType const &a)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::circularEaseOut\fP (genType const &a)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::circularEaseInOut\fP (genType const &a)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::exponentialEaseIn\fP (genType const &a)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::exponentialEaseOut\fP (genType const &a)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::exponentialEaseInOut\fP (genType const &a)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::elasticEaseIn\fP (genType const &a)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::elasticEaseOut\fP (genType const &a)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::elasticEaseInOut\fP (genType const &a)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::backEaseIn\fP (genType const &a)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::backEaseOut\fP (genType const &a)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::backEaseInOut\fP (genType const &a)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::backEaseIn\fP (genType const &a, genType const &o)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::backEaseOut\fP (genType const &a, genType const &o)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::backEaseInOut\fP (genType const &a, genType const &o)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::bounceEaseIn\fP (genType const &a)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::bounceEaseOut\fP (genType const &a)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::bounceEaseInOut\fP (genType const &a)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTX_easing\fP
.PP
\fBAuthor:\fP
.RS 4
Robert Chisholm
.RE
.PP
\fBSee also:\fP
.RS 4
\fBCore features\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
