.TH "Typhoon/ThirdParty/glm/glm/gtc/epsilon.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/gtc/epsilon.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./detail/setup\&.hpp'\fP
.br
\fC#include '\&.\&./detail/qualifier\&.hpp'\fP
.br
\fC#include 'epsilon\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec< L, bool, Q > \fBglm::epsilonEqual\fP (vec< L, T, Q > const &x, vec< L, T, Q > const &y, T const &epsilon)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL bool \fBglm::epsilonEqual\fP (genType const &x, genType const &y, genType const &epsilon)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec< L, bool, Q > \fBglm::epsilonNotEqual\fP (vec< L, T, Q > const &x, vec< L, T, Q > const &y, T const &epsilon)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL bool \fBglm::epsilonNotEqual\fP (genType const &x, genType const &y, genType const &epsilon)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTC_epsilon\fP
.PP
\fBSee also:\fP
.RS 4
\fBCore features\fP (dependence) 
.PP
\fBGLM_GTC_quaternion\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
