.TH "error_code" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
error_code
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBerror_code\fP (int value=0) FMT_NOEXCEPT"
.br
.ti -1c
.RI "int \fBget\fP () const FMT_NOEXCEPT"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
