.TH "ExampleAppConsole" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExampleAppConsole
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBClearLog\fP ()"
.br
.ti -1c
.RI "void \fBAddLog\fP (const char *fmt,\&.\&.\&.) IM_FMTARGS(2)"
.br
.ti -1c
.RI "void \fBDraw\fP (const char *title, bool *p_open)"
.br
.ti -1c
.RI "void \fBExecCommand\fP (const char *command_line)"
.br
.ti -1c
.RI "int \fBTextEditCallback\fP (\fBImGuiInputTextCallbackData\fP *data)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBStricmp\fP (const char *str1, const char *str2)"
.br
.ti -1c
.RI "static int \fBStrnicmp\fP (const char *str1, const char *str2, int n)"
.br
.ti -1c
.RI "static char * \fBStrdup\fP (const char *str)"
.br
.ti -1c
.RI "static void \fBStrtrim\fP (char *str)"
.br
.ti -1c
.RI "static int \fBTextEditCallbackStub\fP (\fBImGuiInputTextCallbackData\fP *data)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBInputBuf\fP [256]"
.br
.ti -1c
.RI "\fBImVector\fP< char * > \fBItems\fP"
.br
.ti -1c
.RI "\fBImVector\fP< const char * > \fBCommands\fP"
.br
.ti -1c
.RI "\fBImVector\fP< char * > \fBHistory\fP"
.br
.ti -1c
.RI "int \fBHistoryPos\fP"
.br
.ti -1c
.RI "\fBImGuiTextFilter\fP \fBFilter\fP"
.br
.ti -1c
.RI "bool \fBAutoScroll\fP"
.br
.ti -1c
.RI "bool \fBScrollToBottom\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
