.TH "ext_matrix_common" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ext_matrix_common
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<length_t C, length_t R, typename T , typename U , qualifier Q> GLM_FUNC_DECL \fBmat\fP< C, R, T, Q > \fBglm::mix\fP (\fBmat\fP< C, R, T, Q > const &x, \fBmat\fP< C, R, T, Q > const &y, \fBmat\fP< C, R, U, Q > const &a)"
.br
.ti -1c
.RI "template<length_t C, length_t R, typename T , typename U , qualifier Q> GLM_FUNC_DECL \fBmat\fP< C, R, T, Q > \fBglm::mix\fP (\fBmat\fP< C, R, T, Q > const &x, \fBmat\fP< C, R, T, Q > const &y, U a)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines functions for common matrix operations\&.
.PP
Include <\fBglm/ext/matrix_common\&.hpp\fP> to use the features of this extension\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_EXT_matrix_common\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
