.TH "ext_scalar_int_sized" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ext_scalar_int_sized
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef detail::int8 \fBglm::int8\fP"
.br
.RI "8 bit signed integer type\&. "
.ti -1c
.RI "typedef detail::int16 \fBglm::int16\fP"
.br
.RI "16 bit signed integer type\&. "
.ti -1c
.RI "typedef detail::int32 \fBglm::int32\fP"
.br
.RI "32 bit signed integer type\&. "
.ti -1c
.RI "typedef detail::int64 \fBglm::int64\fP"
.br
.RI "64 bit signed integer type\&. "
.in -1c
.SH "Detailed Description"
.PP 
Exposes sized signed integer scalar types\&.
.PP
Include <\fBglm/ext/scalar_int_sized\&.hpp\fP> to use the features of this extension\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_EXT_scalar_uint_sized\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
