.TH "ext_quaternion_double_precision" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ext_quaternion_double_precision
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBqua\fP< double, \fBlowp\fP > \fBglm::lowp_dquat\fP"
.br
.ti -1c
.RI "typedef \fBqua\fP< double, \fBmediump\fP > \fBglm::mediump_dquat\fP"
.br
.ti -1c
.RI "typedef \fBqua\fP< double, \fBhighp\fP > \fBglm::highp_dquat\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Exposes double-precision floating point quaternion type with various precision in term of ULPs\&.
.PP
Include <\fBglm/ext/quaternion_double_precision\&.hpp\fP> to use the features of this extension\&. 
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBqua\fP< double, \fBhighp\fP > \fBglm::highp_dquat\fP"
Quaternion of high double-qualifier floating-point numbers using high precision arithmetic in term of ULPs\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_EXT_quaternion_double_precision\fP 
.RE
.PP

.SS "typedef \fBqua\fP< double, \fBlowp\fP > \fBglm::lowp_dquat\fP"
Quaternion of double-precision floating-point numbers using high precision arithmetic in term of ULPs\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_EXT_quaternion_double_precision\fP 
.RE
.PP

.SS "typedef \fBqua\fP< double, \fBmediump\fP > \fBglm::mediump_dquat\fP"
Quaternion of medium double-qualifier floating-point numbers using high precision arithmetic in term of ULPs\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_EXT_quaternion_double_precision\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
