.TH "ext_vector_bool1_precision" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ext_vector_bool1_precision
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBvec\fP< 1, bool, \fBhighp\fP > \fBglm::highp_bvec1\fP"
.br
.RI "1 component vector of bool values\&. "
.ti -1c
.RI "typedef \fBvec\fP< 1, bool, \fBmediump\fP > \fBglm::mediump_bvec1\fP"
.br
.RI "1 component vector of bool values\&. "
.ti -1c
.RI "typedef \fBvec\fP< 1, bool, \fBlowp\fP > \fBglm::lowp_bvec1\fP"
.br
.RI "1 component vector of bool values\&. "
.in -1c
.SH "Detailed Description"
.PP 
Exposes highp_bvec1, mediump_bvec1 and lowp_bvec1 types\&.
.PP
Include <\fBglm/ext/vector_bool1_precision\&.hpp\fP> to use the features of this extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
