.TH "ext_vector_double1_precision" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ext_vector_double1_precision
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBvec\fP< 1, double, \fBhighp\fP > \fBglm::highp_dvec1\fP"
.br
.RI "1 component vector of double-precision floating-point numbers using high precision arithmetic in term of ULPs\&. "
.ti -1c
.RI "typedef \fBvec\fP< 1, double, \fBmediump\fP > \fBglm::mediump_dvec1\fP"
.br
.RI "1 component vector of double-precision floating-point numbers using medium precision arithmetic in term of ULPs\&. "
.ti -1c
.RI "typedef \fBvec\fP< 1, double, \fBlowp\fP > \fBglm::lowp_dvec1\fP"
.br
.RI "1 component vector of double-precision floating-point numbers using low precision arithmetic in term of ULPs\&. "
.in -1c
.SH "Detailed Description"
.PP 
Exposes highp_dvec1, mediump_dvec1 and lowp_dvec1 types\&.
.PP
Include <\fBglm/ext/vector_double1_precision\&.hpp\fP> to use the features of this extension\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_EXT_vector_double1\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
