.TH "ext_quaternion_float_precision" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ext_quaternion_float_precision
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBqua\fP< float, \fBlowp\fP > \fBglm::lowp_quat\fP"
.br
.RI "Quaternion of single-precision floating-point numbers using high precision arithmetic in term of ULPs\&. "
.ti -1c
.RI "typedef \fBqua\fP< float, \fBmediump\fP > \fBglm::mediump_quat\fP"
.br
.RI "Quaternion of single-precision floating-point numbers using high precision arithmetic in term of ULPs\&. "
.ti -1c
.RI "typedef \fBqua\fP< float, \fBhighp\fP > \fBglm::highp_quat\fP"
.br
.RI "Quaternion of single-precision floating-point numbers using high precision arithmetic in term of ULPs\&. "
.in -1c
.SH "Detailed Description"
.PP 
Exposes single-precision floating point quaternion type with various precision in term of ULPs\&.
.PP
Include <\fBglm/ext/quaternion_float_precision\&.hpp\fP> to use the features of this extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
