.TH "ext_quaternion_double" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ext_quaternion_double
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBqua\fP< double, defaultp > \fBglm::dquat\fP"
.br
.RI "Quaternion of double-precision floating-point numbers\&. "
.in -1c
.SH "Detailed Description"
.PP 
Exposes double-precision floating point quaternion type\&.
.PP
Include <\fBglm/ext/quaternion_double\&.hpp\fP> to use the features of this extension\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_EXT_quaternion_float\fP 
.PP
\fBGLM_EXT_quaternion_double_precision\fP 
.PP
\fBGLM_EXT_quaternion_common\fP 
.PP
\fBGLM_EXT_quaternion_exponential\fP 
.PP
\fBGLM_EXT_quaternion_geometric\fP 
.PP
\fBGLM_EXT_quaternion_relational\fP 
.PP
\fBGLM_EXT_quaternion_transform\fP 
.PP
\fBGLM_EXT_quaternion_trigonometric\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
