.TH "ext_quaternion_trigonometric" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ext_quaternion_trigonometric
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL T \fBglm::angle\fP (\fBqua\fP< T, Q > const &x)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP< 3, T, Q > \fBglm::axis\fP (\fBqua\fP< T, Q > const &x)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBqua\fP< T, Q > \fBglm::angleAxis\fP (T const &\fBangle\fP, \fBvec\fP< 3, T, Q > const &\fBaxis\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provides trigonometric functions for quaternion types
.PP
Include <\fBglm/ext/quaternion_trigonometric\&.hpp\fP> to use the features of this extension\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_EXT_quaternion_float\fP 
.PP
\fBGLM_EXT_quaternion_double\fP 
.PP
\fBGLM_EXT_quaternion_exponential\fP 
.PP
\fBGLM_EXT_quaternion_geometric\fP 
.PP
\fBGLM_EXT_quaternion_relational\fP 
.PP
\fBGLM_EXT_quaternion_transform\fP 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL T glm::angle (\fBqua\fP< T, Q > const & x)"
Returns the quaternion rotation angle\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP A floating-point scalar type 
.br
\fIQ\fP A value from qualifier enum 
.RE
.PP

.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBqua\fP<T, Q> glm::angleAxis (T const & angle, \fBvec\fP< 3, T, Q > const & axis)"
Build a quaternion from an angle and a normalized axis\&.
.PP
\fBParameters:\fP
.RS 4
\fIangle\fP Angle expressed in radians\&. 
.br
\fIaxis\fP Axis of the quaternion, must be normalized\&.
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP A floating-point scalar type 
.br
\fIQ\fP A value from qualifier enum 
.RE
.PP

.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP<3, T, Q> glm::axis (\fBqua\fP< T, Q > const & x)"
Returns the q rotation axis\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP A floating-point scalar type 
.br
\fIQ\fP A value from qualifier enum 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
