.TH "ext_vector_int1_precision" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ext_vector_int1_precision
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBvec\fP< 1, int, \fBhighp\fP > \fBglm::highp_ivec1\fP"
.br
.RI "1 component vector of signed integer values\&. "
.ti -1c
.RI "typedef \fBvec\fP< 1, int, \fBmediump\fP > \fBglm::mediump_ivec1\fP"
.br
.RI "1 component vector of signed integer values\&. "
.ti -1c
.RI "typedef \fBvec\fP< 1, int, \fBlowp\fP > \fBglm::lowp_ivec1\fP"
.br
.RI "1 component vector of signed integer values\&. "
.in -1c
.SH "Detailed Description"
.PP 
Exposes highp_ivec1, mediump_ivec1 and lowp_ivec1 types\&.
.PP
Include <\fBglm/ext/vector_int1_precision\&.hpp\fP> to use the features of this extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
