.TH "ext_vector_int1" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ext_vector_int1
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBvec\fP< 1, int, defaultp > \fBglm::ivec1\fP"
.br
.RI "1 component vector of signed integer numbers\&. "
.in -1c
.SH "Detailed Description"
.PP 
Exposes ivec1 vector type\&.
.PP
Include <\fBglm/ext/vector_int1\&.hpp\fP> to use the features of this extension\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_EXT_vector_uint1\fP extension\&. 
.PP
\fBGLM_EXT_vector_int1_precision\fP extension\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
