.TH "Typhoon/ThirdParty/glm/glm/gtx/extend.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/gtx/extend.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./glm\&.hpp'\fP
.br
\fC#include 'extend\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::extend\fP (genType const &Origin, genType const &Source, typename genType::value_type const Length)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTX_extend\fP
.PP
\fBSee also:\fP
.RS 4
\fBCore features\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
