.TH "Typhoon/ThirdParty/glm/glm/gtx/fast_trigonometry.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/gtx/fast_trigonometry.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./gtc/constants\&.hpp'\fP
.br
\fC#include 'fast_trigonometry\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::wrapAngle\fP (T angle)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::fastSin\fP (T angle)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::fastCos\fP (T angle)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::fastTan\fP (T angle)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::fastAsin\fP (T angle)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::fastAcos\fP (T angle)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::fastAtan\fP (T y, T x)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::fastAtan\fP (T angle)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTX_fast_trigonometry\fP
.PP
\fBSee also:\fP
.RS 4
\fBCore features\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
