.TH "fmt::formatter< spdlog::details::bytes_range< T > >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fmt::formatter< spdlog::details::bytes_range< T > >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename ParseContext > auto \fBparse\fP (ParseContext &ctx) \-> decltype(ctx\&.begin())"
.br
.ti -1c
.RI "template<typename FormatContext , typename Container > auto \fBformat\fP (const \fBspdlog::details::bytes_range\fP< Container > &the_range, FormatContext &ctx) \-> decltype(ctx\&.out())"
.br
.ti -1c
.RI "template<typename It > std::size_t \fBput_newline\fP (It inserter, std::size_t pos)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const std::size_t \fBline_size\fP = 100"
.br
.ti -1c
.RI "const char \fBdelimiter\fP = ' '"
.br
.ti -1c
.RI "bool \fBput_newlines\fP = true"
.br
.ti -1c
.RI "bool \fBput_delimiters\fP = true"
.br
.ti -1c
.RI "bool \fBuse_uppercase\fP = false"
.br
.ti -1c
.RI "bool \fBput_positions\fP = true"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
