.TH "formatting_range< Char, Enable >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
formatting_range< Char, Enable >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBformatting_base< Char >\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Char \fBprefix\fP"
.br
.ti -1c
.RI "Char \fBdelimiter\fP"
.br
.ti -1c
.RI "Char \fBpostfix\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static FMT_CONSTEXPR_DECL const std::size_t \fBrange_length_limit\fP"
.br
.ti -1c
.RI "static FMT_CONSTEXPR_DECL const bool \fBadd_delimiter_spaces\fP = true"
.br
.ti -1c
.RI "static FMT_CONSTEXPR_DECL const bool \fBadd_prepostfix_space\fP = false"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Data Documentation"
.PP 
.SS "template<typename Char, typename Enable = void> FMT_CONSTEXPR_DECL const std::size_t \fBformatting_range\fP< Char, Enable >::range_length_limit\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=
      FMT_RANGE_OUTPUT_LENGTH_LIMIT
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
