.TH "Typhoon/ThirdParty/glm/glm/detail/func_exponential.inl" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/detail/func_exponential.inl
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./vector_relational\&.hpp'\fP
.br
\fC#include '_vectorize\&.hpp'\fP
.br
\fC#include <limits>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <cassert>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBglm::detail::compute_log2< L, T, Q, isFloat, Aligned >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_sqrt< L, T, Q, Aligned >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_inversesqrt< L, T, Q, Aligned >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::compute_inversesqrt< L, float, lowp, Aligned >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > genType \fBglm::detail::log2\fP (genType Value)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_QUALIFIER vec< L, T, Q > \fBglm::pow\fP (vec< L, T, Q > const &base, vec< L, T, Q > const &exponent)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_QUALIFIER vec< L, T, Q > \fBglm::exp\fP (vec< L, T, Q > const &x)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_QUALIFIER vec< L, T, Q > \fBglm::log\fP (vec< L, T, Q > const &x)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_QUALIFIER genType \fBglm::exp2\fP (genType x)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_QUALIFIER vec< L, T, Q > \fBglm::exp2\fP (vec< L, T, Q > const &x)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_QUALIFIER genType \fBglm::log2\fP (genType x)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_QUALIFIER vec< L, T, Q > \fBglm::log2\fP (vec< L, T, Q > const &x)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_QUALIFIER vec< L, T, Q > \fBglm::sqrt\fP (vec< L, T, Q > const &x)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_QUALIFIER genType \fBglm::inversesqrt\fP (genType x)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_QUALIFIER vec< L, T, Q > \fBglm::inversesqrt\fP (vec< L, T, Q > const &x)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCore features\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
