.TH "gamepad_buttons" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gamepad_buttons \- Gamepad buttons\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_A\fP   0"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_B\fP   1"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_X\fP   2"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_Y\fP   3"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_LEFT_BUMPER\fP   4"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_RIGHT_BUMPER\fP   5"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_BACK\fP   6"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_START\fP   7"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_GUIDE\fP   8"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_LEFT_THUMB\fP   9"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_RIGHT_THUMB\fP   10"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_DPAD_UP\fP   11"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_DPAD_RIGHT\fP   12"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_DPAD_DOWN\fP   13"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_DPAD_LEFT\fP   14"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_LAST\fP   GLFW_GAMEPAD_BUTTON_DPAD_LEFT"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_CROSS\fP   GLFW_GAMEPAD_BUTTON_A"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_CIRCLE\fP   GLFW_GAMEPAD_BUTTON_B"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_SQUARE\fP   GLFW_GAMEPAD_BUTTON_X"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_BUTTON_TRIANGLE\fP   GLFW_GAMEPAD_BUTTON_Y"
.br
.in -1c
.SH "Detailed Description"
.PP 
Gamepad buttons\&. 

See \fBGamepad input\fP for how these are used\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
