.TH "gamepad_axes" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gamepad_axes \- Gamepad axes\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_AXIS_LEFT_X\fP   0"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_AXIS_LEFT_Y\fP   1"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_AXIS_RIGHT_X\fP   2"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_AXIS_RIGHT_Y\fP   3"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_AXIS_LEFT_TRIGGER\fP   4"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_AXIS_RIGHT_TRIGGER\fP   5"
.br
.ti -1c
.RI "#define \fBGLFW_GAMEPAD_AXIS_LAST\fP   GLFW_GAMEPAD_AXIS_RIGHT_TRIGGER"
.br
.in -1c
.SH "Detailed Description"
.PP 
Gamepad axes\&. 

See \fBGamepad input\fP for how these are used\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
