.TH "GLFWgamepadstate" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLFWgamepadstate \- Gamepad input state\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glfw3\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBbuttons\fP [15]"
.br
.ti -1c
.RI "float \fBaxes\fP [6]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Gamepad input state\&. 

This describes the input state of a gamepad\&.
.PP
\fBSee also:\fP
.RS 4
\fBGamepad input\fP 
.PP
\fBglfwGetGamepadState\fP
.RE
.PP
\fBSince:\fP
.RS 4
Added in version 3\&.3\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "float GLFWgamepadstate::axes[6]"
The states of each \fBgamepad axis\fP, in the range -1\&.0 to 1\&.0 inclusive\&. 
.SS "unsigned char GLFWgamepadstate::buttons[15]"
The states of each \fBgamepad button\fP, \fCGLFW_PRESS\fP or \fCGLFW_RELEASE\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
