.TH "GLFWimage" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLFWimage \- Image data\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glfw3\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "unsigned char * \fBpixels\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Image data\&. 

This describes a single 2D image\&. See the documentation for each related function what the expected pixel format is\&.
.PP
\fBSee also:\fP
.RS 4
\fBCustom cursor creation\fP 
.PP
\fBWindow icon\fP
.RE
.PP
\fBSince:\fP
.RS 4
Added in version 2\&.1\&. @glfw3 Removed format and bytes-per-pixel members\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBCustom cursor creation\fP
.RE
.PP
\fBSince:\fP
.RS 4
Added in version 2\&.1\&. @glfw3 Removed format and bytes-per-pixel members\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "int GLFWimage::height"
The height, in pixels, of this image\&. 
.SS "unsigned char * GLFWimage::pixels"
The pixel data of this image, arranged left-to-right, top-to-bottom\&. 
.SS "int GLFWimage::width"
The width, in pixels, of this image\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
