.TH "glm::compute_YCoCgR< T, Q, isInteger >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::compute_YCoCgR< T, Q, isInteger >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static GLM_FUNC_QUALIFIER \fBvec\fP< 3, T, Q > \fBrgb2YCoCgR\fP (\fBvec\fP< 3, T, Q > const &\fBrgbColor\fP)"
.br
.ti -1c
.RI "static GLM_FUNC_QUALIFIER \fBvec\fP< 3, T, Q > \fBYCoCgR2rgb\fP (\fBvec\fP< 3, T, Q > const &YCoCgRColor)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
