.TH "glm::detail::functor2_vec_sca< vec, 3, T, Q >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::functor2_vec_sca< vec, 3, T, Q >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static GLM_FUNC_QUALIFIER \fBvec\fP< 3, T, Q > \fBcall\fP (T(*Func)(T x, T y), \fBvec\fP< 3, T, Q > const &a, T b)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
