.TH "glm::detail::compute_transpose< 2, 2, T, Q, Aligned >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::compute_transpose< 2, 2, T, Q, Aligned >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static GLM_FUNC_QUALIFIER \fBmat\fP< 2, 2, T, Q > \fBcall\fP (\fBmat\fP< 2, 2, T, Q > const &m)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
