.TH "glm::detail::_swizzle_base2< N, T, Q, E0, E1, E2, E3, 1 >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::_swizzle_base2< N, T, Q, E0, E1, E2, E3, 1 >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBglm::detail::_swizzle_base1< N, T, Q, E0, E1, E2, E3, detail::is_aligned< Q >::value >\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBStub\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "GLM_FUNC_QUALIFIER \fB_swizzle_base2\fP & \fBoperator=\fP (Stub const &)"
.br
.ti -1c
.RI "GLM_FUNC_QUALIFIER T \fBoperator[]\fP (size_t i) const"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
