.TH "glm::detail::init_gentype< genType, GENTYPE_QUAT >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::init_gentype< genType, GENTYPE_QUAT >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "GLM_FUNC_QUALIFIER static GLM_CONSTEXPR genType \fBidentity\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
