.TH "glm::type< mat< C, R, T, Q > >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::type< mat< C, R, T, Q > >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static bool const \fBis_vec\fP = false"
.br
.ti -1c
.RI "static bool const \fBis_mat\fP = true"
.br
.ti -1c
.RI "static bool const \fBis_quat\fP = false"
.br
.ti -1c
.RI "static length_t const \fBcomponents\fP = C"
.br
.ti -1c
.RI "static length_t const \fBcols\fP = C"
.br
.ti -1c
.RI "static length_t const \fBrows\fP = R"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
