.TH "glm::vec< 4, T, Q >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::vec< 4, T, Q >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef T \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, T, Q > \fBtype\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, bool, Q > \fBbool_type\fP"
.br
.ti -1c
.RI "typedef length_t \fBlength_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "GLM_FUNC_DECL GLM_CONSTEXPR T & \fBoperator[]\fP (length_type i)"
.br
.ti -1c
.RI "GLM_FUNC_DECL GLM_CONSTEXPR T const  & \fBoperator[]\fP (length_type i) const"
.br
.ti -1c
.RI "GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 4, T, Q > const &v) GLM_DEFAULT"
.br
.ti -1c
.RI "template<qualifier P> GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 4, T, P > const &v)"
.br
.ti -1c
.RI "GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (T scalar)"
.br
.ti -1c
.RI "GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (T x, T y, T z, T w)"
.br
.ti -1c
.RI "template<typename U , qualifier P> GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 1, U, P > const &v)"
.br
.ti -1c
.RI "template<typename X , typename Y , typename Z , typename W > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (X _x, Y _y, Z _z, W _w)"
.br
.RI "Explicit conversions (From section 5\&.4\&.1 Conversion and scalar constructors of GLSL 1\&.30\&.08 specification) "
.ti -1c
.RI "template<typename X , typename Y , typename Z , typename W > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 1, X, Q > const &_x, Y _y, Z _z, W _w)"
.br
.ti -1c
.RI "template<typename X , typename Y , typename Z , typename W > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (X _x, \fBvec\fP< 1, Y, Q > const &_y, Z _z, W _w)"
.br
.ti -1c
.RI "template<typename X , typename Y , typename Z , typename W > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 1, X, Q > const &_x, \fBvec\fP< 1, Y, Q > const &_y, Z _z, W _w)"
.br
.ti -1c
.RI "template<typename X , typename Y , typename Z , typename W > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (X _x, Y _y, \fBvec\fP< 1, Z, Q > const &_z, W _w)"
.br
.ti -1c
.RI "template<typename X , typename Y , typename Z , typename W > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 1, X, Q > const &_x, Y _y, \fBvec\fP< 1, Z, Q > const &_z, W _w)"
.br
.ti -1c
.RI "template<typename X , typename Y , typename Z , typename W > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (X _x, \fBvec\fP< 1, Y, Q > const &_y, \fBvec\fP< 1, Z, Q > const &_z, W _w)"
.br
.ti -1c
.RI "template<typename X , typename Y , typename Z , typename W > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 1, X, Q > const &_x, \fBvec\fP< 1, Y, Q > const &_y, \fBvec\fP< 1, Z, Q > const &_z, W _w)"
.br
.ti -1c
.RI "template<typename X , typename Y , typename Z , typename W > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 1, X, Q > const &_x, Y _y, Z _z, \fBvec\fP< 1, W, Q > const &_w)"
.br
.ti -1c
.RI "template<typename X , typename Y , typename Z , typename W > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (X _x, \fBvec\fP< 1, Y, Q > const &_y, Z _z, \fBvec\fP< 1, W, Q > const &_w)"
.br
.ti -1c
.RI "template<typename X , typename Y , typename Z , typename W > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 1, X, Q > const &_x, \fBvec\fP< 1, Y, Q > const &_y, Z _z, \fBvec\fP< 1, W, Q > const &_w)"
.br
.ti -1c
.RI "template<typename X , typename Y , typename Z , typename W > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (X _x, Y _y, \fBvec\fP< 1, Z, Q > const &_z, \fBvec\fP< 1, W, Q > const &_w)"
.br
.ti -1c
.RI "template<typename X , typename Y , typename Z , typename W > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 1, X, Q > const &_x, Y _y, \fBvec\fP< 1, Z, Q > const &_z, \fBvec\fP< 1, W, Q > const &_w)"
.br
.ti -1c
.RI "template<typename X , typename Y , typename Z , typename W > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (X _x, \fBvec\fP< 1, Y, Q > const &_y, \fBvec\fP< 1, Z, Q > const &_z, \fBvec\fP< 1, W, Q > const &_w)"
.br
.ti -1c
.RI "template<typename X , typename Y , typename Z , typename W > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 1, X, Q > const &_x, \fBvec\fP< 1, Y, Q > const &_Y, \fBvec\fP< 1, Z, Q > const &_z, \fBvec\fP< 1, W, Q > const &_w)"
.br
.ti -1c
.RI "template<typename A , typename B , typename C , qualifier P> GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 2, A, P > const &_xy, B _z, C _w)"
.br
.RI "Explicit conversions (From section 5\&.4\&.1 Conversion and scalar constructors of GLSL 1\&.30\&.08 specification) "
.ti -1c
.RI "template<typename A , typename B , typename C , qualifier P> GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 2, A, P > const &_xy, \fBvec\fP< 1, B, P > const &_z, C _w)"
.br
.RI "Explicit conversions (From section 5\&.4\&.1 Conversion and scalar constructors of GLSL 1\&.30\&.08 specification) "
.ti -1c
.RI "template<typename A , typename B , typename C , qualifier P> GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 2, A, P > const &_xy, B _z, \fBvec\fP< 1, C, P > const &_w)"
.br
.RI "Explicit conversions (From section 5\&.4\&.1 Conversion and scalar constructors of GLSL 1\&.30\&.08 specification) "
.ti -1c
.RI "template<typename A , typename B , typename C , qualifier P> GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 2, A, P > const &_xy, \fBvec\fP< 1, B, P > const &_z, \fBvec\fP< 1, C, P > const &_w)"
.br
.RI "Explicit conversions (From section 5\&.4\&.1 Conversion and scalar constructors of GLSL 1\&.30\&.08 specification) "
.ti -1c
.RI "template<typename A , typename B , typename C , qualifier P> GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (A _x, \fBvec\fP< 2, B, P > const &_yz, C _w)"
.br
.RI "Explicit conversions (From section 5\&.4\&.1 Conversion and scalar constructors of GLSL 1\&.30\&.08 specification) "
.ti -1c
.RI "template<typename A , typename B , typename C , qualifier P> GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 1, A, P > const &_x, \fBvec\fP< 2, B, P > const &_yz, C _w)"
.br
.RI "Explicit conversions (From section 5\&.4\&.1 Conversion and scalar constructors of GLSL 1\&.30\&.08 specification) "
.ti -1c
.RI "template<typename A , typename B , typename C , qualifier P> GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (A _x, \fBvec\fP< 2, B, P > const &_yz, \fBvec\fP< 1, C, P > const &_w)"
.br
.RI "Explicit conversions (From section 5\&.4\&.1 Conversion and scalar constructors of GLSL 1\&.30\&.08 specification) "
.ti -1c
.RI "template<typename A , typename B , typename C , qualifier P> GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 1, A, P > const &_x, \fBvec\fP< 2, B, P > const &_yz, \fBvec\fP< 1, C, P > const &_w)"
.br
.RI "Explicit conversions (From section 5\&.4\&.1 Conversion and scalar constructors of GLSL 1\&.30\&.08 specification) "
.ti -1c
.RI "template<typename A , typename B , typename C , qualifier P> GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (A _x, B _y, \fBvec\fP< 2, C, P > const &_zw)"
.br
.RI "Explicit conversions (From section 5\&.4\&.1 Conversion and scalar constructors of GLSL 1\&.30\&.08 specification) "
.ti -1c
.RI "template<typename A , typename B , typename C , qualifier P> GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 1, A, P > const &_x, B _y, \fBvec\fP< 2, C, P > const &_zw)"
.br
.RI "Explicit conversions (From section 5\&.4\&.1 Conversion and scalar constructors of GLSL 1\&.30\&.08 specification) "
.ti -1c
.RI "template<typename A , typename B , typename C , qualifier P> GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (A _x, \fBvec\fP< 1, B, P > const &_y, \fBvec\fP< 2, C, P > const &_zw)"
.br
.RI "Explicit conversions (From section 5\&.4\&.1 Conversion and scalar constructors of GLSL 1\&.30\&.08 specification) "
.ti -1c
.RI "template<typename A , typename B , typename C , qualifier P> GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 1, A, P > const &_x, \fBvec\fP< 1, B, P > const &_y, \fBvec\fP< 2, C, P > const &_zw)"
.br
.RI "Explicit conversions (From section 5\&.4\&.1 Conversion and scalar constructors of GLSL 1\&.30\&.08 specification) "
.ti -1c
.RI "template<typename A , typename B , qualifier P> GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 3, A, P > const &_xyz, B _w)"
.br
.RI "Explicit conversions (From section 5\&.4\&.1 Conversion and scalar constructors of GLSL 1\&.30\&.08 specification) "
.ti -1c
.RI "template<typename A , typename B , qualifier P> GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 3, A, P > const &_xyz, \fBvec\fP< 1, B, P > const &_w)"
.br
.RI "Explicit conversions (From section 5\&.4\&.1 Conversion and scalar constructors of GLSL 1\&.30\&.08 specification) "
.ti -1c
.RI "template<typename A , typename B , qualifier P> GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (A _x, \fBvec\fP< 3, B, P > const &_yzw)"
.br
.RI "Explicit conversions (From section 5\&.4\&.1 Conversion and scalar constructors of GLSL 1\&.30\&.08 specification) "
.ti -1c
.RI "template<typename A , typename B , qualifier P> GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 1, A, P > const &_x, \fBvec\fP< 3, B, P > const &_yzw)"
.br
.RI "Explicit conversions (From section 5\&.4\&.1 Conversion and scalar constructors of GLSL 1\&.30\&.08 specification) "
.ti -1c
.RI "template<typename A , typename B , qualifier P> GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 2, A, P > const &_xy, \fBvec\fP< 2, B, P > const &_zw)"
.br
.RI "Explicit conversions (From section 5\&.4\&.1 Conversion and scalar constructors of GLSL 1\&.30\&.08 specification) "
.ti -1c
.RI "template<typename U , qualifier P> GLM_FUNC_DECL GLM_CONSTEXPR GLM_EXPLICIT \fBvec\fP (\fBvec\fP< 4, U, P > const &v)"
.br
.RI "Explicit conversions (From section 5\&.4\&.1 Conversion and scalar constructors of GLSL 1\&.30\&.08 specification) "
.ti -1c
.RI "GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator=\fP (\fBvec\fP< 4, T, Q > const &v) GLM_DEFAULT"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator=\fP (\fBvec\fP< 4, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator+=\fP (U scalar)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator+=\fP (\fBvec\fP< 1, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator+=\fP (\fBvec\fP< 4, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator\-=\fP (U scalar)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator\-=\fP (\fBvec\fP< 1, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator\-=\fP (\fBvec\fP< 4, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator *=\fP (U scalar)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator *=\fP (\fBvec\fP< 1, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator *=\fP (\fBvec\fP< 4, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator/=\fP (U scalar)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator/=\fP (\fBvec\fP< 1, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator/=\fP (\fBvec\fP< 4, U, Q > const &v)"
.br
.ti -1c
.RI "GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator++\fP ()"
.br
.ti -1c
.RI "GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator\-\-\fP ()"
.br
.ti -1c
.RI "GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > \fBoperator++\fP (int)"
.br
.ti -1c
.RI "GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > \fBoperator\-\-\fP (int)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator%=\fP (U scalar)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator%=\fP (\fBvec\fP< 1, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator%=\fP (\fBvec\fP< 4, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator&=\fP (U scalar)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator&=\fP (\fBvec\fP< 1, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator&=\fP (\fBvec\fP< 4, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator|=\fP (U scalar)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator|=\fP (\fBvec\fP< 1, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator|=\fP (\fBvec\fP< 4, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator^=\fP (U scalar)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator^=\fP (\fBvec\fP< 1, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator^=\fP (\fBvec\fP< 4, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator<<=\fP (U scalar)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator<<=\fP (\fBvec\fP< 1, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator<<=\fP (\fBvec\fP< 4, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator>>=\fP (U scalar)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator>>=\fP (\fBvec\fP< 1, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator>>=\fP (\fBvec\fP< 4, U, Q > const &v)"
.br
.ti -1c
.RI "template<qualifier P> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 4, T, P > const &v)"
.br
.ti -1c
.RI "template<typename U, qualifier P> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 1, U, P > const &v)"
.br
.ti -1c
.RI "template<typename X, typename Y, typename Z, typename W> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (X _x, Y _y, Z _z, W _w)"
.br
.ti -1c
.RI "template<typename X, typename Y, typename Z, typename W> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 1, X, Q > const &_x, Y _y, Z _z, W _w)"
.br
.ti -1c
.RI "template<typename X, typename Y, typename Z, typename W> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (X _x, \fBvec\fP< 1, Y, Q > const &_y, Z _z, W _w)"
.br
.ti -1c
.RI "template<typename X, typename Y, typename Z, typename W> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 1, X, Q > const &_x, \fBvec\fP< 1, Y, Q > const &_y, Z _z, W _w)"
.br
.ti -1c
.RI "template<typename X, typename Y, typename Z, typename W> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (X _x, Y _y, \fBvec\fP< 1, Z, Q > const &_z, W _w)"
.br
.ti -1c
.RI "template<typename X, typename Y, typename Z, typename W> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 1, X, Q > const &_x, Y _y, \fBvec\fP< 1, Z, Q > const &_z, W _w)"
.br
.ti -1c
.RI "template<typename X, typename Y, typename Z, typename W> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (X _x, \fBvec\fP< 1, Y, Q > const &_y, \fBvec\fP< 1, Z, Q > const &_z, W _w)"
.br
.ti -1c
.RI "template<typename X, typename Y, typename Z, typename W> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 1, X, Q > const &_x, \fBvec\fP< 1, Y, Q > const &_y, \fBvec\fP< 1, Z, Q > const &_z, W _w)"
.br
.ti -1c
.RI "template<typename X, typename Y, typename Z, typename W> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 1, X, Q > const &_x, Y _y, Z _z, \fBvec\fP< 1, W, Q > const &_w)"
.br
.ti -1c
.RI "template<typename X, typename Y, typename Z, typename W> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (X _x, \fBvec\fP< 1, Y, Q > const &_y, Z _z, \fBvec\fP< 1, W, Q > const &_w)"
.br
.ti -1c
.RI "template<typename X, typename Y, typename Z, typename W> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 1, X, Q > const &_x, \fBvec\fP< 1, Y, Q > const &_y, Z _z, \fBvec\fP< 1, W, Q > const &_w)"
.br
.ti -1c
.RI "template<typename X, typename Y, typename Z, typename W> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (X _x, Y _y, \fBvec\fP< 1, Z, Q > const &_z, \fBvec\fP< 1, W, Q > const &_w)"
.br
.ti -1c
.RI "template<typename X, typename Y, typename Z, typename W> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 1, X, Q > const &_x, Y _y, \fBvec\fP< 1, Z, Q > const &_z, \fBvec\fP< 1, W, Q > const &_w)"
.br
.ti -1c
.RI "template<typename X, typename Y, typename Z, typename W> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (X _x, \fBvec\fP< 1, Y, Q > const &_y, \fBvec\fP< 1, Z, Q > const &_z, \fBvec\fP< 1, W, Q > const &_w)"
.br
.ti -1c
.RI "template<typename X, typename Y, typename Z, typename W> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 1, X, Q > const &_x, \fBvec\fP< 1, Y, Q > const &_y, \fBvec\fP< 1, Z, Q > const &_z, \fBvec\fP< 1, W, Q > const &_w)"
.br
.ti -1c
.RI "template<typename A, typename B, typename C, qualifier P> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 2, A, P > const &_xy, B _z, C _w)"
.br
.ti -1c
.RI "template<typename A, typename B, typename C, qualifier P> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 2, A, P > const &_xy, \fBvec\fP< 1, B, P > const &_z, C _w)"
.br
.ti -1c
.RI "template<typename A, typename B, typename C, qualifier P> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 2, A, P > const &_xy, B _z, \fBvec\fP< 1, C, P > const &_w)"
.br
.ti -1c
.RI "template<typename A, typename B, typename C, qualifier P> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 2, A, P > const &_xy, \fBvec\fP< 1, B, P > const &_z, \fBvec\fP< 1, C, P > const &_w)"
.br
.ti -1c
.RI "template<typename A, typename B, typename C, qualifier P> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (A _x, \fBvec\fP< 2, B, P > const &_yz, C _w)"
.br
.ti -1c
.RI "template<typename A, typename B, typename C, qualifier P> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 1, A, P > const &_x, \fBvec\fP< 2, B, P > const &_yz, C _w)"
.br
.ti -1c
.RI "template<typename A, typename B, typename C, qualifier P> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (A _x, \fBvec\fP< 2, B, P > const &_yz, \fBvec\fP< 1, C, P > const &_w)"
.br
.ti -1c
.RI "template<typename A, typename B, typename C, qualifier P> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 1, A, P > const &_x, \fBvec\fP< 2, B, P > const &_yz, \fBvec\fP< 1, C, P > const &_w)"
.br
.ti -1c
.RI "template<typename A, typename B, typename C, qualifier P> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (A _x, B _y, \fBvec\fP< 2, C, P > const &_zw)"
.br
.ti -1c
.RI "template<typename A, typename B, typename C, qualifier P> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 1, A, P > const &_x, B _y, \fBvec\fP< 2, C, P > const &_zw)"
.br
.ti -1c
.RI "template<typename A, typename B, typename C, qualifier P> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (A _x, \fBvec\fP< 1, B, P > const &_y, \fBvec\fP< 2, C, P > const &_zw)"
.br
.ti -1c
.RI "template<typename A, typename B, typename C, qualifier P> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 1, A, P > const &_x, \fBvec\fP< 1, B, P > const &_y, \fBvec\fP< 2, C, P > const &_zw)"
.br
.ti -1c
.RI "template<typename A, typename B, qualifier P> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 3, A, P > const &_xyz, B _w)"
.br
.ti -1c
.RI "template<typename A, typename B, qualifier P> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 3, A, P > const &_xyz, \fBvec\fP< 1, B, P > const &_w)"
.br
.ti -1c
.RI "template<typename A, typename B, qualifier P> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (A _x, \fBvec\fP< 3, B, P > const &_yzw)"
.br
.ti -1c
.RI "template<typename A, typename B, qualifier P> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 1, A, P > const &_x, \fBvec\fP< 3, B, P > const &_yzw)"
.br
.ti -1c
.RI "template<typename A, typename B, qualifier P> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 2, A, P > const &_xy, \fBvec\fP< 2, B, P > const &_zw)"
.br
.ti -1c
.RI "template<typename U, qualifier P> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP (\fBvec\fP< 4, U, P > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator=\fP (\fBvec\fP< 4, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator+=\fP (U scalar)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator+=\fP (\fBvec\fP< 1, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator+=\fP (\fBvec\fP< 4, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator\-=\fP (U scalar)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator\-=\fP (\fBvec\fP< 1, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator\-=\fP (\fBvec\fP< 4, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator *=\fP (U scalar)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator *=\fP (\fBvec\fP< 1, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator *=\fP (\fBvec\fP< 4, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator/=\fP (U scalar)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator/=\fP (\fBvec\fP< 1, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator/=\fP (\fBvec\fP< 4, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator%=\fP (U scalar)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator%=\fP (\fBvec\fP< 1, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator%=\fP (\fBvec\fP< 4, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator&=\fP (U scalar)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator&=\fP (\fBvec\fP< 1, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator&=\fP (\fBvec\fP< 4, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator|=\fP (U scalar)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator|=\fP (\fBvec\fP< 1, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator|=\fP (\fBvec\fP< 4, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator^=\fP (U scalar)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator^=\fP (\fBvec\fP< 1, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator^=\fP (\fBvec\fP< 4, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator<<=\fP (U scalar)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator<<=\fP (\fBvec\fP< 1, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator<<=\fP (\fBvec\fP< 4, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator>>=\fP (U scalar)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator>>=\fP (\fBvec\fP< 1, U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBvec\fP< 4, T, Q > & \fBoperator>>=\fP (\fBvec\fP< 4, U, Q > const &v)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static GLM_FUNC_DECL GLM_CONSTEXPR length_type \fBlength\fP ()"
.br
.RI "Return the count of components of the vector\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "union \fBglm::vec\fP< 4, T, Q >:: { \&.\&.\&. }  "
.br
.ti -1c
.RI "union \fBglm::vec\fP< 4, T, Q >:: { \&.\&.\&. }  "
.br
.ti -1c
.RI "union \fBglm::vec\fP< 4, T, Q >:: { \&.\&.\&. }  "
.br
.ti -1c
.RI "union \fBglm::vec\fP< 4, T, Q >:: { \&.\&.\&. }  "
.br
.ti -1c
.RI "T \fBx\fP"
.br
.ti -1c
.RI "T \fBr\fP"
.br
.ti -1c
.RI "T \fBs\fP"
.br
.ti -1c
.RI "T \fBy\fP"
.br
.ti -1c
.RI "T \fBg\fP"
.br
.ti -1c
.RI "T \fBt\fP"
.br
.ti -1c
.RI "T \fBz\fP"
.br
.ti -1c
.RI "T \fBb\fP"
.br
.ti -1c
.RI "T \fBp\fP"
.br
.ti -1c
.RI "T \fBw\fP"
.br
.ti -1c
.RI "T \fBa\fP"
.br
.ti -1c
.RI "T \fBq\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
