.TH "glm::detail::compute_vec4_shift_left< T, Q, IsInt, Size, Aligned >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::compute_vec4_shift_left< T, Q, IsInt, Size, Aligned >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "GLM_FUNC_QUALIFIER static GLM_CONSTEXPR \fBvec\fP< 4, T, Q > \fBcall\fP (\fBvec\fP< 4, T, Q > const &a, \fBvec\fP< 4, T, Q > const &b)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
