.TH "glm::detail::u9u9u9e5" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::u9u9u9e5
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint \fBx\fP: 9"
.br
.ti -1c
.RI "   uint \fBy\fP: 9"
.br
.ti -1c
.RI "   uint \fBz\fP: 9"
.br
.ti -1c
.RI "   uint \fBw\fP: 5"
.br
.ti -1c
.RI "} \fBdata\fP"
.br
.ti -1c
.RI "\fBuint32\fP \fBpack\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
