.TH "glm::detail::u3u3u2" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::u3u3u2
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint \fBx\fP: 3"
.br
.ti -1c
.RI "   uint \fBy\fP: 3"
.br
.ti -1c
.RI "   uint \fBz\fP: 2"
.br
.ti -1c
.RI "} \fBdata\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBpack\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
