.TH "glm::mat< 4, 3, T, Q >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::mat< 4, 3, T, Q >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBvec\fP< 3, T, Q > \fBcol_type\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, T, Q > \fBrow_type\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 4, 3, T, Q > \fBtype\fP"
.br
.ti -1c
.RI "typedef \fBmat\fP< 3, 4, T, Q > \fBtranspose_type\fP"
.br
.ti -1c
.RI "typedef T \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef length_t \fBlength_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "GLM_FUNC_DECL \fBcol_type\fP & \fBoperator[]\fP (length_type i)"
.br
.ti -1c
.RI "GLM_FUNC_DECL GLM_CONSTEXPR \fBcol_type\fP const  & \fBoperator[]\fP (length_type i) const"
.br
.ti -1c
.RI "template<qualifier P> GLM_FUNC_DECL GLM_CONSTEXPR \fBmat\fP (\fBmat\fP< 4, 3, T, P > const &m)"
.br
.ti -1c
.RI "GLM_FUNC_DECL GLM_CONSTEXPR \fBmat\fP (T const &x)"
.br
.ti -1c
.RI "GLM_FUNC_DECL GLM_CONSTEXPR \fBmat\fP (T const &x0, T const &y0, T const &z0, T const &x1, T const &y1, T const &z1, T const &x2, T const &y2, T const &z2, T const &x3, T const &y3, T const &z3)"
.br
.ti -1c
.RI "GLM_FUNC_DECL GLM_CONSTEXPR \fBmat\fP (\fBcol_type\fP const &v0, \fBcol_type\fP const &v1, \fBcol_type\fP const &v2, \fBcol_type\fP const &v3)"
.br
.ti -1c
.RI "template<typename X1 , typename Y1 , typename Z1 , typename X2 , typename Y2 , typename Z2 , typename X3 , typename Y3 , typename Z3 , typename X4 , typename Y4 , typename Z4 > GLM_FUNC_DECL GLM_CONSTEXPR \fBmat\fP (X1 const &x1, Y1 const &y1, Z1 const &z1, X2 const &x2, Y2 const &y2, Z2 const &z2, X3 const &x3, Y3 const &y3, Z3 const &z3, X4 const &x4, Y4 const &y4, Z4 const &z4)"
.br
.ti -1c
.RI "template<typename V1 , typename V2 , typename V3 , typename V4 > GLM_FUNC_DECL GLM_CONSTEXPR \fBmat\fP (\fBvec\fP< 3, V1, Q > const &v1, \fBvec\fP< 3, V2, Q > const &v2, \fBvec\fP< 3, V3, Q > const &v3, \fBvec\fP< 3, V4, Q > const &v4)"
.br
.ti -1c
.RI "template<typename U , qualifier P> GLM_FUNC_DECL GLM_EXPLICIT GLM_CONSTEXPR \fBmat\fP (\fBmat\fP< 4, 3, U, P > const &m)"
.br
.ti -1c
.RI "GLM_FUNC_DECL GLM_EXPLICIT GLM_CONSTEXPR \fBmat\fP (\fBmat\fP< 2, 2, T, Q > const &x)"
.br
.ti -1c
.RI "GLM_FUNC_DECL GLM_EXPLICIT GLM_CONSTEXPR \fBmat\fP (\fBmat\fP< 3, 3, T, Q > const &x)"
.br
.ti -1c
.RI "GLM_FUNC_DECL GLM_EXPLICIT GLM_CONSTEXPR \fBmat\fP (\fBmat\fP< 4, 4, T, Q > const &x)"
.br
.ti -1c
.RI "GLM_FUNC_DECL GLM_EXPLICIT GLM_CONSTEXPR \fBmat\fP (\fBmat\fP< 2, 3, T, Q > const &x)"
.br
.ti -1c
.RI "GLM_FUNC_DECL GLM_EXPLICIT GLM_CONSTEXPR \fBmat\fP (\fBmat\fP< 3, 2, T, Q > const &x)"
.br
.ti -1c
.RI "GLM_FUNC_DECL GLM_EXPLICIT GLM_CONSTEXPR \fBmat\fP (\fBmat\fP< 2, 4, T, Q > const &x)"
.br
.ti -1c
.RI "GLM_FUNC_DECL GLM_EXPLICIT GLM_CONSTEXPR \fBmat\fP (\fBmat\fP< 4, 2, T, Q > const &x)"
.br
.ti -1c
.RI "GLM_FUNC_DECL GLM_EXPLICIT GLM_CONSTEXPR \fBmat\fP (\fBmat\fP< 3, 4, T, Q > const &x)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBmat\fP< 4, 3, T, Q > & \fBoperator=\fP (\fBmat\fP< 4, 3, U, Q > const &m)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBmat\fP< 4, 3, T, Q > & \fBoperator+=\fP (U s)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBmat\fP< 4, 3, T, Q > & \fBoperator+=\fP (\fBmat\fP< 4, 3, U, Q > const &m)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBmat\fP< 4, 3, T, Q > & \fBoperator\-=\fP (U s)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBmat\fP< 4, 3, T, Q > & \fBoperator\-=\fP (\fBmat\fP< 4, 3, U, Q > const &m)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBmat\fP< 4, 3, T, Q > & \fBoperator *=\fP (U s)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBmat\fP< 4, 3, T, Q > & \fBoperator/=\fP (U s)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBmat\fP< 4, 3, T, Q > & \fBoperator++\fP ()"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBmat\fP< 4, 3, T, Q > & \fBoperator\-\-\fP ()"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBmat\fP< 4, 3, T, Q > \fBoperator++\fP (int)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBmat\fP< 4, 3, T, Q > \fBoperator\-\-\fP (int)"
.br
.ti -1c
.RI "template<qualifier P> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBmat\fP (\fBmat\fP< 4, 3, T, P > const &m)"
.br
.ti -1c
.RI "template<typename X0, typename Y0, typename Z0 , typename X1 , typename Y1 , typename Z1 , typename X2 , typename Y2 , typename Z2 , typename X3 , typename Y3 , typename Z3 > GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBmat\fP (X0 const &x0, Y0 const &y0, Z0 const &z0, X1 const &x1, Y1 const &y1, Z1 const &z1, X2 const &x2, Y2 const &y2, Z2 const &z2, X3 const &x3, Y3 const &y3, Z3 const &z3)"
.br
.ti -1c
.RI "template<typename V1, typename V2, typename V3 , typename V4 > GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBmat\fP (\fBvec\fP< 3, V1, Q > const &v1, \fBvec\fP< 3, V2, Q > const &v2, \fBvec\fP< 3, V3, Q > const &v3, \fBvec\fP< 3, V4, Q > const &v4)"
.br
.ti -1c
.RI "template<typename U, qualifier P> GLM_FUNC_QUALIFIER GLM_CONSTEXPR \fBmat\fP (\fBmat\fP< 4, 3, U, P > const &m)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBmat\fP< 4, 3, T, Q > & \fBoperator=\fP (\fBmat\fP< 4, 3, U, Q > const &m)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBmat\fP< 4, 3, T, Q > & \fBoperator+=\fP (U s)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBmat\fP< 4, 3, T, Q > & \fBoperator+=\fP (\fBmat\fP< 4, 3, U, Q > const &m)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBmat\fP< 4, 3, T, Q > & \fBoperator\-=\fP (U s)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBmat\fP< 4, 3, T, Q > & \fBoperator\-=\fP (\fBmat\fP< 4, 3, U, Q > const &m)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBmat\fP< 4, 3, T, Q > & \fBoperator *=\fP (U s)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBmat\fP< 4, 3, T, Q > & \fBoperator/=\fP (U s)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static GLM_FUNC_DECL GLM_CONSTEXPR length_type \fBlength\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
