.TH "glm::detail::compute_half< 4, Q >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::compute_half< 4, Q >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static GLM_FUNC_QUALIFIER \fBvec\fP< 4, \fBuint16\fP, Q > \fBpack\fP (\fBvec\fP< 4, float, Q > const &v)"
.br
.ti -1c
.RI "static GLM_FUNC_QUALIFIER \fBvec\fP< 4, float, Q > \fBunpack\fP (\fBvec\fP< 4, \fBuint16\fP, Q > const &v)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
