.TH "gtc" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtc \- Additional features not specified by GLSL specification\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBGLM_GTC_bitfield\fP"
.br
.ti -1c
.RI "\fBGLM_GTC_color_space\fP"
.br
.ti -1c
.RI "\fBGLM_GTC_constants\fP"
.br
.ti -1c
.RI "\fBGLM_GTC_epsilon\fP"
.br
.ti -1c
.RI "\fBGLM_GTC_integer\fP"
.br
.RI "Allow to perform bit operations on integer values\&. "
.ti -1c
.RI "\fBGLM_GTC_matrix_access\fP"
.br
.ti -1c
.RI "\fBGLM_GTC_matrix_integer\fP"
.br
.ti -1c
.RI "\fBGLM_GTC_matrix_inverse\fP"
.br
.ti -1c
.RI "\fBGLM_GTC_matrix_transform\fP"
.br
.ti -1c
.RI "\fBGLM_GTC_noise\fP"
.br
.ti -1c
.RI "\fBGLM_GTC_packing\fP"
.br
.ti -1c
.RI "\fBGLM_GTC_quaternion\fP"
.br
.ti -1c
.RI "\fBGLM_GTC_random\fP"
.br
.ti -1c
.RI "\fBGLM_GTC_reciprocal\fP"
.br
.ti -1c
.RI "\fBGLM_EXT_scalar_integer\fP"
.br
.ti -1c
.RI "\fBGLM_GTC_type_aligned\fP"
.br
.ti -1c
.RI "\fBGLM_GTC_type_precision\fP"
.br
.ti -1c
.RI "\fBGLM_GTC_type_ptr\fP"
.br
.ti -1c
.RI "\fBGLM_GTC_ulp\fP"
.br
.ti -1c
.RI "\fBGLM_GTC_vec1\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Additional features not specified by GLSL specification\&. 

GTC extensions aim to be stable with tests and documentation\&.
.PP
Even if it's highly unrecommended, it's possible to include all the extensions at once by including <\fBglm/ext\&.hpp\fP>\&. Otherwise, each extension needs to be included a specific file\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
