.TH "gtc_ulp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtc_ulp
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Include <\fBglm/gtc/ulp\&.hpp\fP> to use the features of this extension\&.
.PP
Allow the measurement of the accuracy of a function against a reference implementation\&. This extension works on floating-point data and provide results in ULP\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
