.TH "gtc_vec1" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtc_vec1
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Include <\fBglm/gtc/vec1\&.hpp\fP> to use the features of this extension\&.
.PP
Add vec1, ivec1, uvec1 and bvec1 types\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
