.TH "gtc_reciprocal" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtc_reciprocal
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::sec\fP (genType \fBangle\fP)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::csc\fP (genType \fBangle\fP)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::cot\fP (genType \fBangle\fP)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::asec\fP (genType x)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::acsc\fP (genType x)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::acot\fP (genType x)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::sech\fP (genType \fBangle\fP)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::csch\fP (genType \fBangle\fP)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::coth\fP (genType \fBangle\fP)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::asech\fP (genType x)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::acsch\fP (genType x)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::acoth\fP (genType x)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtc/reciprocal\&.hpp\fP> to use the features of this extension\&.
.PP
Define secant, cosecant and cotangent functions\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename genType > GLM_FUNC_DECL genType glm::acot (genType x)"
Inverse cotangent function\&.
.PP
\fBReturns:\fP
.RS 4
Return an angle expressed in radians\&. 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIgenType\fP Floating-point scalar or vector types\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_reciprocal\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::acoth (genType x)"
Inverse cotangent hyperbolic function\&.
.PP
\fBReturns:\fP
.RS 4
Return an angle expressed in radians\&. 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIgenType\fP Floating-point scalar or vector types\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_reciprocal\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::acsc (genType x)"
Inverse cosecant function\&.
.PP
\fBReturns:\fP
.RS 4
Return an angle expressed in radians\&. 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIgenType\fP Floating-point scalar or vector types\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_reciprocal\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::acsch (genType x)"
Inverse cosecant hyperbolic function\&.
.PP
\fBReturns:\fP
.RS 4
Return an angle expressed in radians\&. 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIgenType\fP Floating-point scalar or vector types\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_reciprocal\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::asec (genType x)"
Inverse secant function\&.
.PP
\fBReturns:\fP
.RS 4
Return an angle expressed in radians\&. 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIgenType\fP Floating-point scalar or vector types\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_reciprocal\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::asech (genType x)"
Inverse secant hyperbolic function\&.
.PP
\fBReturns:\fP
.RS 4
Return an angle expressed in radians\&. 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIgenType\fP Floating-point scalar or vector types\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_reciprocal\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::cot (genType angle)"
Cotangent function\&. adjacent / opposite or 1 / tan(x)
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIgenType\fP Floating-point scalar or vector types\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_reciprocal\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::coth (genType angle)"
Cotangent hyperbolic function\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIgenType\fP Floating-point scalar or vector types\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_reciprocal\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::csc (genType angle)"
Cosecant function\&. hypotenuse / opposite or 1 / sin(x)
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIgenType\fP Floating-point scalar or vector types\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_reciprocal\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::csch (genType angle)"
Cosecant hyperbolic function\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIgenType\fP Floating-point scalar or vector types\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_reciprocal\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::sec (genType angle)"
Secant function\&. hypotenuse / adjacent or 1 / cos(x)
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIgenType\fP Floating-point scalar or vector types\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_reciprocal\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::sech (genType angle)"
Secant hyperbolic function\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIgenType\fP Floating-point scalar or vector types\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_reciprocal\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
