.TH "gtc_noise" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtc_noise
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL T \fBglm::perlin\fP (\fBvec\fP< L, T, Q > const &p)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL T \fBglm::perlin\fP (\fBvec\fP< L, T, Q > const &p, \fBvec\fP< L, T, Q > const &rep)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL T \fBglm::simplex\fP (\fBvec\fP< L, T, Q > const &p)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtc/noise\&.hpp\fP> to use the features of this extension\&.
.PP
Defines 2D, 3D and 4D procedural noise functions Based on the work of Stefan Gustavson and Ashima Arts on 'webgl-noise': https://github.com/ashima/webgl-noise Following Stefan Gustavson's paper 'Simplex noise demystified': http://www.itn.liu.se/~stegu/simplexnoise/simplexnoise.pdf 
.SH "Function Documentation"
.PP 
.SS "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL T glm::perlin (\fBvec\fP< L, T, Q > const & p)"
Classic perlin noise\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_noise\fP 
.RE
.PP

.SS "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL T glm::perlin (\fBvec\fP< L, T, Q > const & p, \fBvec\fP< L, T, Q > const & rep)"
Periodic perlin noise\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_noise\fP 
.RE
.PP

.SS "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL T glm::simplex (\fBvec\fP< L, T, Q > const & p)"
Simplex noise\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_noise\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
