.TH "gtc_integer" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtc_integer \- Allow to perform bit operations on integer values\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genIUType > GLM_FUNC_DECL genIUType \fBglm::log2\fP (genIUType x)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP< L, int, Q > \fBglm::iround\fP (\fBvec\fP< L, T, Q > const &x)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP< L, uint, Q > \fBglm::uround\fP (\fBvec\fP< L, T, Q > const &x)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Allow to perform bit operations on integer values\&. 

Include <\fBglm/gtc/integer\&.hpp\fP> to use the features of this extension\&. 
.SH "Function Documentation"
.PP 
.SS "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP<L, int, Q> glm::iround (\fBvec\fP< L, T, Q > const & x)"
Returns a value equal to the nearest integer to x\&. The fraction 0\&.5 will round in a direction chosen by the implementation, presumably the direction that is fastest\&.
.PP
\fBParameters:\fP
.RS 4
\fIx\fP The values of the argument must be greater or equal to zero\&. 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP floating point scalar types\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fCGLSL round man page\fP 
.PP
\fBGLM_GTC_integer\fP 
.RE
.PP

.SS "template<typename genIUType > GLM_FUNC_DECL genIUType glm::log2 (genIUType x)"
Returns the log2 of x for integer values\&. Usefull to compute mipmap count from the texture size\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_integer\fP 
.RE
.PP

.SS "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP<L, uint, Q> glm::uround (\fBvec\fP< L, T, Q > const & x)"
Returns a value equal to the nearest integer to x\&. The fraction 0\&.5 will round in a direction chosen by the implementation, presumably the direction that is fastest\&.
.PP
\fBParameters:\fP
.RS 4
\fIx\fP The values of the argument must be greater or equal to zero\&. 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP floating point scalar types\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fCGLSL round man page\fP 
.PP
\fBGLM_GTC_integer\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
