.TH "gtc_color_space" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtc_color_space
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP< L, T, Q > \fBglm::convertLinearToSRGB\fP (\fBvec\fP< L, T, Q > const &ColorLinear)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP< L, T, Q > \fBglm::convertLinearToSRGB\fP (\fBvec\fP< L, T, Q > const &ColorLinear, T Gamma)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP< L, T, Q > \fBglm::convertSRGBToLinear\fP (\fBvec\fP< L, T, Q > const &ColorSRGB)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP< L, T, Q > \fBglm::convertSRGBToLinear\fP (\fBvec\fP< L, T, Q > const &ColorSRGB, T Gamma)"
.br
.RI "Convert a sRGB color to linear color using a custom gamma correction\&. "
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtc/color_space\&.hpp\fP> to use the features of this extension\&.
.PP
Allow to perform bit operations on integer values 
.SH "Function Documentation"
.PP 
.SS "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP<L, T, Q> glm::convertLinearToSRGB (\fBvec\fP< L, T, Q > const & ColorLinear)"
Convert a linear color to sRGB color using a standard gamma correction\&. IEC 61966-2-1:1999 / Rec\&. 709 specification https://www.w3.org/Graphics/Color/srgb 
.SS "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP<L, T, Q> glm::convertLinearToSRGB (\fBvec\fP< L, T, Q > const & ColorLinear, T Gamma)"
Convert a linear color to sRGB color using a custom gamma correction\&. IEC 61966-2-1:1999 / Rec\&. 709 specification https://www.w3.org/Graphics/Color/srgb 
.SS "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP<L, T, Q> glm::convertSRGBToLinear (\fBvec\fP< L, T, Q > const & ColorSRGB)"
Convert a sRGB color to linear color using a standard gamma correction\&. IEC 61966-2-1:1999 / Rec\&. 709 specification https://www.w3.org/Graphics/Color/srgb 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
