.TH "gtx_transform" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_transform
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP< 4, 4, T, Q > \fBglm::translate\fP (\fBvec\fP< 3, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP< 4, 4, T, Q > \fBglm::rotate\fP (T \fBangle\fP, \fBvec\fP< 3, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP< 4, 4, T, Q > \fBglm::scale\fP (\fBvec\fP< 3, T, Q > const &v)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/transform\&.hpp\fP> to use the features of this extension\&.
.PP
Add transformation matrices 
.SH "Function Documentation"
.PP 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP<4, 4, T, Q> glm::rotate (T angle, \fBvec\fP< 3, T, Q > const & v)"
Builds a rotation 4 * 4 matrix created from an axis of 3 scalars and an angle expressed in radians\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_transform\fP 
.PP
\fBGLM_GTX_transform\fP 
.RE
.PP

.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP<4, 4, T, Q> glm::scale (\fBvec\fP< 3, T, Q > const & v)"
Transforms a matrix with a scale 4 * 4 matrix created from a vector of 3 components\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_transform\fP 
.PP
\fBGLM_GTX_transform\fP 
.RE
.PP

.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP<4, 4, T, Q> glm::translate (\fBvec\fP< 3, T, Q > const & v)"
Transforms a matrix with a translation 4 * 4 matrix created from 3 scalars\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_transform\fP 
.PP
\fBGLM_GTX_transform\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
