.TH "gtx_io" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_io
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , qualifier Q> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, \fBqua\fP< T, Q > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , qualifier Q> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, \fBvec\fP< 1, T, Q > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , qualifier Q> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, \fBvec\fP< 2, T, Q > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , qualifier Q> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, \fBvec\fP< 3, T, Q > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , qualifier Q> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, \fBvec\fP< 4, T, Q > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , qualifier Q> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, \fBmat\fP< 2, 2, T, Q > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , qualifier Q> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, \fBmat\fP< 2, 3, T, Q > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , qualifier Q> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, \fBmat\fP< 2, 4, T, Q > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , qualifier Q> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, \fBmat\fP< 3, 2, T, Q > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , qualifier Q> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, \fBmat\fP< 3, 3, T, Q > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , qualifier Q> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, \fBmat\fP< 3, 4, T, Q > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , qualifier Q> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, \fBmat\fP< 4, 2, T, Q > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , qualifier Q> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, \fBmat\fP< 4, 3, T, Q > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , qualifier Q> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, \fBmat\fP< 4, 4, T, Q > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , qualifier Q> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, std::pair< \fBmat\fP< 4, 4, T, Q > const, \fBmat\fP< 4, 4, T, Q > const > const &)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/io\&.hpp\fP> to use the features of this extension\&.
.PP
std::[w]ostream support for glm types
.PP
std::[w]ostream support for glm types + qualifier/width/etc\&. manipulators based on howard hinnant's std::chrono io proposal [http://home.roadrunner.com/~hinnant/bloomington/chrono_io.html] 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
