.TH "gtx_string_cast" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_string_cast
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL std::string \fBglm::to_string\fP (genType const &x)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/string_cast\&.hpp\fP> to use the features of this extension\&.
.PP
Setup strings for GLM type values
.PP
This extension is not supported with CUDA 
.SH "Function Documentation"
.PP 
.SS "template<typename genType > GLM_FUNC_DECL std::string glm::to_string (genType const & x)"
Create a string from a GLM vector or matrix typed variable\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_string_cast\fP extension\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
