.TH "gtx_matrix_cross_product" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_matrix_cross_product
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP< 3, 3, T, Q > \fBglm::matrixCross3\fP (\fBvec\fP< 3, T, Q > const &x)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP< 4, 4, T, Q > \fBglm::matrixCross4\fP (\fBvec\fP< 3, T, Q > const &x)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/matrix_cross_product\&.hpp\fP> to use the features of this extension\&.
.PP
Build cross product matrices 
.SH "Function Documentation"
.PP 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP<3, 3, T, Q> glm::matrixCross3 (\fBvec\fP< 3, T, Q > const & x)"
Build a cross product matrix\&. From GLM_GTX_matrix_cross_product extension\&. 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP<4, 4, T, Q> glm::matrixCross4 (\fBvec\fP< 3, T, Q > const & x)"
Build a cross product matrix\&. From GLM_GTX_matrix_cross_product extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
