.TH "gtx_std_based_type" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_std_based_type
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBvec\fP< 1, std::size_t, defaultp > \fBglm::size1\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, std::size_t, defaultp > \fBglm::size2\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, std::size_t, defaultp > \fBglm::size3\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, std::size_t, defaultp > \fBglm::size4\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 1, std::size_t, defaultp > \fBglm::size1_t\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 2, std::size_t, defaultp > \fBglm::size2_t\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 3, std::size_t, defaultp > \fBglm::size3_t\fP"
.br
.ti -1c
.RI "typedef \fBvec\fP< 4, std::size_t, defaultp > \fBglm::size4_t\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/std_based_type\&.hpp\fP> to use the features of this extension\&.
.PP
Adds vector types based on STL value types\&. 
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBvec\fP<1, std::size_t, defaultp> \fBglm::size1\fP"
Vector type based of one std::size_t component\&. 
.PP
\fBSee also:\fP
.RS 4
GLM_GTX_std_based_type 
.RE
.PP

.SS "typedef \fBvec\fP<1, std::size_t, defaultp> \fBglm::size1_t\fP"
Vector type based of one std::size_t component\&. 
.PP
\fBSee also:\fP
.RS 4
GLM_GTX_std_based_type 
.RE
.PP

.SS "typedef \fBvec\fP<2, std::size_t, defaultp> \fBglm::size2\fP"
Vector type based of two std::size_t components\&. 
.PP
\fBSee also:\fP
.RS 4
GLM_GTX_std_based_type 
.RE
.PP

.SS "typedef \fBvec\fP<2, std::size_t, defaultp> \fBglm::size2_t\fP"
Vector type based of two std::size_t components\&. 
.PP
\fBSee also:\fP
.RS 4
GLM_GTX_std_based_type 
.RE
.PP

.SS "typedef \fBvec\fP<3, std::size_t, defaultp> \fBglm::size3\fP"
Vector type based of three std::size_t components\&. 
.PP
\fBSee also:\fP
.RS 4
GLM_GTX_std_based_type 
.RE
.PP

.SS "typedef \fBvec\fP<3, std::size_t, defaultp> \fBglm::size3_t\fP"
Vector type based of three std::size_t components\&. 
.PP
\fBSee also:\fP
.RS 4
GLM_GTX_std_based_type 
.RE
.PP

.SS "typedef \fBvec\fP<4, std::size_t, defaultp> \fBglm::size4\fP"
Vector type based of four std::size_t components\&. 
.PP
\fBSee also:\fP
.RS 4
GLM_GTX_std_based_type 
.RE
.PP

.SS "typedef \fBvec\fP<4, std::size_t, defaultp> \fBglm::size4_t\fP"
Vector type based of four std::size_t components\&. 
.PP
\fBSee also:\fP
.RS 4
GLM_GTX_std_based_type 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
