.TH "gtx_normal" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_normal
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP< 3, T, Q > \fBglm::triangleNormal\fP (\fBvec\fP< 3, T, Q > const &p1, \fBvec\fP< 3, T, Q > const &p2, \fBvec\fP< 3, T, Q > const &p3)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/normal\&.hpp\fP> to use the features of this extension\&.
.PP
Compute the normal of a triangle\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP<3, T, Q> glm::triangleNormal (\fBvec\fP< 3, T, Q > const & p1, \fBvec\fP< 3, T, Q > const & p2, \fBvec\fP< 3, T, Q > const & p3)"
Computes triangle normal from triangle points\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_normal\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
