.TH "gtx_polar_coordinates" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_polar_coordinates
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP< 3, T, Q > \fBglm::polar\fP (\fBvec\fP< 3, T, Q > const &\fBeuclidean\fP)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP< 3, T, Q > \fBglm::euclidean\fP (\fBvec\fP< 2, T, Q > const &\fBpolar\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/polar_coordinates\&.hpp\fP> to use the features of this extension\&.
.PP
Conversion from Euclidean space to polar space and revert\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP<3, T, Q> glm::euclidean (\fBvec\fP< 2, T, Q > const & polar)"
Convert Polar to Euclidean coordinates\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_polar_coordinates\fP 
.RE
.PP

.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP<3, T, Q> glm::polar (\fBvec\fP< 3, T, Q > const & euclidean)"
Convert Euclidean to Polar coordinates, x is the xz distance, y, the latitude and z the longitude\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_polar_coordinates\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
