.TH "gtx_matrix_transform_2d" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_matrix_transform_2d
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_QUALIFIER \fBmat\fP< 3, 3, T, Q > \fBglm::translate\fP (\fBmat\fP< 3, 3, T, Q > const &m, \fBvec\fP< 2, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_QUALIFIER \fBmat\fP< 3, 3, T, Q > \fBglm::rotate\fP (\fBmat\fP< 3, 3, T, Q > const &m, T \fBangle\fP)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_QUALIFIER \fBmat\fP< 3, 3, T, Q > \fBglm::scale\fP (\fBmat\fP< 3, 3, T, Q > const &m, \fBvec\fP< 2, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_QUALIFIER \fBmat\fP< 3, 3, T, Q > \fBglm::shearX\fP (\fBmat\fP< 3, 3, T, Q > const &m, T y)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_QUALIFIER \fBmat\fP< 3, 3, T, Q > \fBglm::shearY\fP (\fBmat\fP< 3, 3, T, Q > const &m, T x)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/matrix_transform_2d\&.hpp\fP> to use the features of this extension\&.
.PP
Defines functions that generate common 2d transformation matrices\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T , qualifier Q> GLM_FUNC_QUALIFIER \fBmat\fP< 3, 3, T, Q > glm::rotate (\fBmat\fP< 3, 3, T, Q > const & m, T angle)"
Builds a rotation 3 * 3 matrix created from an angle\&.
.PP
\fBParameters:\fP
.RS 4
\fIm\fP Input matrix multiplied by this translation matrix\&. 
.br
\fIangle\fP Rotation angle expressed in radians\&. 
.RE
.PP

.SS "template<typename T , qualifier Q> GLM_FUNC_QUALIFIER \fBmat\fP< 3, 3, T, Q > glm::scale (\fBmat\fP< 3, 3, T, Q > const & m, \fBvec\fP< 2, T, Q > const & v)"
Builds a scale 3 * 3 matrix created from a vector of 2 components\&.
.PP
\fBParameters:\fP
.RS 4
\fIm\fP Input matrix multiplied by this translation matrix\&. 
.br
\fIv\fP Coordinates of a scale vector\&. 
.RE
.PP

.SS "template<typename T , qualifier Q> GLM_FUNC_QUALIFIER \fBmat\fP< 3, 3, T, Q > glm::shearX (\fBmat\fP< 3, 3, T, Q > const & m, T y)"
Builds an horizontal (parallel to the x axis) shear 3 * 3 matrix\&.
.PP
\fBParameters:\fP
.RS 4
\fIm\fP Input matrix multiplied by this translation matrix\&. 
.br
\fIy\fP Shear factor\&. 
.RE
.PP

.SS "template<typename T , qualifier Q> GLM_FUNC_QUALIFIER \fBmat\fP< 3, 3, T, Q > glm::shearY (\fBmat\fP< 3, 3, T, Q > const & m, T x)"
Builds a vertical (parallel to the y axis) shear 3 * 3 matrix\&.
.PP
\fBParameters:\fP
.RS 4
\fIm\fP Input matrix multiplied by this translation matrix\&. 
.br
\fIx\fP Shear factor\&. 
.RE
.PP

.SS "template<typename T , qualifier Q> GLM_FUNC_QUALIFIER \fBmat\fP< 3, 3, T, Q > glm::translate (\fBmat\fP< 3, 3, T, Q > const & m, \fBvec\fP< 2, T, Q > const & v)"
Builds a translation 3 * 3 matrix created from a vector of 2 components\&.
.PP
\fBParameters:\fP
.RS 4
\fIm\fP Input matrix multiplied by this translation matrix\&. 
.br
\fIv\fP Coordinates of a translation vector\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
