.TH "gtx_closest_point" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_closest_point
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP< 3, T, Q > \fBglm::closestPointOnLine\fP (\fBvec\fP< 3, T, Q > const &point, \fBvec\fP< 3, T, Q > const &a, \fBvec\fP< 3, T, Q > const &b)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP< 2, T, Q > \fBglm::closestPointOnLine\fP (\fBvec\fP< 2, T, Q > const &point, \fBvec\fP< 2, T, Q > const &a, \fBvec\fP< 2, T, Q > const &b)"
.br
.RI "2d lines work as well "
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/closest_point\&.hpp\fP> to use the features of this extension\&.
.PP
Find the point on a straight line which is the closet of a point\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP<3, T, Q> glm::closestPointOnLine (\fBvec\fP< 3, T, Q > const & point, \fBvec\fP< 3, T, Q > const & a, \fBvec\fP< 3, T, Q > const & b)"
Find the point on a straight line which is the closet of a point\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_closest_point\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
