.TH "gtx_projection" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_projection
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::proj\fP (genType const &x, genType const &Normal)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/projection\&.hpp\fP> to use the features of this extension\&.
.PP
Projection of a vector to other one 
.SH "Function Documentation"
.PP 
.SS "template<typename genType > GLM_FUNC_DECL genType glm::proj (genType const & x, genType const & Normal)"
Projects x on Normal\&.
.PP
\fBParameters:\fP
.RS 4
\fIx\fP A vector to project 
.br
\fINormal\fP A normal that doesn't need to be of unit length\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_projection\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
