.TH "gtx_perpendicular" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_perpendicular
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::perp\fP (genType const &x, genType const &Normal)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/perpendicular\&.hpp\fP> to use the features of this extension\&.
.PP
Perpendicular of a vector from other one 
.SH "Function Documentation"
.PP 
.SS "template<typename genType > GLM_FUNC_DECL genType glm::perp (genType const & x, genType const & Normal)"
Projects x a perpendicular axis of Normal\&. From GLM_GTX_perpendicular extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
