.TH "gtx_matrix_interpolation" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_matrix_interpolation
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL void \fBglm::axisAngle\fP (\fBmat\fP< 4, 4, T, Q > const &Mat, \fBvec\fP< 3, T, Q > &Axis, T &Angle)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP< 4, 4, T, Q > \fBglm::axisAngleMatrix\fP (\fBvec\fP< 3, T, Q > const &Axis, T const Angle)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP< 4, 4, T, Q > \fBglm::extractMatrixRotation\fP (\fBmat\fP< 4, 4, T, Q > const &Mat)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP< 4, 4, T, Q > \fBglm::interpolate\fP (\fBmat\fP< 4, 4, T, Q > const &m1, \fBmat\fP< 4, 4, T, Q > const &m2, T const Delta)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/matrix_interpolation\&.hpp\fP> to use the features of this extension\&.
.PP
Allows to directly interpolate two matrices\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL void glm::axisAngle (\fBmat\fP< 4, 4, T, Q > const & Mat, \fBvec\fP< 3, T, Q > & Axis, T & Angle)"
Get the axis and angle of the rotation from a matrix\&. From GLM_GTX_matrix_interpolation extension\&. 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP<4, 4, T, Q> glm::axisAngleMatrix (\fBvec\fP< 3, T, Q > const & Axis, T const Angle)"
Build a matrix from axis and angle\&. From GLM_GTX_matrix_interpolation extension\&. 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP<4, 4, T, Q> glm::extractMatrixRotation (\fBmat\fP< 4, 4, T, Q > const & Mat)"
Extracts the rotation part of a matrix\&. From GLM_GTX_matrix_interpolation extension\&. 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP<4, 4, T, Q> glm::interpolate (\fBmat\fP< 4, 4, T, Q > const & m1, \fBmat\fP< 4, 4, T, Q > const & m2, T const Delta)"
Build a interpolation of 4 * 4 matrixes\&. From GLM_GTX_matrix_interpolation extension\&. Warning! works only with rotation and/or translation matrixes, scale will generate unexpected results\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
