.TH "gtx_bit" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_bit
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genIUType > GLM_FUNC_DECL genIUType \fBglm::highestBitValue\fP (genIUType Value)"
.br
.ti -1c
.RI "template<typename genIUType > GLM_FUNC_DECL genIUType \fBglm::lowestBitValue\fP (genIUType Value)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP< L, T, Q > \fBglm::highestBitValue\fP (\fBvec\fP< L, T, Q > const &value)"
.br
.ti -1c
.RI "template<typename genIUType > GLM_DEPRECATED GLM_FUNC_DECL genIUType \fBglm::powerOfTwoAbove\fP (genIUType Value)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_DEPRECATED GLM_FUNC_DECL \fBvec\fP< L, T, Q > \fBglm::powerOfTwoAbove\fP (\fBvec\fP< L, T, Q > const &value)"
.br
.ti -1c
.RI "template<typename genIUType > GLM_DEPRECATED GLM_FUNC_DECL genIUType \fBglm::powerOfTwoBelow\fP (genIUType Value)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_DEPRECATED GLM_FUNC_DECL \fBvec\fP< L, T, Q > \fBglm::powerOfTwoBelow\fP (\fBvec\fP< L, T, Q > const &value)"
.br
.ti -1c
.RI "template<typename genIUType > GLM_DEPRECATED GLM_FUNC_DECL genIUType \fBglm::powerOfTwoNearest\fP (genIUType Value)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_DEPRECATED GLM_FUNC_DECL \fBvec\fP< L, T, Q > \fBglm::powerOfTwoNearest\fP (\fBvec\fP< L, T, Q > const &value)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/bit\&.hpp\fP> to use the features of this extension\&.
.PP
Allow to perform bit operations on integer values 
.SH "Function Documentation"
.PP 
.SS "template<typename genIUType > GLM_FUNC_DECL genIUType glm::highestBitValue (genIUType Value)"

.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_bit\fP 
.RE
.PP

.SS "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP<L, T, Q> glm::highestBitValue (\fBvec\fP< L, T, Q > const & value)"
Find the highest bit set to 1 in a integer variable and return its value\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_bit\fP 
.RE
.PP

.SS "template<typename genIUType > GLM_FUNC_DECL genIUType glm::lowestBitValue (genIUType Value)"

.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_bit\fP 
.RE
.PP

.SS "template<typename genIUType > GLM_DEPRECATED GLM_FUNC_DECL genIUType glm::powerOfTwoAbove (genIUType Value)"
Return the power of two number which value is just higher the input value\&. Deprecated, use ceilPowerOfTwo from GTC_round instead
.PP
\fBSee also:\fP
.RS 4
\fBGLM_EXT_scalar_integer\fP 
.PP
\fBGLM_GTX_bit\fP 
.RE
.PP

.SS "template<length_t L, typename T , qualifier Q> GLM_DEPRECATED GLM_FUNC_DECL \fBvec\fP<L, T, Q> glm::powerOfTwoAbove (\fBvec\fP< L, T, Q > const & value)"
Return the power of two number which value is just higher the input value\&. Deprecated, use ceilPowerOfTwo from GTC_round instead
.PP
\fBSee also:\fP
.RS 4
\fBGLM_EXT_scalar_integer\fP 
.PP
\fBGLM_GTX_bit\fP 
.RE
.PP

.SS "template<typename genIUType > GLM_DEPRECATED GLM_FUNC_DECL genIUType glm::powerOfTwoBelow (genIUType Value)"
Return the power of two number which value is just lower the input value\&. Deprecated, use floorPowerOfTwo from GTC_round instead
.PP
\fBSee also:\fP
.RS 4
\fBGLM_EXT_scalar_integer\fP 
.PP
\fBGLM_GTX_bit\fP 
.RE
.PP

.SS "template<length_t L, typename T , qualifier Q> GLM_DEPRECATED GLM_FUNC_DECL \fBvec\fP<L, T, Q> glm::powerOfTwoBelow (\fBvec\fP< L, T, Q > const & value)"
Return the power of two number which value is just lower the input value\&. Deprecated, use floorPowerOfTwo from GTC_round instead
.PP
\fBSee also:\fP
.RS 4
\fBGLM_EXT_scalar_integer\fP 
.PP
\fBGLM_GTX_bit\fP 
.RE
.PP

.SS "template<typename genIUType > GLM_DEPRECATED GLM_FUNC_DECL genIUType glm::powerOfTwoNearest (genIUType Value)"
Return the power of two number which value is the closet to the input value\&. Deprecated, use roundPowerOfTwo from GTC_round instead
.PP
\fBSee also:\fP
.RS 4
\fBGLM_EXT_scalar_integer\fP 
.PP
\fBGLM_GTX_bit\fP 
.RE
.PP

.SS "template<length_t L, typename T , qualifier Q> GLM_DEPRECATED GLM_FUNC_DECL \fBvec\fP<L, T, Q> glm::powerOfTwoNearest (\fBvec\fP< L, T, Q > const & value)"
Return the power of two number which value is the closet to the input value\&. Deprecated, use roundPowerOfTwo from GTC_round instead
.PP
\fBSee also:\fP
.RS 4
\fBGLM_EXT_scalar_integer\fP 
.PP
\fBGLM_GTX_bit\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
