.TH "gtx_extend" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_extend
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::extend\fP (genType const &Origin, genType const &Source, typename genType::value_type const Length)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/extend\&.hpp\fP> to use the features of this extension\&.
.PP
Extend a position from a source to a position at a defined length\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename genType > GLM_FUNC_DECL genType glm::extend (genType const & Origin, genType const & Source, typename genType::value_type const Length)"
Extends of Length the Origin position using the (Source - Origin) direction\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_extend\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
