.TH "gtx_fast_exponential" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_fast_exponential
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::fastPow\fP (genType x, genType y)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP< L, T, Q > \fBglm::fastPow\fP (\fBvec\fP< L, T, Q > const &x, \fBvec\fP< L, T, Q > const &y)"
.br
.ti -1c
.RI "template<typename genTypeT , typename genTypeU > GLM_FUNC_DECL genTypeT \fBglm::fastPow\fP (genTypeT x, genTypeU y)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP< L, T, Q > \fBglm::fastPow\fP (\fBvec\fP< L, T, Q > const &x)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::fastExp\fP (T x)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP< L, T, Q > \fBglm::fastExp\fP (\fBvec\fP< L, T, Q > const &x)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::fastLog\fP (T x)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP< L, T, Q > \fBglm::fastLog\fP (\fBvec\fP< L, T, Q > const &x)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::fastExp2\fP (T x)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP< L, T, Q > \fBglm::fastExp2\fP (\fBvec\fP< L, T, Q > const &x)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::fastLog2\fP (T x)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP< L, T, Q > \fBglm::fastLog2\fP (\fBvec\fP< L, T, Q > const &x)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/fast_exponential\&.hpp\fP> to use the features of this extension\&.
.PP
Fast but less accurate implementations of exponential based functions\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T > GLM_FUNC_DECL T glm::fastExp (T x)"
Faster than the common exp function but less accurate\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_exponential\fP 
.RE
.PP

.SS "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP<L, T, Q> glm::fastExp (\fBvec\fP< L, T, Q > const & x)"
Faster than the common exp function but less accurate\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_exponential\fP 
.RE
.PP

.SS "template<typename T > GLM_FUNC_DECL T glm::fastExp2 (T x)"
Faster than the common exp2 function but less accurate\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_exponential\fP 
.RE
.PP

.SS "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP<L, T, Q> glm::fastExp2 (\fBvec\fP< L, T, Q > const & x)"
Faster than the common exp2 function but less accurate\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_exponential\fP 
.RE
.PP

.SS "template<typename T > GLM_FUNC_DECL T glm::fastLog (T x)"
Faster than the common log function but less accurate\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_exponential\fP 
.RE
.PP

.SS "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP<L, T, Q> glm::fastLog (\fBvec\fP< L, T, Q > const & x)"
Faster than the common exp2 function but less accurate\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_exponential\fP 
.RE
.PP

.SS "template<typename T > GLM_FUNC_DECL T glm::fastLog2 (T x)"
Faster than the common log2 function but less accurate\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_exponential\fP 
.RE
.PP

.SS "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP<L, T, Q> glm::fastLog2 (\fBvec\fP< L, T, Q > const & x)"
Faster than the common log2 function but less accurate\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_exponential\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::fastPow (genType x, genType y)"
Faster than the common pow function but less accurate\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_exponential\fP 
.RE
.PP

.SS "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP<L, T, Q> glm::fastPow (\fBvec\fP< L, T, Q > const & x, \fBvec\fP< L, T, Q > const & y)"
Faster than the common pow function but less accurate\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_exponential\fP 
.RE
.PP

.SS "template<typename genTypeT , typename genTypeU > GLM_FUNC_DECL genTypeT glm::fastPow (genTypeT x, genTypeU y)"
Faster than the common pow function but less accurate\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_exponential\fP 
.RE
.PP

.SS "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP<L, T, Q> glm::fastPow (\fBvec\fP< L, T, Q > const & x)"
Faster than the common pow function but less accurate\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_exponential\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
