.TH "gtx_intersect" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_intersect
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL bool \fBglm::intersectRayPlane\fP (genType const &orig, genType const &dir, genType const &planeOrig, genType const &planeNormal, typename genType::value_type &intersectionDistance)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL bool \fBglm::intersectRayTriangle\fP (\fBvec\fP< 3, T, Q > const &orig, \fBvec\fP< 3, T, Q > const &dir, \fBvec\fP< 3, T, Q > const &v0, \fBvec\fP< 3, T, Q > const &v1, \fBvec\fP< 3, T, Q > const &v2, \fBvec\fP< 2, T, Q > &baryPosition, T &distance)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL bool \fBglm::intersectLineTriangle\fP (genType const &orig, genType const &dir, genType const &vert0, genType const &vert1, genType const &vert2, genType &position)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL bool \fBglm::intersectRaySphere\fP (genType const &rayStarting, genType const &rayNormalizedDirection, genType const &sphereCenter, typename genType::value_type const sphereRadiusSquered, typename genType::value_type &intersectionDistance)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL bool \fBglm::intersectRaySphere\fP (genType const &rayStarting, genType const &rayNormalizedDirection, genType const &sphereCenter, const typename genType::value_type sphereRadius, genType &intersectionPosition, genType &intersectionNormal)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL bool \fBglm::intersectLineSphere\fP (genType const &point0, genType const &point1, genType const &sphereCenter, typename genType::value_type sphereRadius, genType &intersectionPosition1, genType &intersectionNormal1, genType &intersectionPosition2=genType(), genType &intersectionNormal2=genType())"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/intersect\&.hpp\fP> to use the features of this extension\&.
.PP
Add intersection functions 
.SH "Function Documentation"
.PP 
.SS "template<typename genType > GLM_FUNC_DECL bool glm::intersectLineSphere (genType const & point0, genType const & point1, genType const & sphereCenter, typename genType::value_type sphereRadius, genType & intersectionPosition1, genType & intersectionNormal1, genType & intersectionPosition2 = \fCgenType()\fP, genType & intersectionNormal2 = \fCgenType()\fP)"
Compute the intersection of a line and a sphere\&. From GLM_GTX_intersect extension 
.SS "template<typename genType > GLM_FUNC_DECL bool glm::intersectLineTriangle (genType const & orig, genType const & dir, genType const & vert0, genType const & vert1, genType const & vert2, genType & position)"
Compute the intersection of a line and a triangle\&. From GLM_GTX_intersect extension\&. 
.SS "template<typename genType > GLM_FUNC_DECL bool glm::intersectRayPlane (genType const & orig, genType const & dir, genType const & planeOrig, genType const & planeNormal, typename genType::value_type & intersectionDistance)"
Compute the intersection of a ray and a plane\&. Ray direction and plane normal must be unit length\&. From GLM_GTX_intersect extension\&. 
.SS "template<typename genType > GLM_FUNC_DECL bool glm::intersectRaySphere (genType const & rayStarting, genType const & rayNormalizedDirection, genType const & sphereCenter, typename genType::value_type const sphereRadiusSquered, typename genType::value_type & intersectionDistance)"
Compute the intersection distance of a ray and a sphere\&. The ray direction vector is unit length\&. From GLM_GTX_intersect extension\&. 
.SS "template<typename genType > GLM_FUNC_DECL bool glm::intersectRaySphere (genType const & rayStarting, genType const & rayNormalizedDirection, genType const & sphereCenter, const typename genType::value_type sphereRadius, genType & intersectionPosition, genType & intersectionNormal)"
Compute the intersection of a ray and a sphere\&. From GLM_GTX_intersect extension\&. 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL bool glm::intersectRayTriangle (\fBvec\fP< 3, T, Q > const & orig, \fBvec\fP< 3, T, Q > const & dir, \fBvec\fP< 3, T, Q > const & v0, \fBvec\fP< 3, T, Q > const & v1, \fBvec\fP< 3, T, Q > const & v2, \fBvec\fP< 2, T, Q > & baryPosition, T & distance)"
Compute the intersection of a ray and a triangle\&. Based om Tomas Möller implementation http://fileadmin.cs.lth.se/cs/Personal/Tomas_Akenine-Moller/raytri/ From GLM_GTX_intersect extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
