.TH "gtx_wrap" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_wrap
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::clamp\fP (genType const &Texcoord)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::repeat\fP (genType const &Texcoord)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::mirrorClamp\fP (genType const &Texcoord)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::mirrorRepeat\fP (genType const &Texcoord)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/wrap\&.hpp\fP> to use the features of this extension\&.
.PP
Wrapping mode of texture coordinates\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename genType > GLM_FUNC_DECL genType glm::clamp (genType const & Texcoord)"
Simulate GL_CLAMP OpenGL wrap mode 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_wrap\fP extension\&. 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::mirrorClamp (genType const & Texcoord)"
Simulate GL_MIRRORED_REPEAT OpenGL wrap mode 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_wrap\fP extension\&. 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::mirrorRepeat (genType const & Texcoord)"
Simulate GL_MIRROR_REPEAT OpenGL wrap mode 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_wrap\fP extension\&. 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::repeat (genType const & Texcoord)"
Simulate GL_REPEAT OpenGL wrap mode 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_wrap\fP extension\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
