.TH "gtx_matrix_major_storage" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_matrix_major_storage
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP< 2, 2, T, Q > \fBglm::rowMajor2\fP (\fBvec\fP< 2, T, Q > const &v1, \fBvec\fP< 2, T, Q > const &v2)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP< 2, 2, T, Q > \fBglm::rowMajor2\fP (\fBmat\fP< 2, 2, T, Q > const &m)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP< 3, 3, T, Q > \fBglm::rowMajor3\fP (\fBvec\fP< 3, T, Q > const &v1, \fBvec\fP< 3, T, Q > const &v2, \fBvec\fP< 3, T, Q > const &v3)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP< 3, 3, T, Q > \fBglm::rowMajor3\fP (\fBmat\fP< 3, 3, T, Q > const &m)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP< 4, 4, T, Q > \fBglm::rowMajor4\fP (\fBvec\fP< 4, T, Q > const &v1, \fBvec\fP< 4, T, Q > const &v2, \fBvec\fP< 4, T, Q > const &v3, \fBvec\fP< 4, T, Q > const &v4)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP< 4, 4, T, Q > \fBglm::rowMajor4\fP (\fBmat\fP< 4, 4, T, Q > const &m)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP< 2, 2, T, Q > \fBglm::colMajor2\fP (\fBvec\fP< 2, T, Q > const &v1, \fBvec\fP< 2, T, Q > const &v2)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP< 2, 2, T, Q > \fBglm::colMajor2\fP (\fBmat\fP< 2, 2, T, Q > const &m)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP< 3, 3, T, Q > \fBglm::colMajor3\fP (\fBvec\fP< 3, T, Q > const &v1, \fBvec\fP< 3, T, Q > const &v2, \fBvec\fP< 3, T, Q > const &v3)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP< 3, 3, T, Q > \fBglm::colMajor3\fP (\fBmat\fP< 3, 3, T, Q > const &m)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP< 4, 4, T, Q > \fBglm::colMajor4\fP (\fBvec\fP< 4, T, Q > const &v1, \fBvec\fP< 4, T, Q > const &v2, \fBvec\fP< 4, T, Q > const &v3, \fBvec\fP< 4, T, Q > const &v4)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP< 4, 4, T, Q > \fBglm::colMajor4\fP (\fBmat\fP< 4, 4, T, Q > const &m)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/matrix_major_storage\&.hpp\fP> to use the features of this extension\&.
.PP
Build matrices with specific matrix order, row or column 
.SH "Function Documentation"
.PP 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP<2, 2, T, Q> glm::colMajor2 (\fBvec\fP< 2, T, Q > const & v1, \fBvec\fP< 2, T, Q > const & v2)"
Build a column major matrix from column vectors\&. From GLM_GTX_matrix_major_storage extension\&. 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP<2, 2, T, Q> glm::colMajor2 (\fBmat\fP< 2, 2, T, Q > const & m)"
Build a column major matrix from other matrix\&. From GLM_GTX_matrix_major_storage extension\&. 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP<3, 3, T, Q> glm::colMajor3 (\fBvec\fP< 3, T, Q > const & v1, \fBvec\fP< 3, T, Q > const & v2, \fBvec\fP< 3, T, Q > const & v3)"
Build a column major matrix from column vectors\&. From GLM_GTX_matrix_major_storage extension\&. 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP<3, 3, T, Q> glm::colMajor3 (\fBmat\fP< 3, 3, T, Q > const & m)"
Build a column major matrix from other matrix\&. From GLM_GTX_matrix_major_storage extension\&. 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP<4, 4, T, Q> glm::colMajor4 (\fBvec\fP< 4, T, Q > const & v1, \fBvec\fP< 4, T, Q > const & v2, \fBvec\fP< 4, T, Q > const & v3, \fBvec\fP< 4, T, Q > const & v4)"
Build a column major matrix from column vectors\&. From GLM_GTX_matrix_major_storage extension\&. 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP<4, 4, T, Q> glm::colMajor4 (\fBmat\fP< 4, 4, T, Q > const & m)"
Build a column major matrix from other matrix\&. From GLM_GTX_matrix_major_storage extension\&. 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP<2, 2, T, Q> glm::rowMajor2 (\fBvec\fP< 2, T, Q > const & v1, \fBvec\fP< 2, T, Q > const & v2)"
Build a row major matrix from row vectors\&. From GLM_GTX_matrix_major_storage extension\&. 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP<2, 2, T, Q> glm::rowMajor2 (\fBmat\fP< 2, 2, T, Q > const & m)"
Build a row major matrix from other matrix\&. From GLM_GTX_matrix_major_storage extension\&. 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP<3, 3, T, Q> glm::rowMajor3 (\fBvec\fP< 3, T, Q > const & v1, \fBvec\fP< 3, T, Q > const & v2, \fBvec\fP< 3, T, Q > const & v3)"
Build a row major matrix from row vectors\&. From GLM_GTX_matrix_major_storage extension\&. 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP<3, 3, T, Q> glm::rowMajor3 (\fBmat\fP< 3, 3, T, Q > const & m)"
Build a row major matrix from other matrix\&. From GLM_GTX_matrix_major_storage extension\&. 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP<4, 4, T, Q> glm::rowMajor4 (\fBvec\fP< 4, T, Q > const & v1, \fBvec\fP< 4, T, Q > const & v2, \fBvec\fP< 4, T, Q > const & v3, \fBvec\fP< 4, T, Q > const & v4)"
Build a row major matrix from row vectors\&. From GLM_GTX_matrix_major_storage extension\&. 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP<4, 4, T, Q> glm::rowMajor4 (\fBmat\fP< 4, 4, T, Q > const & m)"
Build a row major matrix from other matrix\&. From GLM_GTX_matrix_major_storage extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
