.TH "gtx_normalize_dot" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_normalize_dot
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL T \fBglm::normalizeDot\fP (\fBvec\fP< L, T, Q > const &x, \fBvec\fP< L, T, Q > const &y)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL T \fBglm::fastNormalizeDot\fP (\fBvec\fP< L, T, Q > const &x, \fBvec\fP< L, T, Q > const &y)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <glm/gtx/normalized_dot\&.hpp> to use the features of this extension\&.
.PP
Dot product of vectors that need to be normalize with a single square root\&. 
.SH "Function Documentation"
.PP 
.SS "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL T glm::fastNormalizeDot (\fBvec\fP< L, T, Q > const & x, \fBvec\fP< L, T, Q > const & y)"
Normalize parameters and returns the dot product of x and y\&. Faster that dot(fastNormalize(x), fastNormalize(y))\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_normalize_dot\fP extension\&. 
.RE
.PP

.SS "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL T glm::normalizeDot (\fBvec\fP< L, T, Q > const & x, \fBvec\fP< L, T, Q > const & y)"
Normalize parameters and returns the dot product of x and y\&. It's faster that dot(normalize(x), normalize(y))\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_normalize_dot\fP extension\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
