.TH "gtx_transform2" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_transform2
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP< 3, 3, T, Q > \fBglm::shearX2D\fP (\fBmat\fP< 3, 3, T, Q > const &m, T y)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP< 3, 3, T, Q > \fBglm::shearY2D\fP (\fBmat\fP< 3, 3, T, Q > const &m, T x)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP< 4, 4, T, Q > \fBglm::shearX3D\fP (\fBmat\fP< 4, 4, T, Q > const &m, T y, T z)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP< 4, 4, T, Q > \fBglm::shearY3D\fP (\fBmat\fP< 4, 4, T, Q > const &m, T x, T z)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP< 4, 4, T, Q > \fBglm::shearZ3D\fP (\fBmat\fP< 4, 4, T, Q > const &m, T x, T y)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP< 3, 3, T, Q > \fBglm::proj2D\fP (\fBmat\fP< 3, 3, T, Q > const &m, \fBvec\fP< 3, T, Q > const &normal)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP< 4, 4, T, Q > \fBglm::proj3D\fP (\fBmat\fP< 4, 4, T, Q > const &m, \fBvec\fP< 3, T, Q > const &normal)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP< 4, 4, T, Q > \fBglm::scaleBias\fP (T \fBscale\fP, T bias)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP< 4, 4, T, Q > \fBglm::scaleBias\fP (\fBmat\fP< 4, 4, T, Q > const &m, T \fBscale\fP, T bias)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/transform2\&.hpp\fP> to use the features of this extension\&.
.PP
Add extra transformation matrices 
.SH "Function Documentation"
.PP 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP<3, 3, T, Q> glm::proj2D (\fBmat\fP< 3, 3, T, Q > const & m, \fBvec\fP< 3, T, Q > const & normal)"
Build planar projection matrix along normal axis\&. From GLM_GTX_transform2 extension\&. 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP<4, 4, T, Q> glm::proj3D (\fBmat\fP< 4, 4, T, Q > const & m, \fBvec\fP< 3, T, Q > const & normal)"
Build planar projection matrix along normal axis\&. From GLM_GTX_transform2 extension\&. 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP<4, 4, T, Q> glm::scaleBias (T scale, T bias)"
Build a scale bias matrix\&. From GLM_GTX_transform2 extension\&. 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP<4, 4, T, Q> glm::scaleBias (\fBmat\fP< 4, 4, T, Q > const & m, T scale, T bias)"
Build a scale bias matrix\&. From GLM_GTX_transform2 extension\&. 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP<3, 3, T, Q> glm::shearX2D (\fBmat\fP< 3, 3, T, Q > const & m, T y)"
Transforms a matrix with a shearing on X axis\&. From GLM_GTX_transform2 extension\&. 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP<4, 4, T, Q> glm::shearX3D (\fBmat\fP< 4, 4, T, Q > const & m, T y, T z)"
Transforms a matrix with a shearing on X axis From GLM_GTX_transform2 extension\&. 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP<3, 3, T, Q> glm::shearY2D (\fBmat\fP< 3, 3, T, Q > const & m, T x)"
Transforms a matrix with a shearing on Y axis\&. From GLM_GTX_transform2 extension\&. 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP<4, 4, T, Q> glm::shearY3D (\fBmat\fP< 4, 4, T, Q > const & m, T x, T z)"
Transforms a matrix with a shearing on Y axis\&. From GLM_GTX_transform2 extension\&. 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP<4, 4, T, Q> glm::shearZ3D (\fBmat\fP< 4, 4, T, Q > const & m, T x, T y)"
Transforms a matrix with a shearing on Z axis\&. From GLM_GTX_transform2 extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
