.TH "gtx_hash" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_hash \- Add std::hash support for glm types\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Add std::hash support for glm types\&. 

Include <\fBglm/gtx/hash\&.hpp\fP> to use the features of this extension\&.
.PP
Add std::hash support for glm types
.PP
\fBGLM_GTX_hash\fP
.PP
\fBSee also:\fP
.RS 4
\fBCore features\fP (dependence)
.RE
.PP
<glm/gtx/hash\&.inl> need to be included to use the features of this extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
