.TH "gtx_matrix_decompose" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_matrix_decompose
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL bool \fBglm::decompose\fP (\fBmat\fP< 4, 4, T, Q > const &modelMatrix, \fBvec\fP< 3, T, Q > &\fBscale\fP, \fBqua\fP< T, Q > &\fBorientation\fP, \fBvec\fP< 3, T, Q > &translation, \fBvec\fP< 3, T, Q > &skew, \fBvec\fP< 4, T, Q > &\fBperspective\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/matrix_decompose\&.hpp\fP> to use the features of this extension\&.
.PP
Decomposes a model matrix to translations, rotation and scale components 
.SH "Function Documentation"
.PP 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL bool glm::decompose (\fBmat\fP< 4, 4, T, Q > const & modelMatrix, \fBvec\fP< 3, T, Q > & scale, \fBqua\fP< T, Q > & orientation, \fBvec\fP< 3, T, Q > & translation, \fBvec\fP< 3, T, Q > & skew, \fBvec\fP< 4, T, Q > & perspective)"
Decomposes a model matrix to translations, rotation and scale components 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_matrix_decompose\fP 
.RE
.PP
TODO: Fixme! 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
