.TH "gtx_raw_data" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_raw_data
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef detail::uint8 \fBglm::byte\fP"
.br
.ti -1c
.RI "typedef detail::uint16 \fBglm::word\fP"
.br
.ti -1c
.RI "typedef detail::uint32 \fBglm::dword\fP"
.br
.ti -1c
.RI "typedef detail::uint64 \fBglm::qword\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/raw_data\&.hpp\fP> to use the features of this extension\&.
.PP
Projection of a vector to other one 
.SH "Typedef Documentation"
.PP 
.SS "typedef detail::uint8 \fBglm::byte\fP"
Type for byte numbers\&. From GLM_GTX_raw_data extension\&. 
.SS "typedef detail::uint32 \fBglm::dword\fP"
Type for dword numbers\&. From GLM_GTX_raw_data extension\&. 
.SS "typedef detail::uint64 \fBglm::qword\fP"
Type for qword numbers\&. From GLM_GTX_raw_data extension\&. 
.SS "typedef detail::uint16 \fBglm::word\fP"
Type for word numbers\&. From GLM_GTX_raw_data extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
