.TH "gtx_orthonormalize" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_orthonormalize
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP< 3, 3, T, Q > \fBglm::orthonormalize\fP (\fBmat\fP< 3, 3, T, Q > const &m)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP< 3, T, Q > \fBglm::orthonormalize\fP (\fBvec\fP< 3, T, Q > const &x, \fBvec\fP< 3, T, Q > const &y)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/orthonormalize\&.hpp\fP> to use the features of this extension\&.
.PP
Orthonormalize matrices\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBmat\fP<3, 3, T, Q> glm::orthonormalize (\fBmat\fP< 3, 3, T, Q > const & m)"
Returns the orthonormalized matrix of m\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_orthonormalize\fP 
.RE
.PP

.SS "template<typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP<3, T, Q> glm::orthonormalize (\fBvec\fP< 3, T, Q > const & x, \fBvec\fP< 3, T, Q > const & y)"
Orthonormalizes x according y\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_orthonormalize\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
