.TH "gtx_exterior_product" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_exterior_product \- Allow to perform bit operations on integer values\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL T \fBglm::cross\fP (\fBvec\fP< 2, T, Q > const &v, \fBvec\fP< 2, T, Q > const &u)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Allow to perform bit operations on integer values\&. 

Include <\fBglm/gtx/exterior_product\&.hpp\fP> to use the features of this extension\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T , qualifier Q> GLM_FUNC_DECL T glm::cross (\fBvec\fP< 2, T, Q > const & v, \fBvec\fP< 2, T, Q > const & u)"
Returns the cross product of x and y\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP Floating-point scalar types 
.br
\fIQ\fP Value from qualifier enum
.RE
.PP
\fBSee also:\fP
.RS 4
\fCExterior product\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
