.TH "gtx_mixed_product" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_mixed_product
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL T \fBglm::mixedProduct\fP (\fBvec\fP< 3, T, Q > const &v1, \fBvec\fP< 3, T, Q > const &v2, \fBvec\fP< 3, T, Q > const &v3)"
.br
.RI "Mixed product of 3 vectors (from GLM_GTX_mixed_product extension) "
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/mixed_product\&.hpp\fP> to use the features of this extension\&.
.PP
Mixed product of 3 vectors\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
