.TH "gtx_component_wise" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_component_wise
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename floatType , length_t L, typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP< L, floatType, Q > \fBglm::compNormalize\fP (\fBvec\fP< L, T, Q > const &v)"
.br
.ti -1c
.RI "template<length_t L, typename T , typename floatType , qualifier Q> GLM_FUNC_DECL \fBvec\fP< L, T, Q > \fBglm::compScale\fP (\fBvec\fP< L, floatType, Q > const &v)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType::value_type \fBglm::compAdd\fP (genType const &v)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType::value_type \fBglm::compMul\fP (genType const &v)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType::value_type \fBglm::compMin\fP (genType const &v)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType::value_type \fBglm::compMax\fP (genType const &v)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include <\fBglm/gtx/component_wise\&.hpp\fP> to use the features of this extension\&.
.PP
Operations between components of a type 
.SH "Function Documentation"
.PP 
.SS "template<typename genType > GLM_FUNC_DECL genType::value_type glm::compAdd (genType const & v)"
Add all vector components together\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_component_wise\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType::value_type glm::compMax (genType const & v)"
Find the maximum value between single vector components\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_component_wise\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType::value_type glm::compMin (genType const & v)"
Find the minimum value between single vector components\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_component_wise\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType::value_type glm::compMul (genType const & v)"
Multiply all vector components together\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_component_wise\fP 
.RE
.PP

.SS "template<typename floatType , length_t L, typename T , qualifier Q> GLM_FUNC_DECL \fBvec\fP<L, floatType, Q> glm::compNormalize (\fBvec\fP< L, T, Q > const & v)"
Convert an integer vector to a normalized float vector\&. If the parameter value type is already a floating qualifier type, the value is passed through\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_component_wise\fP 
.RE
.PP

.SS "template<length_t L, typename T , typename floatType , qualifier Q> GLM_FUNC_DECL \fBvec\fP<L, T, Q> glm::compScale (\fBvec\fP< L, floatType, Q > const & v)"
Convert a normalized float vector to an integer vector\&. If the parameter value type is already a floating qualifier type, the value is passed through\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_component_wise\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
