.TH "hat_state" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hat_state \- Joystick hat states\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGLFW_HAT_CENTERED\fP   0"
.br
.ti -1c
.RI "#define \fBGLFW_HAT_UP\fP   1"
.br
.ti -1c
.RI "#define \fBGLFW_HAT_RIGHT\fP   2"
.br
.ti -1c
.RI "#define \fBGLFW_HAT_DOWN\fP   4"
.br
.ti -1c
.RI "#define \fBGLFW_HAT_LEFT\fP   8"
.br
.ti -1c
.RI "#define \fBGLFW_HAT_RIGHT_UP\fP   (GLFW_HAT_RIGHT | GLFW_HAT_UP)"
.br
.ti -1c
.RI "#define \fBGLFW_HAT_RIGHT_DOWN\fP   (GLFW_HAT_RIGHT | GLFW_HAT_DOWN)"
.br
.ti -1c
.RI "#define \fBGLFW_HAT_LEFT_UP\fP   (GLFW_HAT_LEFT  | GLFW_HAT_UP)"
.br
.ti -1c
.RI "#define \fBGLFW_HAT_LEFT_DOWN\fP   (GLFW_HAT_LEFT  | GLFW_HAT_DOWN)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Joystick hat states\&. 

See \fBjoystick hat input\fP for how these are used\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
