.TH "ieee_float_shape_type" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ieee_float_shape_type
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBvalue\fP"
.br
.ti -1c
.RI "unsigned int \fBword\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Copyright (C) 1993 by Sun Microsystems, Inc\&. All rights reserved\&.
.PP
Developed at SunPro, a Sun Microsystems, Inc\&. business\&. Permission to use, copy, modify, and distribute this software is freely granted, provided that this notice is preserved\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
