.TH "ImColor" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImColor
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImColor\fP (int r, int g, int b, int a=255)"
.br
.ti -1c
.RI "\fBImColor\fP (ImU32 rgba)"
.br
.ti -1c
.RI "\fBImColor\fP (float r, float g, float b, float a=1\&.0f)"
.br
.ti -1c
.RI "\fBImColor\fP (const \fBImVec4\fP &col)"
.br
.ti -1c
.RI "\fBoperator ImU32\fP () const"
.br
.ti -1c
.RI "\fBoperator ImVec4\fP () const"
.br
.ti -1c
.RI "void \fBSetHSV\fP (float h, float s, float v, float a=1\&.0f)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBImColor\fP \fBHSV\fP (float h, float s, float v, float a=1\&.0f)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImVec4\fP \fBValue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
