.TH "ImDrawListSharedData" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImDrawListSharedData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImVec2\fP \fBTexUvWhitePixel\fP"
.br
.ti -1c
.RI "\fBImFont\fP * \fBFont\fP"
.br
.ti -1c
.RI "float \fBFontSize\fP"
.br
.ti -1c
.RI "float \fBCurveTessellationTol\fP"
.br
.ti -1c
.RI "\fBImVec4\fP \fBClipRectFullscreen\fP"
.br
.ti -1c
.RI "ImDrawListFlags \fBInitialFlags\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBCircleVtx12\fP [12]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
