.TH "ImDrawCmd" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImDrawCmd
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBElemCount\fP"
.br
.ti -1c
.RI "\fBImVec4\fP \fBClipRect\fP"
.br
.ti -1c
.RI "ImTextureID \fBTextureId\fP"
.br
.ti -1c
.RI "unsigned int \fBVtxOffset\fP"
.br
.ti -1c
.RI "unsigned int \fBIdxOffset\fP"
.br
.ti -1c
.RI "ImDrawCallback \fBUserCallback\fP"
.br
.ti -1c
.RI "void * \fBUserCallbackData\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
