.TH "ImFontConfig" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImFontConfig
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBFontData\fP"
.br
.ti -1c
.RI "int \fBFontDataSize\fP"
.br
.ti -1c
.RI "bool \fBFontDataOwnedByAtlas\fP"
.br
.ti -1c
.RI "int \fBFontNo\fP"
.br
.ti -1c
.RI "float \fBSizePixels\fP"
.br
.ti -1c
.RI "int \fBOversampleH\fP"
.br
.ti -1c
.RI "int \fBOversampleV\fP"
.br
.ti -1c
.RI "bool \fBPixelSnapH\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBGlyphExtraSpacing\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBGlyphOffset\fP"
.br
.ti -1c
.RI "const ImWchar * \fBGlyphRanges\fP"
.br
.ti -1c
.RI "float \fBGlyphMinAdvanceX\fP"
.br
.ti -1c
.RI "float \fBGlyphMaxAdvanceX\fP"
.br
.ti -1c
.RI "bool \fBMergeMode\fP"
.br
.ti -1c
.RI "unsigned int \fBRasterizerFlags\fP"
.br
.ti -1c
.RI "float \fBRasterizerMultiply\fP"
.br
.ti -1c
.RI "char \fBName\fP [40]"
.br
.ti -1c
.RI "\fBImFont\fP * \fBDstFont\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
