.TH "ImFontAtlas::CustomRect" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImFontAtlas::CustomRect
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBIsPacked\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBID\fP"
.br
.ti -1c
.RI "unsigned short \fBWidth\fP"
.br
.ti -1c
.RI "unsigned short \fBHeight\fP"
.br
.ti -1c
.RI "unsigned short \fBX\fP"
.br
.ti -1c
.RI "unsigned short \fBY\fP"
.br
.ti -1c
.RI "float \fBGlyphAdvanceX\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBGlyphOffset\fP"
.br
.ti -1c
.RI "\fBImFont\fP * \fBFont\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
