.TH "ImFontBuildDstDataFT" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImFontBuildDstDataFT
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBSrcCount\fP"
.br
.ti -1c
.RI "int \fBGlyphsHighest\fP"
.br
.ti -1c
.RI "int \fBGlyphsCount\fP"
.br
.ti -1c
.RI "\fBImBoolVector\fP \fBGlyphsSet\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
