.TH "ImGuiViewport" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiViewport
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBImGuiViewportP\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImGuiID \fBID\fP"
.br
.ti -1c
.RI "ImGuiViewportFlags \fBFlags\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBPos\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBSize\fP"
.br
.ti -1c
.RI "float \fBDpiScale\fP"
.br
.ti -1c
.RI "\fBImDrawData\fP * \fBDrawData\fP"
.br
.ti -1c
.RI "ImGuiID \fBParentViewportId\fP"
.br
.ti -1c
.RI "void * \fBRendererUserData\fP"
.br
.ti -1c
.RI "void * \fBPlatformUserData\fP"
.br
.ti -1c
.RI "void * \fBPlatformHandle\fP"
.br
.ti -1c
.RI "void * \fBPlatformHandleRaw\fP"
.br
.ti -1c
.RI "bool \fBPlatformRequestClose\fP"
.br
.ti -1c
.RI "bool \fBPlatformRequestMove\fP"
.br
.ti -1c
.RI "bool \fBPlatformRequestResize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
