.TH "ImGuiTextFilter" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiTextFilter
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBTextRange\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "IMGUI_API \fBImGuiTextFilter\fP (const char *default_filter='')"
.br
.ti -1c
.RI "IMGUI_API bool \fBDraw\fP (const char *label='Filter (inc,\-exc)', float width=0\&.0f)"
.br
.ti -1c
.RI "IMGUI_API bool \fBPassFilter\fP (const char *text, const char *text_end=NULL) const"
.br
.ti -1c
.RI "IMGUI_API void \fBBuild\fP ()"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "bool \fBIsActive\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBInputBuf\fP [256]"
.br
.ti -1c
.RI "\fBImVector\fP< \fBTextRange\fP > \fBFilters\fP"
.br
.ti -1c
.RI "int \fBCountGrep\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
