.TH "ImGuiColumns" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiColumns
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBClear\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImGuiID \fBID\fP"
.br
.ti -1c
.RI "ImGuiColumnsFlags \fBFlags\fP"
.br
.ti -1c
.RI "bool \fBIsFirstFrame\fP"
.br
.ti -1c
.RI "bool \fBIsBeingResized\fP"
.br
.ti -1c
.RI "int \fBCurrent\fP"
.br
.ti -1c
.RI "int \fBCount\fP"
.br
.ti -1c
.RI "float \fBOffMinX\fP"
.br
.ti -1c
.RI "float \fBOffMaxX\fP"
.br
.ti -1c
.RI "float \fBLineMinY\fP"
.br
.ti -1c
.RI "float \fBLineMaxY\fP"
.br
.ti -1c
.RI "float \fBHostCursorPosY\fP"
.br
.ti -1c
.RI "float \fBHostCursorMaxPosX\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBHostClipRect\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBHostWorkRect\fP"
.br
.ti -1c
.RI "\fBImVector\fP< \fBImGuiColumnData\fP > \fBColumns\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
