.TH "ImGuiStyle" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiStyle
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "IMGUI_API void \fBScaleAllSizes\fP (float scale_factor)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBAlpha\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBWindowPadding\fP"
.br
.ti -1c
.RI "float \fBWindowRounding\fP"
.br
.ti -1c
.RI "float \fBWindowBorderSize\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBWindowMinSize\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBWindowTitleAlign\fP"
.br
.ti -1c
.RI "ImGuiDir \fBWindowMenuButtonPosition\fP"
.br
.ti -1c
.RI "float \fBChildRounding\fP"
.br
.ti -1c
.RI "float \fBChildBorderSize\fP"
.br
.ti -1c
.RI "float \fBPopupRounding\fP"
.br
.ti -1c
.RI "float \fBPopupBorderSize\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBFramePadding\fP"
.br
.ti -1c
.RI "float \fBFrameRounding\fP"
.br
.ti -1c
.RI "float \fBFrameBorderSize\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBItemSpacing\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBItemInnerSpacing\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBTouchExtraPadding\fP"
.br
.ti -1c
.RI "float \fBIndentSpacing\fP"
.br
.ti -1c
.RI "float \fBColumnsMinSpacing\fP"
.br
.ti -1c
.RI "float \fBScrollbarSize\fP"
.br
.ti -1c
.RI "float \fBScrollbarRounding\fP"
.br
.ti -1c
.RI "float \fBGrabMinSize\fP"
.br
.ti -1c
.RI "float \fBGrabRounding\fP"
.br
.ti -1c
.RI "float \fBTabRounding\fP"
.br
.ti -1c
.RI "float \fBTabBorderSize\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBButtonTextAlign\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBSelectableTextAlign\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBDisplayWindowPadding\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBDisplaySafeAreaPadding\fP"
.br
.ti -1c
.RI "float \fBMouseCursorScale\fP"
.br
.ti -1c
.RI "bool \fBAntiAliasedLines\fP"
.br
.ti -1c
.RI "bool \fBAntiAliasedFill\fP"
.br
.ti -1c
.RI "float \fBCurveTessellationTol\fP"
.br
.ti -1c
.RI "\fBImVec4\fP \fBColors\fP [ImGuiCol_COUNT]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
