.TH "ImGui_ImplVulkanH_FrameRenderBuffers" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGui_ImplVulkanH_FrameRenderBuffers
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "VkDeviceMemory \fBVertexBufferMemory\fP"
.br
.ti -1c
.RI "VkDeviceMemory \fBIndexBufferMemory\fP"
.br
.ti -1c
.RI "VkDeviceSize \fBVertexBufferSize\fP"
.br
.ti -1c
.RI "VkDeviceSize \fBIndexBufferSize\fP"
.br
.ti -1c
.RI "VkBuffer \fBVertexBuffer\fP"
.br
.ti -1c
.RI "VkBuffer \fBIndexBuffer\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
