.TH "ImGuiWindowTempData" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiWindowTempData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImVec2\fP \fBCursorPos\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBCursorPosPrevLine\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBCursorStartPos\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBCursorMaxPos\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBCurrLineSize\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBPrevLineSize\fP"
.br
.ti -1c
.RI "float \fBCurrLineTextBaseOffset\fP"
.br
.ti -1c
.RI "float \fBPrevLineTextBaseOffset\fP"
.br
.ti -1c
.RI "int \fBTreeDepth\fP"
.br
.ti -1c
.RI "ImU32 \fBTreeStoreMayJumpToParentOnPop\fP"
.br
.ti -1c
.RI "ImGuiID \fBLastItemId\fP"
.br
.ti -1c
.RI "ImGuiItemStatusFlags \fBLastItemStatusFlags\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBLastItemRect\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBLastItemDisplayRect\fP"
.br
.ti -1c
.RI "ImGuiNavLayer \fBNavLayerCurrent\fP"
.br
.ti -1c
.RI "int \fBNavLayerCurrentMask\fP"
.br
.ti -1c
.RI "int \fBNavLayerActiveMask\fP"
.br
.ti -1c
.RI "int \fBNavLayerActiveMaskNext\fP"
.br
.ti -1c
.RI "bool \fBNavHideHighlightOneFrame\fP"
.br
.ti -1c
.RI "bool \fBNavHasScroll\fP"
.br
.ti -1c
.RI "bool \fBMenuBarAppending\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBMenuBarOffset\fP"
.br
.ti -1c
.RI "\fBImVector\fP< \fBImGuiWindow\fP * > \fBChildWindows\fP"
.br
.ti -1c
.RI "\fBImGuiStorage\fP * \fBStateStorage\fP"
.br
.ti -1c
.RI "ImGuiLayoutType \fBLayoutType\fP"
.br
.ti -1c
.RI "ImGuiLayoutType \fBParentLayoutType\fP"
.br
.ti -1c
.RI "int \fBFocusCounterAll\fP"
.br
.ti -1c
.RI "int \fBFocusCounterTab\fP"
.br
.ti -1c
.RI "ImGuiItemFlags \fBItemFlags\fP"
.br
.ti -1c
.RI "float \fBItemWidth\fP"
.br
.ti -1c
.RI "float \fBTextWrapPos\fP"
.br
.ti -1c
.RI "\fBImVector\fP< ImGuiItemFlags > \fBItemFlagsStack\fP"
.br
.ti -1c
.RI "\fBImVector\fP< float > \fBItemWidthStack\fP"
.br
.ti -1c
.RI "\fBImVector\fP< float > \fBTextWrapPosStack\fP"
.br
.ti -1c
.RI "\fBImVector\fP< \fBImGuiGroupData\fP > \fBGroupStack\fP"
.br
.ti -1c
.RI "short \fBStackSizesBackup\fP [6]"
.br
.ti -1c
.RI "\fBImVec1\fP \fBIndent\fP"
.br
.ti -1c
.RI "\fBImVec1\fP \fBGroupOffset\fP"
.br
.ti -1c
.RI "\fBImVec1\fP \fBColumnsOffset\fP"
.br
.ti -1c
.RI "\fBImGuiColumns\fP * \fBCurrentColumns\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
