.TH "ImGuiWindowSettings" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiWindowSettings
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBName\fP"
.br
.ti -1c
.RI "ImGuiID \fBID\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBPos\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBSize\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBViewportPos\fP"
.br
.ti -1c
.RI "ImGuiID \fBViewportId\fP"
.br
.ti -1c
.RI "ImGuiID \fBDockId\fP"
.br
.ti -1c
.RI "ImGuiID \fBClassId\fP"
.br
.ti -1c
.RI "short \fBDockOrder\fP"
.br
.ti -1c
.RI "bool \fBCollapsed\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
