.TH "ImGuiStyleVarInfo" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiStyleVarInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void * \fBGetVarPtr\fP (\fBImGuiStyle\fP *style) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImGuiDataType \fBType\fP"
.br
.ti -1c
.RI "ImU32 \fBCount\fP"
.br
.ti -1c
.RI "ImU32 \fBOffset\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
