.TH "ImGuiTabBarRef" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiTabBarRef
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiTabBarRef\fP (\fBImGuiTabBar\fP *ptr)"
.br
.ti -1c
.RI "\fBImGuiTabBarRef\fP (int index_in_main_pool)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiTabBar\fP * \fBPtr\fP"
.br
.ti -1c
.RI "int \fBIndexInMainPool\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
