.TH "ImGuiNextWindowData" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiNextWindowData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBClearFlags\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImGuiNextWindowDataFlags \fBFlags\fP"
.br
.ti -1c
.RI "ImGuiCond \fBPosCond\fP"
.br
.ti -1c
.RI "ImGuiCond \fBSizeCond\fP"
.br
.ti -1c
.RI "ImGuiCond \fBCollapsedCond\fP"
.br
.ti -1c
.RI "ImGuiCond \fBDockCond\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBPosVal\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBPosPivotVal\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBSizeVal\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBContentSizeVal\fP"
.br
.ti -1c
.RI "bool \fBPosUndock\fP"
.br
.ti -1c
.RI "bool \fBCollapsedVal\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBSizeConstraintRect\fP"
.br
.ti -1c
.RI "ImGuiSizeCallback \fBSizeCallback\fP"
.br
.ti -1c
.RI "void * \fBSizeCallbackUserData\fP"
.br
.ti -1c
.RI "float \fBBgAlphaVal\fP"
.br
.ti -1c
.RI "ImGuiID \fBViewportId\fP"
.br
.ti -1c
.RI "ImGuiID \fBDockId\fP"
.br
.ti -1c
.RI "\fBImGuiWindowClass\fP \fBWindowClass\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBMenuBarOffsetMinVal\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
