.TH "ImGuiViewportP" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiViewportP
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBImGuiViewport\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImRect\fP \fBGetRect\fP () const"
.br
.ti -1c
.RI "\fBImVec2\fP \fBGetCenter\fP () const"
.br
.ti -1c
.RI "void \fBClearRequestFlags\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBIdx\fP"
.br
.ti -1c
.RI "int \fBLastFrameActive\fP"
.br
.ti -1c
.RI "int \fBLastFrameDrawLists\fP [2]"
.br
.ti -1c
.RI "int \fBLastFrontMostStampCount\fP"
.br
.ti -1c
.RI "ImGuiID \fBLastNameHash\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBLastPos\fP"
.br
.ti -1c
.RI "float \fBAlpha\fP"
.br
.ti -1c
.RI "float \fBLastAlpha\fP"
.br
.ti -1c
.RI "short \fBPlatformMonitor\fP"
.br
.ti -1c
.RI "bool \fBPlatformWindowCreated\fP"
.br
.ti -1c
.RI "\fBImGuiWindow\fP * \fBWindow\fP"
.br
.ti -1c
.RI "\fBImDrawList\fP * \fBDrawLists\fP [2]"
.br
.ti -1c
.RI "\fBImDrawData\fP \fBDrawDataP\fP"
.br
.ti -1c
.RI "\fBImDrawDataBuilder\fP \fBDrawDataBuilder\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBLastPlatformPos\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBLastPlatformSize\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBLastRendererSize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
