.TH "ImGuiTabBar" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiTabBar
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBGetTabOrder\fP (const \fBImGuiTabItem\fP *tab) const"
.br
.ti -1c
.RI "const char * \fBGetTabName\fP (const \fBImGuiTabItem\fP *tab) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImVector\fP< \fBImGuiTabItem\fP > \fBTabs\fP"
.br
.ti -1c
.RI "ImGuiID \fBID\fP"
.br
.ti -1c
.RI "ImGuiID \fBSelectedTabId\fP"
.br
.ti -1c
.RI "ImGuiID \fBNextSelectedTabId\fP"
.br
.ti -1c
.RI "ImGuiID \fBVisibleTabId\fP"
.br
.ti -1c
.RI "int \fBCurrFrameVisible\fP"
.br
.ti -1c
.RI "int \fBPrevFrameVisible\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBBarRect\fP"
.br
.ti -1c
.RI "float \fBContentsHeight\fP"
.br
.ti -1c
.RI "float \fBOffsetMax\fP"
.br
.ti -1c
.RI "float \fBOffsetNextTab\fP"
.br
.ti -1c
.RI "float \fBScrollingAnim\fP"
.br
.ti -1c
.RI "float \fBScrollingTarget\fP"
.br
.ti -1c
.RI "float \fBScrollingTargetDistToVisibility\fP"
.br
.ti -1c
.RI "float \fBScrollingSpeed\fP"
.br
.ti -1c
.RI "ImGuiTabBarFlags \fBFlags\fP"
.br
.ti -1c
.RI "ImGuiID \fBReorderRequestTabId\fP"
.br
.ti -1c
.RI "int \fBReorderRequestDir\fP"
.br
.ti -1c
.RI "bool \fBWantLayout\fP"
.br
.ti -1c
.RI "bool \fBVisibleTabWasSubmitted\fP"
.br
.ti -1c
.RI "short \fBLastTabItemIdx\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBFramePadding\fP"
.br
.ti -1c
.RI "\fBImGuiTextBuffer\fP \fBTabsNames\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
