.TH "ImGuiWindow" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiWindow
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiWindow\fP (\fBImGuiContext\fP *\fBcontext\fP, const char *name)"
.br
.ti -1c
.RI "ImGuiID \fBGetID\fP (const char *str, const char *str_end=NULL)"
.br
.ti -1c
.RI "ImGuiID \fBGetID\fP (const void *ptr)"
.br
.ti -1c
.RI "ImGuiID \fBGetID\fP (int n)"
.br
.ti -1c
.RI "ImGuiID \fBGetIDNoKeepAlive\fP (const char *str, const char *str_end=NULL)"
.br
.ti -1c
.RI "ImGuiID \fBGetIDNoKeepAlive\fP (const void *ptr)"
.br
.ti -1c
.RI "ImGuiID \fBGetIDNoKeepAlive\fP (int n)"
.br
.ti -1c
.RI "ImGuiID \fBGetIDFromRectangle\fP (const \fBImRect\fP &r_abs)"
.br
.ti -1c
.RI "\fBImRect\fP \fBRect\fP () const"
.br
.ti -1c
.RI "float \fBCalcFontSize\fP () const"
.br
.ti -1c
.RI "float \fBTitleBarHeight\fP () const"
.br
.ti -1c
.RI "\fBImRect\fP \fBTitleBarRect\fP () const"
.br
.ti -1c
.RI "float \fBMenuBarHeight\fP () const"
.br
.ti -1c
.RI "\fBImRect\fP \fBMenuBarRect\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBName\fP"
.br
.ti -1c
.RI "ImGuiID \fBID\fP"
.br
.ti -1c
.RI "ImGuiWindowFlags \fBFlags\fP"
.br
.ti -1c
.RI "ImGuiWindowFlags \fBFlagsPreviousFrame\fP"
.br
.ti -1c
.RI "\fBImGuiWindowClass\fP \fBWindowClass\fP"
.br
.ti -1c
.RI "\fBImGuiViewportP\fP * \fBViewport\fP"
.br
.ti -1c
.RI "ImGuiID \fBViewportId\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBViewportPos\fP"
.br
.ti -1c
.RI "int \fBViewportAllowPlatformMonitorExtend\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBPos\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBSize\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBSizeFull\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBContentSize\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBContentSizeExplicit\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBWindowPadding\fP"
.br
.ti -1c
.RI "float \fBWindowRounding\fP"
.br
.ti -1c
.RI "float \fBWindowBorderSize\fP"
.br
.ti -1c
.RI "int \fBNameBufLen\fP"
.br
.ti -1c
.RI "ImGuiID \fBMoveId\fP"
.br
.ti -1c
.RI "ImGuiID \fBChildId\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBScroll\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBScrollMax\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBScrollTarget\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBScrollTargetCenterRatio\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBScrollbarSizes\fP"
.br
.ti -1c
.RI "bool \fBScrollbarX\fP"
.br
.ti -1c
.RI "bool \fBScrollbarY\fP"
.br
.ti -1c
.RI "bool \fBViewportOwned\fP"
.br
.ti -1c
.RI "bool \fBActive\fP"
.br
.ti -1c
.RI "bool \fBWasActive\fP"
.br
.ti -1c
.RI "bool \fBWriteAccessed\fP"
.br
.ti -1c
.RI "bool \fBCollapsed\fP"
.br
.ti -1c
.RI "bool \fBWantCollapseToggle\fP"
.br
.ti -1c
.RI "bool \fBSkipItems\fP"
.br
.ti -1c
.RI "bool \fBAppearing\fP"
.br
.ti -1c
.RI "bool \fBHidden\fP"
.br
.ti -1c
.RI "bool \fBHasCloseButton\fP"
.br
.ti -1c
.RI "signed char \fBResizeBorderHeld\fP"
.br
.ti -1c
.RI "short \fBBeginCount\fP"
.br
.ti -1c
.RI "short \fBBeginOrderWithinParent\fP"
.br
.ti -1c
.RI "short \fBBeginOrderWithinContext\fP"
.br
.ti -1c
.RI "ImGuiID \fBPopupId\fP"
.br
.ti -1c
.RI "int \fBAutoFitFramesX\fP"
.br
.ti -1c
.RI "int \fBAutoFitFramesY\fP"
.br
.ti -1c
.RI "bool \fBAutoFitOnlyGrows\fP"
.br
.ti -1c
.RI "int \fBAutoFitChildAxises\fP"
.br
.ti -1c
.RI "ImGuiDir \fBAutoPosLastDirection\fP"
.br
.ti -1c
.RI "int \fBHiddenFramesCanSkipItems\fP"
.br
.ti -1c
.RI "int \fBHiddenFramesCannotSkipItems\fP"
.br
.ti -1c
.RI "ImGuiCond \fBSetWindowPosAllowFlags\fP"
.br
.ti -1c
.RI "ImGuiCond \fBSetWindowSizeAllowFlags\fP"
.br
.ti -1c
.RI "ImGuiCond \fBSetWindowCollapsedAllowFlags\fP"
.br
.ti -1c
.RI "ImGuiCond \fBSetWindowDockAllowFlags\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBSetWindowPosVal\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBSetWindowPosPivot\fP"
.br
.ti -1c
.RI "\fBImGuiWindowTempData\fP \fBDC\fP"
.br
.ti -1c
.RI "\fBImVector\fP< ImGuiID > \fBIDStack\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBOuterRectClipped\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBInnerRect\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBInnerClipRect\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBWorkRect\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBClipRect\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBContentsRegionRect\fP"
.br
.ti -1c
.RI "\fBImVec2ih\fP \fBHitTestHoleSize\fP"
.br
.ti -1c
.RI "\fBImVec2ih\fP \fBHitTestHoleOffset\fP"
.br
.ti -1c
.RI "int \fBLastFrameActive\fP"
.br
.ti -1c
.RI "int \fBLastFrameJustFocused\fP"
.br
.ti -1c
.RI "float \fBItemWidthDefault\fP"
.br
.ti -1c
.RI "\fBImGuiMenuColumns\fP \fBMenuColumns\fP"
.br
.ti -1c
.RI "\fBImGuiStorage\fP \fBStateStorage\fP"
.br
.ti -1c
.RI "\fBImVector\fP< \fBImGuiColumns\fP > \fBColumnsStorage\fP"
.br
.ti -1c
.RI "float \fBFontWindowScale\fP"
.br
.ti -1c
.RI "float \fBFontDpiScale\fP"
.br
.ti -1c
.RI "int \fBSettingsIdx\fP"
.br
.ti -1c
.RI "\fBImDrawList\fP * \fBDrawList\fP"
.br
.ti -1c
.RI "\fBImDrawList\fP \fBDrawListInst\fP"
.br
.ti -1c
.RI "\fBImGuiWindow\fP * \fBParentWindow\fP"
.br
.ti -1c
.RI "\fBImGuiWindow\fP * \fBRootWindow\fP"
.br
.ti -1c
.RI "\fBImGuiWindow\fP * \fBRootWindowDockStop\fP"
.br
.ti -1c
.RI "\fBImGuiWindow\fP * \fBRootWindowForTitleBarHighlight\fP"
.br
.ti -1c
.RI "\fBImGuiWindow\fP * \fBRootWindowForNav\fP"
.br
.ti -1c
.RI "\fBImGuiWindow\fP * \fBNavLastChildNavWindow\fP"
.br
.ti -1c
.RI "ImGuiID \fBNavLastIds\fP [ImGuiNavLayer_COUNT]"
.br
.ti -1c
.RI "\fBImRect\fP \fBNavRectRel\fP [ImGuiNavLayer_COUNT]"
.br
.ti -1c
.RI "\fBImGuiDockNode\fP * \fBDockNode\fP"
.br
.ti -1c
.RI "\fBImGuiDockNode\fP * \fBDockNodeAsHost\fP"
.br
.ti -1c
.RI "ImGuiID \fBDockId\fP"
.br
.ti -1c
.RI "ImGuiItemStatusFlags \fBDockTabItemStatusFlags\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBDockTabItemRect\fP"
.br
.ti -1c
.RI "short \fBDockOrder\fP"
.br
.ti -1c
.RI "bool \fBDockIsActive\fP:1"
.br
.ti -1c
.RI "bool \fBDockTabIsVisible\fP:1"
.br
.ti -1c
.RI "bool \fBDockTabWantClose\fP:1"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
