.TH "ImGuiItemHoveredDataBackup" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiItemHoveredDataBackup
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBBackup\fP ()"
.br
.ti -1c
.RI "void \fBRestore\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImGuiID \fBLastItemId\fP"
.br
.ti -1c
.RI "ImGuiItemStatusFlags \fBLastItemStatusFlags\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBLastItemRect\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBLastItemDisplayRect\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
