.TH "ImGuiListClipper" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiListClipper
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiListClipper\fP (int items_count=\-1, float items_height=\-1\&.0f)"
.br
.ti -1c
.RI "IMGUI_API bool \fBStep\fP ()"
.br
.ti -1c
.RI "IMGUI_API void \fBBegin\fP (int items_count, float items_height=\-1\&.0f)"
.br
.ti -1c
.RI "IMGUI_API void \fBEnd\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBStartPosY\fP"
.br
.ti -1c
.RI "float \fBItemsHeight\fP"
.br
.ti -1c
.RI "int \fBItemsCount\fP"
.br
.ti -1c
.RI "int \fBStepNo\fP"
.br
.ti -1c
.RI "int \fBDisplayStart\fP"
.br
.ti -1c
.RI "int \fBDisplayEnd\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
