.TH "ImGuiPopupData" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiPopupData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImGuiID \fBPopupId\fP"
.br
.ti -1c
.RI "\fBImGuiWindow\fP * \fBWindow\fP"
.br
.ti -1c
.RI "\fBImGuiWindow\fP * \fBSourceWindow\fP"
.br
.ti -1c
.RI "int \fBOpenFrameCount\fP"
.br
.ti -1c
.RI "ImGuiID \fBOpenParentId\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBOpenPopupPos\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBOpenMousePos\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
