.TH "ImGui_ImplVulkan_InitInfo" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGui_ImplVulkan_InitInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "VkInstance \fBInstance\fP"
.br
.ti -1c
.RI "VkPhysicalDevice \fBPhysicalDevice\fP"
.br
.ti -1c
.RI "VkDevice \fBDevice\fP"
.br
.ti -1c
.RI "uint32_t \fBQueueFamily\fP"
.br
.ti -1c
.RI "VkQueue \fBQueue\fP"
.br
.ti -1c
.RI "VkPipelineCache \fBPipelineCache\fP"
.br
.ti -1c
.RI "VkDescriptorPool \fBDescriptorPool\fP"
.br
.ti -1c
.RI "uint32_t \fBMinImageCount\fP"
.br
.ti -1c
.RI "uint32_t \fBImageCount\fP"
.br
.ti -1c
.RI "const \fBVkAllocationCallbacks\fP * \fBAllocator\fP"
.br
.ti -1c
.RI "void(* \fBCheckVkResultFn\fP )(VkResult err)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
