.TH "ImGuiStorage::Pair" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiStorage::Pair
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPair\fP (ImGuiID _key, int _val_i)"
.br
.ti -1c
.RI "\fBPair\fP (ImGuiID _key, float _val_f)"
.br
.ti -1c
.RI "\fBPair\fP (ImGuiID _key, void *_val_p)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImGuiID \fBkey\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   int \fBval_i\fP"
.br
.ti -1c
.RI "   float \fBval_f\fP"
.br
.ti -1c
.RI "   void * \fBval_p\fP"
.br
.ti -1c
.RI "}; "
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
