.TH "ImGuiTextFilter::TextRange" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiTextFilter::TextRange
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextRange\fP (const char *_b, const char *_e)"
.br
.ti -1c
.RI "const char * \fBbegin\fP () const"
.br
.ti -1c
.RI "const char * \fBend\fP () const"
.br
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.ti -1c
.RI "IMGUI_API void \fBsplit\fP (char separator, \fBImVector\fP< \fBTextRange\fP > *out) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBb\fP"
.br
.ti -1c
.RI "const char * \fBe\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
