.TH "ImGuiDataTypeInfo" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiDataTypeInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBSize\fP"
.br
.ti -1c
.RI "const char * \fBPrintFmt\fP"
.br
.ti -1c
.RI "const char * \fBScanFmt\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
