.TH "ImGuiDockNodeSettings" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiDockNodeSettings
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImGuiID \fBID\fP"
.br
.ti -1c
.RI "ImGuiID \fBParentID\fP"
.br
.ti -1c
.RI "ImGuiID \fBSelectedTabID\fP"
.br
.ti -1c
.RI "signed char \fBSplitAxis\fP"
.br
.ti -1c
.RI "char \fBDepth\fP"
.br
.ti -1c
.RI "ImGuiDockNodeFlags \fBFlags\fP"
.br
.ti -1c
.RI "\fBImVec2ih\fP \fBPos\fP"
.br
.ti -1c
.RI "\fBImVec2ih\fP \fBSize\fP"
.br
.ti -1c
.RI "\fBImVec2ih\fP \fBSizeRef\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
