.TH "ImGui_ImplVulkanH_Window" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGui_ImplVulkanH_Window
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBWidth\fP"
.br
.ti -1c
.RI "int \fBHeight\fP"
.br
.ti -1c
.RI "VkSwapchainKHR \fBSwapchain\fP"
.br
.ti -1c
.RI "VkSurfaceKHR \fBSurface\fP"
.br
.ti -1c
.RI "\fBVkSurfaceFormatKHR\fP \fBSurfaceFormat\fP"
.br
.ti -1c
.RI "VkPresentModeKHR \fBPresentMode\fP"
.br
.ti -1c
.RI "VkRenderPass \fBRenderPass\fP"
.br
.ti -1c
.RI "bool \fBClearEnable\fP"
.br
.ti -1c
.RI "\fBVkClearValue\fP \fBClearValue\fP"
.br
.ti -1c
.RI "uint32_t \fBFrameIndex\fP"
.br
.ti -1c
.RI "uint32_t \fBImageCount\fP"
.br
.ti -1c
.RI "uint32_t \fBSemaphoreIndex\fP"
.br
.ti -1c
.RI "\fBImGui_ImplVulkanH_Frame\fP * \fBFrames\fP"
.br
.ti -1c
.RI "\fBImGui_ImplVulkanH_FrameSemaphores\fP * \fBFrameSemaphores\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
