.TH "ImGuiMenuColumns" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiMenuColumns
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdate\fP (int count, float spacing, bool clear)"
.br
.ti -1c
.RI "float \fBDeclColumns\fP (float w0, float w1, float w2)"
.br
.ti -1c
.RI "float \fBCalcExtraSpace\fP (float avail_w)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBSpacing\fP"
.br
.ti -1c
.RI "float \fBWidth\fP"
.br
.ti -1c
.RI "float \fBNextWidth\fP"
.br
.ti -1c
.RI "float \fBPos\fP [3]"
.br
.ti -1c
.RI "float \fBNextWidths\fP [3]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
