.TH "ImStb::StbTexteditRow" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImStb::StbTexteditRow
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx0\fP"
.br
.ti -1c
.RI "float \fBx1\fP"
.br
.ti -1c
.RI "float \fBbaseline_y_delta\fP"
.br
.ti -1c
.RI "float \fBymin\fP"
.br
.ti -1c
.RI "float \fBymax\fP"
.br
.ti -1c
.RI "int \fBnum_chars\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
