.TH "InputTextCallback_UserData" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InputTextCallback_UserData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string * \fBStr\fP"
.br
.ti -1c
.RI "ImGuiInputTextCallback \fBChainCallback\fP"
.br
.ti -1c
.RI "void * \fBChainCallbackUserData\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
