.TH "internal::named_arg_base< Char >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::named_arg_base< Char >
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBinternal::named_arg< T, Char >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBnamed_arg_base\fP (\fBbasic_string_view\fP< Char > nm)"
.br
.ti -1c
.RI "template<typename Context > \fBbasic_format_arg\fP< Context > \fBdeserialize\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbasic_string_view\fP< Char > \fBname\fP"
.br
.ti -1c
.RI "char \fBdata\fP [sizeof(\fBbasic_format_arg\fP< typename \fBbuffer_context\fP< Char >::type >)]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
