.TH "internal::add_thousands_sep< Char >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::add_thousands_sep< Char >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBsize\fP = 1 }"
.br
.ti -1c
.RI "typedef Char \fBchar_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBadd_thousands_sep\fP (\fBbasic_string_view\fP< Char > sep)"
.br
.ti -1c
.RI "void \fBoperator()\fP (Char *&\fBbuffer\fP)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
