.TH "Typhoon/ThirdParty/glm/glm/integer.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/integer.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'detail/qualifier\&.hpp'\fP
.br
\fC#include 'common\&.hpp'\fP
.br
\fC#include 'vector_relational\&.hpp'\fP
.br
\fC#include 'detail/func_integer\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<length_t L, qualifier Q> GLM_FUNC_DECL vec< L, uint, Q > \fBglm::uaddCarry\fP (vec< L, uint, Q > const &x, vec< L, uint, Q > const &y, vec< L, uint, Q > &carry)"
.br
.ti -1c
.RI "template<length_t L, qualifier Q> GLM_FUNC_DECL vec< L, uint, Q > \fBglm::usubBorrow\fP (vec< L, uint, Q > const &x, vec< L, uint, Q > const &y, vec< L, uint, Q > &borrow)"
.br
.ti -1c
.RI "template<length_t L, qualifier Q> GLM_FUNC_DECL void \fBglm::umulExtended\fP (vec< L, uint, Q > const &x, vec< L, uint, Q > const &y, vec< L, uint, Q > &msb, vec< L, uint, Q > &lsb)"
.br
.ti -1c
.RI "template<length_t L, qualifier Q> GLM_FUNC_DECL void \fBglm::imulExtended\fP (vec< L, int, Q > const &x, vec< L, int, Q > const &y, vec< L, int, Q > &msb, vec< L, int, Q > &lsb)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec< L, T, Q > \fBglm::bitfieldExtract\fP (vec< L, T, Q > const &Value, int Offset, int Bits)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec< L, T, Q > \fBglm::bitfieldInsert\fP (vec< L, T, Q > const &Base, vec< L, T, Q > const &Insert, int Offset, int Bits)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec< L, T, Q > \fBglm::bitfieldReverse\fP (vec< L, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL int \fBglm::bitCount\fP (genType v)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec< L, int, Q > \fBglm::bitCount\fP (vec< L, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename genIUType > GLM_FUNC_DECL int \fBglm::findLSB\fP (genIUType x)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec< L, int, Q > \fBglm::findLSB\fP (vec< L, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename genIUType > GLM_FUNC_DECL int \fBglm::findMSB\fP (genIUType x)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec< L, int, Q > \fBglm::findMSB\fP (vec< L, T, Q > const &v)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCore features\fP
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 8\&.8 Integer Functions\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
