.TH "internal::printf_precision_handler" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::printf_precision_handler
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBinternal::function< int >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T > std::enable_if< std::is_integral< T >::\fBvalue\fP, int >::type \fBoperator()\fP (T \fBvalue\fP)"
.br
.ti -1c
.RI "template<typename T > std::enable_if<!std::is_integral< T >::\fBvalue\fP, int >::type \fBoperator()\fP (T)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
