.TH "internal::specs_checker< Handler >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::specs_checker< Handler >
.SH SYNOPSIS
.br
.PP
.PP
Inherits Handler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "FMT_CONSTEXPR \fBspecs_checker\fP (const Handler &handler, internal::type arg_type)"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBspecs_checker\fP (const \fBspecs_checker\fP &other)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_align\fP (alignment align)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_plus\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_minus\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_space\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_hash\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_zero\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBend_precision\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
