.TH "internal::container_buffer< Container >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::container_buffer< Container >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBinternal::basic_buffer< Container::value_type >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcontainer_buffer\fP (Container &c)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBgrow\fP (std::size_t \fBcapacity\fP) FMT_OVERRIDE"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "template<typename Container> void \fBinternal::container_buffer\fP< Container >::grow (std::size_t capacity)\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"
Increases the buffer capacity to hold at least \fIcapacity\fP elements\&. 
.PP
Implements \fBinternal::basic_buffer< Container::value_type >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
