.TH "internals_guide" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internals_guide \- Internal structure 
There are several interfaces inside GLFW\&. Each interface has its own area of responsibility and its own naming conventions\&.
.SH "Public interface"
.PP
The most well-known is the public interface, described in the glfw3\&.h header file\&. This is implemented in source files shared by all platforms and these files contain no platform-specific code\&. This code usually ends up calling the platform and internal interfaces to do the actual work\&.
.PP
The public interface uses the OpenGL naming conventions except with GLFW and glfw instead of GL and gl\&. For struct members, where OpenGL sets no precedent, it use headless camel case\&.
.PP
Examples: \fCglfwCreateWindow\fP, \fCGLFWwindow\fP, \fCGLFW_RED_BITS\fP
.SH "Native interface"
.PP
The \fBnative interface\fP is a small set of publicly available but platform-specific functions, described in the glfw3native\&.h header file and used to gain access to the underlying window, context and (on some platforms) display handles used by the platform interface\&.
.PP
The function names of the native interface are similar to those of the public interface, but embeds the name of the interface that the returned handle is from\&.
.PP
Examples: \fCglfwGetX11Window\fP, \fCglfwGetWGLContext\fP
.SH "Internal interface"
.PP
The internal interface consists of utility functions used by all other interfaces\&. It is shared code implemented in the same shared source files as the public and event interfaces\&. The internal interface is described in the \fBinternal\&.h\fP header file\&.
.PP
The internal interface is in charge of GLFW's global data, which it stores in a \fC\fB_GLFWlibrary\fP\fP struct named \fC_glfw\fP\&.
.PP
The internal interface uses the same style as the public interface, except all global names have a leading underscore\&.
.PP
Examples: \fC_glfwIsValidContextConfig\fP, \fC\fB_GLFWwindow\fP\fP, \fC_glfw\&.monitorCount\fP
.SH "Platform interface"
.PP
The platform interface implements all platform-specific operations as a service to the public interface\&. This includes event processing\&. The platform interface is never directly called by application code and never directly calls application-provided callbacks\&. It is also prohibited from modifying the platform-independent part of the internal structs\&. Instead, it calls the event interface when events interesting to GLFW are received\&.
.PP
The platform interface mirrors those parts of the public interface that needs to perform platform-specific operations on some or all platforms\&. The are also named the same except that the glfw function prefix is replaced by _glfwPlatform\&.
.PP
Examples: \fC_glfwPlatformCreateWindow\fP
.PP
The platform interface also defines structs that contain platform-specific global and per-object state\&. Their names mirror those of the internal interface, except that an interface-specific suffix is added\&.
.PP
Examples: \fC\fB_GLFWwindowX11\fP\fP, \fC\fB_GLFWcontextWGL\fP\fP
.PP
These structs are incorporated as members into the internal interface structs using special macros that name them after the specific interface used\&. This prevents shared code from accidentally using these members\&.
.PP
Examples: \fCwindow->win32\&.handle\fP, \fC_glfw\&.x11\&.display\fP
.SH "Event interface"
.PP
The event interface is implemented in the same shared source files as the public interface and is responsible for delivering the events it receives to the application, either via callbacks, via window state changes or both\&.
.PP
The function names of the event interface use a \fC_glfwInput\fP prefix and the ObjectEvent pattern\&.
.PP
Examples: \fC_glfwInputWindowFocus\fP, \fC_glfwInputCursorPos\fP
.SH "Static functions"
.PP
Static functions may be used by any interface and have no prefixes or suffixes\&. These use headless camel case\&.
.PP
Examples: \fCisValidElementForJoystick\fP
.SH "Configuration macros"
.PP
GLFW uses a number of configuration macros to select at compile time which interfaces and code paths to use\&. They are defined in the glfw_config\&.h header file, which is generated from the \fCglfw_config\&.h\&.in\fP file by CMake\&.
.PP
Configuration macros the same style as tokens in the public interface, except with a leading underscore\&.
.PP
Examples: \fC_GLFW_WIN32\fP, \fC_GLFW_BUILD_DLL\fP 
