.TH "internal::fp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::fp
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBfp\fP (uint64_t f_val, int e_val)"
.br
.ti -1c
.RI "template<typename Double > \fBfp\fP (Double d)"
.br
.ti -1c
.RI "template<int SHIFT = 0> void \fBnormalize\fP ()"
.br
.ti -1c
.RI "void \fBcompute_boundaries\fP (\fBfp\fP &lower, \fBfp\fP &upper) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "significand_type \fBf\fP"
.br
.ti -1c
.RI "int \fBe\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static FMT_CONSTEXPR_DECL const int \fBsignificand_size\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "FMT_CONSTEXPR_DECL const int internal::fp::significand_size\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=
    sizeof(significand_type) * char_size
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
