.TH "internal::specs_setter< Char >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::specs_setter< Char >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "FMT_CONSTEXPR \fBspecs_setter\fP (\fBbasic_format_specs\fP< Char > &specs)"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBspecs_setter\fP (const \fBspecs_setter\fP &other)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_align\fP (alignment align)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_fill\fP (Char \fBfill\fP)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_plus\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_minus\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_space\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_hash\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_zero\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_width\fP (unsigned width)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_precision\fP (unsigned precision)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBend_precision\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_type\fP (Char type)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBbasic_format_specs\fP< Char > & \fBspecs_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
