.TH "internal::int_checker< true >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::int_checker< true >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T > static bool \fBfits_in_int\fP (T \fBvalue\fP)"
.br
.ti -1c
.RI "static bool \fBfits_in_int\fP (int)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
