.TH "internal::dynamic_specs_handler< ParseContext >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::dynamic_specs_handler< ParseContext >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBinternal::specs_setter< ParseContext::char_type >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef ParseContext::char_type \fBchar_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "FMT_CONSTEXPR \fBdynamic_specs_handler\fP (\fBdynamic_format_specs\fP< char_type > &specs, ParseContext &ctx)"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBdynamic_specs_handler\fP (const \fBdynamic_specs_handler\fP &other)"
.br
.ti -1c
.RI "template<typename Id > FMT_CONSTEXPR void \fBon_dynamic_width\fP (Id arg_id)"
.br
.ti -1c
.RI "template<typename Id > FMT_CONSTEXPR void \fBon_dynamic_precision\fP (Id arg_id)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_error\fP (const char *message)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
