.TH "internal::custom_formatter< Char, Context >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::custom_formatter< Char, Context >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBinternal::function< bool >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcustom_formatter\fP (Context &ctx)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (typename \fBbasic_format_arg\fP< Context >::handle h) const"
.br
.ti -1c
.RI "template<typename T > bool \fBoperator()\fP (T) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
