.TH "internal::color_type" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::color_type
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "union \fBcolor_union\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "FMT_CONSTEXPR \fBcolor_type\fP (color rgb_color) FMT_NOEXCEPT"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBcolor_type\fP (\fBrgb\fP rgb_color) FMT_NOEXCEPT"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBcolor_type\fP (terminal_color term_color) FMT_NOEXCEPT"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBis_rgb\fP"
.br
.ti -1c
.RI "union \fBinternal::color_type::color_union\fP \fBvalue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
