.TH "internal::decimal_formatter_null" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::decimal_formatter_null
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBinternal::decimal_formatter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdecimal_formatter_null\fP (char *buf)"
.br
.ti -1c
.RI "template<unsigned N> char * \fBon\fP (uint32_t u)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
