.TH "internal::char_traits< wchar_t >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::char_traits< wchar_t >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T > int \fBformat_float\fP (wchar_t *buf, std::size_t size, const wchar_t *format, int precision, T \fBvalue\fP)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T > static FMT_API int \fBformat_float\fP (wchar_t *\fBbuffer\fP, std::size_t size, const wchar_t *format, int precision, T \fBvalue\fP)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
