.TH "internal::chrono_format_checker" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::chrono_format_checker
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBreport_no_date\fP ()"
.br
.ti -1c
.RI "template<typename Char > void \fBon_text\fP (const Char *, const Char *)"
.br
.ti -1c
.RI "void \fBon_abbr_weekday\fP ()"
.br
.ti -1c
.RI "void \fBon_full_weekday\fP ()"
.br
.ti -1c
.RI "void \fBon_dec0_weekday\fP (numeric_system)"
.br
.ti -1c
.RI "void \fBon_dec1_weekday\fP (numeric_system)"
.br
.ti -1c
.RI "void \fBon_abbr_month\fP ()"
.br
.ti -1c
.RI "void \fBon_full_month\fP ()"
.br
.ti -1c
.RI "void \fBon_24_hour\fP (numeric_system)"
.br
.ti -1c
.RI "void \fBon_12_hour\fP (numeric_system)"
.br
.ti -1c
.RI "void \fBon_minute\fP (numeric_system)"
.br
.ti -1c
.RI "void \fBon_second\fP (numeric_system)"
.br
.ti -1c
.RI "void \fBon_datetime\fP (numeric_system)"
.br
.ti -1c
.RI "void \fBon_loc_date\fP (numeric_system)"
.br
.ti -1c
.RI "void \fBon_loc_time\fP (numeric_system)"
.br
.ti -1c
.RI "void \fBon_us_date\fP ()"
.br
.ti -1c
.RI "void \fBon_iso_date\fP ()"
.br
.ti -1c
.RI "void \fBon_12_hour_time\fP ()"
.br
.ti -1c
.RI "void \fBon_24_hour_time\fP ()"
.br
.ti -1c
.RI "void \fBon_iso_time\fP ()"
.br
.ti -1c
.RI "void \fBon_am_pm\fP ()"
.br
.ti -1c
.RI "void \fBon_utc_offset\fP ()"
.br
.ti -1c
.RI "void \fBon_tz_name\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
