.TH "internal::prettify_handler" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::prettify_handler
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBprettify_handler\fP (\fBbuffer\fP &b, ptrdiff_t n)"
.br
.ti -1c
.RI "template<typename F > void \fBinsert\fP (ptrdiff_t pos, ptrdiff_t n, F f)"
.br
.ti -1c
.RI "void \fBinsert\fP (ptrdiff_t pos, char c)"
.br
.ti -1c
.RI "void \fBappend\fP (ptrdiff_t n, char c)"
.br
.ti -1c
.RI "void \fBappend\fP (char c)"
.br
.ti -1c
.RI "void \fBremove_trailing\fP (char c)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBdata\fP"
.br
.ti -1c
.RI "ptrdiff_t \fBsize\fP"
.br
.ti -1c
.RI "\fBbuffer\fP & \fBbuf\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
