.TH "internal::context_base< OutputIt, Context, Char >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::context_base< OutputIt, Context, Char >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef OutputIt \fBiterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbasic_parse_context\fP< char_type > & \fBparse_context\fP ()"
.br
.ti -1c
.RI "\fBbasic_format_args\fP< Context > \fBargs\fP () const"
.br
.ti -1c
.RI "\fBbasic_format_arg\fP< Context > \fBarg\fP (unsigned id) const"
.br
.ti -1c
.RI "\fBinternal::error_handler\fP \fBerror_handler\fP ()"
.br
.ti -1c
.RI "void \fBon_error\fP (const char *message)"
.br
.ti -1c
.RI "iterator \fBout\fP ()"
.br
.ti -1c
.RI "iterator \fBbegin\fP ()"
.br
.ti -1c
.RI "void \fBadvance_to\fP (iterator it)"
.br
.ti -1c
.RI "\fBlocale_ref\fP \fBlocale\fP ()"
.br
.in -1c
.SS "Protected Types"

.in +1c
.ti -1c
.RI "typedef Char \fBchar_type\fP"
.br
.ti -1c
.RI "typedef \fBbasic_format_arg\fP< Context > \fBformat_arg\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBcontext_base\fP (OutputIt out, \fBbasic_string_view\fP< char_type > format_str, \fBbasic_format_args\fP< Context > ctx_args, \fBlocale_ref\fP loc=\fBlocale_ref\fP())"
.br
.ti -1c
.RI "\fBformat_arg\fP \fBdo_get_arg\fP (unsigned arg_id)"
.br
.ti -1c
.RI "\fBformat_arg\fP \fBget_arg\fP (unsigned arg_id)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
