.TH "internal::format_type< Context, T >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::format_type< Context, T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits integral_constant< bool, get_type< Context, T >::value !=custom_type >\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
