.TH "internal::counting_iterator< T >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::counting_iterator< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::output_iterator_tag \fBiterator_category\fP"
.br
.ti -1c
.RI "typedef T \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef std::ptrdiff_t \fBdifference_type\fP"
.br
.ti -1c
.RI "typedef T * \fBpointer\fP"
.br
.ti -1c
.RI "typedef T & \fBreference\fP"
.br
.ti -1c
.RI "typedef \fBcounting_iterator\fP \fB_Unchecked_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::size_t \fBcount\fP () const"
.br
.ti -1c
.RI "\fBcounting_iterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBcounting_iterator\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "T & \fBoperator *\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
