.TH "internal::format_string_checker< Char, ErrorHandler, Args >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::format_string_checker< Char, ErrorHandler, Args >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "FMT_CONSTEXPR \fBformat_string_checker\fP (\fBbasic_string_view\fP< Char > format_str, ErrorHandler eh)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_text\fP (const Char *, const Char *)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_arg_id\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_arg_id\fP (unsigned id)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_arg_id\fP (\fBbasic_string_view\fP< Char >)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_replacement_field\fP (const Char *)"
.br
.ti -1c
.RI "FMT_CONSTEXPR const Char * \fBon_format_specs\fP (const Char *begin, const Char *)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_error\fP (const char *message)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
