.TH "internal::is_like_std_string< fmt::basic_string_view< Char > >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::is_like_std_string< fmt::basic_string_view< Char > >
.SH SYNOPSIS
.br
.PP
.PP
Inherits true_type\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
