.TH "internal::formatbuf< Char >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::formatbuf< Char >
.SH SYNOPSIS
.br
.PP
.PP
Inherits basic_streambuf< Char >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBformatbuf\fP (\fBbasic_buffer\fP< Char > &\fBbuffer\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "int_type \fBoverflow\fP (int_type ch=traits_type::eof()) FMT_OVERRIDE"
.br
.ti -1c
.RI "std::streamsize \fBxsputn\fP (const Char *s, std::streamsize count) FMT_OVERRIDE"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
