.TH "is_tuple_like< T >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
is_tuple_like< T >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static FMT_CONSTEXPR_DECL const bool \fBvalue\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "template<typename T > FMT_CONSTEXPR_DECL const bool \fBis_tuple_like\fP< T >::value\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=
    internal::is_tuple_like_<T>::value && !internal::is_range_<T>::value
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
