.TH "Typhoon/ThirdParty/glm/glm/mat2x4.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/mat2x4.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&./ext/matrix_double2x4\&.hpp'\fP
.br
\fC#include '\&./ext/matrix_double2x4_precision\&.hpp'\fP
.br
\fC#include '\&./ext/matrix_float2x4\&.hpp'\fP
.br
\fC#include '\&./ext/matrix_float2x4_precision\&.hpp'\fP
.br

.SH "Detailed Description"
.PP 
\fBCore features\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
