.TH "Typhoon/ThirdParty/glm/glm/gtx/matrix_interpolation.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/gtx/matrix_interpolation.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./glm\&.hpp'\fP
.br
\fC#include 'matrix_interpolation\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL void \fBglm::axisAngle\fP (mat< 4, 4, T, Q > const &Mat, vec< 3, T, Q > &Axis, T &Angle)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL mat< 4, 4, T, Q > \fBglm::axisAngleMatrix\fP (vec< 3, T, Q > const &Axis, T const Angle)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL mat< 4, 4, T, Q > \fBglm::extractMatrixRotation\fP (mat< 4, 4, T, Q > const &Mat)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL mat< 4, 4, T, Q > \fBglm::interpolate\fP (mat< 4, 4, T, Q > const &m1, mat< 4, 4, T, Q > const &m2, T const Delta)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTX_matrix_interpolation\fP
.PP
\fBAuthor:\fP
.RS 4
Ghenadii Ursachi (the.asteroth@gmail.com)
.RE
.PP
\fBSee also:\fP
.RS 4
\fBCore features\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
