.TH "Typhoon/ThirdParty/glm/glm/gtx/matrix_operation.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/gtx/matrix_operation.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./glm\&.hpp'\fP
.br
\fC#include 'matrix_operation\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL mat< 2, 2, T, Q > \fBglm::diagonal2x2\fP (vec< 2, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL mat< 2, 3, T, Q > \fBglm::diagonal2x3\fP (vec< 2, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL mat< 2, 4, T, Q > \fBglm::diagonal2x4\fP (vec< 2, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL mat< 3, 2, T, Q > \fBglm::diagonal3x2\fP (vec< 2, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL mat< 3, 3, T, Q > \fBglm::diagonal3x3\fP (vec< 3, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL mat< 3, 4, T, Q > \fBglm::diagonal3x4\fP (vec< 3, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL mat< 4, 2, T, Q > \fBglm::diagonal4x2\fP (vec< 2, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL mat< 4, 3, T, Q > \fBglm::diagonal4x3\fP (vec< 3, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL mat< 4, 4, T, Q > \fBglm::diagonal4x4\fP (vec< 4, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL mat< 2, 2, T, Q > \fBglm::adjugate\fP (mat< 2, 2, T, Q > const &m)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL mat< 3, 3, T, Q > \fBglm::adjugate\fP (mat< 3, 3, T, Q > const &m)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL mat< 4, 4, T, Q > \fBglm::adjugate\fP (mat< 4, 4, T, Q > const &m)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTX_matrix_operation\fP
.PP
\fBSee also:\fP
.RS 4
\fBCore features\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
