.TH "Typhoon/ThirdParty/glm/glm/gtx/matrix_transform_2d.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/gtx/matrix_transform_2d.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./mat3x3\&.hpp'\fP
.br
\fC#include '\&.\&./vec2\&.hpp'\fP
.br
\fC#include 'matrix_transform_2d\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_QUALIFIER mat< 3, 3, T, Q > \fBglm::translate\fP (mat< 3, 3, T, Q > const &m, vec< 2, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_QUALIFIER mat< 3, 3, T, Q > \fBglm::rotate\fP (mat< 3, 3, T, Q > const &m, T angle)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_QUALIFIER mat< 3, 3, T, Q > \fBglm::scale\fP (mat< 3, 3, T, Q > const &m, vec< 2, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_QUALIFIER mat< 3, 3, T, Q > \fBglm::shearX\fP (mat< 3, 3, T, Q > const &m, T y)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_QUALIFIER mat< 3, 3, T, Q > \fBglm::shearY\fP (mat< 3, 3, T, Q > const &m, T x)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTX_matrix_transform_2d\fP
.PP
\fBAuthor:\fP
.RS 4
Miguel Ángel Pérez Martínez
.RE
.PP
\fBSee also:\fP
.RS 4
\fBCore features\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
