.TH "Typhoon/ThirdParty/glm/glm/gtc/matrix_access.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/gtc/matrix_access.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./detail/setup\&.hpp'\fP
.br
\fC#include 'matrix_access\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType::row_type \fBglm::row\fP (genType const &m, length_t index)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::row\fP (genType const &m, length_t index, typename genType::row_type const &x)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType::col_type \fBglm::column\fP (genType const &m, length_t index)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::column\fP (genType const &m, length_t index, typename genType::col_type const &x)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTC_matrix_access\fP
.PP
\fBSee also:\fP
.RS 4
\fBCore features\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
