.TH "Typhoon/ThirdParty/glm/glm/matrix.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/matrix.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'detail/qualifier\&.hpp'\fP
.br
\fC#include 'detail/setup\&.hpp'\fP
.br
\fC#include 'vec2\&.hpp'\fP
.br
\fC#include 'vec3\&.hpp'\fP
.br
\fC#include 'vec4\&.hpp'\fP
.br
\fC#include 'mat2x2\&.hpp'\fP
.br
\fC#include 'mat2x3\&.hpp'\fP
.br
\fC#include 'mat2x4\&.hpp'\fP
.br
\fC#include 'mat3x2\&.hpp'\fP
.br
\fC#include 'mat3x3\&.hpp'\fP
.br
\fC#include 'mat3x4\&.hpp'\fP
.br
\fC#include 'mat4x2\&.hpp'\fP
.br
\fC#include 'mat4x3\&.hpp'\fP
.br
\fC#include 'mat4x4\&.hpp'\fP
.br
\fC#include 'detail/func_matrix\&.inl'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBglm::detail::outerProduct_trait< C, R, T, Q >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::outerProduct_trait< 2, 2, T, Q >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::outerProduct_trait< 2, 3, T, Q >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::outerProduct_trait< 2, 4, T, Q >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::outerProduct_trait< 3, 2, T, Q >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::outerProduct_trait< 3, 3, T, Q >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::outerProduct_trait< 3, 4, T, Q >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::outerProduct_trait< 4, 2, T, Q >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::outerProduct_trait< 4, 3, T, Q >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::outerProduct_trait< 4, 4, T, Q >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<length_t C, length_t R, typename T , qualifier Q> GLM_FUNC_DECL mat< C, R, T, Q > \fBglm::matrixCompMult\fP (mat< C, R, T, Q > const &x, mat< C, R, T, Q > const &y)"
.br
.ti -1c
.RI "template<length_t C, length_t R, typename T , qualifier Q> GLM_FUNC_DECL detail::outerProduct_trait< C, R, T, Q >::type \fBglm::outerProduct\fP (vec< C, T, Q > const &c, vec< R, T, Q > const &r)"
.br
.ti -1c
.RI "template<length_t C, length_t R, typename T , qualifier Q> GLM_FUNC_DECL mat< C, R, T, Q >::transpose_type \fBglm::transpose\fP (mat< C, R, T, Q > const &x)"
.br
.ti -1c
.RI "template<length_t C, length_t R, typename T , qualifier Q> GLM_FUNC_DECL T \fBglm::determinant\fP (mat< C, R, T, Q > const &m)"
.br
.ti -1c
.RI "template<length_t C, length_t R, typename T , qualifier Q> GLM_FUNC_DECL mat< C, R, T, Q > \fBglm::inverse\fP (mat< C, R, T, Q > const &m)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCore features\fP
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 8\&.6 Matrix Functions\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
