.TH "md__typhoon__third_party__g_l_fw__l_i_c_e_n_s_e" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__typhoon__third_party__g_l_fw__l_i_c_e_n_s_e \- LICENSE 
Copyright (c) 2002-2006 Marcus Geelnard Copyright (c) 2006-2016 Camilla Löwy elmindreda@glfw.org
.PP
This software is provided 'as-is', without any express or implied warranty\&. In no event will the authors be held liable for any damages arising from the use of this software\&.
.PP
Permission is granted to anyone to use this software for any purpose, including commercial applications, and to alter it and redistribute it freely, subject to the following restrictions:
.PP
.IP "1." 4
The origin of this software must not be misrepresented; you must not claim that you wrote the original software\&. If you use this software in a product, an acknowledgment in the product documentation would be appreciated but is not required\&.
.IP "2." 4
Altered source versions must be plainly marked as such, and must not be misrepresented as being the original software\&.
.IP "3." 4
This notice may not be removed or altered from any source distribution\&. 
.PP

