.TH "md__typhoon__third_party__g_l_fw__r_e_a_d_m_e" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__typhoon__third_party__g_l_fw__r_e_a_d_m_e \- GLFW 
\fC\fP \fC\fP \fC\fP
.PP
.SS "Introduction"
.PP
GLFW is an Open Source, multi-platform library for OpenGL, OpenGL ES and Vulkan application development\&. It provides a simple, platform-independent API for creating windows, contexts and surfaces, reading input, handling events, etc\&.
.PP
GLFW natively supports Windows, macOS and Linux and other Unix-like systems\&. On Linux both X11 and Wayland is supported\&.
.PP
GLFW is licensed under the \fCzlib/libpng license\fP\&.
.PP
You can \fCdownload\fP the latest stable release as source or Windows binaries, or fetch the \fClatest\fP branch from GitHub\&. Each release starting with 3\&.0 also has a corresponding \fCannotated tag\fP with source and binary archives\&.
.PP
The \fCdocumentation\fP is available online and is included in all source and binary archives\&. See the \fCrelease notes\fP for new features, caveats and deprecations in the latest release\&. For more details see the \fCversion history\fP\&.
.PP
The \fCmaster\fP branch is the stable integration branch and \fIshould\fP always compile and run on all supported platforms, although details of newly added features may change until they have been included in a release\&. New features and many bug fixes live in \fCother branches\fP until they are stable enough to merge\&.
.PP
If you are new to GLFW, you may find the \fCtutorial\fP for GLFW 3 useful\&. If you have used GLFW 2 in the past, there is a \fCtransition guide\fP for moving to the GLFW 3 API\&.
.PP
.SS "Compiling GLFW"
.PP
GLFW itself requires only the headers and libraries for your OS and window system\&. It does not need the headers for any context creation API (WGL, GLX, EGL, NSGL, OSMesa) or rendering API (OpenGL, OpenGL ES, Vulkan) to enable support for them\&.
.PP
GLFW supports compilation on Windows with Visual C++ 2010 and later, MinGW and MinGW-w64, on macOS with Clang and on Linux and other Unix-like systems with GCC and Clang\&. It will likely compile in other environments as well, but this is not regularly tested\&.
.PP
There are \fCpre-compiled Windows binaries\fP available for all supported compilers\&.
.PP
See the \fCcompilation guide\fP for more information about how to compile GLFW yourself\&.
.PP
.SS "Using GLFW"
.PP
See the \fCdocumentation\fP for tutorials, guides and the API reference\&.
.PP
.SS "Contributing to GLFW"
.PP
See the \fBcontribution\fPguide" for more information\&.
.PP
.SS "System requirements"
.PP
GLFW supports Windows XP and later and macOS 10\&.8 and later\&. Linux and other Unix-like systems running the X Window System are supported even without a desktop environment or modern extensions, although some features require a running window or clipboard manager\&. The OSMesa backend requires Mesa 6\&.3\&.
.PP
See the \fCcompatibility guide\fP in the documentation for more information\&.
.PP
.SS "Dependencies"
.PP
GLFW itself depends only on the headers and libraries for your window system\&.
.PP
The (experimental) Wayland backend also depends on the \fCextra-cmake-modules\fP package, which is used to generated Wayland protocol headers\&.
.PP
The examples and test programs depend on a number of tiny libraries\&. These are located in the \fCdeps/\fP directory\&.
.PP
.IP "\(bu" 2
\fCgetopt_port\fP for examples with command-line options
.IP "\(bu" 2
\fCTinyCThread\fP for threaded examples
.IP "\(bu" 2
\fCglad2\fP for loading OpenGL and Vulkan functions
.IP "\(bu" 2
\fClinmath\&.h\fP for linear algebra in examples
.IP "\(bu" 2
\fCNuklear\fP for test and example UI
.IP "\(bu" 2
\fCstb_image_write\fP for writing images to disk
.PP
.PP
The documentation is generated with \fCDoxygen\fP if CMake can find that tool\&.
.PP
.SS "Reporting bugs"
.PP
Bugs are reported to our \fCissue tracker\fP\&. Please check the \fBcontribution\fPguide" for information on what to include when reporting a bug\&.
.PP
.SS "Changelog"
.PP
.IP "\(bu" 2
Disabled tests and examples by default when built as a CMake subdirectory
.IP "\(bu" 2
Bugfix: The CMake config-file package used an absolute path and was not relocatable (#1470)
.IP "\(bu" 2
[Win32] Bugfix: \fCGLFW_INCLUDE_VULKAN\fP plus \fCVK_USE_PLATFORM_WIN32_KHR\fP caused symbol redefinition (#1524)
.IP "\(bu" 2
[Win32] Bugfix: The cursor position event was emitted before its cursor enter event (#1490)
.IP "\(bu" 2
[X11] Bugfix: The CMake files did not check for the XInput headers (#1480)
.IP "\(bu" 2
[X11] Bugfix: Key names were not updated when the keyboard layout changed (#1462,#1528)
.IP "\(bu" 2
[NSGL] Removed enforcement of forward-compatible flag for core contexts
.PP
.PP
.SS "Contact"
.PP
On \fCglfw\&.org\fP you can find the latest version of GLFW, as well as news, documentation and other information about the project\&.
.PP
If you have questions related to the use of GLFW, we have a \fCforum\fP, and the \fC#glfw\fP IRC channel on \fCFreenode\fP\&.
.PP
If you have a bug to report, a patch to submit or a feature you'd like to request, please file it in the \fCissue tracker\fP on GitHub\&.
.PP
Finally, if you're interested in helping out with the development of GLFW or porting it to your favorite platform, join us on the forum, GitHub or IRC\&.
.PP
.SS "Acknowledgements"
.PP
GLFW exists because people around the world donated their time and lent their skills\&.
.PP
.IP "\(bu" 2
Bobyshev Alexander
.IP "\(bu" 2
Matt Arsenault
.IP "\(bu" 2
David Avedissian
.IP "\(bu" 2
Keith Bauer
.IP "\(bu" 2
John Bartholomew
.IP "\(bu" 2
Coşku Baş
.IP "\(bu" 2
Niklas Behrens
.IP "\(bu" 2
Andrew Belt
.IP "\(bu" 2
Niklas Bergström
.IP "\(bu" 2
Denis Bernard
.IP "\(bu" 2
Doug Binks
.IP "\(bu" 2
blanco
.IP "\(bu" 2
Kyle Brenneman
.IP "\(bu" 2
Rok Breulj
.IP "\(bu" 2
Martin Capitanio
.IP "\(bu" 2
David Carlier
.IP "\(bu" 2
Arturo Castro
.IP "\(bu" 2
Chi-kwan Chan
.IP "\(bu" 2
Ian Clarkson
.IP "\(bu" 2
Michał Cichoń
.IP "\(bu" 2
Lambert Clara
.IP "\(bu" 2
Anna Clarke
.IP "\(bu" 2
Yaron Cohen-Tal
.IP "\(bu" 2
Omar Cornut
.IP "\(bu" 2
Andrew Corrigan
.IP "\(bu" 2
Bailey Cosier
.IP "\(bu" 2
Noel Cower
.IP "\(bu" 2
Jason Daly
.IP "\(bu" 2
Jarrod Davis
.IP "\(bu" 2
Olivier Delannoy
.IP "\(bu" 2
Paul R\&. Deppe
.IP "\(bu" 2
Michael Dickens
.IP "\(bu" 2
Роман Донченко
.IP "\(bu" 2
Mario Dorn
.IP "\(bu" 2
Wolfgang Draxinger
.IP "\(bu" 2
Jonathan Dummer
.IP "\(bu" 2
Ralph Eastwood
.IP "\(bu" 2
Fredrik Ehnbom
.IP "\(bu" 2
Robin Eklind
.IP "\(bu" 2
Siavash Eliasi
.IP "\(bu" 2
Felipe Ferreira
.IP "\(bu" 2
Michael Fogleman
.IP "\(bu" 2
Gerald Franz
.IP "\(bu" 2
Mário Freitas
.IP "\(bu" 2
GeO4d
.IP "\(bu" 2
Marcus Geelnard
.IP "\(bu" 2
Stephen Gowen
.IP "\(bu" 2
Kovid Goyal
.IP "\(bu" 2
Eloi Marín Gratacós
.IP "\(bu" 2
Stefan Gustavson
.IP "\(bu" 2
Jonathan Hale
.IP "\(bu" 2
Sylvain Hellegouarch
.IP "\(bu" 2
Matthew Henry
.IP "\(bu" 2
heromyth
.IP "\(bu" 2
Lucas Hinderberger
.IP "\(bu" 2
Paul Holden
.IP "\(bu" 2
Warren Hu
.IP "\(bu" 2
Charles Huber
.IP "\(bu" 2
IntellectualKitty
.IP "\(bu" 2
Aaron Jacobs
.IP "\(bu" 2
Erik S\&. V\&. Jansson
.IP "\(bu" 2
Toni Jovanoski
.IP "\(bu" 2
Arseny Kapoulkine
.IP "\(bu" 2
Cem Karan
.IP "\(bu" 2
Osman Keskin
.IP "\(bu" 2
Josh Kilmer
.IP "\(bu" 2
Cameron King
.IP "\(bu" 2
Peter Knut
.IP "\(bu" 2
Christoph Kubisch
.IP "\(bu" 2
Yuri Kunde Schlesner
.IP "\(bu" 2
Konstantin Käfer
.IP "\(bu" 2
Eric Larson
.IP "\(bu" 2
Robin Leffmann
.IP "\(bu" 2
Glenn Lewis
.IP "\(bu" 2
Shane Liesegang
.IP "\(bu" 2
Anders Lindqvist
.IP "\(bu" 2
Leon Linhart
.IP "\(bu" 2
Eyal Lotem
.IP "\(bu" 2
Aaron Loucks
.IP "\(bu" 2
Luflosi
.IP "\(bu" 2
Tristam MacDonald
.IP "\(bu" 2
Hans Mackowiak
.IP "\(bu" 2
Дмитри Малышев
.IP "\(bu" 2
Zbigniew Mandziejewicz
.IP "\(bu" 2
Adam Marcus
.IP "\(bu" 2
Célestin Marot
.IP "\(bu" 2
Kyle McDonald
.IP "\(bu" 2
David Medlock
.IP "\(bu" 2
Bryce Mehring
.IP "\(bu" 2
Jonathan Mercier
.IP "\(bu" 2
Marcel Metz
.IP "\(bu" 2
Liam Middlebrook
.IP "\(bu" 2
Jonathan Miller
.IP "\(bu" 2
Kenneth Miller
.IP "\(bu" 2
Bruce Mitchener
.IP "\(bu" 2
Jack Moffitt
.IP "\(bu" 2
Jeff Molofee
.IP "\(bu" 2
Alexander Monakov
.IP "\(bu" 2
Pierre Morel
.IP "\(bu" 2
Jon Morton
.IP "\(bu" 2
Pierre Moulon
.IP "\(bu" 2
Martins Mozeiko
.IP "\(bu" 2
Julian Møller
.IP "\(bu" 2
ndogxj
.IP "\(bu" 2
Kristian Nielsen
.IP "\(bu" 2
Kamil Nowakowski
.IP "\(bu" 2
Denis Ovod
.IP "\(bu" 2
Ozzy
.IP "\(bu" 2
Andri Pálsson
.IP "\(bu" 2
Peoro
.IP "\(bu" 2
Braden Pellett
.IP "\(bu" 2
Christopher Pelloux
.IP "\(bu" 2
Arturo J\&. Pérez
.IP "\(bu" 2
Anthony Pesch
.IP "\(bu" 2
Orson Peters
.IP "\(bu" 2
Emmanuel Gil Peyrot
.IP "\(bu" 2
Cyril Pichard
.IP "\(bu" 2
Keith Pitt
.IP "\(bu" 2
Stanislav Podgorskiy
.IP "\(bu" 2
Konstantin Podsvirov
.IP "\(bu" 2
Nathan Poirier
.IP "\(bu" 2
Alexandre Pretyman
.IP "\(bu" 2
przemekmirek
.IP "\(bu" 2
Philip Rideout
.IP "\(bu" 2
Eddie Ringle
.IP "\(bu" 2
Max Risuhin
.IP "\(bu" 2
Jorge Rodriguez
.IP "\(bu" 2
Ed Ropple
.IP "\(bu" 2
Aleksey Rybalkin
.IP "\(bu" 2
Riku Salminen
.IP "\(bu" 2
Brandon Schaefer
.IP "\(bu" 2
Sebastian Schuberth
.IP "\(bu" 2
Christian Sdunek
.IP "\(bu" 2
Matt Sealey
.IP "\(bu" 2
Steve Sexton
.IP "\(bu" 2
Arkady Shapkin
.IP "\(bu" 2
Yoshiki Shibukawa
.IP "\(bu" 2
Dmitri Shuralyov
.IP "\(bu" 2
Daniel Skorupski
.IP "\(bu" 2
Bradley Smith
.IP "\(bu" 2
Cliff Smolinsky
.IP "\(bu" 2
Patrick Snape
.IP "\(bu" 2
Erlend Sogge Heggen
.IP "\(bu" 2
Julian Squires
.IP "\(bu" 2
Johannes Stein
.IP "\(bu" 2
Pontus Stenetorp
.IP "\(bu" 2
Michael Stocker
.IP "\(bu" 2
Justin Stoecker
.IP "\(bu" 2
Elviss Strazdins
.IP "\(bu" 2
Paul Sultana
.IP "\(bu" 2
Nathan Sweet
.IP "\(bu" 2
TTK-Bandit
.IP "\(bu" 2
Sergey Tikhomirov
.IP "\(bu" 2
Arthur Tombs
.IP "\(bu" 2
Ioannis Tsakpinis
.IP "\(bu" 2
Samuli Tuomola
.IP "\(bu" 2
Matthew Turner
.IP "\(bu" 2
urraka
.IP "\(bu" 2
Elias Vanderstuyft
.IP "\(bu" 2
Stef Velzel
.IP "\(bu" 2
Jari Vetoniemi
.IP "\(bu" 2
Ricardo Vieira
.IP "\(bu" 2
Nicholas Vitovitch
.IP "\(bu" 2
Simon Voordouw
.IP "\(bu" 2
Corentin Wallez
.IP "\(bu" 2
Torsten Walluhn
.IP "\(bu" 2
Patrick Walton
.IP "\(bu" 2
Xo Wang
.IP "\(bu" 2
Jay Weisskopf
.IP "\(bu" 2
Frank Wille
.IP "\(bu" 2
Ryogo Yoshimura
.IP "\(bu" 2
Lukas Zanner
.IP "\(bu" 2
Andrey Zholos
.IP "\(bu" 2
Santi Zupancic
.IP "\(bu" 2
Jonas Ådahl
.IP "\(bu" 2
Lasse Öörni
.IP "\(bu" 2
All the unmentioned and anonymous contributors in the GLFW community, for bug reports, patches, feedback, testing and encouragement 
.PP

