.TH "md__typhoon__third_party_imgui_examples_example_sdl_opengl3__r_e_a_d_m_e" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__typhoon__third_party_imgui_examples_example_sdl_opengl3__r_e_a_d_m_e \- How to Build 

.IP "\(bu" 2
On Windows with Visual Studio's CLI
.PP
.PP
.PP
.nf
set SDL2_DIR=path_to_your_sdl2_folder
cl /Zi /MD /I\&.\&. /I\&.\&.\\&.\&. /I%SDL2_DIR%\include /I\&.\&.\libs\gl3w main\&.cpp \&.\&.\imgui_impl_sdl\&.cpp \&.\&.\imgui_impl_opengl3\&.cpp \&.\&.\\&.\&.\imgui*\&.cpp \&.\&.\libs\gl3w\GL\gl3w\&.c /FeDebug/example_sdl_opengl3\&.exe /FoDebug/ /link /libpath:%SDL2_DIR%\lib\x86 SDL2\&.lib SDL2main\&.lib opengl32\&.lib /subsystem:console
#          ^^ include paths                                 ^^ source files                                                                                  ^^ output exe                    ^^ output dir   ^^ libraries
# or for 64-bit:
cl /Zi /MD /I\&.\&. /I\&.\&.\\&.\&. /I%SDL2_DIR%\include /I\&.\&.\libs\gl3w main\&.cpp \&.\&.\imgui_impl_sdl\&.cpp \&.\&.\imgui_impl_opengl3\&.cpp \&.\&.\\&.\&.\imgui*\&.cpp \&.\&.\libs\gl3w\GL\gl3w\&.c /FeDebug/example_sdl_opengl3\&.exe /FoDebug/ /link /libpath:%SDL2_DIR%\lib\x64 SDL2\&.lib SDL2main\&.lib opengl32\&.lib /subsystem:console
.fi
.PP
.PP
.IP "\(bu" 2
On Linux and similar Unixes
.PP
.PP
.PP
.nf
c++ `sdl2-config --cflags` -I \&.\&. -I \&.\&./\&.\&. -I \&.\&./libs/gl3w main\&.cpp \&.\&./imgui_impl_sdl\&.cpp \&.\&./imgui_impl_opengl3\&.cpp \&.\&./\&.\&./imgui*\&.cpp \&.\&./libs/gl3w/GL/gl3w\&.c `sdl2-config --libs` -lGL -ldl
.fi
.PP
.PP
.IP "\(bu" 2
On Mac OS X
.PP
.PP
.PP
.nf
brew install sdl2
c++ `sdl2-config --cflags` -I \&.\&. -I \&.\&./\&.\&. -I \&.\&./libs/gl3w main\&.cpp \&.\&./imgui_impl_sdl\&.cpp \&.\&./imgui_impl_opengl3\&.cpp \&.\&./\&.\&./imgui*\&.cpp \&.\&./libs/gl3w/GL/gl3w\&.c `sdl2-config --libs` -framework OpenGl -framework CoreFoundation
.fi
.PP
 
