.TH "md__typhoon__third_party_glm_readme" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__typhoon__third_party_glm_readme \- readme 

.PP
\fCOpenGL Mathematics\fP (\fIGLM\fP) is a header only C++ mathematics library for graphics software based on the \fCOpenGL Shading Language (GLSL) specifications\fP\&.
.PP
\fIGLM\fP provides classes and functions designed and implemented with the same naming conventions and functionality than \fIGLSL\fP so that anyone who knows \fIGLSL\fP, can use \fIGLM\fP as well in C++\&.
.PP
This project isn't limited to \fIGLSL\fP features\&. An extension system, based on the \fIGLSL\fP extension conventions, provides extended capabilities: matrix transformations, quaternions, data packing, random numbers, noise, etc\&.\&.\&.
.PP
This library works perfectly with \fI\fCOpenGL\fP\fP but it also ensures interoperability with other third party libraries and SDK\&. It is a good candidate for software rendering (raytracing / rasterisation), image processing, physic simulations and any development context that requires a simple and convenient mathematics library\&.
.PP
\fIGLM\fP is written in C++98 but can take advantage of C++11 when supported by the compiler\&. It is a platform independent library with no dependence and it officially supports the following compilers:
.IP "\(bu" 2
\fCApple Clang 6\&.0\fP and higher
.IP "\(bu" 2
\fCGCC\fP 4\&.7 and higher
.IP "\(bu" 2
\fCIntel C++ Composer\fP XE 2013 and higher
.IP "\(bu" 2
\fCLLVM\fP 3\&.4 and higher
.IP "\(bu" 2
\fCVisual C++\fP 2013 and higher
.IP "\(bu" 2
\fCCUDA\fP 7\&.0 and higher (experimental)
.IP "\(bu" 2
\fCSYCL\fP (experimental: only \fCComputeCpp\fP implementation has been tested)\&.
.IP "\(bu" 2
Any C++11 compiler
.PP
.PP
For more information about \fIGLM\fP, please have a look at the \fBmanual\fP and the \fCAPI reference documentation\fP\&. The source code and the documentation are licensed under both the \fCHappy Bunny License (Modified MIT) or the MIT License\fP\&.
.PP
Thanks for contributing to the project by \fCsubmitting issues\fP for bug reports and feature requests\&. Any feedback is welcome at \fCglm@g-truc\&.net\fP\&.
.PP
.PP
.nf
#include <glm/vec3\&.hpp> // glm::vec3
#include <glm/vec4\&.hpp> // glm::vec4
#include <glm/mat4x4\&.hpp> // glm::mat4
#include <glm/ext/matrix_transform\&.hpp> // glm::translate, glm::rotate, glm::scale
#include <glm/ext/matrix_clip_space\&.hpp> // glm::perspective
#include <glm/ext/constants\&.hpp> // glm::pi

glm::mat4 camera(float Translate, glm::vec2 const& Rotate)
{
    glm::mat4 Projection = glm::perspective(glm::pi<float>() * 0\&.25f, 4\&.0f / 3\&.0f, 0\&.1f, 100\&.f);
    glm::mat4 View = glm::translate(glm::mat4(1\&.0f), glm::vec3(0\&.0f, 0\&.0f, -Translate));
    View = glm::rotate(View, Rotate\&.y, glm::vec3(-1\&.0f, 0\&.0f, 0\&.0f));
    View = glm::rotate(View, Rotate\&.x, glm::vec3(0\&.0f, 1\&.0f, 0\&.0f));
    glm::mat4 Model = glm::scale(glm::mat4(1\&.0f), glm::vec3(0\&.5f));
    return Projection * View * Model;
}
.fi
.PP
.PP
.SS "\fCLastest release\fP"
.PP
.SS "Project Health"
.PP
Service  System  Compiler  Status   \fCTravis CI\fP  MacOSX, Linux 64 bits  Clang 3\&.6, Clang 5\&.0, GCC 4\&.9, GCC 7\&.3  \fC\fP   \fCAppVeyor\fP  Windows 32 and 64  Visual Studio 2013, Visual Studio 2015, Visual Studio 2017  \fC\fP   
.PP
.SS "Release notes"
.PP
.SS "\fCGLM 0\&.9\&.9\&.6\fP"
.PP
.SS "Features:"
.PP
.IP "\(bu" 2
Added EXT_scalar_integer extension with power of two and multiple scalar functions
.IP "\(bu" 2
Added EXT_vector_integer extension with power of two and multiple vector functions
.PP
.PP
.SS "Improvements:"
.PP
.IP "\(bu" 2
Added SYCL support #914
.IP "\(bu" 2
Added Visual C++ 2019 detection
.IP "\(bu" 2
Added Visual C++ 2017 15\&.8 and 15\&.9 detection
.PP
.PP
.SS "Fixes:"
.PP
.IP "\(bu" 2
Fixed for g++6 where -std=c++1z sets __cplusplus to 201500 instead of 201402 #921
.IP "\(bu" 2
Fixed hash hashes qua instead of tquat #919
.IP "\(bu" 2
Fixed \&.natvis as structs renamed #915
.IP "\(bu" 2
Fixed ldexp and frexp declaration #895
.IP "\(bu" 2
Fixed missing const to quaternion conversion operators #890
.IP "\(bu" 2
Fixed EXT_scalar_ulp and EXT_vector_ulp API coding style
.IP "\(bu" 2
Fixed quaternion componant order: w, {x, y, z} #916
.PP
.PP
.SS "\fCGLM 0\&.9\&.9\&.5\fP - 2019-04-01"
.PP
.SS "Fixes:"
.PP
.IP "\(bu" 2
Fixed build errors when defining GLM_ENABLE_EXPERIMENTAL #884 #883
.IP "\(bu" 2
Fixed 'if constexpr' warning #887
.IP "\(bu" 2
Fixed missing declarations for frexp and ldexp #886
.PP
.PP
.SS "\fCGLM 0\&.9\&.9\&.4\fP - 2019-03-19"
.PP
.SS "Features:"
.PP
.IP "\(bu" 2
Added mix implementation for matrices in EXT_matrix_common #842
.IP "\(bu" 2
Added BUILD_SHARED_LIBS and BUILD_STATIC_LIBS build options #871
.PP
.PP
.SS "Improvements:"
.PP
.IP "\(bu" 2
Added GLM_FORCE_INTRINSICS to enable SIMD instruction code path\&. By default, it's disabled allowing constexpr support by default\&. #865
.IP "\(bu" 2
Optimized inverseTransform #867
.PP
.PP
.SS "Fixes:"
.PP
.IP "\(bu" 2
Fixed in mat4x3 conversion #829
.IP "\(bu" 2
Fixed constexpr issue on GCC #832 #865
.IP "\(bu" 2
Fixed mix implementation to improve GLSL conformance #866
.IP "\(bu" 2
Fixed int8 being defined as unsigned char with some compiler #839
.IP "\(bu" 2
Fixed vec1 include #856
.IP "\(bu" 2
Ignore \&.vscode #848
.PP
.PP
.SS "\fCGLM 0\&.9\&.9\&.3\fP - 2018-10-31"
.PP
.SS "Features:"
.PP
.IP "\(bu" 2
Added equal and notEqual overload with max ULPs parameters for scalar numbers #121
.IP "\(bu" 2
Added GLM_FORCE_SILENT_WARNINGS to silent GLM warnings when using language extensions but using W4 or Wpedantic warnings #814 #775
.IP "\(bu" 2
Added adjugate functions to GTX_matrix_operation #151
.IP "\(bu" 2
Added GLM_FORCE_ALIGNED_GENTYPES to enable aligned types and SIMD instruction are not enabled\&. This disable constexpr #816
.PP
.PP
.SS "Improvements:"
.PP
.IP "\(bu" 2
Added constant time ULP distance between float #121
.IP "\(bu" 2
Added GLM_FORCE_SILENT_WARNINGS to suppress GLM warnings #822
.PP
.PP
.SS "Fixes:"
.PP
.IP "\(bu" 2
Fixed simplex noise build with double #734
.IP "\(bu" 2
Fixed bitfieldInsert according to GLSL spec #818
.IP "\(bu" 2
Fixed refract for negative 'k' #808
.PP
.PP
.SS "\fCGLM 0\&.9\&.9\&.2\fP - 2018-09-14"
.PP
.SS "Fixes:"
.PP
.IP "\(bu" 2
Fixed GLM_FORCE_CXX** section in the manual
.IP "\(bu" 2
Fixed default initialization with vector and quaternion types using GLM_FORCE_CTOR_INIT #812
.PP
.PP
.SS "\fCGLM 0\&.9\&.9\&.1\fP - 2018-09-03"
.PP
.SS "Features:"
.PP
.IP "\(bu" 2
Added bitfieldDeinterleave to GTC_bitfield
.IP "\(bu" 2
Added missing equal and notEqual with epsilon for quaternion types to GTC_quaternion
.IP "\(bu" 2
Added EXT_matrix_relational: equal and notEqual with epsilon for matrix types
.IP "\(bu" 2
Added missing aligned matrix types to GTC_type_aligned
.IP "\(bu" 2
Added C++17 detection
.IP "\(bu" 2
Added Visual C++ language standard version detection
.IP "\(bu" 2
Added PDF manual build from markdown
.PP
.PP
.SS "Improvements:"
.PP
.IP "\(bu" 2
Added a section to the manual for contributing to GLM
.IP "\(bu" 2
Refactor manual, lists all configuration defines
.IP "\(bu" 2
Added missing vec1 based constructors
.IP "\(bu" 2
Redesigned constexpr support which excludes both SIMD and constexpr #783
.IP "\(bu" 2
Added detection of Visual C++ 2017 toolsets
.IP "\(bu" 2
Added identity functions #765
.IP "\(bu" 2
Splitted headers into EXT extensions to improve compilation time #670
.IP "\(bu" 2
Added separated performance tests
.IP "\(bu" 2
Clarified refract valid range of the indices of refraction, between -1 and 1 inclusively #806
.PP
.PP
.SS "Fixes:"
.PP
.IP "\(bu" 2
Fixed SIMD detection on Clang and GCC
.IP "\(bu" 2
Fixed build problems due to printf and std::clock_t #778
.IP "\(bu" 2
Fixed int mod
.IP "\(bu" 2
Anonymous unions require C++ language extensions
.IP "\(bu" 2
Fixed ortho #790
.IP "\(bu" 2
Fixed Visual C++ 2013 warnings in vector relational code #782
.IP "\(bu" 2
Fixed ICC build errors with constexpr #704
.IP "\(bu" 2
Fixed defaulted operator= and constructors #791
.IP "\(bu" 2
Fixed invalid conversion from int scalar with vec4 constructor when using SSE instruction
.IP "\(bu" 2
Fixed infinite loop in random functions when using negative radius values using an assert #739
.PP
.PP
.SS "\fCGLM 0\&.9\&.9\&.0\fP - 2018-05-22"
.PP
.SS "Features:"
.PP
.IP "\(bu" 2
Added RGBM encoding in GTC_packing #420
.IP "\(bu" 2
Added GTX_color_encoding extension
.IP "\(bu" 2
Added GTX_vec_swizzle, faster compile time swizzling then swizzle operator #558
.IP "\(bu" 2
Added GTX_exterior_product with a \fBvec2\fP cross implementation #621
.IP "\(bu" 2
Added GTX_matrix_factorisation to factor matrices in various forms #654
.IP "\(bu" 2
Added \fCGLM_ENABLE_EXPERIMENTAL\fP to enable experimental features\&.
.IP "\(bu" 2
Added packing functions for integer vectors #639
.IP "\(bu" 2
Added conan packaging configuration #643 #641
.IP "\(bu" 2
Added quatLookAt to GTX_quaternion #659
.IP "\(bu" 2
Added fmin, fmax and fclamp to GTX_extended_min_max #372
.IP "\(bu" 2
Added EXT_vector_relational: extend equal and notEqual to take an epsilon argument
.IP "\(bu" 2
Added EXT_vector_relational: openBounded and closeBounded
.IP "\(bu" 2
Added EXT_vec1: *vec1 types
.IP "\(bu" 2
Added GTX_texture: levels function
.IP "\(bu" 2
Added spearate functions to use both nagative one and zero near clip plans #680
.IP "\(bu" 2
Added GLM_FORCE_SINGLE_ONLY to use GLM on platforms that don't support double #627
.IP "\(bu" 2
Added GTX_easing for interpolation functions #761
.PP
.PP
.SS "Improvements:"
.PP
.IP "\(bu" 2
No more default initialization of vector, matrix and quaternion types
.IP "\(bu" 2
Added lowp variant of GTC_color_space convertLinearToSRGB #419
.IP "\(bu" 2
Replaced the manual by a markdown version #458
.IP "\(bu" 2
Improved API documentation #668
.IP "\(bu" 2
Optimized GTC_packing implementation
.IP "\(bu" 2
Optimized GTC_noise functions
.IP "\(bu" 2
Optimized GTC_color_space HSV to RGB conversions
.IP "\(bu" 2
Optimised GTX_color_space_YCoCg YCoCgR conversions
.IP "\(bu" 2
Optimized GTX_matrix_interpolation axisAngle function
.IP "\(bu" 2
Added FAQ 12: Windows headers cause build errors\&.\&.\&. #557
.IP "\(bu" 2
Removed GCC shadow warnings #595
.IP "\(bu" 2
Added error for including of different versions of GLM #619
.IP "\(bu" 2
Added GLM_FORCE_IGNORE_VERSION to ignore error caused by including different version of GLM #619
.IP "\(bu" 2
Reduced warnings when using very strict compilation flags #646
.IP "\(bu" 2
\fBlength()\fP member functions are constexpr #657
.IP "\(bu" 2
Added support of -Weverything with Clang #646
.IP "\(bu" 2
Improved exponential function test coverage
.IP "\(bu" 2
Enabled warnings as error with Clang unit tests
.IP "\(bu" 2
Conan package is an external repository: https://github.com/bincrafters/conan-glm
.IP "\(bu" 2
Clarify quat_cast documentation, applying on pure rotation matrices #759
.PP
.PP
.SS "Fixes:"
.PP
.IP "\(bu" 2
Removed doxygen references to GTC_half_float which was removed in 0\&.9\&.4
.IP "\(bu" 2
Fixed \fBglm::decompose\fP #448
.IP "\(bu" 2
Fixed intersectRayTriangle #6
.IP "\(bu" 2
Fixed dual quaternion != operator #629
.IP "\(bu" 2
Fixed usused variable warning in GTX_spline #618
.IP "\(bu" 2
Fixed references to GLM_FORCE_RADIANS which was removed #642
.IP "\(bu" 2
Fixed \fBglm::fastInverseSqrt\fP to use fast inverse square #640
.IP "\(bu" 2
Fixed axisAngle NaN #638
.IP "\(bu" 2
Fixed integer pow from GTX_integer with null exponent #658
.IP "\(bu" 2
Fixed quat normalize build error #656
.IP "\(bu" 2
Fixed Visual C++ 2017\&.2 warning regarding __has_feature definision #655
.IP "\(bu" 2
Fixed documentation warnings
.IP "\(bu" 2
Fixed GLM_HAS_OPENMP when OpenMP is not enabled
.IP "\(bu" 2
Fixed Better follow GLSL min and max specification #372
.IP "\(bu" 2
Fixed quaternion constructor from two vectors special cases #469
.IP "\(bu" 2
Fixed \fBglm::to_string\fP on quaternions wrong components order #681
.IP "\(bu" 2
Fixed acsch #698
.IP "\(bu" 2
Fixed isnan on CUDA #727
.PP
.PP
.SS "Deprecation:"
.PP
.IP "\(bu" 2
Requires Visual Studio 2013, GCC 4\&.7, Clang 3\&.4, Cuda 7, ICC 2013 or a C++11 compiler
.IP "\(bu" 2
Removed GLM_GTX_simd_vec4 extension
.IP "\(bu" 2
Removed GLM_GTX_simd_mat4 extension
.IP "\(bu" 2
Removed GLM_GTX_simd_quat extension
.IP "\(bu" 2
Removed GLM_SWIZZLE, use GLM_FORCE_SWIZZLE instead
.IP "\(bu" 2
Removed GLM_MESSAGES, use GLM_FORCE_MESSAGES instead
.IP "\(bu" 2
Removed GLM_DEPTH_ZERO_TO_ONE, use GLM_FORCE_DEPTH_ZERO_TO_ONE instead
.IP "\(bu" 2
Removed GLM_LEFT_HANDED, use GLM_FORCE_LEFT_HANDED instead
.IP "\(bu" 2
Removed GLM_FORCE_NO_CTOR_INIT
.IP "\(bu" 2
Removed glm::uninitialize
.PP
.PP
.PP
 
.SS "\fCGLM 0\&.9\&.8\&.5\fP - 2017-08-16"
.PP
.SS "Features:"
.PP
.IP "\(bu" 2
Added Conan package support #647
.PP
.PP
.SS "Fixes:"
.PP
.IP "\(bu" 2
Fixed Clang version detection from source #608
.IP "\(bu" 2
Fixed packF3x9_E1x5 exponent packing #614
.IP "\(bu" 2
Fixed build error min and max specializations with integer #616
.IP "\(bu" 2
Fixed simd_mat4 build error #652
.PP
.PP
.PP
 
.SS "\fCGLM 0\&.9\&.8\&.4\fP - 2017-01-22"
.PP
.SS "Fixes:"
.PP
.IP "\(bu" 2
Fixed GTC_packing test failing on GCC x86 due to denorms #212 #577
.IP "\(bu" 2
Fixed POPCNT optimization build in Clang #512
.IP "\(bu" 2
Fixed intersectRayPlane returns true in parallel case #578
.IP "\(bu" 2
Fixed GCC 6\&.2 compiler warnings #580
.IP "\(bu" 2
Fixed GTX_matrix_decompose decompose #582 #448
.IP "\(bu" 2
Fixed GCC 4\&.5 and older build #566
.IP "\(bu" 2
Fixed Visual C++ internal error when declaring a global vec type with siwzzle expression enabled #594
.IP "\(bu" 2
Fixed GLM_FORCE_CXX11 with Clang and libstlc++ which wasn't using C++11 STL features\&. #604
.PP
.PP
.PP
 
.SS "\fCGLM 0\&.9\&.8\&.3\fP - 2016-11-12"
.PP
.SS "Improvements:"
.PP
.IP "\(bu" 2
Broader support of GLM_FORCE_UNRESTRICTED_GENTYPE #378
.PP
.PP
.SS "Fixes:"
.PP
.IP "\(bu" 2
Fixed Android build error with C++11 compiler but C++98 STL #284 #564
.IP "\(bu" 2
Fixed GTX_transform2 shear* functions #403
.IP "\(bu" 2
Fixed interaction between GLM_FORCE_UNRESTRICTED_GENTYPE and ortho function #568
.IP "\(bu" 2
Fixed bitCount with AVX on 32 bit builds #567
.IP "\(bu" 2
Fixed CMake find_package with version specification #572 #573
.PP
.PP
.PP
 
.SS "\fCGLM 0\&.9\&.8\&.2\fP - 2016-11-01"
.PP
.SS "Improvements:"
.PP
.IP "\(bu" 2
Added Visual C++ 15 detection
.IP "\(bu" 2
Added Clang 4\&.0 detection
.IP "\(bu" 2
Added warning messages when using GLM_FORCE_CXX** but the compiler is known to not fully support the requested C++ version #555
.IP "\(bu" 2
Refactored GLM_COMPILER_VC values
.IP "\(bu" 2
Made quat, vec, mat type component \fBlength()\fP static #565
.PP
.PP
.SS "Fixes:"
.PP
.IP "\(bu" 2
Fixed Visual C++ constexpr build error #555, #556
.PP
.PP
.PP
 
.SS "\fCGLM 0\&.9\&.8\&.1\fP - 2016-09-25"
.PP
.SS "Improvements:"
.PP
.IP "\(bu" 2
Optimized quaternion log function #554
.PP
.PP
.SS "Fixes:"
.PP
.IP "\(bu" 2
Fixed GCC warning filtering, replaced -pedantic by -Wpedantic
.IP "\(bu" 2
Fixed SIMD faceforward bug\&. #549
.IP "\(bu" 2
Fixed GCC 4\&.8 with C++11 compilation option #550
.IP "\(bu" 2
Fixed Visual Studio aligned type W4 warning #548
.IP "\(bu" 2
Fixed packing/unpacking function fixed for 5_6_5 and 5_5_5_1 #552
.PP
.PP
.PP
 
.SS "\fCGLM 0\&.9\&.8\&.0\fP - 2016-09-11"
.PP
.SS "Features:"
.PP
.IP "\(bu" 2
Added right and left handed projection and clip control support #447 #415 #119
.IP "\(bu" 2
Added compNormalize and compScale functions to GTX_component_wise
.IP "\(bu" 2
Added packF3x9_E1x5 and unpackF3x9_E1x5 to GTC_packing for RGB9E5 #416
.IP "\(bu" 2
Added (un)packHalf to GTC_packing
.IP "\(bu" 2
Added (un)packUnorm and (un)packSnorm to GTC_packing
.IP "\(bu" 2
Added 16bit pack and unpack to GTC_packing
.IP "\(bu" 2
Added 8bit pack and unpack to GTC_packing
.IP "\(bu" 2
Added missing bvec* && and || operators
.IP "\(bu" 2
Added iround and uround to GTC_integer, fast round on positive values
.IP "\(bu" 2
Added raw SIMD API
.IP "\(bu" 2
Added 'aligned' qualifiers
.IP "\(bu" 2
Added GTC_type_aligned with aligned \fIvec\fP types
.IP "\(bu" 2
Added GTC_functions extension
.IP "\(bu" 2
Added quaternion version of isnan and isinf #521
.IP "\(bu" 2
Added lowestBitValue to GTX_bit #536
.IP "\(bu" 2
Added GLM_FORCE_UNRESTRICTED_GENTYPE allowing non basic genType #543
.PP
.PP
.SS "Improvements:"
.PP
.IP "\(bu" 2
Improved SIMD and swizzle operators interactions with GCC and Clang #474
.IP "\(bu" 2
Improved GTC_random linearRand documentation
.IP "\(bu" 2
Improved GTC_reciprocal documentation
.IP "\(bu" 2
Improved GLM_FORCE_EXPLICIT_CTOR coverage #481
.IP "\(bu" 2
Improved OpenMP support detection for Clang, GCC, ICC and VC
.IP "\(bu" 2
Improved GTX_wrap for SIMD friendliness
.IP "\(bu" 2
Added constexpr for \fIvec\fP, \fImat\fP, \fIquat\fP and \fIdual_quat\fP types #493
.IP "\(bu" 2
Added NEON instruction set detection
.IP "\(bu" 2
Added MIPS CPUs detection
.IP "\(bu" 2
Added PowerPC CPUs detection
.IP "\(bu" 2
Use Cuda built-in function for abs function implementation with Cuda compiler
.IP "\(bu" 2
Factorized GLM_COMPILER_LLVM and GLM_COMPILER_APPLE_CLANG into GLM_COMPILER_CLANG
.IP "\(bu" 2
No more warnings for use of long long
.IP "\(bu" 2
Added more information to build messages
.PP
.PP
.SS "Fixes:"
.PP
.IP "\(bu" 2
Fixed GTX_extended_min_max filename typo #386
.IP "\(bu" 2
Fixed intersectRayTriangle to not do any unintentional backface culling
.IP "\(bu" 2
Fixed long long warnings when using C++98 on GCC and Clang #482
.IP "\(bu" 2
Fixed sign with signed integer function on non-x86 architecture
.IP "\(bu" 2
Fixed strict aliasing warnings #473
.IP "\(bu" 2
Fixed missing vec1 overload to length2 and distance2 functions #431
.IP "\(bu" 2
Fixed GLM test '/fp:fast' and '/Za' command-line options are incompatible
.IP "\(bu" 2
Fixed quaterion to mat3 cast function mat3_cast from GTC_quaternion #542
.IP "\(bu" 2
Fixed GTX_io for Cuda #547 #546
.PP
.PP
.SS "Deprecation:"
.PP
.IP "\(bu" 2
Removed GLM_FORCE_SIZE_FUNC define
.IP "\(bu" 2
Deprecated GLM_GTX_simd_vec4 extension
.IP "\(bu" 2
Deprecated GLM_GTX_simd_mat4 extension
.IP "\(bu" 2
Deprecated GLM_GTX_simd_quat extension
.IP "\(bu" 2
Deprecated GLM_SWIZZLE, use GLM_FORCE_SWIZZLE instead
.IP "\(bu" 2
Deprecated GLM_MESSAGES, use GLM_FORCE_MESSAGES instead
.PP
.PP
.PP
 
.SS "\fCGLM 0\&.9\&.7\&.6\fP - 2016-07-16"
.PP
.SS "Improvements:"
.PP
.IP "\(bu" 2
Added pkg-config file #509
.IP "\(bu" 2
Updated list of compiler versions detected
.IP "\(bu" 2
Improved C++ 11 STL detection #523
.PP
.PP
.SS "Fixes:"
.PP
.IP "\(bu" 2
Fixed STL for C++11 detection on ICC #510
.IP "\(bu" 2
Fixed missing vec1 overload to length2 and distance2 functions #431
.IP "\(bu" 2
Fixed long long warnings when using C++98 on GCC and Clang #482
.IP "\(bu" 2
Fixed scalar reciprocal functions (GTC_reciprocal) #520
.PP
.PP
.PP
 
.SS "\fCGLM 0\&.9\&.7\&.5\fP - 2016-05-24"
.PP
.SS "Improvements:"
.PP
.IP "\(bu" 2
Added Visual C++ Clang toolset detection
.PP
.PP
.SS "Fixes:"
.PP
.IP "\(bu" 2
Fixed uaddCarry warning #497
.IP "\(bu" 2
Fixed roundPowerOfTwo and floorPowerOfTwo #503
.IP "\(bu" 2
Fixed Visual C++ SIMD instruction set automatic detection in 64 bits
.IP "\(bu" 2
Fixed to_string when used with GLM_FORCE_INLINE #506
.IP "\(bu" 2
Fixed GLM_FORCE_INLINE with binary vec4 operators
.IP "\(bu" 2
Fixed GTX_extended_min_max filename typo #386
.IP "\(bu" 2
Fixed intersectRayTriangle to not do any unintentional backface culling
.PP
.PP
.PP
 
.SS "\fCGLM 0\&.9\&.7\&.4\fP - 2016-03-19"
.PP
.SS "Fixes:"
.PP
.IP "\(bu" 2
Fixed asinh and atanh warning with C++98 STL #484
.IP "\(bu" 2
Fixed polar coordinates function latitude #485
.IP "\(bu" 2
Fixed outerProduct defintions and operator signatures for mat2x4 and vec4 #475
.IP "\(bu" 2
Fixed eulerAngles precision error, returns NaN #451
.IP "\(bu" 2
Fixed undefined reference errors #489
.IP "\(bu" 2
Fixed missing GLM_PLATFORM_CYGWIN declaration #495
.IP "\(bu" 2
Fixed various undefined reference errors #490
.PP
.PP
.PP
 
.SS "\fCGLM 0\&.9\&.7\&.3\fP - 2016-02-21"
.PP
.SS "Improvements:"
.PP
.IP "\(bu" 2
Added AVX512 detection
.PP
.PP
.SS "Fixes:"
.PP
.IP "\(bu" 2
Fixed CMake policy warning
.IP "\(bu" 2
Fixed GCC 6\&.0 detection #477
.IP "\(bu" 2
Fixed Clang build on Windows #479
.IP "\(bu" 2
Fixed 64 bits constants warnings on GCC #463
.PP
.PP
.PP
 
.SS "\fCGLM 0\&.9\&.7\&.2\fP - 2016-01-03"
.PP
.SS "Fixes:"
.PP
.IP "\(bu" 2
Fixed GTC_round floorMultiple/ceilMultiple #412
.IP "\(bu" 2
Fixed GTC_packing unpackUnorm3x10_1x2 #414
.IP "\(bu" 2
Fixed GTC_matrix_inverse affineInverse #192
.IP "\(bu" 2
Fixed ICC on Linux build errors #449
.IP "\(bu" 2
Fixed ldexp and frexp compilation errors
.IP "\(bu" 2
Fixed 'Declaration shadows a field' warning #468
.IP "\(bu" 2
Fixed 'GLM_COMPILER_VC2005 is not defined' warning #468
.IP "\(bu" 2
Fixed various 'X is not defined' warnings #468
.IP "\(bu" 2
Fixed missing unary + operator #435
.IP "\(bu" 2
Fixed Cygwin build errors when using C++11 #405
.PP
.PP
.PP
 
.SS "\fCGLM 0\&.9\&.7\&.1\fP - 2015-09-07"
.PP
.SS "Improvements:"
.PP
.IP "\(bu" 2
Improved constexpr for constant functions coverage #198
.IP "\(bu" 2
Added to_string for quat and dual_quat in GTX_string_cast #375
.IP "\(bu" 2
Improved overall execution time of unit tests #396
.PP
.PP
.SS "Fixes:"
.PP
.IP "\(bu" 2
Fixed strict alignment warnings #235 #370
.IP "\(bu" 2
Fixed link errors on compilers not supported default function #377
.IP "\(bu" 2
Fixed compilation warnings in vec4
.IP "\(bu" 2
Fixed non-identity quaternions for equal vectors #234
.IP "\(bu" 2
Fixed excessive GTX_fast_trigonometry execution time #396
.IP "\(bu" 2
Fixed Visual Studio 2015 'hides class member' warnings #394
.IP "\(bu" 2
Fixed builtin bitscan never being used #392
.IP "\(bu" 2
Removed unused func_noise\&.* files #398
.PP
.PP
.PP
 
.SS "\fCGLM 0\&.9\&.7\&.0\fP - 2015-08-02"
.PP
.SS "Features:"
.PP
.IP "\(bu" 2
Added GTC_color_space: convertLinearToSRGB and convertSRGBToLinear functions
.IP "\(bu" 2
Added 'fmod' overload to GTX_common with tests #308
.IP "\(bu" 2
Left handed perspective and lookAt functions #314
.IP "\(bu" 2
Added functions eulerAngleXYZ and extractEulerAngleXYZ #311
.IP "\(bu" 2
Added <\fBglm/gtx/hash\&.hpp\fP> to perform std::hash on GLM types #320 #367
.IP "\(bu" 2
Added <\fBglm/gtx/wrap\&.hpp\fP> for texcoord wrapping
.IP "\(bu" 2
Added static components and precision members to all vector and quat types #350
.IP "\(bu" 2
Added \&.gitignore #349
.IP "\(bu" 2
Added support of defaulted functions to GLM types, to use them in unions #366
.PP
.PP
.SS "Improvements:"
.PP
.IP "\(bu" 2
Changed usage of __has_include to support Intel compiler #307
.IP "\(bu" 2
Specialized integer implementation of YCoCg-R #310
.IP "\(bu" 2
Don't show status message in 'FindGLM' if 'QUIET' option is set\&. #317
.IP "\(bu" 2
Added master branch continuous integration service on Linux 64 #332
.IP "\(bu" 2
Clarified manual regarding angle unit in GLM, added FAQ 11 #326
.IP "\(bu" 2
Updated list of compiler versions
.PP
.PP
.SS "Fixes:"
.PP
.IP "\(bu" 2
Fixed default precision for quat and dual_quat type #312
.IP "\(bu" 2
Fixed (u)int64 MSB/LSB handling on BE archs #306
.IP "\(bu" 2
Fixed multi-line comment warning in g++\&. #315
.IP "\(bu" 2
Fixed specifier removal by 'std::make_pair<>' #333
.IP "\(bu" 2
Fixed perspective fovy argument documentation #327
.IP "\(bu" 2
Removed -m64 causing build issues on Linux 32 #331
.IP "\(bu" 2
Fixed isfinite with C++98 compilers #343
.IP "\(bu" 2
Fixed Intel compiler build error on Linux #354
.IP "\(bu" 2
Fixed use of libstdc++ with Clang #351
.IP "\(bu" 2
Fixed quaternion pow #346
.IP "\(bu" 2
Fixed decompose warnings #373
.IP "\(bu" 2
Fixed matrix conversions #371
.PP
.PP
.SS "Deprecation:"
.PP
.IP "\(bu" 2
Removed integer specification for 'mod' in GTC_integer #308
.IP "\(bu" 2
Removed GTX_multiple, replaced by GTC_round
.PP
.PP
.PP
 
.SS "\fCGLM 0\&.9\&.6\&.3\fP - 2015-02-15"
.PP
.IP "\(bu" 2
Fixed Android doesn't have C++ 11 STL #284
.PP
.PP
.PP
 
.SS "\fCGLM 0\&.9\&.6\&.2\fP - 2015-02-15"
.PP
.SS "Features:"
.PP
.IP "\(bu" 2
Added display of GLM version with other GLM_MESSAGES
.IP "\(bu" 2
Added ARM instruction set detection
.PP
.PP
.SS "Improvements:"
.PP
.IP "\(bu" 2
Removed assert for perspective with zFar < zNear #298
.IP "\(bu" 2
Added Visual Studio natvis support for vec1, quat and dualqual types
.IP "\(bu" 2
Cleaned up C++11 feature detections
.IP "\(bu" 2
Clarify GLM licensing
.PP
.PP
.SS "Fixes:"
.PP
.IP "\(bu" 2
Fixed faceforward build #289
.IP "\(bu" 2
Fixed conflict with Xlib #define True 1 #293
.IP "\(bu" 2
Fixed decompose function VS2010 templating issues #294
.IP "\(bu" 2
Fixed mat4x3 = mat2x3 * mat4x2 operator #297
.IP "\(bu" 2
Fixed warnings in F2x11_1x10 packing function in GTC_packing #295
.IP "\(bu" 2
Fixed Visual Studio natvis support for vec4 #288
.IP "\(bu" 2
Fixed GTC_packing \fIpack*norm*x\fP build and added tests #292
.IP "\(bu" 2
Disabled GTX_scalar_multiplication for GCC, failing to build tests #242
.IP "\(bu" 2
Fixed Visual C++ 2015 constexpr errors: Disabled only partial support
.IP "\(bu" 2
Fixed functions not inlined with Clang #302
.IP "\(bu" 2
Fixed memory corruption (undefined behaviour) #303
.PP
.PP
.PP
 
.SS "\fCGLM 0\&.9\&.6\&.1\fP - 2014-12-10"
.PP
.SS "Features:"
.PP
.IP "\(bu" 2
Added GLM_LANG_CXX14_FLAG and GLM_LANG_CXX1Z_FLAG language feature flags
.IP "\(bu" 2
Added C++14 detection
.PP
.PP
.SS "Improvements:"
.PP
.IP "\(bu" 2
Clean up GLM_MESSAGES compilation log to report only detected capabilities
.PP
.PP
.SS "Fixes:"
.PP
.IP "\(bu" 2
Fixed scalar uaddCarry build error with Cuda #276
.IP "\(bu" 2
Fixed C++11 explicit conversion operators detection #282
.IP "\(bu" 2
Fixed missing explicit conversion when using integer log2 with *vec1 types
.IP "\(bu" 2
Fixed 64 bits integer GTX_string_cast to_string on VC 32 bit compiler
.IP "\(bu" 2
Fixed Android build issue, STL C++11 is not supported by the NDK #284
.IP "\(bu" 2
Fixed unsupported _BitScanForward64 and _BitScanReverse64 in VC10
.IP "\(bu" 2
Fixed Visual C++ 32 bit build #283
.IP "\(bu" 2
Fixed GLM_FORCE_SIZE_FUNC pragma message
.IP "\(bu" 2
Fixed C++98 only build
.IP "\(bu" 2
Fixed conflict between GTX_compatibility and GTC_quaternion #286
.IP "\(bu" 2
Fixed C++ language restriction using GLM_FORCE_CXX**
.PP
.PP
.PP
 
.SS "\fCGLM 0\&.9\&.6\&.0\fP - 2014-11-30"
.PP
.SS "Features:"
.PP
.IP "\(bu" 2
Exposed template vector and matrix types in 'glm' namespace #239, #244
.IP "\(bu" 2
Added GTX_scalar_multiplication for C++ 11 compiler only #242
.IP "\(bu" 2
Added GTX_range for C++ 11 compiler only #240
.IP "\(bu" 2
Added closestPointOnLine function for tvec2 to GTX_closest_point #238
.IP "\(bu" 2
Added GTC_vec1 extension, \fIvec1 support to *vec\fP types
.IP "\(bu" 2
Updated GTX_associated_min_max with vec1 support
.IP "\(bu" 2
Added support of precision and integers to linearRand #230
.IP "\(bu" 2
Added Integer types support to GTX_string_cast #249
.IP "\(bu" 2
Added vec3 slerp #237
.IP "\(bu" 2
Added GTX_common with isdenomal #223
.IP "\(bu" 2
Added GLM_FORCE_SIZE_FUNC to replace \&.\fBlength()\fP by \&.size() #245
.IP "\(bu" 2
Added GLM_FORCE_NO_CTOR_INIT
.IP "\(bu" 2
Added 'uninitialize' to explicitly not initialize a GLM type
.IP "\(bu" 2
Added GTC_bitfield extension, promoted GTX_bit
.IP "\(bu" 2
Added GTC_integer extension, promoted GTX_bit and GTX_integer
.IP "\(bu" 2
Added GTC_round extension, promoted GTX_bit
.IP "\(bu" 2
Added GLM_FORCE_EXPLICIT_CTOR to require explicit type conversions #269
.IP "\(bu" 2
Added GTX_type_aligned for aligned vector, matrix and quaternion types
.PP
.PP
.SS "Improvements:"
.PP
.IP "\(bu" 2
Rely on C++11 to implement isinf and isnan
.IP "\(bu" 2
Removed GLM_FORCE_CUDA, Cuda is implicitly detected
.IP "\(bu" 2
Separated Apple Clang and LLVM compiler detection
.IP "\(bu" 2
Used pragma once
.IP "\(bu" 2
Undetected C++ compiler automatically compile with GLM_FORCE_CXX98 and GLM_FORCE_PURE
.IP "\(bu" 2
Added not function (from GLSL specification) on VC12
.IP "\(bu" 2
Optimized bitfieldReverse and bitCount functions
.IP "\(bu" 2
Optimized findLSB and findMSB functions\&.
.IP "\(bu" 2
Optimized matrix-vector multiple performance with Cuda #257, #258
.IP "\(bu" 2
Reduced integer type redifinitions #233
.IP "\(bu" 2
Rewrited of GTX_fast_trigonometry #264 #265
.IP "\(bu" 2
Made types trivially copyable #263
.IP "\(bu" 2
Removed <iostream> in GLM tests
.IP "\(bu" 2
Used std features within GLM without redeclaring
.IP "\(bu" 2
Optimized cot function #272
.IP "\(bu" 2
Optimized sign function #272
.IP "\(bu" 2
Added explicit cast from quat to mat3 and mat4 #275
.PP
.PP
.SS "Fixes:"
.PP
.IP "\(bu" 2
Fixed std::nextafter not supported with C++11 on Android #217
.IP "\(bu" 2
Fixed missing value_type for dual quaternion
.IP "\(bu" 2
Fixed return type of dual quaternion length
.IP "\(bu" 2
Fixed infinite loop in isfinite function with GCC #221
.IP "\(bu" 2
Fixed Visual Studio 14 compiler warnings
.IP "\(bu" 2
Fixed implicit conversion from another tvec2 type to another tvec2 #241
.IP "\(bu" 2
Fixed lack of consistency of quat and dualquat constructors
.IP "\(bu" 2
Fixed uaddCarray #253
.IP "\(bu" 2
Fixed float comparison warnings #270
.PP
.PP
.SS "Deprecation:"
.PP
.IP "\(bu" 2
Requires Visual Studio 2010, GCC 4\&.2, Apple Clang 4\&.0, LLVM 3\&.0, Cuda 4, ICC 2013 or a C++98 compiler
.IP "\(bu" 2
Removed degrees for function parameters
.IP "\(bu" 2
Removed GLM_FORCE_RADIANS, active by default
.IP "\(bu" 2
Removed VC 2005 / 8 and 2008 / 9 support
.IP "\(bu" 2
Removed GCC 3\&.4 to 4\&.3 support
.IP "\(bu" 2
Removed LLVM GCC support
.IP "\(bu" 2
Removed LLVM 2\&.6 to 3\&.1 support
.IP "\(bu" 2
Removed CUDA 3\&.0 to 3\&.2 support
.PP
.PP
.PP
 
.SS "\fCGLM 0\&.9\&.5\&.4 - 2014-06-21\fP"
.PP
.IP "\(bu" 2
Fixed non-utf8 character #196
.IP "\(bu" 2
Added FindGLM install for CMake #189
.IP "\(bu" 2
Fixed GTX_color_space - saturation #195
.IP "\(bu" 2
Fixed \fBglm::isinf\fP and \fBglm::isnan\fP for with Android NDK 9d #191
.IP "\(bu" 2
Fixed builtin GLM_ARCH_SSE4 #204
.IP "\(bu" 2
Optimized Quaternion vector rotation #205
.IP "\(bu" 2
Fixed missing doxygen tag #211
.IP "\(bu" 2
Fixed instruction set detection with Clang #158
.IP "\(bu" 2
Fixed orientate3 function #207
.IP "\(bu" 2
Fixed lerp when cosTheta is close to 1 in quaternion slerp #210
.IP "\(bu" 2
Added GTX_io for io with <iostream> #144
.IP "\(bu" 2
Fixed fastDistance ambiguity #215
.IP "\(bu" 2
Fixed tweakedInfinitePerspective #208 and added user-defined epsilon to tweakedInfinitePerspective
.IP "\(bu" 2
Fixed std::copy and std::vector with GLM types #214
.IP "\(bu" 2
Fixed strict aliasing issues #212, #152
.IP "\(bu" 2
Fixed std::nextafter not supported with C++11 on Android #213
.IP "\(bu" 2
Fixed corner cases in exp and log functions for quaternions #199
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.5\&.3 - 2014-04-02"
.PP
.IP "\(bu" 2
Added instruction set auto detection with Visual C++ using _M_IX86_FP - /arch compiler argument
.IP "\(bu" 2
Fixed GTX_raw_data code dependency
.IP "\(bu" 2
Fixed GCC instruction set detection
.IP "\(bu" 2
Added GLM_GTX_matrix_transform_2d extension (#178, #176)
.IP "\(bu" 2
Fixed CUDA issues (#169, #168, #183, #182)
.IP "\(bu" 2
Added support for all extensions but GTX_string_cast to CUDA
.IP "\(bu" 2
Fixed strict aliasing warnings in GCC 4\&.8\&.1 / Android NDK 9c (#152)
.IP "\(bu" 2
Fixed missing bitfieldInterleave definisions
.IP "\(bu" 2
Fixed usubBorrow (#171)
.IP "\(bu" 2
Fixed eulerAngle*** not consistent for right-handed coordinate system (#173)
.IP "\(bu" 2
Added full tests for eulerAngle*** functions (#173)
.IP "\(bu" 2
Added workaround for a CUDA compiler bug (#186, #185)
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.5\&.2 - 2014-02-08"
.PP
.IP "\(bu" 2
Fixed initializer list ambiguity (#159, #160)
.IP "\(bu" 2
Fixed warnings with the Android NDK 9c
.IP "\(bu" 2
Fixed non power of two matrix products
.IP "\(bu" 2
Fixed mix function link error
.IP "\(bu" 2
Fixed SSE code included in GLM tests on 'pure' platforms
.IP "\(bu" 2
Fixed undefined reference to fastInverseSqrt (#161)
.IP "\(bu" 2
Fixed GLM_FORCE_RADIANS with <\fBglm/ext\&.hpp\fP> build error (#165)
.IP "\(bu" 2
Fix dot product clamp range for vector angle functions\&. (#163)
.IP "\(bu" 2
Tentative fix for strict aliasing warning in GCC 4\&.8\&.1 / Android NDK 9c (#152)
.IP "\(bu" 2
Fixed GLM_GTC_constants description brief (#162)
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.5\&.1 - 2014-01-11"
.PP
.IP "\(bu" 2
Fixed angle and orientedAngle that sometimes return NaN values (#145)
.IP "\(bu" 2
Deprecated degrees for function parameters and display a message
.IP "\(bu" 2
Added possible static_cast conversion of GLM types (#72)
.IP "\(bu" 2
Fixed error 'inverse' is not a member of 'glm' from \fBglm::unProject\fP (#146)
.IP "\(bu" 2
Fixed mismatch between some declarations and definitions
.IP "\(bu" 2
Fixed inverse link error when using namespace glm; (#147)
.IP "\(bu" 2
Optimized matrix inverse and division code (#149)
.IP "\(bu" 2
Added intersectRayPlane function (#153)
.IP "\(bu" 2
Fixed outerProduct return type (#155)
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.5\&.0 - 2013-12-25"
.PP
.IP "\(bu" 2
Added forward declarations (\fBglm/fwd\&.hpp\fP) for faster compilations
.IP "\(bu" 2
Added per feature headers
.IP "\(bu" 2
Minimized GLM internal dependencies
.IP "\(bu" 2
Improved Intel Compiler detection
.IP "\(bu" 2
Added bitfieldInterleave and _mm_bit_interleave_si128 functions
.IP "\(bu" 2
Added GTX_scalar_relational
.IP "\(bu" 2
Added GTX_dual_quaternion
.IP "\(bu" 2
Added rotation function to GTX_quaternion (#22)
.IP "\(bu" 2
Added precision variation of each type
.IP "\(bu" 2
Added quaternion comparison functions
.IP "\(bu" 2
Fixed GTX_multiple for negative value
.IP "\(bu" 2
Removed GTX_ocl_type extension
.IP "\(bu" 2
Fixed post increment and decrement operators
.IP "\(bu" 2
Fixed perspective with zNear == 0 (#71)
.IP "\(bu" 2
Removed l-value swizzle operators
.IP "\(bu" 2
Cleaned up compiler detection code for unsupported compilers
.IP "\(bu" 2
Replaced C cast by C++ casts
.IP "\(bu" 2
Fixed \&.\fBlength()\fP that should return a int and not a size_t
.IP "\(bu" 2
Added GLM_FORCE_SIZE_T_LENGTH and glm::length_t
.IP "\(bu" 2
Removed unnecessary conversions
.IP "\(bu" 2
Optimized packing and unpacking functions
.IP "\(bu" 2
Removed the normalization of the up argument of lookAt function (#114)
.IP "\(bu" 2
Added low precision specializations of inversesqrt
.IP "\(bu" 2
Fixed ldexp and frexp implementations
.IP "\(bu" 2
Increased assert coverage
.IP "\(bu" 2
Increased static_assert coverage
.IP "\(bu" 2
Replaced GLM traits by STL traits when possible
.IP "\(bu" 2
Allowed including individual core feature
.IP "\(bu" 2
Increased unit tests completness
.IP "\(bu" 2
Added creating of a quaternion from two vectors
.IP "\(bu" 2
Added C++11 initializer lists
.IP "\(bu" 2
Fixed umulExtended and imulExtended implementations for vector types (#76)
.IP "\(bu" 2
Fixed CUDA coverage for GTC extensions
.IP "\(bu" 2
Added GTX_io extension
.IP "\(bu" 2
Improved GLM messages enabled when defining GLM_MESSAGES
.IP "\(bu" 2
Hidden matrix _inverse function implementation detail into private section
.PP
.PP
.PP
 
.SS "\fCGLM 0\&.9\&.4\&.6\fP - 2013-09-20"
.PP
.IP "\(bu" 2
Fixed detection to select the last known compiler if newer version #106
.IP "\(bu" 2
Fixed is_int and is_uint code duplication with GCC and C++11 #107
.IP "\(bu" 2
Fixed test suite build while using Clang in C++11 mode
.IP "\(bu" 2
Added c++1y mode support in CMake test suite
.IP "\(bu" 2
Removed ms extension mode to CMake when no using Visual C++
.IP "\(bu" 2
Added pedantic mode to CMake test suite for Clang and GCC
.IP "\(bu" 2
Added use of GCC frontend on Unix for ICC and Visual C++ fronted on Windows for ICC
.IP "\(bu" 2
Added compilation errors for unsupported compiler versions
.IP "\(bu" 2
Fixed \fBglm::orientation\fP with GLM_FORCE_RADIANS defined #112
.IP "\(bu" 2
Fixed const ref issue on assignment operator taking a scalar parameter #116
.IP "\(bu" 2
Fixed \fBglm::eulerAngleY\fP implementation #117
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.4\&.5 - 2013-08-12"
.PP
.IP "\(bu" 2
Fixed CUDA support
.IP "\(bu" 2
Fixed inclusion of intrinsics in 'pure' mode #92
.IP "\(bu" 2
Fixed language detection on GCC when the C++0x mode isn't enabled #95
.IP "\(bu" 2
Fixed issue #97: register is deprecated in C++11
.IP "\(bu" 2
Fixed issue #96: CUDA issues
.IP "\(bu" 2
Added Windows CE detection #92
.IP "\(bu" 2
Added missing value_ptr for quaternions #99
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.4\&.4 - 2013-05-29"
.PP
.IP "\(bu" 2
Fixed slerp when costheta is close to 1 #65
.IP "\(bu" 2
Fixed mat4x2 value_type constructor #70
.IP "\(bu" 2
Fixed glm\&.natvis for Visual C++ 12 #82
.IP "\(bu" 2
Added assert in inversesqrt to detect division by zero #61
.IP "\(bu" 2
Fixed missing swizzle operators #86
.IP "\(bu" 2
Fixed CUDA warnings #86
.IP "\(bu" 2
Fixed GLM natvis for VC11 #82
.IP "\(bu" 2
Fixed GLM_GTX_multiple with negative values #79
.IP "\(bu" 2
Fixed \fBglm::perspective\fP when zNear is zero #71
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.4\&.3 - 2013-03-20"
.PP
.IP "\(bu" 2
Detected qualifier for Clang
.IP "\(bu" 2
Fixed C++11 mode for GCC, couldn't be enabled without MS extensions
.IP "\(bu" 2
Fixed squad, intermediate and exp quaternion functions
.IP "\(bu" 2
Fixed GTX_polar_coordinates euclidean function, takes a \fBvec2\fP instead of a vec3
.IP "\(bu" 2
Clarify the license applying on the manual
.IP "\(bu" 2
Added a docx copy of the manual
.IP "\(bu" 2
Fixed GLM_GTX_matrix_interpolation
.IP "\(bu" 2
Fixed isnan and isinf on Android with Clang
.IP "\(bu" 2
Autodetected C++ version using __cplusplus value
.IP "\(bu" 2
Fixed mix for bool and bvec* third parameter
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.4\&.2 - 2013-02-14"
.PP
.IP "\(bu" 2
Fixed compAdd from GTX_component_wise
.IP "\(bu" 2
Fixed SIMD support for Intel compiler on Windows
.IP "\(bu" 2
Fixed isnan and isinf for CUDA compiler
.IP "\(bu" 2
Fixed GLM_FORCE_RADIANS on \fBglm::perspective\fP
.IP "\(bu" 2
Fixed GCC warnings
.IP "\(bu" 2
Fixed packDouble2x32 on Xcode
.IP "\(bu" 2
Fixed mix for vec4 SSE implementation
.IP "\(bu" 2
Fixed 0x2013 dash character in comments that cause issue in Windows Japanese mode
.IP "\(bu" 2
Fixed documentation warnings
.IP "\(bu" 2
Fixed CUDA warnings
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.4\&.1 - 2012-12-22"
.PP
.IP "\(bu" 2
Improved half support: -0\&.0 case and implicit conversions
.IP "\(bu" 2
Fixed Intel Composer Compiler support on Linux
.IP "\(bu" 2
Fixed interaction between quaternion and euler angles
.IP "\(bu" 2
Fixed GTC_constants build
.IP "\(bu" 2
Fixed GTX_multiple
.IP "\(bu" 2
Fixed quat slerp using mix function when cosTheta close to 1
.IP "\(bu" 2
Improved fvec4SIMD and fmat4x4SIMD implementations
.IP "\(bu" 2
Fixed assert messages
.IP "\(bu" 2
Added slerp and lerp quaternion functions and tests
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.4\&.0 - 2012-11-18"
.PP
.IP "\(bu" 2
Added Intel Composer Compiler support
.IP "\(bu" 2
Promoted GTC_espilon extension
.IP "\(bu" 2
Promoted GTC_ulp extension
.IP "\(bu" 2
Removed GLM website from the source repository
.IP "\(bu" 2
Added GLM_FORCE_RADIANS so that all functions takes radians for arguments
.IP "\(bu" 2
Fixed detection of Clang and LLVM GCC on MacOS X
.IP "\(bu" 2
Added debugger visualizers for Visual C++ 2012
.IP "\(bu" 2
Requires Visual Studio 2005, GCC 4\&.2, Clang 2\&.6, Cuda 3, ICC 2013 or a C++98 compiler
.PP
.PP
.PP
 
.SS "\fCGLM 0\&.9\&.3\&.4\fP - 2012-06-30"
.PP
.IP "\(bu" 2
Added SSE4 and AVX2 detection\&.
.IP "\(bu" 2
Removed VIRTREV_xstream and the incompatibility generated with GCC
.IP "\(bu" 2
Fixed C++11 compiler option for GCC
.IP "\(bu" 2
Removed MS language extension option for GCC (not fonctionnal)
.IP "\(bu" 2
Fixed bitfieldExtract for vector types
.IP "\(bu" 2
Fixed warnings
.IP "\(bu" 2
Fixed SSE includes
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.3\&.3 - 2012-05-10"
.PP
.IP "\(bu" 2
Fixed isinf and isnan
.IP "\(bu" 2
Improved compatibility with Intel compiler
.IP "\(bu" 2
Added CMake test build options: SIMD, C++11, fast math and MS land ext
.IP "\(bu" 2
Fixed SIMD mat4 test on GCC
.IP "\(bu" 2
Fixed perspectiveFov implementation
.IP "\(bu" 2
Fixed matrixCompMult for none-square matrices
.IP "\(bu" 2
Fixed namespace issue on stream operators
.IP "\(bu" 2
Fixed various warnings
.IP "\(bu" 2
Added VC11 support
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.3\&.2 - 2012-03-15"
.PP
.IP "\(bu" 2
Fixed doxygen documentation
.IP "\(bu" 2
Fixed Clang version detection
.IP "\(bu" 2
Fixed simd mat4 /= operator
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.3\&.1 - 2012-01-25"
.PP
.IP "\(bu" 2
Fixed platform detection
.IP "\(bu" 2
Fixed warnings
.IP "\(bu" 2
Removed detail code from Doxygen doc
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.3\&.0 - 2012-01-09"
.PP
.IP "\(bu" 2
Added CPP Check project
.IP "\(bu" 2
Fixed conflict with Windows headers
.IP "\(bu" 2
Fixed isinf implementation
.IP "\(bu" 2
Fixed Boost conflict
.IP "\(bu" 2
Fixed warnings
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.3\&.B - 2011-12-12"
.PP
.IP "\(bu" 2
Added support for Chrone Native Client
.IP "\(bu" 2
Added epsilon constant
.IP "\(bu" 2
Removed value_size function from vector types
.IP "\(bu" 2
Fixed roundEven on GCC
.IP "\(bu" 2
Improved API documentation
.IP "\(bu" 2
Fixed modf implementation
.IP "\(bu" 2
Fixed step function accuracy
.IP "\(bu" 2
Fixed outerProduct
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.3\&.A - 2011-11-11"
.PP
.IP "\(bu" 2
Improved doxygen documentation
.IP "\(bu" 2
Added new swizzle operators for C++11 compilers
.IP "\(bu" 2
Added new swizzle operators declared as functions
.IP "\(bu" 2
Added GLSL 4\&.20 length for vector and matrix types
.IP "\(bu" 2
Promoted GLM_GTC_noise extension: simplex, perlin, periodic noise functions
.IP "\(bu" 2
Promoted GLM_GTC_random extension: linear, gaussian and various random number generation distribution
.IP "\(bu" 2
Added GLM_GTX_constants: provides useful constants
.IP "\(bu" 2
Added extension versioning
.IP "\(bu" 2
Removed many unused namespaces
.IP "\(bu" 2
Fixed half based type contructors
.IP "\(bu" 2
Added GLSL core noise functions
.PP
.PP
.PP
 
.SS "\fCGLM 0\&.9\&.2\&.7\fP - 2011-10-24"
.PP
.IP "\(bu" 2
Added more swizzling constructors
.IP "\(bu" 2
Added missing none-squared matrix products
.PP
.PP
.PP
 
.SS "\fCGLM 0\&.9\&.2\&.6\fP - 2011-10-01"
.PP
.IP "\(bu" 2
Fixed half based type build on old GCC
.IP "\(bu" 2
Fixed /W4 warnings on Visual C++
.IP "\(bu" 2
Fixed some missing l-value swizzle operators
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.2\&.5 - 2011-09-20"
.PP
.IP "\(bu" 2
Fixed floatBitToXint functions
.IP "\(bu" 2
Fixed pack and unpack functions
.IP "\(bu" 2
Fixed round functions
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.2\&.4 - 2011-09-03"
.PP
.IP "\(bu" 2
Fixed extensions bugs
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.2\&.3 - 2011-06-08"
.PP
.IP "\(bu" 2
Fixed build issues
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.2\&.2 - 2011-06-02"
.PP
.IP "\(bu" 2
Expend matrix constructors flexibility
.IP "\(bu" 2
Improved quaternion implementation
.IP "\(bu" 2
Fixed many warnings across platforms and compilers
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.2\&.1 - 2011-05-24"
.PP
.IP "\(bu" 2
Automatically detect CUDA support
.IP "\(bu" 2
Improved compiler detection
.IP "\(bu" 2
Fixed errors and warnings in VC with C++ extensions disabled
.IP "\(bu" 2
Fixed and tested GLM_GTX_vector_angle
.IP "\(bu" 2
Fixed and tested GLM_GTX_rotate_vector
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.2\&.0 - 2011-05-09"
.PP
.IP "\(bu" 2
Added CUDA support
.IP "\(bu" 2
Added CTest test suite
.IP "\(bu" 2
Added GLM_GTX_ulp extension
.IP "\(bu" 2
Added GLM_GTX_noise extension
.IP "\(bu" 2
Added GLM_GTX_matrix_interpolation extension
.IP "\(bu" 2
Updated quaternion slerp interpolation
.PP
.PP
.PP
 
.SS "\fCGLM 0\&.9\&.1\&.3\fP - 2011-05-07"
.PP
.IP "\(bu" 2
Fixed bugs
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.1\&.2 - 2011-04-15"
.PP
.IP "\(bu" 2
Fixed bugs
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.1\&.1 - 2011-03-17"
.PP
.IP "\(bu" 2
Fixed bugs
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.1\&.0 - 2011-03-03"
.PP
.IP "\(bu" 2
Fixed bugs
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.1\&.B - 2011-02-13"
.PP
.IP "\(bu" 2
Updated API documentation
.IP "\(bu" 2
Improved SIMD implementation
.IP "\(bu" 2
Fixed Linux build
.PP
.PP
.PP
 
.SS "\fCGLM 0\&.9\&.0\&.8\fP - 2011-02-13"
.PP
.IP "\(bu" 2
Added quaternion product operator\&.
.IP "\(bu" 2
Clarify that GLM is a header only library\&.
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.1\&.A - 2011-01-31"
.PP
.IP "\(bu" 2
Added SIMD support
.IP "\(bu" 2
Added new swizzle functions
.IP "\(bu" 2
Improved static assert error message with C++0x static_assert
.IP "\(bu" 2
New setup system
.IP "\(bu" 2
Reduced branching
.IP "\(bu" 2
Fixed trunc implementation
.PP
.PP
.PP
 
.SS "\fCGLM 0\&.9\&.0\&.7\fP - 2011-01-30"
.PP
.IP "\(bu" 2
Added GLSL 4\&.10 packing functions
.IP "\(bu" 2
Added == and != operators for every types\&.
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.0\&.6 - 2010-12-21"
.PP
.IP "\(bu" 2
Many matrices bugs fixed
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.0\&.5 - 2010-11-01"
.PP
.IP "\(bu" 2
Improved Clang support
.IP "\(bu" 2
Fixed bugs
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.0\&.4 - 2010-10-04"
.PP
.IP "\(bu" 2
Added autoexp for GLM
.IP "\(bu" 2
Fixed bugs
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.0\&.3 - 2010-08-26"
.PP
.IP "\(bu" 2
Fixed non-squared matrix operators
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.0\&.2 - 2010-07-08"
.PP
.IP "\(bu" 2
Added GLM_GTX_int_10_10_10_2
.IP "\(bu" 2
Fixed bugs
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.0\&.1 - 2010-06-21"
.PP
.IP "\(bu" 2
Fixed extensions errors
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.0\&.0 - 2010-05-25"
.PP
.IP "\(bu" 2
Objective-C support
.IP "\(bu" 2
Fixed warnings
.IP "\(bu" 2
Updated documentation
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.B\&.2 - 2010-04-30"
.PP
.IP "\(bu" 2
Git transition
.IP "\(bu" 2
Removed experimental code from releases
.IP "\(bu" 2
Fixed bugs
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.B\&.1 - 2010-04-03"
.PP
.IP "\(bu" 2
Based on GLSL 4\&.00 specification
.IP "\(bu" 2
Added the new core functions
.IP "\(bu" 2
Added some implicit conversion support
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.A\&.2 - 2010-02-20"
.PP
.IP "\(bu" 2
Improved some possible errors messages
.IP "\(bu" 2
Improved declarations and definitions match
.PP
.PP
.PP
 
.SS "GLM 0\&.9\&.A\&.1 - 2010-02-09"
.PP
.IP "\(bu" 2
Removed deprecated features
.IP "\(bu" 2
Internal redesign
.PP
.PP
.PP
 
.SS "GLM 0\&.8\&.4\&.4 final - 2010-01-25"
.PP
.IP "\(bu" 2
Fixed warnings
.PP
.PP
.PP
 
.SS "GLM 0\&.8\&.4\&.3 final - 2009-11-16"
.PP
.IP "\(bu" 2
Fixed Half float arithmetic
.IP "\(bu" 2
Fixed setup defines
.PP
.PP
.PP
 
.SS "GLM 0\&.8\&.4\&.2 final - 2009-10-19"
.PP
.IP "\(bu" 2
Fixed Half float adds
.PP
.PP
.PP
 
.SS "GLM 0\&.8\&.4\&.1 final - 2009-10-05"
.PP
.IP "\(bu" 2
Updated documentation
.IP "\(bu" 2
Fixed MacOS X build
.PP
.PP
.PP
 
.SS "GLM 0\&.8\&.4\&.0 final - 2009-09-16"
.PP
.IP "\(bu" 2
Added GCC 4\&.4 and VC2010 support
.IP "\(bu" 2
Added matrix optimizations
.PP
.PP
.PP
 
.SS "GLM 0\&.8\&.3\&.5 final - 2009-08-11"
.PP
.IP "\(bu" 2
Fixed bugs
.PP
.PP
.PP
 
.SS "GLM 0\&.8\&.3\&.4 final - 2009-08-10"
.PP
.IP "\(bu" 2
Updated GLM according GLSL 1\&.5 spec
.IP "\(bu" 2
Fixed bugs
.PP
.PP
.PP
 
.SS "GLM 0\&.8\&.3\&.3 final - 2009-06-25"
.PP
.IP "\(bu" 2
Fixed bugs
.PP
.PP
.PP
 
.SS "GLM 0\&.8\&.3\&.2 final - 2009-06-04"
.PP
.IP "\(bu" 2
Added GLM_GTC_quaternion
.IP "\(bu" 2
Added GLM_GTC_type_precision
.PP
.PP
.PP
 
.SS "GLM 0\&.8\&.3\&.1 final - 2009-05-21"
.PP
.IP "\(bu" 2
Fixed old extension system\&.
.PP
.PP
.PP
 
.SS "GLM 0\&.8\&.3\&.0 final - 2009-05-06"
.PP
.IP "\(bu" 2
Added stable extensions\&.
.IP "\(bu" 2
Added new extension system\&.
.PP
.PP
.PP
 
.SS "GLM 0\&.8\&.2\&.3 final - 2009-04-01"
.PP
.IP "\(bu" 2
Fixed bugs\&.
.PP
.PP
.PP
 
.SS "GLM 0\&.8\&.2\&.2 final - 2009-02-24"
.PP
.IP "\(bu" 2
Fixed bugs\&.
.PP
.PP
.PP
 
.SS "GLM 0\&.8\&.2\&.1 final - 2009-02-13"
.PP
.IP "\(bu" 2
Fixed bugs\&.
.PP
.PP
.PP
 
.SS "GLM 0\&.8\&.2 final - 2009-01-21"
.PP
.IP "\(bu" 2
Fixed bugs\&.
.PP
.PP
.PP
 
.SS "GLM 0\&.8\&.1 final - 2008-10-30"
.PP
.IP "\(bu" 2
Fixed bugs\&.
.PP
.PP
.PP
 
.SS "GLM 0\&.8\&.0 final - 2008-10-23"
.PP
.IP "\(bu" 2
New method to use extension\&.
.PP
.PP
.PP
 
.SS "GLM 0\&.8\&.0 beta3 - 2008-10-10"
.PP
.IP "\(bu" 2
Added CMake support for GLM tests\&.
.PP
.PP
.PP
 
.SS "GLM 0\&.8\&.0 beta2 - 2008-10-04"
.PP
.IP "\(bu" 2
Improved half scalars and vectors support\&.
.PP
.PP
.PP
 
.SS "GLM 0\&.8\&.0 beta1 - 2008-09-26"
.PP
.IP "\(bu" 2
Improved GLSL conformance
.IP "\(bu" 2
Added GLSL 1\&.30 support
.IP "\(bu" 2
Improved API documentation
.PP
.PP
.PP
 
.SS "GLM 0\&.7\&.6 final - 2008-08-08"
.PP
.IP "\(bu" 2
Improved C++ standard comformance
.IP "\(bu" 2
Added Static assert for types checking
.PP
.PP
.PP
 
.SS "GLM 0\&.7\&.5 final - 2008-07-05"
.PP
.IP "\(bu" 2
Added build message system with Visual Studio
.IP "\(bu" 2
Pedantic build with GCC
.PP
.PP
.PP
 
.SS "GLM 0\&.7\&.4 final - 2008-06-01"
.PP
.IP "\(bu" 2
Added external dependencies system\&.
.PP
.PP
.PP
 
.SS "GLM 0\&.7\&.3 final - 2008-05-24"
.PP
.IP "\(bu" 2
Fixed bugs
.IP "\(bu" 2
Added new extension group
.PP
.PP
.PP
 
.SS "GLM 0\&.7\&.2 final - 2008-04-27"
.PP
.IP "\(bu" 2
Updated documentation
.IP "\(bu" 2
Added preprocessor options
.PP
.PP
.PP
 
.SS "GLM 0\&.7\&.1 final - 2008-03-24"
.PP
.IP "\(bu" 2
Disabled half on GCC
.IP "\(bu" 2
Fixed extensions
.PP
.PP
.PP
 
.SS "GLM 0\&.7\&.0 final - 2008-03-22"
.PP
.IP "\(bu" 2
Changed to MIT license
.IP "\(bu" 2
Added new documentation
.PP
.PP
.PP
 
.SS "GLM 0\&.6\&.4 - 2007-12-10"
.PP
.IP "\(bu" 2
Fixed swizzle operators
.PP
.PP
.PP
 
.SS "GLM 0\&.6\&.3 - 2007-11-05"
.PP
.IP "\(bu" 2
Fixed type data accesses
.IP "\(bu" 2
Fixed 3DSMax sdk conflict
.PP
.PP
.PP
 
.SS "GLM 0\&.6\&.2 - 2007-10-08"
.PP
.IP "\(bu" 2
Fixed extension
.PP
.PP
.PP
 
.SS "GLM 0\&.6\&.1 - 2007-10-07"
.PP
.IP "\(bu" 2
Fixed a namespace error
.IP "\(bu" 2
Added extensions
.PP
.PP
.PP
 
.SS "GLM 0\&.6\&.0 : 2007-09-16"
.PP
.IP "\(bu" 2
Added new extension namespace mecanium
.IP "\(bu" 2
Added Automatic compiler detection
.PP
.PP
.PP
 
.SS "GLM 0\&.5\&.1 - 2007-02-19"
.PP
.IP "\(bu" 2
Fixed swizzle operators
.PP
.PP
.PP
 
.SS "GLM 0\&.5\&.0 - 2007-01-06"
.PP
.IP "\(bu" 2
Upgrated to GLSL 1\&.2
.IP "\(bu" 2
Added swizzle operators
.IP "\(bu" 2
Added setup settings
.PP
.PP
.PP
 
.SS "GLM 0\&.4\&.1 - 2006-05-22"
.PP
.IP "\(bu" 2
Added OpenGL examples
.PP
.PP
.PP
 
.SS "GLM 0\&.4\&.0 - 2006-05-17"
.PP
.IP "\(bu" 2
Added missing operators to vec* and mat*
.IP "\(bu" 2
Added first GLSL 1\&.2 features
.IP "\(bu" 2
Fixed windows\&.h before glm\&.h when windows\&.h required
.PP
.PP
.PP
 
.SS "GLM 0\&.3\&.2 - 2006-04-21"
.PP
.IP "\(bu" 2
Fixed texcoord components access\&.
.IP "\(bu" 2
Fixed mat4 and imat4 division operators\&.
.PP
.PP
.PP
 
.SS "GLM 0\&.3\&.1 - 2006-03-28"
.PP
.IP "\(bu" 2
Added GCC 4\&.0 support under MacOS X\&.
.IP "\(bu" 2
Added GCC 4\&.0 and 4\&.1 support under Linux\&.
.IP "\(bu" 2
Added code optimisations\&.
.PP
.PP
.PP
 
.SS "GLM 0\&.3 - 2006-02-19"
.PP
.IP "\(bu" 2
Improved GLSL type conversion and construction compliance\&.
.IP "\(bu" 2
Added experimental extensions\&.
.IP "\(bu" 2
Added Doxygen Documentation\&.
.IP "\(bu" 2
Added code optimisations\&.
.IP "\(bu" 2
Fixed bugs\&.
.PP
.PP
.PP
 
.SS "GLM 0\&.2 - 2005-05-05"
.PP
.IP "\(bu" 2
Improve adaptative from GLSL\&.
.IP "\(bu" 2
Add experimental extensions based on OpenGL extension process\&.
.IP "\(bu" 2
Fixe bugs\&.
.PP
.PP
.PP
 
.SS "GLM 0\&.1 - 2005-02-21"
.PP
.IP "\(bu" 2
Add \fBvec2\fP, vec3, vec4 GLSL types
.IP "\(bu" 2
Add ivec2, ivec3, ivec4 GLSL types
.IP "\(bu" 2
Add bvec2, bvec3, bvec4 GLSL types
.IP "\(bu" 2
Add mat2, mat3, mat4 GLSL types
.IP "\(bu" 2
Add almost all functions 
.PP

