.TH "mods" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mods \- Modifier key flags\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGLFW_MOD_SHIFT\fP   0x0001"
.br
.RI "If this bit is set one or more Shift keys were held down\&. "
.ti -1c
.RI "#define \fBGLFW_MOD_CONTROL\fP   0x0002"
.br
.RI "If this bit is set one or more Control keys were held down\&. "
.ti -1c
.RI "#define \fBGLFW_MOD_ALT\fP   0x0004"
.br
.RI "If this bit is set one or more Alt keys were held down\&. "
.ti -1c
.RI "#define \fBGLFW_MOD_SUPER\fP   0x0008"
.br
.RI "If this bit is set one or more Super keys were held down\&. "
.ti -1c
.RI "#define \fBGLFW_MOD_CAPS_LOCK\fP   0x0010"
.br
.RI "If this bit is set the Caps Lock key is enabled\&. "
.ti -1c
.RI "#define \fBGLFW_MOD_NUM_LOCK\fP   0x0020"
.br
.RI "If this bit is set the Num Lock key is enabled\&. "
.ti -1c
.RI "#define \fBGLFW_MOD_SHIFT\fP   0x0001"
.br
.RI "If this bit is set one or more Shift keys were held down\&. "
.ti -1c
.RI "#define \fBGLFW_MOD_CONTROL\fP   0x0002"
.br
.RI "If this bit is set one or more Control keys were held down\&. "
.ti -1c
.RI "#define \fBGLFW_MOD_ALT\fP   0x0004"
.br
.RI "If this bit is set one or more Alt keys were held down\&. "
.ti -1c
.RI "#define \fBGLFW_MOD_SUPER\fP   0x0008"
.br
.RI "If this bit is set one or more Super keys were held down\&. "
.in -1c
.SH "Detailed Description"
.PP 
Modifier key flags\&. 

See \fBkey input\fP for how these are used\&. 
.SH "Macro Definition Documentation"
.PP 
.SS "#define GLFW_MOD_ALT   0x0004"

.PP
If this bit is set one or more Alt keys were held down\&. If this bit is set one or more Alt keys were held down\&. 
.SS "#define GLFW_MOD_CAPS_LOCK   0x0010"

.PP
If this bit is set the Caps Lock key is enabled\&. If this bit is set the Caps Lock key is enabled and the \fBGLFW_LOCK_KEY_MODS\fP input mode is set\&. 
.SS "#define GLFW_MOD_CONTROL   0x0002"

.PP
If this bit is set one or more Control keys were held down\&. If this bit is set one or more Control keys were held down\&. 
.SS "#define GLFW_MOD_NUM_LOCK   0x0020"

.PP
If this bit is set the Num Lock key is enabled\&. If this bit is set the Num Lock key is enabled and the \fBGLFW_LOCK_KEY_MODS\fP input mode is set\&. 
.SS "#define GLFW_MOD_SHIFT   0x0001"

.PP
If this bit is set one or more Shift keys were held down\&. If this bit is set one or more Shift keys were held down\&. 
.SS "#define GLFW_MOD_SUPER   0x0008"

.PP
If this bit is set one or more Super keys were held down\&. If this bit is set one or more Super keys were held down\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
