.TH "nk_buffer" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_buffer
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnk_buffer_marker\fP \fBmarker\fP [NK_BUFFER_MAX]"
.br
.ti -1c
.RI "struct \fBnk_allocator\fP \fBpool\fP"
.br
.ti -1c
.RI "enum nk_allocation_type \fBtype\fP"
.br
.ti -1c
.RI "struct \fBnk_memory\fP \fBmemory\fP"
.br
.ti -1c
.RI "float \fBgrow_factor\fP"
.br
.ti -1c
.RI "nk_size \fBallocated\fP"
.br
.ti -1c
.RI "nk_size \fBneeded\fP"
.br
.ti -1c
.RI "nk_size \fBcalls\fP"
.br
.ti -1c
.RI "nk_size \fBsize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
