.TH "nk_command_text" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_command_text
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnk_command\fP \fBheader\fP"
.br
.ti -1c
.RI "const struct \fBnk_user_font\fP * \fBfont\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBbackground\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBforeground\fP"
.br
.ti -1c
.RI "short \fBx\fP"
.br
.ti -1c
.RI "short \fBy\fP"
.br
.ti -1c
.RI "unsigned short \fBw\fP"
.br
.ti -1c
.RI "unsigned short \fBh\fP"
.br
.ti -1c
.RI "float \fBheight\fP"
.br
.ti -1c
.RI "int \fBlength\fP"
.br
.ti -1c
.RI "char \fBstring\fP [1]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
