.TH "nk_chart_slot" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_chart_slot
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "enum nk_chart_type \fBtype\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBcolor\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBhighlight\fP"
.br
.ti -1c
.RI "float \fBmin\fP"
.br
.ti -1c
.RI "float \fBmax\fP"
.br
.ti -1c
.RI "float \fBrange\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBlast\fP"
.br
.ti -1c
.RI "int \fBindex\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
