.TH "nk_convert_config" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_convert_config
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBglobal_alpha\fP"
.br
.ti -1c
.RI "enum nk_anti_aliasing \fBline_AA\fP"
.br
.ti -1c
.RI "enum nk_anti_aliasing \fBshape_AA\fP"
.br
.ti -1c
.RI "unsigned \fBcircle_segment_count\fP"
.br
.ti -1c
.RI "unsigned \fBarc_segment_count\fP"
.br
.ti -1c
.RI "unsigned \fBcurve_segment_count\fP"
.br
.ti -1c
.RI "struct \fBnk_draw_null_texture\fP \fBnull\fP"
.br
.ti -1c
.RI "const struct nk_draw_vertex_layout_element * \fBvertex_layout\fP"
.br
.ti -1c
.RI "nk_size \fBvertex_size\fP"
.br
.ti -1c
.RI "nk_size \fBvertex_alignment\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
