.TH "nk_color" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_color
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "nk_byte \fBr\fP"
.br
.ti -1c
.RI "nk_byte \fBg\fP"
.br
.ti -1c
.RI "nk_byte \fBb\fP"
.br
.ti -1c
.RI "nk_byte \fBa\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
