.TH "nk_edit_state" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_edit_state
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "nk_hash \fBname\fP"
.br
.ti -1c
.RI "unsigned int \fBseq\fP"
.br
.ti -1c
.RI "unsigned int \fBold\fP"
.br
.ti -1c
.RI "int \fBactive\fP"
.br
.ti -1c
.RI "int \fBprev\fP"
.br
.ti -1c
.RI "int \fBcursor\fP"
.br
.ti -1c
.RI "int \fBsel_start\fP"
.br
.ti -1c
.RI "int \fBsel_end\fP"
.br
.ti -1c
.RI "struct \fBnk_scroll\fP \fBscrollbar\fP"
.br
.ti -1c
.RI "unsigned char \fBmode\fP"
.br
.ti -1c
.RI "unsigned char \fBsingle_line\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
