.TH "nk_list_view" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_list_view
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBbegin\fP"
.br
.ti -1c
.RI "int \fBend\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "int \fBtotal_height\fP"
.br
.ti -1c
.RI "struct \fBnk_context\fP * \fBctx\fP"
.br
.ti -1c
.RI "nk_uint * \fBscroll_pointer\fP"
.br
.ti -1c
.RI "nk_uint \fBscroll_value\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
