.TH "nk_panel" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_panel
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "enum nk_panel_type \fBtype\fP"
.br
.ti -1c
.RI "nk_flags \fBflags\fP"
.br
.ti -1c
.RI "struct \fBnk_rect\fP \fBbounds\fP"
.br
.ti -1c
.RI "nk_uint * \fBoffset_x\fP"
.br
.ti -1c
.RI "nk_uint * \fBoffset_y\fP"
.br
.ti -1c
.RI "float \fBat_x\fP"
.br
.ti -1c
.RI "float \fBat_y\fP"
.br
.ti -1c
.RI "float \fBmax_x\fP"
.br
.ti -1c
.RI "float \fBfooter_height\fP"
.br
.ti -1c
.RI "float \fBheader_height\fP"
.br
.ti -1c
.RI "float \fBborder\fP"
.br
.ti -1c
.RI "unsigned int \fBhas_scrolling\fP"
.br
.ti -1c
.RI "struct \fBnk_rect\fP \fBclip\fP"
.br
.ti -1c
.RI "struct \fBnk_menu_state\fP \fBmenu\fP"
.br
.ti -1c
.RI "struct \fBnk_row_layout\fP \fBrow\fP"
.br
.ti -1c
.RI "struct \fBnk_chart\fP \fBchart\fP"
.br
.ti -1c
.RI "struct \fBnk_command_buffer\fP * \fBbuffer\fP"
.br
.ti -1c
.RI "struct \fBnk_panel\fP * \fBparent\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
