.TH "nk_page_element" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_page_element
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "union \fBnk_page_data\fP \fBdata\fP"
.br
.ti -1c
.RI "struct \fBnk_page_element\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBnk_page_element\fP * \fBprev\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
