.TH "nk_popup_state" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_popup_state
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnk_window\fP * \fBwin\fP"
.br
.ti -1c
.RI "enum nk_panel_type \fBtype\fP"
.br
.ti -1c
.RI "struct \fBnk_popup_buffer\fP \fBbuf\fP"
.br
.ti -1c
.RI "nk_hash \fBname\fP"
.br
.ti -1c
.RI "int \fBactive\fP"
.br
.ti -1c
.RI "unsigned \fBcombo_count\fP"
.br
.ti -1c
.RI "unsigned \fBcon_count\fP"
.br
.ti -1c
.RI "unsigned \fBcon_old\fP"
.br
.ti -1c
.RI "unsigned \fBactive_con\fP"
.br
.ti -1c
.RI "struct \fBnk_rect\fP \fBheader\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
