.TH "nk_row_layout" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_row_layout
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "enum nk_panel_row_layout_type \fBtype\fP"
.br
.ti -1c
.RI "int \fBindex\fP"
.br
.ti -1c
.RI "float \fBheight\fP"
.br
.ti -1c
.RI "float \fBmin_height\fP"
.br
.ti -1c
.RI "int \fBcolumns\fP"
.br
.ti -1c
.RI "const float * \fBratio\fP"
.br
.ti -1c
.RI "float \fBitem_width\fP"
.br
.ti -1c
.RI "float \fBitem_height\fP"
.br
.ti -1c
.RI "float \fBitem_offset\fP"
.br
.ti -1c
.RI "float \fBfilled\fP"
.br
.ti -1c
.RI "struct \fBnk_rect\fP \fBitem\fP"
.br
.ti -1c
.RI "int \fBtree_depth\fP"
.br
.ti -1c
.RI "float \fBtemplates\fP [NK_MAX_LAYOUT_ROW_TEMPLATE_COLUMNS]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
