.TH "nk_style" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_style
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const struct \fBnk_user_font\fP * \fBfont\fP"
.br
.ti -1c
.RI "const struct \fBnk_cursor\fP * \fBcursors\fP [NK_CURSOR_COUNT]"
.br
.ti -1c
.RI "const struct \fBnk_cursor\fP * \fBcursor_active\fP"
.br
.ti -1c
.RI "struct \fBnk_cursor\fP * \fBcursor_last\fP"
.br
.ti -1c
.RI "int \fBcursor_visible\fP"
.br
.ti -1c
.RI "struct \fBnk_style_text\fP \fBtext\fP"
.br
.ti -1c
.RI "struct \fBnk_style_button\fP \fBbutton\fP"
.br
.ti -1c
.RI "struct \fBnk_style_button\fP \fBcontextual_button\fP"
.br
.ti -1c
.RI "struct \fBnk_style_button\fP \fBmenu_button\fP"
.br
.ti -1c
.RI "struct \fBnk_style_toggle\fP \fBoption\fP"
.br
.ti -1c
.RI "struct \fBnk_style_toggle\fP \fBcheckbox\fP"
.br
.ti -1c
.RI "struct \fBnk_style_selectable\fP \fBselectable\fP"
.br
.ti -1c
.RI "struct \fBnk_style_slider\fP \fBslider\fP"
.br
.ti -1c
.RI "struct \fBnk_style_progress\fP \fBprogress\fP"
.br
.ti -1c
.RI "struct \fBnk_style_property\fP \fBproperty\fP"
.br
.ti -1c
.RI "struct \fBnk_style_edit\fP \fBedit\fP"
.br
.ti -1c
.RI "struct \fBnk_style_chart\fP \fBchart\fP"
.br
.ti -1c
.RI "struct \fBnk_style_scrollbar\fP \fBscrollh\fP"
.br
.ti -1c
.RI "struct \fBnk_style_scrollbar\fP \fBscrollv\fP"
.br
.ti -1c
.RI "struct \fBnk_style_tab\fP \fBtab\fP"
.br
.ti -1c
.RI "struct \fBnk_style_combo\fP \fBcombo\fP"
.br
.ti -1c
.RI "struct \fBnk_style_window\fP \fBwindow\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
