.TH "nk_style_progress" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_style_progress
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnk_style_item\fP \fBnormal\fP"
.br
.ti -1c
.RI "struct \fBnk_style_item\fP \fBhover\fP"
.br
.ti -1c
.RI "struct \fBnk_style_item\fP \fBactive\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBborder_color\fP"
.br
.ti -1c
.RI "struct \fBnk_style_item\fP \fBcursor_normal\fP"
.br
.ti -1c
.RI "struct \fBnk_style_item\fP \fBcursor_hover\fP"
.br
.ti -1c
.RI "struct \fBnk_style_item\fP \fBcursor_active\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBcursor_border_color\fP"
.br
.ti -1c
.RI "float \fBrounding\fP"
.br
.ti -1c
.RI "float \fBborder\fP"
.br
.ti -1c
.RI "float \fBcursor_border\fP"
.br
.ti -1c
.RI "float \fBcursor_rounding\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBpadding\fP"
.br
.ti -1c
.RI "\fBnk_handle\fP \fBuserdata\fP"
.br
.ti -1c
.RI "void(* \fBdraw_begin\fP )(struct \fBnk_command_buffer\fP *, \fBnk_handle\fP)"
.br
.ti -1c
.RI "void(* \fBdraw_end\fP )(struct \fBnk_command_buffer\fP *, \fBnk_handle\fP)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
