.TH "nk_style_combo" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_style_combo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnk_style_item\fP \fBnormal\fP"
.br
.ti -1c
.RI "struct \fBnk_style_item\fP \fBhover\fP"
.br
.ti -1c
.RI "struct \fBnk_style_item\fP \fBactive\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBborder_color\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBlabel_normal\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBlabel_hover\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBlabel_active\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBsymbol_normal\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBsymbol_hover\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBsymbol_active\fP"
.br
.ti -1c
.RI "struct \fBnk_style_button\fP \fBbutton\fP"
.br
.ti -1c
.RI "enum nk_symbol_type \fBsym_normal\fP"
.br
.ti -1c
.RI "enum nk_symbol_type \fBsym_hover\fP"
.br
.ti -1c
.RI "enum nk_symbol_type \fBsym_active\fP"
.br
.ti -1c
.RI "float \fBborder\fP"
.br
.ti -1c
.RI "float \fBrounding\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBcontent_padding\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBbutton_padding\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBspacing\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
