.TH "nk_style_window_header" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_style_window_header
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnk_style_item\fP \fBnormal\fP"
.br
.ti -1c
.RI "struct \fBnk_style_item\fP \fBhover\fP"
.br
.ti -1c
.RI "struct \fBnk_style_item\fP \fBactive\fP"
.br
.ti -1c
.RI "struct \fBnk_style_button\fP \fBclose_button\fP"
.br
.ti -1c
.RI "struct \fBnk_style_button\fP \fBminimize_button\fP"
.br
.ti -1c
.RI "enum nk_symbol_type \fBclose_symbol\fP"
.br
.ti -1c
.RI "enum nk_symbol_type \fBminimize_symbol\fP"
.br
.ti -1c
.RI "enum nk_symbol_type \fBmaximize_symbol\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBlabel_normal\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBlabel_hover\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBlabel_active\fP"
.br
.ti -1c
.RI "enum nk_style_header_align \fBalign\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBpadding\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBlabel_padding\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBspacing\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
