.TH "nk_style_tab" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_style_tab
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnk_style_item\fP \fBbackground\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBborder_color\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBtext\fP"
.br
.ti -1c
.RI "struct \fBnk_style_button\fP \fBtab_maximize_button\fP"
.br
.ti -1c
.RI "struct \fBnk_style_button\fP \fBtab_minimize_button\fP"
.br
.ti -1c
.RI "struct \fBnk_style_button\fP \fBnode_maximize_button\fP"
.br
.ti -1c
.RI "struct \fBnk_style_button\fP \fBnode_minimize_button\fP"
.br
.ti -1c
.RI "enum nk_symbol_type \fBsym_minimize\fP"
.br
.ti -1c
.RI "enum nk_symbol_type \fBsym_maximize\fP"
.br
.ti -1c
.RI "float \fBborder\fP"
.br
.ti -1c
.RI "float \fBrounding\fP"
.br
.ti -1c
.RI "float \fBindent\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBpadding\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBspacing\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
