.TH "nk_style_edit" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_style_edit
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnk_style_item\fP \fBnormal\fP"
.br
.ti -1c
.RI "struct \fBnk_style_item\fP \fBhover\fP"
.br
.ti -1c
.RI "struct \fBnk_style_item\fP \fBactive\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBborder_color\fP"
.br
.ti -1c
.RI "struct \fBnk_style_scrollbar\fP \fBscrollbar\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBcursor_normal\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBcursor_hover\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBcursor_text_normal\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBcursor_text_hover\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBtext_normal\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBtext_hover\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBtext_active\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBselected_normal\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBselected_hover\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBselected_text_normal\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBselected_text_hover\fP"
.br
.ti -1c
.RI "float \fBborder\fP"
.br
.ti -1c
.RI "float \fBrounding\fP"
.br
.ti -1c
.RI "float \fBcursor_size\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBscrollbar_size\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBpadding\fP"
.br
.ti -1c
.RI "float \fBrow_padding\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
