.TH "nk_text_edit" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_text_edit
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnk_clipboard\fP \fBclip\fP"
.br
.ti -1c
.RI "struct \fBnk_str\fP \fBstring\fP"
.br
.ti -1c
.RI "nk_plugin_filter \fBfilter\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBscrollbar\fP"
.br
.ti -1c
.RI "int \fBcursor\fP"
.br
.ti -1c
.RI "int \fBselect_start\fP"
.br
.ti -1c
.RI "int \fBselect_end\fP"
.br
.ti -1c
.RI "unsigned char \fBmode\fP"
.br
.ti -1c
.RI "unsigned char \fBcursor_at_end_of_line\fP"
.br
.ti -1c
.RI "unsigned char \fBinitialized\fP"
.br
.ti -1c
.RI "unsigned char \fBhas_preferred_x\fP"
.br
.ti -1c
.RI "unsigned char \fBsingle_line\fP"
.br
.ti -1c
.RI "unsigned char \fBactive\fP"
.br
.ti -1c
.RI "unsigned char \fBpadding1\fP"
.br
.ti -1c
.RI "float \fBpreferred_x\fP"
.br
.ti -1c
.RI "struct \fBnk_text_undo_state\fP \fBundo\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
