.TH "nk_text_undo_state" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_text_undo_state
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnk_text_undo_record\fP \fBundo_rec\fP [NK_TEXTEDIT_UNDOSTATECOUNT]"
.br
.ti -1c
.RI "nk_rune \fBundo_char\fP [NK_TEXTEDIT_UNDOCHARCOUNT]"
.br
.ti -1c
.RI "short \fBundo_point\fP"
.br
.ti -1c
.RI "short \fBredo_point\fP"
.br
.ti -1c
.RI "short \fBundo_char_point\fP"
.br
.ti -1c
.RI "short \fBredo_char_point\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
