.TH "nk_text_undo_record" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_text_undo_record
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBwhere\fP"
.br
.ti -1c
.RI "short \fBinsert_length\fP"
.br
.ti -1c
.RI "short \fBdelete_length\fP"
.br
.ti -1c
.RI "short \fBchar_storage\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
