.TH "nk_window" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_window
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBseq\fP"
.br
.ti -1c
.RI "nk_hash \fBname\fP"
.br
.ti -1c
.RI "char \fBname_string\fP [NK_WINDOW_MAX_NAME]"
.br
.ti -1c
.RI "nk_flags \fBflags\fP"
.br
.ti -1c
.RI "struct \fBnk_rect\fP \fBbounds\fP"
.br
.ti -1c
.RI "struct \fBnk_scroll\fP \fBscrollbar\fP"
.br
.ti -1c
.RI "struct \fBnk_command_buffer\fP \fBbuffer\fP"
.br
.ti -1c
.RI "struct \fBnk_panel\fP * \fBlayout\fP"
.br
.ti -1c
.RI "float \fBscrollbar_hiding_timer\fP"
.br
.ti -1c
.RI "struct \fBnk_property_state\fP \fBproperty\fP"
.br
.ti -1c
.RI "struct \fBnk_popup_state\fP \fBpopup\fP"
.br
.ti -1c
.RI "struct \fBnk_edit_state\fP \fBedit\fP"
.br
.ti -1c
.RI "unsigned int \fBscrolled\fP"
.br
.ti -1c
.RI "struct \fBnk_table\fP * \fBtables\fP"
.br
.ti -1c
.RI "unsigned int \fBtable_count\fP"
.br
.ti -1c
.RI "struct \fBnk_window\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBnk_window\fP * \fBprev\fP"
.br
.ti -1c
.RI "struct \fBnk_window\fP * \fBparent\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
