.TH "Typhoon/ThirdParty/glm/glm/gtx/norm.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/gtx/norm.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./geometric\&.hpp'\fP
.br
\fC#include '\&.\&./gtx/quaternion\&.hpp'\fP
.br
\fC#include 'norm\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL T \fBglm::length2\fP (vec< L, T, Q > const &x)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL T \fBglm::distance2\fP (vec< L, T, Q > const &p0, vec< L, T, Q > const &p1)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL T \fBglm::l1Norm\fP (vec< 3, T, Q > const &x, vec< 3, T, Q > const &y)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL T \fBglm::l1Norm\fP (vec< 3, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL T \fBglm::l2Norm\fP (vec< 3, T, Q > const &x, vec< 3, T, Q > const &y)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL T \fBglm::l2Norm\fP (vec< 3, T, Q > const &x)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL T \fBglm::lxNorm\fP (vec< 3, T, Q > const &x, vec< 3, T, Q > const &y, unsigned int Depth)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL T \fBglm::lxNorm\fP (vec< 3, T, Q > const &x, unsigned int Depth)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTX_norm\fP
.PP
\fBSee also:\fP
.RS 4
\fBCore features\fP (dependence) 
.PP
\fBGLM_GTX_quaternion\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
