.TH "Typhoon/ThirdParty/glm/glm/gtx/number_precision.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/gtx/number_precision.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./glm\&.hpp'\fP
.br
\fC#include '\&.\&./gtc/type_precision\&.hpp'\fP
.br
\fC#include 'number_precision\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef u8 \fBglm::gtx::u8vec1\fP"
.br
.RI "8bit unsigned integer scalar\&. (from GLM_GTX_number_precision extension) "
.ti -1c
.RI "typedef u16 \fBglm::gtx::u16vec1\fP"
.br
.RI "16bit unsigned integer scalar\&. (from GLM_GTX_number_precision extension) "
.ti -1c
.RI "typedef u32 \fBglm::gtx::u32vec1\fP"
.br
.RI "32bit unsigned integer scalar\&. (from GLM_GTX_number_precision extension) "
.ti -1c
.RI "typedef u64 \fBglm::gtx::u64vec1\fP"
.br
.RI "64bit unsigned integer scalar\&. (from GLM_GTX_number_precision extension) "
.ti -1c
.RI "typedef f32 \fBglm::gtx::f32vec1\fP"
.br
.RI "Single-qualifier floating-point scalar\&. (from GLM_GTX_number_precision extension) "
.ti -1c
.RI "typedef f64 \fBglm::gtx::f64vec1\fP"
.br
.RI "Single-qualifier floating-point scalar\&. (from GLM_GTX_number_precision extension) "
.ti -1c
.RI "typedef f32 \fBglm::gtx::f32mat1\fP"
.br
.RI "Single-qualifier floating-point scalar\&. (from GLM_GTX_number_precision extension) "
.ti -1c
.RI "typedef f32 \fBglm::gtx::f32mat1x1\fP"
.br
.RI "Single-qualifier floating-point scalar\&. (from GLM_GTX_number_precision extension) "
.ti -1c
.RI "typedef f64 \fBglm::gtx::f64mat1\fP"
.br
.RI "Double-qualifier floating-point scalar\&. (from GLM_GTX_number_precision extension) "
.ti -1c
.RI "typedef f64 \fBglm::gtx::f64mat1x1\fP"
.br
.RI "Double-qualifier floating-point scalar\&. (from GLM_GTX_number_precision extension) "
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTX_number_precision\fP
.PP
\fBSee also:\fP
.RS 4
\fBCore features\fP (dependence) 
.PP
\fBGLM_GTC_type_precision\fP (dependence) 
.PP
\fBGLM_GTC_quaternion\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
