.TH "Typhoon/ThirdParty/glm/glm/gtx/orthonormalize.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/gtx/orthonormalize.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./vec3\&.hpp'\fP
.br
\fC#include '\&.\&./mat3x3\&.hpp'\fP
.br
\fC#include '\&.\&./geometric\&.hpp'\fP
.br
\fC#include 'orthonormalize\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL mat< 3, 3, T, Q > \fBglm::orthonormalize\fP (mat< 3, 3, T, Q > const &m)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 3, T, Q > \fBglm::orthonormalize\fP (vec< 3, T, Q > const &x, vec< 3, T, Q > const &y)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTX_orthonormalize\fP
.PP
\fBSee also:\fP
.RS 4
\fBCore features\fP (dependence) 
.PP
gtx_extented_min_max (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
