.TH "printf_arg_formatter< Range >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
printf_arg_formatter< Range >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <printf\&.h>\fP
.PP
Inherits \fBinternal::function< internal::arg_formatter_base< Range >::iterator >\fP, and \fBinternal::arg_formatter_base< Range >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBbase::format_specs\fP \fBformat_specs\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBprintf_arg_formatter\fP (\fBinternal::basic_buffer\fP< char_type > &buffer, \fBformat_specs\fP &spec, \fBcontext_type\fP &ctx)"
.br
.ti -1c
.RI "template<typename T > std::enable_if< std::is_integral< T >::value, iterator >::type \fBoperator()\fP (T value)"
.br
.ti -1c
.RI "template<typename T > std::enable_if< std::is_floating_point< T >::value, iterator >::type \fBoperator()\fP (T value)"
.br
.ti -1c
.RI "iterator \fBoperator()\fP (const char *value)"
.br
.ti -1c
.RI "iterator \fBoperator()\fP (const wchar_t *value)"
.br
.ti -1c
.RI "iterator \fBoperator()\fP (\fBbasic_string_view\fP< char_type > value)"
.br
.ti -1c
.RI "iterator \fBoperator()\fP (\fBmonostate\fP value)"
.br
.ti -1c
.RI "iterator \fBoperator()\fP (const void *value)"
.br
.ti -1c
.RI "iterator \fBoperator()\fP (typename \fBbasic_format_arg\fP< \fBcontext_type\fP >::handle handle)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename Range>
.br
class printf_arg_formatter< Range >"
\\rst The \fCprintf\fP argument formatter\&. \\endrst 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename Range > \fBprintf_arg_formatter\fP< Range >::\fBprintf_arg_formatter\fP (\fBinternal::basic_buffer\fP< char_type > & buffer, \fBformat_specs\fP & spec, \fBcontext_type\fP & ctx)\fC [inline]\fP"
\\rst Constructs an argument formatter object\&. buffer* is a reference to the output buffer and \fIspec\fP contains format specifier information for standard argument types\&. \\endrst 
.SH "Member Function Documentation"
.PP 
.SS "template<typename Range > iterator \fBprintf_arg_formatter\fP< Range >::operator() (const char * value)\fC [inline]\fP"
Formats a null-terminated C string\&. 
.SS "template<typename Range > iterator \fBprintf_arg_formatter\fP< Range >::operator() (const wchar_t * value)\fC [inline]\fP"
Formats a null-terminated wide C string\&. 
.SS "template<typename Range > iterator \fBprintf_arg_formatter\fP< Range >::operator() (const void * value)\fC [inline]\fP"
Formats a pointer\&. 
.SS "template<typename Range > iterator \fBprintf_arg_formatter\fP< Range >::operator() (typename \fBbasic_format_arg\fP< \fBcontext_type\fP >::handle handle)\fC [inline]\fP"
Formats an argument of a custom (user-defined) type\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
