.TH "printf_formatter< T >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
printf_formatter< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename ParseContext > auto \fBparse\fP (ParseContext &ctx) \-> decltype(ctx\&.begin())"
.br
.ti -1c
.RI "template<typename FormatContext > auto \fBformat\fP (const T &value, FormatContext &ctx) \-> decltype(ctx\&.out())"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
