.TH "Typhoon/ThirdParty/glm/glm/ext/quaternion_float_precision.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/ext/quaternion_float_precision.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./detail/type_quat\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef qua< float, lowp > \fBglm::lowp_quat\fP"
.br
.RI "Quaternion of single-precision floating-point numbers using high precision arithmetic in term of ULPs\&. "
.ti -1c
.RI "typedef qua< float, mediump > \fBglm::mediump_quat\fP"
.br
.RI "Quaternion of single-precision floating-point numbers using high precision arithmetic in term of ULPs\&. "
.ti -1c
.RI "typedef qua< float, highp > \fBglm::highp_quat\fP"
.br
.RI "Quaternion of single-precision floating-point numbers using high precision arithmetic in term of ULPs\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_EXT_quaternion_float_precision\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
