.TH "Typhoon/ThirdParty/glm/glm/ext/quaternion_relational.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/ext/quaternion_relational.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./vector_relational\&.hpp'\fP
.br
\fC#include 'quaternion_relational\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 4, bool, Q > \fBglm::equal\fP (qua< T, Q > const &x, qua< T, Q > const &y)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 4, bool, Q > \fBglm::equal\fP (qua< T, Q > const &x, qua< T, Q > const &y, T epsilon)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 4, bool, Q > \fBglm::notEqual\fP (qua< T, Q > const &x, qua< T, Q > const &y)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 4, bool, Q > \fBglm::notEqual\fP (qua< T, Q > const &x, qua< T, Q > const &y, T epsilon)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_EXT_quaternion_relational\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
