.TH "Typhoon/ThirdParty/glm/glm/ext/quaternion_float.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/ext/quaternion_float.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./detail/type_quat\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef qua< float, defaultp > \fBglm::quat\fP"
.br
.RI "Quaternion of single-precision floating-point numbers\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_EXT_quaternion_float\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
