.TH "Typhoon/ThirdParty/glm/glm/ext/quaternion_geometric.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/ext/quaternion_geometric.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./geometric\&.hpp'\fP
.br
\fC#include '\&.\&./exponential\&.hpp'\fP
.br
\fC#include '\&.\&./ext/vector_relational\&.hpp'\fP
.br
\fC#include 'quaternion_geometric\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL T \fBglm::length\fP (qua< T, Q > const &q)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL qua< T, Q > \fBglm::normalize\fP (qua< T, Q > const &q)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL T \fBglm::dot\fP (qua< T, Q > const &x, qua< T, Q > const &y)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_QUALIFIER qua< T, Q > \fBglm::cross\fP (qua< T, Q > const &q1, qua< T, Q > const &q2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_EXT_quaternion_geometric\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
