.TH "Typhoon/ThirdParty/glm/glm/ext/quaternion_transform.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/ext/quaternion_transform.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./common\&.hpp'\fP
.br
\fC#include '\&.\&./trigonometric\&.hpp'\fP
.br
\fC#include '\&.\&./geometric\&.hpp'\fP
.br
\fC#include 'quaternion_transform\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL qua< T, Q > \fBglm::rotate\fP (qua< T, Q > const &q, T const &angle, vec< 3, T, Q > const &axis)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_EXT_quaternion_transform\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
