.TH "quick_guide" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
quick_guide \- Getting started 
This guide takes you through writing a small application using GLFW 3\&. The application will create a window and OpenGL context, render a rotating triangle and exit when the user closes the window or presses \fIEscape\fP\&. This guide will introduce a few of the most commonly used functions, but there are many more\&.
.PP
This guide assumes no experience with earlier versions of GLFW\&. If you have used GLFW 2 in the past, read \fBMoving from GLFW 2 to 3\fP, as some functions behave differently in GLFW 3\&.
.SH "Step by step"
.PP
.SS "Including the GLFW header"
In the source files of your application where you use OpenGL or GLFW, you need to include the GLFW 3 header file\&.
.PP
.PP
.nf
#include <GLFW/glfw3\&.h>
.fi
.PP
.PP
This defines all the constants, types and function prototypes of the GLFW API\&. It also includes the OpenGL header from your development environment and defines all the constants and types necessary for it to work on your platform without including any platform-specific headers\&.
.PP
In other words:
.PP
.IP "\(bu" 2
Do \fInot\fP include the OpenGL header yourself, as GLFW does this for you in a platform-independent way
.IP "\(bu" 2
Do \fInot\fP include \fCwindows\&.h\fP or other platform-specific headers unless you plan on using those APIs yourself
.IP "\(bu" 2
If you \fIdo\fP need to include such headers, include them \fIbefore\fP the GLFW header and it will detect this
.PP
.PP
On some platforms supported by GLFW the OpenGL header and link library only expose older versions of OpenGL\&. The most extreme case is Windows, which only exposes OpenGL 1\&.2\&. The easiest way to work around this is to use an \fBextension loader library\fP\&.
.PP
If you are using such a library then you should include its header \fIbefore\fP the GLFW header\&. This lets it replace the OpenGL header included by GLFW without conflicts\&. This example uses \fCglad2\fP, but the same rule applies to all such libraries\&.
.PP
.PP
.nf
#include <glad/gl\&.h>
#include <GLFW/glfw3\&.h>
.fi
.PP
.SS "Initializing and terminating GLFW"
Before you can use most GLFW functions, the library must be initialized\&. On successful initialization, \fCGLFW_TRUE\fP is returned\&. If an error occurred, \fCGLFW_FALSE\fP is returned\&.
.PP
.PP
.nf
if (!glfwInit())
{
    // Initialization failed
}
.fi
.PP
.PP
Note that \fCGLFW_TRUE\fP and \fCGLFW_FALSE\fP are and will always be one and zero\&.
.PP
When you are done using GLFW, typically just before the application exits, you need to terminate GLFW\&.
.PP
.PP
.nf
glfwTerminate();
.fi
.PP
.PP
This destroys any remaining windows and releases any other resources allocated by GLFW\&. After this call, you must initialize GLFW again before using any GLFW functions that require it\&.
.SS "Setting an error callback"
Most events are reported through callbacks, whether it's a key being pressed, a GLFW window being moved, or an error occurring\&. Callbacks are C functions (or C++ static methods) that are called by GLFW with arguments describing the event\&.
.PP
In case a GLFW function fails, an error is reported to the GLFW error callback\&. You can receive these reports with an error callback\&. This function must have the signature below but may do anything permitted in other callbacks\&.
.PP
.PP
.nf
void error_callback(int error, const char* description)
{
    fprintf(stderr, "Error: %s\n", description);
}
.fi
.PP
.PP
Callback functions must be set, so GLFW knows to call them\&. The function to set the error callback is one of the few GLFW functions that may be called before initialization, which lets you be notified of errors both during and after initialization\&.
.PP
.PP
.nf
glfwSetErrorCallback(error_callback);
.fi
.PP
.SS "Creating a window and context"
The window and its OpenGL context are created with a single call to \fBglfwCreateWindow\fP, which returns a handle to the created combined window and context object
.PP
.PP
.nf
GLFWwindow* window = glfwCreateWindow(640, 480, "My Title", NULL, NULL);
if (!window)
{
    // Window or OpenGL context creation failed
}
.fi
.PP
.PP
This creates a 640 by 480 windowed mode window with an OpenGL context\&. If window or OpenGL context creation fails, \fCNULL\fP will be returned\&. You should always check the return value\&. While window creation rarely fails, context creation depends on properly installed drivers and may fail even on machines with the necessary hardware\&.
.PP
By default, the OpenGL context GLFW creates may have any version\&. You can require a minimum OpenGL version by setting the \fCGLFW_CONTEXT_VERSION_MAJOR\fP and \fCGLFW_CONTEXT_VERSION_MINOR\fP hints \fIbefore\fP creation\&. If the required minimum version is not supported on the machine, context (and window) creation fails\&.
.PP
You can select the OpenGL profile by setting the \fCGLFW_OPENGL_PROFILE\fP hint\&. This program uses the core profile as that is the only profile macOS supports for OpenGL 3\&.x and 4\&.x\&.
.PP
.PP
.nf
glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
GLFWwindow* window = glfwCreateWindow(640, 480, "My Title", NULL, NULL);
if (!window)
{
    // Window or context creation failed
}
.fi
.PP
.PP
The window handle is passed to all window related functions and is provided to along to all window related callbacks, so they can tell which window received the event\&.
.PP
When a window and context is no longer needed, destroy it\&.
.PP
.PP
.nf
glfwDestroyWindow(window);
.fi
.PP
.PP
Once this function is called, no more events will be delivered for that window and its handle becomes invalid\&.
.SS "Making the OpenGL context current"
Before you can use the OpenGL API, you must have a current OpenGL context\&.
.PP
.PP
.nf
glfwMakeContextCurrent(window);
.fi
.PP
.PP
The context will remain current until you make another context current or until the window owning the current context is destroyed\&.
.PP
If you are using an \fBextension loader library\fP to access modern OpenGL then this is when to initialize it, as the loader needs a current context to load from\&. This example uses \fCglad\fP, but the same rule applies to all such libraries\&.
.PP
.PP
.nf
gladLoadGL(glfwGetProcAddress);
.fi
.PP
.SS "Checking the window close flag"
Each window has a flag indicating whether the window should be closed\&.
.PP
When the user attempts to close the window, either by pressing the close widget in the title bar or using a key combination like Alt+F4, this flag is set to 1\&. Note that \fBthe window isn't actually closed\fP, so you are expected to monitor this flag and either destroy the window or give some kind of feedback to the user\&.
.PP
.PP
.nf
while (!glfwWindowShouldClose(window))
{
    // Keep running
}
.fi
.PP
.PP
You can be notified when the user is attempting to close the window by setting a close callback with \fBglfwSetWindowCloseCallback\fP\&. The callback will be called immediately after the close flag has been set\&.
.PP
You can also set it yourself with \fBglfwSetWindowShouldClose\fP\&. This can be useful if you want to interpret other kinds of input as closing the window, like for example pressing the \fIEscape\fP key\&.
.SS "Receiving input events"
Each window has a large number of callbacks that can be set to receive all the various kinds of events\&. To receive key press and release events, create a key callback function\&.
.PP
.PP
.nf
static void key_callback(GLFWwindow* window, int key, int scancode, int action, int mods)
{
    if (key == GLFW_KEY_ESCAPE && action == GLFW_PRESS)
        glfwSetWindowShouldClose(window, GLFW_TRUE);
}
.fi
.PP
.PP
The key callback, like other window related callbacks, are set per-window\&.
.PP
.PP
.nf
glfwSetKeyCallback(window, key_callback);
.fi
.PP
.PP
In order for event callbacks to be called when events occur, you need to process events as described below\&.
.SS "Rendering with OpenGL"
Once you have a current OpenGL context, you can use OpenGL normally\&. In this tutorial, a multi-colored rotating triangle will be rendered\&. The framebuffer size needs to be retrieved for \fCglViewport\fP\&.
.PP
.PP
.nf
int width, height;
glfwGetFramebufferSize(window, &width, &height);
glViewport(0, 0, width, height);
.fi
.PP
.PP
You can also set a framebuffer size callback using \fBglfwSetFramebufferSizeCallback\fP and be notified when the size changes\&.
.PP
Actual rendering with OpenGL is outside the scope of this tutorial, but there are \fCmany\fP \fCexcellent\fP \fCtutorial\fP \fCsites\fP that teach modern OpenGL\&. Some of them use GLFW to create the context and window while others use GLUT or SDL, but remember that OpenGL itself always works the same\&.
.SS "Reading the timer"
To create smooth animation, a time source is needed\&. GLFW provides a timer that returns the number of seconds since initialization\&. The time source used is the most accurate on each platform and generally has micro- or nanosecond resolution\&.
.PP
.PP
.nf
double time = glfwGetTime();
.fi
.PP
.SS "Swapping buffers"
GLFW windows by default use double buffering\&. That means that each window has two rendering buffers; a front buffer and a back buffer\&. The front buffer is the one being displayed and the back buffer the one you render to\&.
.PP
When the entire frame has been rendered, the buffers need to be swapped with one another, so the back buffer becomes the front buffer and vice versa\&.
.PP
.PP
.nf
glfwSwapBuffers(window);
.fi
.PP
.PP
The swap interval indicates how many frames to wait until swapping the buffers, commonly known as \fIvsync\fP\&. By default, the swap interval is zero, meaning buffer swapping will occur immediately\&. On fast machines, many of those frames will never be seen, as the screen is still only updated typically 60-75 times per second, so this wastes a lot of CPU and GPU cycles\&.
.PP
Also, because the buffers will be swapped in the middle the screen update, leading to \fCscreen tearing\fP\&.
.PP
For these reasons, applications will typically want to set the swap interval to one\&. It can be set to higher values, but this is usually not recommended, because of the input latency it leads to\&.
.PP
.PP
.nf
glfwSwapInterval(1);
.fi
.PP
.PP
This function acts on the current context and will fail unless a context is current\&.
.SS "Processing events"
GLFW needs to communicate regularly with the window system both in order to receive events and to show that the application hasn't locked up\&. Event processing must be done regularly while you have visible windows and is normally done each frame after buffer swapping\&.
.PP
There are two methods for processing pending events; polling and waiting\&. This example will use event polling, which processes only those events that have already been received and then returns immediately\&.
.PP
.PP
.nf
glfwPollEvents();
.fi
.PP
.PP
This is the best choice when rendering continually, like most games do\&. If instead you only need to update your rendering once you have received new input, \fBglfwWaitEvents\fP is a better choice\&. It waits until at least one event has been received, putting the thread to sleep in the meantime, and then processes all received events\&. This saves a great deal of CPU cycles and is useful for, for example, many kinds of editing tools\&.
.SH "Putting it together"
.PP
Now that you know how to initialize GLFW, create a window and poll for keyboard input, it's possible to create a small program\&.
.PP
This program creates a 640 by 480 windowed mode window and starts a loop that clears the screen, renders a triangle and processes events until the user either presses \fIEscape\fP or closes the window\&.
.PP
.PP
.nf
.fi
.PP
 The program above can be found in the \fCsource package\fP as \fCexamples/triangle-opengl\&.c\fP and is compiled along with all other examples when you build GLFW\&. If you built GLFW from the source package then you already have this as \fCtriangle-opengl\&.exe\fP on Windows, \fCtriangle-opengl\fP on Linux or \fCtriangle-opengl\&.app\fP on macOS\&.
.PP
This tutorial used only a few of the many functions GLFW provides\&. There are guides for each of the areas covered by GLFW\&. Each guide will introduce all the functions for that category\&.
.PP
.IP "\(bu" 2
\fBIntroduction to the API\fP
.IP "\(bu" 2
\fBWindow guide\fP
.IP "\(bu" 2
\fBContext guide\fP
.IP "\(bu" 2
\fBMonitor guide\fP
.IP "\(bu" 2
\fBInput guide\fP
.PP
.PP
You can access reference documentation for any GLFW function by clicking it and the reference for each function links to related functions and guide sections\&.
.PP
The tutorial ends here\&. Once you have written a program that uses GLFW, you will need to compile and link it\&. How to do that depends on the development environment you are using and is best explained by the documentation for that environment\&. To learn about the details that are specific to GLFW, see \fBBuilding applications\fP\&. 
