.TH "Typhoon/ThirdParty/glm/glm/gtx/raw_data.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/gtx/raw_data.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./ext/scalar_uint_sized\&.hpp'\fP
.br
\fC#include '\&.\&./detail/setup\&.hpp'\fP
.br
\fC#include 'raw_data\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef detail::uint8 \fBglm::byte\fP"
.br
.ti -1c
.RI "typedef detail::uint16 \fBglm::word\fP"
.br
.ti -1c
.RI "typedef detail::uint32 \fBglm::dword\fP"
.br
.ti -1c
.RI "typedef detail::uint64 \fBglm::qword\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTX_raw_data\fP
.PP
\fBSee also:\fP
.RS 4
\fBCore features\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
