.TH "rgb" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rgb
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "FMT_CONSTEXPR_DECL \fBrgb\fP (uint8_t r_, uint8_t g_, uint8_t b_)"
.br
.ti -1c
.RI "FMT_CONSTEXPR_DECL \fBrgb\fP (uint32_t hex)"
.br
.ti -1c
.RI "FMT_CONSTEXPR_DECL \fBrgb\fP (color hex)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBr\fP"
.br
.ti -1c
.RI "uint8_t \fBg\fP"
.br
.ti -1c
.RI "uint8_t \fBb\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
