.TH "Typhoon/ThirdParty/glm/glm/gtx/rotate_vector.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/gtx/rotate_vector.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./gtx/transform\&.hpp'\fP
.br
\fC#include '\&.\&./gtc/epsilon\&.hpp'\fP
.br
\fC#include '\&.\&./ext/vector_relational\&.hpp'\fP
.br
\fC#include '\&.\&./glm\&.hpp'\fP
.br
\fC#include 'rotate_vector\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 3, T, Q > \fBglm::slerp\fP (vec< 3, T, Q > const &x, vec< 3, T, Q > const &y, T const &a)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 2, T, Q > \fBglm::rotate\fP (vec< 2, T, Q > const &v, T const &angle)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 3, T, Q > \fBglm::rotate\fP (vec< 3, T, Q > const &v, T const &angle, vec< 3, T, Q > const &normal)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 4, T, Q > \fBglm::rotate\fP (vec< 4, T, Q > const &v, T const &angle, vec< 3, T, Q > const &normal)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 3, T, Q > \fBglm::rotateX\fP (vec< 3, T, Q > const &v, T const &angle)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 3, T, Q > \fBglm::rotateY\fP (vec< 3, T, Q > const &v, T const &angle)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 3, T, Q > \fBglm::rotateZ\fP (vec< 3, T, Q > const &v, T const &angle)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 4, T, Q > \fBglm::rotateX\fP (vec< 4, T, Q > const &v, T const &angle)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 4, T, Q > \fBglm::rotateY\fP (vec< 4, T, Q > const &v, T const &angle)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 4, T, Q > \fBglm::rotateZ\fP (vec< 4, T, Q > const &v, T const &angle)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL mat< 4, 4, T, Q > \fBglm::orientation\fP (vec< 3, T, Q > const &Normal, vec< 3, T, Q > const &Up)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTX_rotate_vector\fP
.PP
\fBSee also:\fP
.RS 4
\fBCore features\fP (dependence) 
.PP
\fBGLM_GTX_transform\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
