.TH "Typhoon/ThirdParty/glm/glm/gtx/rotate_normalized_axis.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/gtx/rotate_normalized_axis.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./glm\&.hpp'\fP
.br
\fC#include '\&.\&./gtc/epsilon\&.hpp'\fP
.br
\fC#include '\&.\&./gtc/quaternion\&.hpp'\fP
.br
\fC#include 'rotate_normalized_axis\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL mat< 4, 4, T, Q > \fBglm::rotateNormalizedAxis\fP (mat< 4, 4, T, Q > const &m, T const &angle, vec< 3, T, Q > const &axis)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL qua< T, Q > \fBglm::rotateNormalizedAxis\fP (qua< T, Q > const &q, T const &angle, vec< 3, T, Q > const &axis)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTX_rotate_normalized_axis\fP
.PP
\fBSee also:\fP
.RS 4
\fBCore features\fP (dependence) 
.PP
\fBGLM_GTC_matrix_transform\fP 
.PP
\fBGLM_GTC_quaternion\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
