.TH "Typhoon/ThirdParty/glm/glm/gtc/round.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/gtc/round.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./detail/setup\&.hpp'\fP
.br
\fC#include '\&.\&./detail/qualifier\&.hpp'\fP
.br
\fC#include '\&.\&./detail/_vectorize\&.hpp'\fP
.br
\fC#include '\&.\&./vector_relational\&.hpp'\fP
.br
\fC#include '\&.\&./common\&.hpp'\fP
.br
\fC#include <limits>\fP
.br
\fC#include 'round\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genIUType > GLM_FUNC_DECL bool \fBglm::isPowerOfTwo\fP (genIUType v)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec< L, bool, Q > \fBglm::isPowerOfTwo\fP (vec< L, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename genIUType > GLM_FUNC_DECL genIUType \fBglm::ceilPowerOfTwo\fP (genIUType v)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec< L, T, Q > \fBglm::ceilPowerOfTwo\fP (vec< L, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename genIUType > GLM_FUNC_DECL genIUType \fBglm::floorPowerOfTwo\fP (genIUType v)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec< L, T, Q > \fBglm::floorPowerOfTwo\fP (vec< L, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename genIUType > GLM_FUNC_DECL genIUType \fBglm::roundPowerOfTwo\fP (genIUType v)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec< L, T, Q > \fBglm::roundPowerOfTwo\fP (vec< L, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename genIUType > GLM_FUNC_DECL bool \fBglm::isMultiple\fP (genIUType v, genIUType Multiple)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec< L, bool, Q > \fBglm::isMultiple\fP (vec< L, T, Q > const &v, T Multiple)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec< L, bool, Q > \fBglm::isMultiple\fP (vec< L, T, Q > const &v, vec< L, T, Q > const &Multiple)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::ceilMultiple\fP (genType v, genType Multiple)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec< L, T, Q > \fBglm::ceilMultiple\fP (vec< L, T, Q > const &v, vec< L, T, Q > const &Multiple)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::floorMultiple\fP (genType v, genType Multiple)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec< L, T, Q > \fBglm::floorMultiple\fP (vec< L, T, Q > const &v, vec< L, T, Q > const &Multiple)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::roundMultiple\fP (genType v, genType Multiple)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec< L, T, Q > \fBglm::roundMultiple\fP (vec< L, T, Q > const &v, vec< L, T, Q > const &Multiple)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_EXT_scalar_integer\fP
.PP
\fBSee also:\fP
.RS 4
\fBCore features\fP (dependence) 
.PP
\fBGLM_EXT_scalar_integer\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
