.TH "Typhoon/ThirdParty/glm/glm/ext/scalar_ulp.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/ext/scalar_ulp.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./ext/scalar_int_sized\&.hpp'\fP
.br
\fC#include '\&.\&./common\&.hpp'\fP
.br
\fC#include '\&.\&./detail/qualifier\&.hpp'\fP
.br
\fC#include 'scalar_ulp\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::nextFloat\fP (genType x)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::prevFloat\fP (genType x)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::nextFloat\fP (genType x, int ULPs)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::prevFloat\fP (genType x, int ULPs)"
.br
.ti -1c
.RI "GLM_FUNC_DECL int \fBglm::floatDistance\fP (float x, float y)"
.br
.ti -1c
.RI "GLM_FUNC_DECL int64 \fBglm::floatDistance\fP (double x, double y)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_EXT_scalar_ulp\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
