.TH "Typhoon/ThirdParty/glm/glm/ext/scalar_uint_sized.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/ext/scalar_uint_sized.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./detail/setup\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBglm::detail::is_int< uint8 >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::is_int< uint16 >\fP"
.br
.ti -1c
.RI "struct \fBglm::detail::is_int< uint64 >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned char \fBglm::detail::uint8\fP"
.br
.ti -1c
.RI "typedef unsigned short \fBglm::detail::uint16\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBglm::detail::uint32\fP"
.br
.ti -1c
.RI "typedef detail::uint8 \fBglm::uint8\fP"
.br
.RI "8 bit unsigned integer type\&. "
.ti -1c
.RI "typedef detail::uint16 \fBglm::uint16\fP"
.br
.RI "16 bit unsigned integer type\&. "
.ti -1c
.RI "typedef detail::uint32 \fBglm::uint32\fP"
.br
.RI "32 bit unsigned integer type\&. "
.ti -1c
.RI "typedef detail::uint64 \fBglm::uint64\fP"
.br
.RI "64 bit unsigned integer type\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_EXT_scalar_uint_sized\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
