.TH "Typhoon/ThirdParty/glm/glm/ext/scalar_common.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/ext/scalar_common.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./common\&.hpp'\fP
.br
\fC#include 'scalar_common\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::min\fP (T a, T b, T c)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::min\fP (T a, T b, T c, T d)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::max\fP (T a, T b, T c)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::max\fP (T a, T b, T c, T d)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::fmin\fP (T a, T b)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::fmin\fP (T a, T b, T c)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::fmin\fP (T a, T b, T c, T d)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::fmax\fP (T a, T b)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::fmax\fP (T a, T b, T C)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::fmax\fP (T a, T b, T C, T D)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_EXT_scalar_common\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
