.TH "spdlog::formatter" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spdlog::formatter
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBspdlog::pattern_formatter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBformat\fP (const \fBdetails::log_msg\fP &msg, fmt::memory_buffer &dest)=0"
.br
.ti -1c
.RI "virtual std::unique_ptr< \fBformatter\fP > \fBclone\fP () const =0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
