.TH "spdlog::sinks::base_sink< Mutex >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spdlog::sinks::base_sink< Mutex >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBspdlog::sinks::sink\fP\&.
.PP
Inherited by \fBspdlog::sinks::basic_file_sink< Mutex >\fP, \fBspdlog::sinks::daily_file_sink< Mutex, FileNameCalc >\fP, \fBspdlog::sinks::dist_sink< Mutex >\fP, \fBspdlog::sinks::null_sink< Mutex >\fP, \fBspdlog::sinks::ostream_sink< Mutex >\fP, \fBspdlog::sinks::rotating_file_sink< Mutex >\fP, \fBspdlog::sinks::syslog_sink< Mutex >\fP, \fBspdlog::sinks::systemd_sink< Mutex >\fP, and \fBspdlog::sinks::test_sink< Mutex >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbase_sink\fP (std::unique_ptr< \fBspdlog::formatter\fP > \fBformatter\fP)"
.br
.ti -1c
.RI "\fBbase_sink\fP (const \fBbase_sink\fP &)=delete"
.br
.ti -1c
.RI "\fBbase_sink\fP & \fBoperator=\fP (const \fBbase_sink\fP &)=delete"
.br
.ti -1c
.RI "void \fBlog\fP (const \fBdetails::log_msg\fP &msg) final"
.br
.ti -1c
.RI "void \fBflush\fP () final"
.br
.ti -1c
.RI "void \fBset_pattern\fP (const std::string &pattern) final"
.br
.ti -1c
.RI "void \fBset_formatter\fP (std::unique_ptr< \fBspdlog::formatter\fP > sink_formatter) final"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBsink_it_\fP (const \fBdetails::log_msg\fP &msg)=0"
.br
.ti -1c
.RI "virtual void \fBflush_\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBset_pattern_\fP (const std::string &pattern)"
.br
.ti -1c
.RI "virtual void \fBset_formatter_\fP (std::unique_ptr< \fBspdlog::formatter\fP > sink_formatter)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBspdlog::formatter\fP > \fBformatter_\fP"
.br
.ti -1c
.RI "Mutex \fBmutex_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
