.TH "spdlog::sinks::null_sink< Mutex >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spdlog::sinks::null_sink< Mutex >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBspdlog::sinks::base_sink< Mutex >\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBsink_it_\fP (const \fBdetails::log_msg\fP &) override"
.br
.ti -1c
.RI "void \fBflush_\fP () override"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
