.TH "spdlog::details::mpmc_blocking_queue< T >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spdlog::details::mpmc_blocking_queue< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBitem_type\fP = T"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmpmc_blocking_queue\fP (size_t max_items)"
.br
.ti -1c
.RI "void \fBenqueue\fP (T &&item)"
.br
.ti -1c
.RI "void \fBenqueue_nowait\fP (T &&item)"
.br
.ti -1c
.RI "bool \fBdequeue_for\fP (T &popped_item, std::chrono::milliseconds wait_duration)"
.br
.ti -1c
.RI "size_t \fBoverrun_counter\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
