.TH "spdlog::details::circular_q< T >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spdlog::details::circular_q< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBitem_type\fP = T"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcircular_q\fP (size_t max_items)"
.br
.ti -1c
.RI "void \fBpush_back\fP (T &&item)"
.br
.ti -1c
.RI "void \fBpop_front\fP (T &popped_item)"
.br
.ti -1c
.RI "bool \fBempty\fP ()"
.br
.ti -1c
.RI "bool \fBfull\fP ()"
.br
.ti -1c
.RI "size_t \fBoverrun_counter\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
