.TH "spdlog::details::console_mutex" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spdlog::details::console_mutex
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBmutex_t\fP = std::mutex"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static mutex_t & \fBmutex\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
