.TH "spdlog::details::short_level_formatter" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spdlog::details::short_level_formatter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBspdlog::details::flag_formatter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBshort_level_formatter\fP (\fBpadding_info\fP padinfo)"
.br
.ti -1c
.RI "void \fBformat\fP (const \fBdetails::log_msg\fP &msg, const std::tm &, fmt::memory_buffer &dest) override"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
