.TH "spdlog::sinks::wincolor_sink< ConsoleMutex >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spdlog::sinks::wincolor_sink< ConsoleMutex >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBspdlog::sinks::sink\fP\&.
.PP
Inherited by \fBspdlog::sinks::wincolor_stderr_sink< ConsoleMutex >\fP, and \fBspdlog::sinks::wincolor_stdout_sink< ConsoleMutex >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBwincolor_sink\fP (HANDLE out_handle, color_mode mode)"
.br
.ti -1c
.RI "\fBwincolor_sink\fP (const \fBwincolor_sink\fP &other)=delete"
.br
.ti -1c
.RI "\fBwincolor_sink\fP & \fBoperator=\fP (const \fBwincolor_sink\fP &other)=delete"
.br
.ti -1c
.RI "void \fBset_color\fP (level::level_enum level, WORD color)"
.br
.ti -1c
.RI "void \fBlog\fP (const \fBdetails::log_msg\fP &msg) final override"
.br
.ti -1c
.RI "void \fBflush\fP () final override"
.br
.ti -1c
.RI "void \fBset_pattern\fP (const std::string &pattern) override final"
.br
.ti -1c
.RI "void \fBset_formatter\fP (std::unique_ptr< \fBspdlog::formatter\fP > sink_formatter) override final"
.br
.ti -1c
.RI "void \fBset_color_mode\fP (color_mode mode)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const WORD \fBBOLD\fP = FOREGROUND_INTENSITY"
.br
.ti -1c
.RI "const WORD \fBRED\fP = FOREGROUND_RED"
.br
.ti -1c
.RI "const WORD \fBGREEN\fP = FOREGROUND_GREEN"
.br
.ti -1c
.RI "const WORD \fBCYAN\fP = FOREGROUND_GREEN | FOREGROUND_BLUE"
.br
.ti -1c
.RI "const WORD \fBWHITE\fP = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE"
.br
.ti -1c
.RI "const WORD \fBYELLOW\fP = FOREGROUND_RED | FOREGROUND_GREEN"
.br
.in -1c
.SS "Protected Types"

.in +1c
.ti -1c
.RI "using \fBmutex_t\fP = typename ConsoleMutex::mutex_t"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "WORD \fBset_console_attribs\fP (WORD attribs)"
.br
.ti -1c
.RI "void \fBprint_range_\fP (const fmt::memory_buffer &formatted, size_t start, size_t end)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "HANDLE \fBout_handle_\fP"
.br
.ti -1c
.RI "mutex_t & \fBmutex_\fP"
.br
.ti -1c
.RI "bool \fBshould_do_colors_\fP"
.br
.ti -1c
.RI "std::unique_ptr< \fBspdlog::formatter\fP > \fBformatter_\fP"
.br
.ti -1c
.RI "std::unordered_map< level::level_enum, WORD, level::level_hasher > \fBcolors_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
