.TH "spdlog::sinks::daily_file_sink< Mutex, FileNameCalc >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spdlog::sinks::daily_file_sink< Mutex, FileNameCalc >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBspdlog::sinks::base_sink< Mutex >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdaily_file_sink\fP (filename_t base_filename, int rotation_hour, int rotation_minute, bool truncate=false)"
.br
.ti -1c
.RI "const filename_t & \fBfilename\fP () const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBsink_it_\fP (const \fBdetails::log_msg\fP &msg) override"
.br
.ti -1c
.RI "void \fBflush_\fP () override"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
