.TH "spdlog::sinks::dup_filter_sink< Mutex >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spdlog::sinks::dup_filter_sink< Mutex >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBspdlog::sinks::dist_sink< Mutex >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<class Rep , class Period > \fBdup_filter_sink\fP (std::chrono::duration< Rep, Period > max_skip_duration)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBsink_it_\fP (const \fBdetails::log_msg\fP &msg) override"
.br
.ti -1c
.RI "bool \fBfilter_\fP (const \fBdetails::log_msg\fP &msg)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::chrono::microseconds \fBmax_skip_duration_\fP"
.br
.ti -1c
.RI "log_clock::time_point \fBlast_msg_time_\fP"
.br
.ti -1c
.RI "std::string \fBlast_msg_payload_\fP"
.br
.ti -1c
.RI "size_t \fBskip_counter_\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
