.TH "spdlog::sinks::wincolor_stderr_sink< ConsoleMutex >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spdlog::sinks::wincolor_stderr_sink< ConsoleMutex >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBspdlog::sinks::wincolor_sink< ConsoleMutex >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBwincolor_stderr_sink\fP (color_mode mode=color_mode::automatic)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
