.TH "spdlog::async_logger" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spdlog::async_logger
.SH SYNOPSIS
.br
.PP
.PP
Inherits enable_shared_from_this< async_logger >, and \fBspdlog::logger\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename It > \fBasync_logger\fP (std::string logger_name, It begin, It end, std::weak_ptr< \fBdetails::thread_pool\fP > tp, async_overflow_policy overflow_policy=async_overflow_policy::block)"
.br
.ti -1c
.RI "\fBasync_logger\fP (std::string logger_name, sinks_init_list sinks_list, std::weak_ptr< \fBdetails::thread_pool\fP > tp, async_overflow_policy overflow_policy=async_overflow_policy::block)"
.br
.ti -1c
.RI "\fBasync_logger\fP (std::string logger_name, sink_ptr single_sink, std::weak_ptr< \fBdetails::thread_pool\fP > tp, async_overflow_policy overflow_policy=async_overflow_policy::block)"
.br
.ti -1c
.RI "std::shared_ptr< \fBlogger\fP > \fBclone\fP (std::string new_name) override"
.br
.ti -1c
.RI "template<typename It > SPDLOG_INLINE \fBasync_logger\fP (std::string logger_name, It begin, It end, std::weak_ptr< \fBdetails::thread_pool\fP > tp, async_overflow_policy overflow_policy)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBsink_it_\fP (\fBdetails::log_msg\fP &msg) override"
.br
.ti -1c
.RI "void \fBflush_\fP () override"
.br
.ti -1c
.RI "void \fBbackend_log_\fP (const \fBdetails::log_msg\fP &incoming_log_msg)"
.br
.ti -1c
.RI "void \fBbackend_flush_\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBdetails::thread_pool\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
