.TH "spdlog::source_loc" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spdlog::source_loc
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "SPDLOG_CONSTEXPR \fBsource_loc\fP (const char *filename_in, int line_in, const char *funcname_in)"
.br
.ti -1c
.RI "SPDLOG_CONSTEXPR bool \fBempty\fP () const SPDLOG_NOEXCEPT"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBfilename\fP {nullptr}"
.br
.ti -1c
.RI "int \fBline\fP {0}"
.br
.ti -1c
.RI "const char * \fBfuncname\fP {nullptr}"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
