.TH "spdlog::details::async_msg" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spdlog::details::async_msg
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBasync_msg\fP (const \fBasync_msg\fP &)=delete"
.br
.ti -1c
.RI "\fBasync_msg\fP (\fBasync_msg\fP &&)=default"
.br
.ti -1c
.RI "\fBasync_msg\fP & \fBoperator=\fP (\fBasync_msg\fP &&)=default"
.br
.ti -1c
.RI "\fBasync_msg\fP (async_logger_ptr &&worker, async_msg_type the_type, \fBdetails::log_msg\fP &m)"
.br
.ti -1c
.RI "\fBasync_msg\fP (async_logger_ptr &&worker, async_msg_type the_type)"
.br
.ti -1c
.RI "\fBasync_msg\fP (async_msg_type the_type)"
.br
.ti -1c
.RI "\fBlog_msg\fP \fBto_log_msg\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "async_msg_type \fBmsg_type\fP"
.br
.ti -1c
.RI "level::level_enum \fBlevel\fP"
.br
.ti -1c
.RI "log_clock::time_point \fBtime\fP"
.br
.ti -1c
.RI "size_t \fBthread_id\fP"
.br
.ti -1c
.RI "fmt::basic_memory_buffer< char, 176 > \fBraw\fP"
.br
.ti -1c
.RI "\fBsource_loc\fP \fBsource\fP"
.br
.ti -1c
.RI "async_logger_ptr \fBworker_ptr\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
