.TH "spdlog::details::padding_info" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spdlog::details::padding_info
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBpad_side\fP { \fBleft\fP, \fBright\fP, \fBcenter\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpadding_info\fP (size_t width, padding_info::pad_side side)"
.br
.ti -1c
.RI "bool \fBenabled\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const size_t \fBwidth_\fP = 0"
.br
.ti -1c
.RI "const pad_side \fBside_\fP = left"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
