.TH "spdlog::sinks::systemd_sink< Mutex >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spdlog::sinks::systemd_sink< Mutex >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <systemd_sink\&.h>\fP
.PP
Inherits \fBspdlog::sinks::base_sink< Mutex >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsystemd_sink\fP (const \fBsystemd_sink\fP &)=delete"
.br
.ti -1c
.RI "\fBsystemd_sink\fP & \fBoperator=\fP (const \fBsystemd_sink\fP &)=delete"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBsink_it_\fP (const \fBdetails::log_msg\fP &msg) override"
.br
.ti -1c
.RI "int \fBsyslog_level\fP (level::level_enum l)"
.br
.ti -1c
.RI "void \fBflush_\fP () override"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::array< int, 7 > \fBsyslog_levels_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Mutex>
.br
class spdlog::sinks::systemd_sink< Mutex >"
Sink that write to systemd journal using the \fCsd_journal_send()\fP library call\&.
.PP
Locking is not needed, as \fCsd_journal_send()\fP itself is thread-safe\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
