.TH "spdlog::details::file_helper" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spdlog::details::file_helper
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBfile_helper\fP (const \fBfile_helper\fP &)=delete"
.br
.ti -1c
.RI "\fBfile_helper\fP & \fBoperator=\fP (const \fBfile_helper\fP &)=delete"
.br
.ti -1c
.RI "void \fBopen\fP (const filename_t &fname, bool truncate=false)"
.br
.ti -1c
.RI "void \fBreopen\fP (bool truncate)"
.br
.ti -1c
.RI "void \fBflush\fP ()"
.br
.ti -1c
.RI "void \fBclose\fP ()"
.br
.ti -1c
.RI "void \fBwrite\fP (const fmt::memory_buffer &buf)"
.br
.ti -1c
.RI "size_t \fBsize\fP () const"
.br
.ti -1c
.RI "const filename_t & \fBfilename\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBfile_exists\fP (const filename_t &fname)"
.br
.ti -1c
.RI "static std::tuple< filename_t, filename_t > \fBsplit_by_extension\fP (const filename_t &fname)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
