.TH "spdlog::details::scoped_pad" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spdlog::details::scoped_pad
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBscoped_pad\fP (size_t wrapped_size, \fBpadding_info\fP &padinfo, fmt::memory_buffer &dest)"
.br
.ti -1c
.RI "\fBscoped_pad\fP (const spdlog::string_view_t &txt, \fBpadding_info\fP &padinfo, fmt::memory_buffer &dest)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
