.TH "spdlog::details::null_atomic_int" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spdlog::details::null_atomic_int
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBnull_atomic_int\fP (int val)"
.br
.ti -1c
.RI "int \fBload\fP (std::memory_order) const"
.br
.ti -1c
.RI "void \fBstore\fP (int val)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBvalue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
