.TH "spdlog::details::periodic_worker" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spdlog::details::periodic_worker
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBperiodic_worker\fP (const std::function< void()> &callback_fun, std::chrono::seconds interval)"
.br
.ti -1c
.RI "\fBperiodic_worker\fP (const \fBperiodic_worker\fP &)=delete"
.br
.ti -1c
.RI "\fBperiodic_worker\fP & \fBoperator=\fP (const \fBperiodic_worker\fP &)=delete"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
