.TH "spdlog::sinks::syslog_sink< Mutex >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spdlog::sinks::syslog_sink< Mutex >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <syslog_sink\&.h>\fP
.PP
Inherits \fBspdlog::sinks::base_sink< Mutex >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsyslog_sink\fP (std::string ident, int syslog_option, int syslog_facility, bool enable_formatting)"
.br
.ti -1c
.RI "\fBsyslog_sink\fP (const \fBsyslog_sink\fP &)=delete"
.br
.ti -1c
.RI "\fBsyslog_sink\fP & \fBoperator=\fP (const \fBsyslog_sink\fP &)=delete"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBsink_it_\fP (const \fBdetails::log_msg\fP &msg) override"
.br
.ti -1c
.RI "void \fBflush_\fP () override"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fBenable_formatting_\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Mutex>
.br
class spdlog::sinks::syslog_sink< Mutex >"
Sink that write to syslog using the \fCsyscall()\fP library call\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
