.TH "stbtt_fontinfo" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stbtt_fontinfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBuserdata\fP"
.br
.ti -1c
.RI "unsigned char * \fBdata\fP"
.br
.ti -1c
.RI "int \fBfontstart\fP"
.br
.ti -1c
.RI "int \fBnumGlyphs\fP"
.br
.ti -1c
.RI "int \fBloca\fP"
.br
.ti -1c
.RI "int \fBhead\fP"
.br
.ti -1c
.RI "int \fBglyf\fP"
.br
.ti -1c
.RI "int \fBhhea\fP"
.br
.ti -1c
.RI "int \fBhmtx\fP"
.br
.ti -1c
.RI "int \fBkern\fP"
.br
.ti -1c
.RI "int \fBgpos\fP"
.br
.ti -1c
.RI "int \fBindex_map\fP"
.br
.ti -1c
.RI "int \fBindexToLocFormat\fP"
.br
.ti -1c
.RI "\fBstbtt__buf\fP \fBcff\fP"
.br
.ti -1c
.RI "\fBstbtt__buf\fP \fBcharstrings\fP"
.br
.ti -1c
.RI "\fBstbtt__buf\fP \fBgsubrs\fP"
.br
.ti -1c
.RI "\fBstbtt__buf\fP \fBsubrs\fP"
.br
.ti -1c
.RI "\fBstbtt__buf\fP \fBfontdicts\fP"
.br
.ti -1c
.RI "\fBstbtt__buf\fP \fBfdselect\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
