.TH "stbtt_pack_range" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stbtt_pack_range
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBfont_size\fP"
.br
.ti -1c
.RI "int \fBfirst_unicode_codepoint_in_range\fP"
.br
.ti -1c
.RI "int * \fBarray_of_unicode_codepoints\fP"
.br
.ti -1c
.RI "int \fBnum_chars\fP"
.br
.ti -1c
.RI "\fBstbtt_packedchar\fP * \fBchardata_for_range\fP"
.br
.ti -1c
.RI "unsigned char \fBh_oversample\fP"
.br
.ti -1c
.RI "unsigned char \fBv_oversample\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
