.TH "stbtt_vertex" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stbtt_vertex
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "stbtt_vertex_type \fBx\fP"
.br
.ti -1c
.RI "stbtt_vertex_type \fBy\fP"
.br
.ti -1c
.RI "stbtt_vertex_type \fBcx\fP"
.br
.ti -1c
.RI "stbtt_vertex_type \fBcy\fP"
.br
.ti -1c
.RI "stbtt_vertex_type \fBcx1\fP"
.br
.ti -1c
.RI "stbtt_vertex_type \fBcy1\fP"
.br
.ti -1c
.RI "unsigned char \fBtype\fP"
.br
.ti -1c
.RI "unsigned char \fBpadding\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
