.TH "step_::entry< EDGE, VEC >" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
step_::entry< EDGE, VEC >
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "EDGE \fBedge\fP"
.br
.ti -1c
.RI "VEC \fBx\fP"
.br
.ti -1c
.RI "VEC \fBresult\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
