.TH "Typhoon/ThirdParty/glm/glm/gtx/string_cast.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/gtx/string_cast.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./glm\&.hpp'\fP
.br
\fC#include '\&.\&./gtc/type_precision\&.hpp'\fP
.br
\fC#include '\&.\&./gtc/quaternion\&.hpp'\fP
.br
\fC#include '\&.\&./gtx/dual_quaternion\&.hpp'\fP
.br
\fC#include <string>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include 'string_cast\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL std::string \fBglm::to_string\fP (genType const &x)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTX_string_cast\fP
.PP
\fBSee also:\fP
.RS 4
\fBCore features\fP (dependence) 
.PP
\fBGLM_GTX_integer\fP (dependence) 
.PP
\fBGLM_GTX_quaternion\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
