.TH "texture_object" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
texture_object
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "VkSampler \fBsampler\fP"
.br
.ti -1c
.RI "VkImage \fBimage\fP"
.br
.ti -1c
.RI "VkImageLayout \fBimageLayout\fP"
.br
.ti -1c
.RI "VkDeviceMemory \fBmem\fP"
.br
.ti -1c
.RI "VkImageView \fBview\fP"
.br
.ti -1c
.RI "int32_t \fBtex_width\fP"
.br
.ti -1c
.RI "int32_t \fBtex_height\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
