.TH "Typhoon/ThirdParty/glm/glm/gtx/texture.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/gtx/texture.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./glm\&.hpp'\fP
.br
\fC#include '\&.\&./gtc/integer\&.hpp'\fP
.br
\fC#include '\&.\&./gtx/component_wise\&.hpp'\fP
.br
\fC#include 'texture\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> T \fBglm::levels\fP (vec< L, T, Q > const &Extent)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTX_texture\fP
.PP
\fBSee also:\fP
.RS 4
\fBCore features\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
