.TH "Typhoon/ThirdParty/glm/glm/detail/type_mat4x2.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/detail/type_mat4x2.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'type_vec2\&.hpp'\fP
.br
\fC#include 'type_vec4\&.hpp'\fP
.br
\fC#include <limits>\fP
.br
\fC#include <cstddef>\fP
.br
\fC#include 'type_mat4x2\&.inl'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBglm::mat< 4, 2, T, Q >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL mat< 4, 2, T, Q > \fBglm::operator+\fP (mat< 4, 2, T, Q > const &m)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL mat< 4, 2, T, Q > \fBglm::operator\-\fP (mat< 4, 2, T, Q > const &m)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL mat< 4, 2, T, Q > \fBglm::operator+\fP (mat< 4, 2, T, Q > const &m, T scalar)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL mat< 4, 2, T, Q > \fBglm::operator+\fP (mat< 4, 2, T, Q > const &m1, mat< 4, 2, T, Q > const &m2)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL mat< 4, 2, T, Q > \fBglm::operator\-\fP (mat< 4, 2, T, Q > const &m, T scalar)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL mat< 4, 2, T, Q > \fBglm::operator\-\fP (mat< 4, 2, T, Q > const &m1, mat< 4, 2, T, Q > const &m2)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL mat< 4, 2, T, Q > \fBglm::operator *\fP (mat< 4, 2, T, Q > const &m, T scalar)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL mat< 4, 2, T, Q > \fBglm::operator *\fP (T scalar, mat< 4, 2, T, Q > const &m)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL mat< 4, 2, T, Q >::col_type \fBglm::operator *\fP (mat< 4, 2, T, Q > const &m, typename mat< 4, 2, T, Q >::row_type const &v)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL mat< 4, 2, T, Q >::row_type \fBglm::operator *\fP (typename mat< 4, 2, T, Q >::col_type const &v, mat< 4, 2, T, Q > const &m)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL mat< 2, 2, T, Q > \fBglm::operator *\fP (mat< 4, 2, T, Q > const &m1, mat< 2, 4, T, Q > const &m2)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL mat< 3, 2, T, Q > \fBglm::operator *\fP (mat< 4, 2, T, Q > const &m1, mat< 3, 4, T, Q > const &m2)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL mat< 4, 2, T, Q > \fBglm::operator *\fP (mat< 4, 2, T, Q > const &m1, mat< 4, 4, T, Q > const &m2)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL mat< 4, 2, T, Q > \fBglm::operator/\fP (mat< 4, 2, T, Q > const &m, T scalar)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL mat< 4, 2, T, Q > \fBglm::operator/\fP (T scalar, mat< 4, 2, T, Q > const &m)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL bool \fBglm::operator==\fP (mat< 4, 2, T, Q > const &m1, mat< 4, 2, T, Q > const &m2)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL bool \fBglm::operator!=\fP (mat< 4, 2, T, Q > const &m1, mat< 4, 2, T, Q > const &m2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCore features\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
