.TH "Typhoon/ThirdParty/glm/glm/gtc/type_ptr.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/gtc/type_ptr.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./gtc/quaternion\&.hpp'\fP
.br
\fC#include '\&.\&./gtc/vec1\&.hpp'\fP
.br
\fC#include '\&.\&./vec2\&.hpp'\fP
.br
\fC#include '\&.\&./vec3\&.hpp'\fP
.br
\fC#include '\&.\&./vec4\&.hpp'\fP
.br
\fC#include '\&.\&./mat2x2\&.hpp'\fP
.br
\fC#include '\&.\&./mat2x3\&.hpp'\fP
.br
\fC#include '\&.\&./mat2x4\&.hpp'\fP
.br
\fC#include '\&.\&./mat3x2\&.hpp'\fP
.br
\fC#include '\&.\&./mat3x3\&.hpp'\fP
.br
\fC#include '\&.\&./mat3x4\&.hpp'\fP
.br
\fC#include '\&.\&./mat4x2\&.hpp'\fP
.br
\fC#include '\&.\&./mat4x3\&.hpp'\fP
.br
\fC#include '\&.\&./mat4x4\&.hpp'\fP
.br
\fC#include <cstring>\fP
.br
\fC#include 'type_ptr\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType::value_type const  * \fBglm::value_ptr\fP (genType const &v)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 1, T, Q > \fBglm::make_vec1\fP (vec< 1, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 1, T, Q > \fBglm::make_vec1\fP (vec< 2, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 1, T, Q > \fBglm::make_vec1\fP (vec< 3, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 1, T, Q > \fBglm::make_vec1\fP (vec< 4, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 2, T, Q > \fBglm::make_vec2\fP (vec< 1, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 2, T, Q > \fBglm::make_vec2\fP (vec< 2, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 2, T, Q > \fBglm::make_vec2\fP (vec< 3, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 2, T, Q > \fBglm::make_vec2\fP (vec< 4, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 3, T, Q > \fBglm::make_vec3\fP (vec< 1, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 3, T, Q > \fBglm::make_vec3\fP (vec< 2, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 3, T, Q > \fBglm::make_vec3\fP (vec< 3, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 3, T, Q > \fBglm::make_vec3\fP (vec< 4, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 4, T, Q > \fBglm::make_vec4\fP (vec< 1, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 4, T, Q > \fBglm::make_vec4\fP (vec< 2, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 4, T, Q > \fBglm::make_vec4\fP (vec< 3, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename T , qualifier Q> GLM_FUNC_DECL vec< 4, T, Q > \fBglm::make_vec4\fP (vec< 4, T, Q > const &v)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL vec< 2, T, defaultp > \fBglm::make_vec2\fP (T const *const ptr)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL vec< 3, T, defaultp > \fBglm::make_vec3\fP (T const *const ptr)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL vec< 4, T, defaultp > \fBglm::make_vec4\fP (T const *const ptr)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL mat< 2, 2, T, defaultp > \fBglm::make_mat2x2\fP (T const *const ptr)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL mat< 2, 3, T, defaultp > \fBglm::make_mat2x3\fP (T const *const ptr)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL mat< 2, 4, T, defaultp > \fBglm::make_mat2x4\fP (T const *const ptr)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL mat< 3, 2, T, defaultp > \fBglm::make_mat3x2\fP (T const *const ptr)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL mat< 3, 3, T, defaultp > \fBglm::make_mat3x3\fP (T const *const ptr)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL mat< 3, 4, T, defaultp > \fBglm::make_mat3x4\fP (T const *const ptr)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL mat< 4, 2, T, defaultp > \fBglm::make_mat4x2\fP (T const *const ptr)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL mat< 4, 3, T, defaultp > \fBglm::make_mat4x3\fP (T const *const ptr)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL mat< 4, 4, T, defaultp > \fBglm::make_mat4x4\fP (T const *const ptr)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL mat< 2, 2, T, defaultp > \fBglm::make_mat2\fP (T const *const ptr)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL mat< 3, 3, T, defaultp > \fBglm::make_mat3\fP (T const *const ptr)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL mat< 4, 4, T, defaultp > \fBglm::make_mat4\fP (T const *const ptr)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL qua< T, defaultp > \fBglm::make_quat\fP (T const *const ptr)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTC_type_ptr\fP
.PP
\fBSee also:\fP
.RS 4
\fBCore features\fP (dependence) 
.PP
\fBGLM_GTC_quaternion\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
