.TH "Typhoon/ThirdParty/glm/glm/gtc/type_precision.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/gtc/type_precision.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./gtc/quaternion\&.hpp'\fP
.br
\fC#include '\&.\&./gtc/vec1\&.hpp'\fP
.br
\fC#include '\&.\&./ext/scalar_int_sized\&.hpp'\fP
.br
\fC#include '\&.\&./ext/scalar_uint_sized\&.hpp'\fP
.br
\fC#include '\&.\&./detail/type_vec2\&.hpp'\fP
.br
\fC#include '\&.\&./detail/type_vec3\&.hpp'\fP
.br
\fC#include '\&.\&./detail/type_vec4\&.hpp'\fP
.br
\fC#include '\&.\&./detail/type_mat2x2\&.hpp'\fP
.br
\fC#include '\&.\&./detail/type_mat2x3\&.hpp'\fP
.br
\fC#include '\&.\&./detail/type_mat2x4\&.hpp'\fP
.br
\fC#include '\&.\&./detail/type_mat3x2\&.hpp'\fP
.br
\fC#include '\&.\&./detail/type_mat3x3\&.hpp'\fP
.br
\fC#include '\&.\&./detail/type_mat3x4\&.hpp'\fP
.br
\fC#include '\&.\&./detail/type_mat4x2\&.hpp'\fP
.br
\fC#include '\&.\&./detail/type_mat4x3\&.hpp'\fP
.br
\fC#include '\&.\&./detail/type_mat4x4\&.hpp'\fP
.br
\fC#include 'type_precision\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_GTC_type_precision\fP
.PP
\fBSee also:\fP
.RS 4
\fBCore features\fP (dependence) 
.PP
\fBGLM_GTC_quaternion\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
