.TH "TyphoonEngine::Renderers::OpenGLIndexBuffer" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TyphoonEngine::Renderers::OpenGLIndexBuffer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTyphoonEngine::Renderers::IIndexBuffer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOpenGLIndexBuffer\fP (const \fBglm::uint32\fP *indices, \fBglm::uint32\fP count)"
.br
.ti -1c
.RI "virtual void \fBBind\fP () const override"
.br
.ti -1c
.RI "virtual void \fBUnbind\fP () const override"
.br
.ti -1c
.RI "virtual const \fBglm::uint32\fP \fBGetCount\fP () const override"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
