.TH "TyphoonEngine::WindowWin64" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TyphoonEngine::WindowWin64
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTyphoonEngine::IWindow\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBWindowData\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWindowWin64\fP (const \fBWindowProperties\fP &props)"
.br
.ti -1c
.RI "virtual void \fBSetEventCallback\fP (const EventCallbackFn &callback) override"
.br
.ti -1c
.RI "virtual bool \fBUpdate\fP () override"
.br
.ti -1c
.RI "virtual void \fBSetVSync\fP (bool bEnable) override"
.br
.ti -1c
.RI "virtual bool \fBIsVSync\fP () const override"
.br
.ti -1c
.RI "virtual const \fBglm::ivec2\fP \fBGetWindowSize\fP () const override"
.br
.ti -1c
.RI "virtual void * \fBGetNativeWindow\fP () const override"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
