.TH "TyphoonEngine::Renderers::IRenderingContext" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TyphoonEngine::Renderers::IRenderingContext
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBTyphoonEngine::Renderers::DirectXContext\fP, \fBTyphoonEngine::Renderers::MetalContext\fP, \fBTyphoonEngine::Renderers::OpenGLContext\fP, and \fBTyphoonEngine::Renderers::VulkanContext\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBInit\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBSwapBuffers\fP ()=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
