.TH "TyphoonEngine::Renderers::IVertexBuffer" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TyphoonEngine::Renderers::IVertexBuffer
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBTyphoonEngine::Renderers::OpenGLVertexBuffer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBBind\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBUnbind\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBSetLayout\fP (const \fBBufferLayout\fP &layout)=0"
.br
.ti -1c
.RI "virtual const \fBBufferLayout\fP & \fBGetLayout\fP () const =0"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBIVertexBuffer\fP * \fBCreate\fP (const float *vertices, \fBglm::uint32\fP size)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
