.TH "TyphoonEngine::WindowWin64::WindowData" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TyphoonEngine::WindowWin64::WindowData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBglm::ivec2\fP \fBm_dims\fP"
.br
.ti -1c
.RI "\fBglm::uint8\fP \fBm_monitorId\fP"
.br
.ti -1c
.RI "bool \fBm_bVSync\fP"
.br
.ti -1c
.RI "EWINDOW_TYPE \fBm_type\fP"
.br
.ti -1c
.RI "EventCallbackFn \fBm_callback\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
