.TH "TyphoonEngine::Layer" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TyphoonEngine::Layer
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBTyphoonEngine::ImGuiLayer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLayer\fP (const std::string &name='Layer', bool bEnable=true)"
.br
.ti -1c
.RI "virtual void \fBOnAttach\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnDetach\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnUpdate\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnEvent\fP (\fBEvent\fP &Evt)"
.br
.ti -1c
.RI "virtual void \fBOnImGuiRender\fP ()"
.br
.ti -1c
.RI "void \fBSetEnabled\fP (bool bEnable)"
.br
.ti -1c
.RI "bool \fBIsEnabled\fP () const"
.br
.ti -1c
.RI "const std::string & \fBGetName\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
