.TH "TyphoonEngine::Renderers::OpenGLRendererAPI" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TyphoonEngine::Renderers::OpenGLRendererAPI
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTyphoonEngine::Renderers::RendererAPI\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBSetClearColour\fP (const \fBglm::vec4\fP &colour) override"
.br
.ti -1c
.RI "virtual void \fBClear\fP () override"
.br
.ti -1c
.RI "virtual void \fBDrawIndexed\fP (const std::shared_ptr< \fBVertexArray\fP > &vArray) override"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
