.TH "TyphoonEngine::EventDispatch" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TyphoonEngine::EventDispatch
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEventDispatch\fP (\fBEvent\fP &event)"
.br
.ti -1c
.RI "template<typename T > bool \fBDispatch\fP (EventFn< T > func)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
