.TH "TyphoonEngine::Application" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TyphoonEngine::Application
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const \fBIWindow\fP * \fBGetWindow\fP () const"
.br
.ti -1c
.RI "void \fBRun\fP ()"
.br
.ti -1c
.RI "void \fBOnEvent\fP (\fBEvent\fP &Evt)"
.br
.ti -1c
.RI "bool \fBOnWindowClose\fP (\fBWindowCloseEvent\fP &Evt)"
.br
.ti -1c
.RI "bool \fBOnKeyPressed\fP (\fBKeyPressedEvent\fP &Evt)"
.br
.ti -1c
.RI "void \fBPushLayer\fP (\fBLayer\fP *layer)"
.br
.ti -1c
.RI "void \fBPushOverlay\fP (\fBLayer\fP *layer)"
.br
.ti -1c
.RI "void \fBPopLayer\fP (\fBLayer\fP *layer)"
.br
.ti -1c
.RI "void \fBPopOverlay\fP (\fBLayer\fP *layer)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const \fBApplication\fP & \fBGet\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
