.TH "TyphoonEngine::Log" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TyphoonEngine::Log
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBInit\fP (\fBglm::int32\fP logLevel=0, const std::string &logFormat='%^[%T] %n: %v%$')"
.br
.ti -1c
.RI "static std::shared_ptr< \fBspdlog::logger\fP > & \fBGetCoreLogger\fP ()"
.br
.ti -1c
.RI "static std::shared_ptr< \fBspdlog::logger\fP > & \fBGetClientLogger\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
