.TH "TyphoonEngine::Renderers::MetalContext" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TyphoonEngine::Renderers::MetalContext
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTyphoonEngine::Renderers::IRenderingContext\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP () override"
.br
.ti -1c
.RI "void \fBSwapBuffers\fP () override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
