.TH "TyphoonEngine::Renderers::OpenGLVertexBuffer" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TyphoonEngine::Renderers::OpenGLVertexBuffer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTyphoonEngine::Renderers::IVertexBuffer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOpenGLVertexBuffer\fP (const float *vertices, \fBglm::uint32\fP size)"
.br
.ti -1c
.RI "virtual void \fBBind\fP () const override"
.br
.ti -1c
.RI "virtual void \fBUnbind\fP () const override"
.br
.ti -1c
.RI "virtual void \fBSetLayout\fP (const \fBBufferLayout\fP &layout) override"
.br
.ti -1c
.RI "virtual const \fBBufferLayout\fP & \fBGetLayout\fP () const override"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
