.TH "TyphoonEngine::MouseMovedEvent" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TyphoonEngine::MouseMovedEvent
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTyphoonEngine::Event\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMouseMovedEvent\fP (float x, float y)"
.br
.ti -1c
.RI "const std::string \fBToString\fP () const override"
.br
.ti -1c
.RI "void \fBGetPosition\fP (float &x, float &y) const"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
