.TH "TyphoonEngine::Renderers::RendererAPI" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TyphoonEngine::Renderers::RendererAPI
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBTyphoonEngine::Renderers::OpenGLRendererAPI\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBAPI\fP : unsigned char { \fBNone\fP = 0, \fBOpenGL\fP, \fBDirectX\fP, \fBVulkan\fP, \fBMetal\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBSetClearColour\fP (const \fBglm::vec4\fP &colour=\fBglm::vec4\fP(0\&.4, 0\&.4, 0\&.1, 1\&.0))=0"
.br
.ti -1c
.RI "virtual void \fBClear\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBDrawIndexed\fP (const std::shared_ptr< \fBVertexArray\fP > &vArray)=0"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static API \fBGetAPI\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
