.TH "TyphoonEngine::Renderers::OpenGLVertexArray" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TyphoonEngine::Renderers::OpenGLVertexArray
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTyphoonEngine::Renderers::VertexArray\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBBind\fP () const override"
.br
.ti -1c
.RI "virtual void \fBUnbind\fP () const override"
.br
.ti -1c
.RI "virtual void \fBAddVertexBuffer\fP (const std::shared_ptr< \fBIVertexBuffer\fP > &vBuffer) override"
.br
.ti -1c
.RI "virtual void \fBSetIndexBuffer\fP (const std::shared_ptr< \fBIIndexBuffer\fP > &iBuffer) override"
.br
.ti -1c
.RI "virtual const std::vector< std::shared_ptr< \fBIVertexBuffer\fP > > & \fBGetVertexBuffers\fP () const"
.br
.ti -1c
.RI "virtual const std::shared_ptr< \fBIIndexBuffer\fP > & \fBGetIndexBuffer\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
