.TH "TyphoonEngine::KeyEvent" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TyphoonEngine::KeyEvent
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTyphoonEngine::Event\fP\&.
.PP
Inherited by \fBTyphoonEngine::KeyPressedEvent\fP, and \fBTyphoonEngine::KeyReleasedEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBglm::int32\fP \fBGetKeyCode\fP () const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBKeyEvent\fP (\fBglm::int32\fP keyCode)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
