.TH "uSynergyCookie" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uSynergyCookie \- User context type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <uSynergy\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBignored\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
User context type\&. 

The \fBuSynergyCookie\fP type is an opaque type that is used by uSynergy to communicate to the client\&. It is passed along to callback functions as context\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
