.TH "Typhoon/ThirdParty/glm/glm/ext/vector_uint1.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/ext/vector_uint1.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./detail/type_vec1\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef vec< 1, unsigned int, defaultp > \fBglm::uvec1\fP"
.br
.RI "1 component vector of unsigned integer numbers\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_EXT_vector_uint1\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
