.TH "Typhoon/ThirdParty/glm/glm/ext/vector_int3_precision.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/ext/vector_int3_precision.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./detail/type_vec3\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef vec< 3, int, highp > \fBglm::highp_ivec3\fP"
.br
.ti -1c
.RI "typedef vec< 3, int, mediump > \fBglm::mediump_ivec3\fP"
.br
.ti -1c
.RI "typedef vec< 3, int, lowp > \fBglm::lowp_ivec3\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCore features\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
