.TH "Typhoon/ThirdParty/glm/glm/ext/vector_ulp.hpp" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typhoon/ThirdParty/glm/glm/ext/vector_ulp.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./ext/scalar_ulp\&.hpp'\fP
.br
\fC#include 'vector_ulp\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.RI "\fBCore features\fP "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec< L, T, Q > \fBglm::nextFloat\fP (vec< L, T, Q > const &x)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec< L, T, Q > \fBglm::nextFloat\fP (vec< L, T, Q > const &x, int ULPs)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec< L, T, Q > \fBglm::nextFloat\fP (vec< L, T, Q > const &x, vec< L, int, Q > const &ULPs)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec< L, T, Q > \fBglm::prevFloat\fP (vec< L, T, Q > const &x)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec< L, T, Q > \fBglm::prevFloat\fP (vec< L, T, Q > const &x, int ULPs)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec< L, T, Q > \fBglm::prevFloat\fP (vec< L, T, Q > const &x, vec< L, int, Q > const &ULPs)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec< L, int, Q > \fBglm::floatDistance\fP (vec< L, float, Q > const &x, vec< L, float, Q > const &y)"
.br
.ti -1c
.RI "template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec< L, int64, Q > \fBglm::floatDistance\fP (vec< L, double, Q > const &x, vec< L, double, Q > const &y)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGLM_EXT_vector_ulp\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
