.TH "VkAllocationCallbacks" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VkAllocationCallbacks
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBpUserData\fP"
.br
.ti -1c
.RI "PFN_vkAllocationFunction \fBpfnAllocation\fP"
.br
.ti -1c
.RI "PFN_vkReallocationFunction \fBpfnReallocation\fP"
.br
.ti -1c
.RI "PFN_vkFreeFunction \fBpfnFree\fP"
.br
.ti -1c
.RI "PFN_vkInternalAllocationNotification \fBpfnInternalAllocation\fP"
.br
.ti -1c
.RI "PFN_vkInternalFreeNotification \fBpfnInternalFree\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
