.TH "VkBindImageMemoryDeviceGroupInfo" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VkBindImageMemoryDeviceGroupInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "VkStructureType \fBsType\fP"
.br
.ti -1c
.RI "const void * \fBpNext\fP"
.br
.ti -1c
.RI "uint32_t \fBdeviceIndexCount\fP"
.br
.ti -1c
.RI "const uint32_t * \fBpDeviceIndices\fP"
.br
.ti -1c
.RI "uint32_t \fBsplitInstanceBindRegionCount\fP"
.br
.ti -1c
.RI "const \fBVkRect2D\fP * \fBpSplitInstanceBindRegions\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
