.TH "VkBufferViewCreateInfo" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VkBufferViewCreateInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "VkStructureType \fBsType\fP"
.br
.ti -1c
.RI "const void * \fBpNext\fP"
.br
.ti -1c
.RI "VkBufferViewCreateFlags \fBflags\fP"
.br
.ti -1c
.RI "VkBuffer \fBbuffer\fP"
.br
.ti -1c
.RI "VkFormat \fBformat\fP"
.br
.ti -1c
.RI "VkDeviceSize \fBoffset\fP"
.br
.ti -1c
.RI "VkDeviceSize \fBrange\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
