.TH "VkClearColorValue" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VkClearColorValue
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBfloat32\fP [4]"
.br
.ti -1c
.RI "int32_t \fBint32\fP [4]"
.br
.ti -1c
.RI "uint32_t \fBuint32\fP [4]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
