.TH "VkDescriptorUpdateTemplateCreateInfo" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VkDescriptorUpdateTemplateCreateInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "VkStructureType \fBsType\fP"
.br
.ti -1c
.RI "const void * \fBpNext\fP"
.br
.ti -1c
.RI "VkDescriptorUpdateTemplateCreateFlags \fBflags\fP"
.br
.ti -1c
.RI "uint32_t \fBdescriptorUpdateEntryCount\fP"
.br
.ti -1c
.RI "const \fBVkDescriptorUpdateTemplateEntry\fP * \fBpDescriptorUpdateEntries\fP"
.br
.ti -1c
.RI "VkDescriptorUpdateTemplateType \fBtemplateType\fP"
.br
.ti -1c
.RI "VkDescriptorSetLayout \fBdescriptorSetLayout\fP"
.br
.ti -1c
.RI "VkPipelineBindPoint \fBpipelineBindPoint\fP"
.br
.ti -1c
.RI "VkPipelineLayout \fBpipelineLayout\fP"
.br
.ti -1c
.RI "uint32_t \fBset\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
