.TH "VkDeviceCreateInfo" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VkDeviceCreateInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "VkStructureType \fBsType\fP"
.br
.ti -1c
.RI "const void * \fBpNext\fP"
.br
.ti -1c
.RI "VkDeviceCreateFlags \fBflags\fP"
.br
.ti -1c
.RI "uint32_t \fBqueueCreateInfoCount\fP"
.br
.ti -1c
.RI "const \fBVkDeviceQueueCreateInfo\fP * \fBpQueueCreateInfos\fP"
.br
.ti -1c
.RI "uint32_t \fBenabledLayerCount\fP"
.br
.ti -1c
.RI "const char *const  * \fBppEnabledLayerNames\fP"
.br
.ti -1c
.RI "uint32_t \fBenabledExtensionCount\fP"
.br
.ti -1c
.RI "const char *const  * \fBppEnabledExtensionNames\fP"
.br
.ti -1c
.RI "const \fBVkPhysicalDeviceFeatures\fP * \fBpEnabledFeatures\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
