.TH "VkDeviceGroupSubmitInfo" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VkDeviceGroupSubmitInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "VkStructureType \fBsType\fP"
.br
.ti -1c
.RI "const void * \fBpNext\fP"
.br
.ti -1c
.RI "uint32_t \fBwaitSemaphoreCount\fP"
.br
.ti -1c
.RI "const uint32_t * \fBpWaitSemaphoreDeviceIndices\fP"
.br
.ti -1c
.RI "uint32_t \fBcommandBufferCount\fP"
.br
.ti -1c
.RI "const uint32_t * \fBpCommandBufferDeviceMasks\fP"
.br
.ti -1c
.RI "uint32_t \fBsignalSemaphoreCount\fP"
.br
.ti -1c
.RI "const uint32_t * \fBpSignalSemaphoreDeviceIndices\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
