.TH "VkFramebufferCreateInfo" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VkFramebufferCreateInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "VkStructureType \fBsType\fP"
.br
.ti -1c
.RI "const void * \fBpNext\fP"
.br
.ti -1c
.RI "VkFramebufferCreateFlags \fBflags\fP"
.br
.ti -1c
.RI "VkRenderPass \fBrenderPass\fP"
.br
.ti -1c
.RI "uint32_t \fBattachmentCount\fP"
.br
.ti -1c
.RI "const VkImageView * \fBpAttachments\fP"
.br
.ti -1c
.RI "uint32_t \fBwidth\fP"
.br
.ti -1c
.RI "uint32_t \fBheight\fP"
.br
.ti -1c
.RI "uint32_t \fBlayers\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
