.TH "VkImageFormatProperties" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VkImageFormatProperties
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVkExtent3D\fP \fBmaxExtent\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxMipLevels\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxArrayLayers\fP"
.br
.ti -1c
.RI "VkSampleCountFlags \fBsampleCounts\fP"
.br
.ti -1c
.RI "VkDeviceSize \fBmaxResourceSize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
