.TH "VkImageSubresourceRange" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VkImageSubresourceRange
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "VkImageAspectFlags \fBaspectMask\fP"
.br
.ti -1c
.RI "uint32_t \fBbaseMipLevel\fP"
.br
.ti -1c
.RI "uint32_t \fBlevelCount\fP"
.br
.ti -1c
.RI "uint32_t \fBbaseArrayLayer\fP"
.br
.ti -1c
.RI "uint32_t \fBlayerCount\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
