.TH "VkImageCreateInfo" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VkImageCreateInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "VkStructureType \fBsType\fP"
.br
.ti -1c
.RI "const void * \fBpNext\fP"
.br
.ti -1c
.RI "VkImageCreateFlags \fBflags\fP"
.br
.ti -1c
.RI "VkImageType \fBimageType\fP"
.br
.ti -1c
.RI "VkFormat \fBformat\fP"
.br
.ti -1c
.RI "\fBVkExtent3D\fP \fBextent\fP"
.br
.ti -1c
.RI "uint32_t \fBmipLevels\fP"
.br
.ti -1c
.RI "uint32_t \fBarrayLayers\fP"
.br
.ti -1c
.RI "VkSampleCountFlagBits \fBsamples\fP"
.br
.ti -1c
.RI "VkImageTiling \fBtiling\fP"
.br
.ti -1c
.RI "VkImageUsageFlags \fBusage\fP"
.br
.ti -1c
.RI "VkSharingMode \fBsharingMode\fP"
.br
.ti -1c
.RI "uint32_t \fBqueueFamilyIndexCount\fP"
.br
.ti -1c
.RI "const uint32_t * \fBpQueueFamilyIndices\fP"
.br
.ti -1c
.RI "VkImageLayout \fBinitialLayout\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
