.TH "VkInputAttachmentAspectReference" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VkInputAttachmentAspectReference
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBsubpass\fP"
.br
.ti -1c
.RI "uint32_t \fBinputAttachmentIndex\fP"
.br
.ti -1c
.RI "VkImageAspectFlags \fBaspectMask\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
