.TH "VkPhysicalDeviceMemoryProperties" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VkPhysicalDeviceMemoryProperties
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBmemoryTypeCount\fP"
.br
.ti -1c
.RI "\fBVkMemoryType\fP \fBmemoryTypes\fP [VK_MAX_MEMORY_TYPES]"
.br
.ti -1c
.RI "uint32_t \fBmemoryHeapCount\fP"
.br
.ti -1c
.RI "\fBVkMemoryHeap\fP \fBmemoryHeaps\fP [VK_MAX_MEMORY_HEAPS]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
