.TH "VkPhysicalDeviceFeatures" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VkPhysicalDeviceFeatures
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "VkBool32 \fBrobustBufferAccess\fP"
.br
.ti -1c
.RI "VkBool32 \fBfullDrawIndexUint32\fP"
.br
.ti -1c
.RI "VkBool32 \fBimageCubeArray\fP"
.br
.ti -1c
.RI "VkBool32 \fBindependentBlend\fP"
.br
.ti -1c
.RI "VkBool32 \fBgeometryShader\fP"
.br
.ti -1c
.RI "VkBool32 \fBtessellationShader\fP"
.br
.ti -1c
.RI "VkBool32 \fBsampleRateShading\fP"
.br
.ti -1c
.RI "VkBool32 \fBdualSrcBlend\fP"
.br
.ti -1c
.RI "VkBool32 \fBlogicOp\fP"
.br
.ti -1c
.RI "VkBool32 \fBmultiDrawIndirect\fP"
.br
.ti -1c
.RI "VkBool32 \fBdrawIndirectFirstInstance\fP"
.br
.ti -1c
.RI "VkBool32 \fBdepthClamp\fP"
.br
.ti -1c
.RI "VkBool32 \fBdepthBiasClamp\fP"
.br
.ti -1c
.RI "VkBool32 \fBfillModeNonSolid\fP"
.br
.ti -1c
.RI "VkBool32 \fBdepthBounds\fP"
.br
.ti -1c
.RI "VkBool32 \fBwideLines\fP"
.br
.ti -1c
.RI "VkBool32 \fBlargePoints\fP"
.br
.ti -1c
.RI "VkBool32 \fBalphaToOne\fP"
.br
.ti -1c
.RI "VkBool32 \fBmultiViewport\fP"
.br
.ti -1c
.RI "VkBool32 \fBsamplerAnisotropy\fP"
.br
.ti -1c
.RI "VkBool32 \fBtextureCompressionETC2\fP"
.br
.ti -1c
.RI "VkBool32 \fBtextureCompressionASTC_LDR\fP"
.br
.ti -1c
.RI "VkBool32 \fBtextureCompressionBC\fP"
.br
.ti -1c
.RI "VkBool32 \fBocclusionQueryPrecise\fP"
.br
.ti -1c
.RI "VkBool32 \fBpipelineStatisticsQuery\fP"
.br
.ti -1c
.RI "VkBool32 \fBvertexPipelineStoresAndAtomics\fP"
.br
.ti -1c
.RI "VkBool32 \fBfragmentStoresAndAtomics\fP"
.br
.ti -1c
.RI "VkBool32 \fBshaderTessellationAndGeometryPointSize\fP"
.br
.ti -1c
.RI "VkBool32 \fBshaderImageGatherExtended\fP"
.br
.ti -1c
.RI "VkBool32 \fBshaderStorageImageExtendedFormats\fP"
.br
.ti -1c
.RI "VkBool32 \fBshaderStorageImageMultisample\fP"
.br
.ti -1c
.RI "VkBool32 \fBshaderStorageImageReadWithoutFormat\fP"
.br
.ti -1c
.RI "VkBool32 \fBshaderStorageImageWriteWithoutFormat\fP"
.br
.ti -1c
.RI "VkBool32 \fBshaderUniformBufferArrayDynamicIndexing\fP"
.br
.ti -1c
.RI "VkBool32 \fBshaderSampledImageArrayDynamicIndexing\fP"
.br
.ti -1c
.RI "VkBool32 \fBshaderStorageBufferArrayDynamicIndexing\fP"
.br
.ti -1c
.RI "VkBool32 \fBshaderStorageImageArrayDynamicIndexing\fP"
.br
.ti -1c
.RI "VkBool32 \fBshaderClipDistance\fP"
.br
.ti -1c
.RI "VkBool32 \fBshaderCullDistance\fP"
.br
.ti -1c
.RI "VkBool32 \fBshaderFloat64\fP"
.br
.ti -1c
.RI "VkBool32 \fBshaderInt64\fP"
.br
.ti -1c
.RI "VkBool32 \fBshaderInt16\fP"
.br
.ti -1c
.RI "VkBool32 \fBshaderResourceResidency\fP"
.br
.ti -1c
.RI "VkBool32 \fBshaderResourceMinLod\fP"
.br
.ti -1c
.RI "VkBool32 \fBsparseBinding\fP"
.br
.ti -1c
.RI "VkBool32 \fBsparseResidencyBuffer\fP"
.br
.ti -1c
.RI "VkBool32 \fBsparseResidencyImage2D\fP"
.br
.ti -1c
.RI "VkBool32 \fBsparseResidencyImage3D\fP"
.br
.ti -1c
.RI "VkBool32 \fBsparseResidency2Samples\fP"
.br
.ti -1c
.RI "VkBool32 \fBsparseResidency4Samples\fP"
.br
.ti -1c
.RI "VkBool32 \fBsparseResidency8Samples\fP"
.br
.ti -1c
.RI "VkBool32 \fBsparseResidency16Samples\fP"
.br
.ti -1c
.RI "VkBool32 \fBsparseResidencyAliased\fP"
.br
.ti -1c
.RI "VkBool32 \fBvariableMultisampleRate\fP"
.br
.ti -1c
.RI "VkBool32 \fBinheritedQueries\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
