.TH "VkPhysicalDeviceGroupProperties" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VkPhysicalDeviceGroupProperties
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "VkStructureType \fBsType\fP"
.br
.ti -1c
.RI "void * \fBpNext\fP"
.br
.ti -1c
.RI "uint32_t \fBphysicalDeviceCount\fP"
.br
.ti -1c
.RI "VkPhysicalDevice \fBphysicalDevices\fP [VK_MAX_DEVICE_GROUP_SIZE]"
.br
.ti -1c
.RI "VkBool32 \fBsubsetAllocation\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
