.TH "VkPhysicalDeviceProperties" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VkPhysicalDeviceProperties
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBapiVersion\fP"
.br
.ti -1c
.RI "uint32_t \fBdriverVersion\fP"
.br
.ti -1c
.RI "uint32_t \fBvendorID\fP"
.br
.ti -1c
.RI "uint32_t \fBdeviceID\fP"
.br
.ti -1c
.RI "VkPhysicalDeviceType \fBdeviceType\fP"
.br
.ti -1c
.RI "char \fBdeviceName\fP [VK_MAX_PHYSICAL_DEVICE_NAME_SIZE]"
.br
.ti -1c
.RI "uint8_t \fBpipelineCacheUUID\fP [VK_UUID_SIZE]"
.br
.ti -1c
.RI "\fBVkPhysicalDeviceLimits\fP \fBlimits\fP"
.br
.ti -1c
.RI "\fBVkPhysicalDeviceSparseProperties\fP \fBsparseProperties\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
