.TH "VkPhysicalDeviceExternalBufferInfo" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VkPhysicalDeviceExternalBufferInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "VkStructureType \fBsType\fP"
.br
.ti -1c
.RI "const void * \fBpNext\fP"
.br
.ti -1c
.RI "VkBufferCreateFlags \fBflags\fP"
.br
.ti -1c
.RI "VkBufferUsageFlags \fBusage\fP"
.br
.ti -1c
.RI "VkExternalMemoryHandleTypeFlagBits \fBhandleType\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
