.TH "VkPipelineRasterizationStateCreateInfo" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VkPipelineRasterizationStateCreateInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "VkStructureType \fBsType\fP"
.br
.ti -1c
.RI "const void * \fBpNext\fP"
.br
.ti -1c
.RI "VkPipelineRasterizationStateCreateFlags \fBflags\fP"
.br
.ti -1c
.RI "VkBool32 \fBdepthClampEnable\fP"
.br
.ti -1c
.RI "VkBool32 \fBrasterizerDiscardEnable\fP"
.br
.ti -1c
.RI "VkPolygonMode \fBpolygonMode\fP"
.br
.ti -1c
.RI "VkCullModeFlags \fBcullMode\fP"
.br
.ti -1c
.RI "VkFrontFace \fBfrontFace\fP"
.br
.ti -1c
.RI "VkBool32 \fBdepthBiasEnable\fP"
.br
.ti -1c
.RI "float \fBdepthBiasConstantFactor\fP"
.br
.ti -1c
.RI "float \fBdepthBiasClamp\fP"
.br
.ti -1c
.RI "float \fBdepthBiasSlopeFactor\fP"
.br
.ti -1c
.RI "float \fBlineWidth\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
