.TH "VkPipelineColorBlendAttachmentState" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VkPipelineColorBlendAttachmentState
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "VkBool32 \fBblendEnable\fP"
.br
.ti -1c
.RI "VkBlendFactor \fBsrcColorBlendFactor\fP"
.br
.ti -1c
.RI "VkBlendFactor \fBdstColorBlendFactor\fP"
.br
.ti -1c
.RI "VkBlendOp \fBcolorBlendOp\fP"
.br
.ti -1c
.RI "VkBlendFactor \fBsrcAlphaBlendFactor\fP"
.br
.ti -1c
.RI "VkBlendFactor \fBdstAlphaBlendFactor\fP"
.br
.ti -1c
.RI "VkBlendOp \fBalphaBlendOp\fP"
.br
.ti -1c
.RI "VkColorComponentFlags \fBcolorWriteMask\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
