.TH "VkPipelineColorBlendStateCreateInfo" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VkPipelineColorBlendStateCreateInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "VkStructureType \fBsType\fP"
.br
.ti -1c
.RI "const void * \fBpNext\fP"
.br
.ti -1c
.RI "VkPipelineColorBlendStateCreateFlags \fBflags\fP"
.br
.ti -1c
.RI "VkBool32 \fBlogicOpEnable\fP"
.br
.ti -1c
.RI "VkLogicOp \fBlogicOp\fP"
.br
.ti -1c
.RI "uint32_t \fBattachmentCount\fP"
.br
.ti -1c
.RI "const \fBVkPipelineColorBlendAttachmentState\fP * \fBpAttachments\fP"
.br
.ti -1c
.RI "float \fBblendConstants\fP [4]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
