.TH "VkSamplerYcbcrConversionCreateInfo" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VkSamplerYcbcrConversionCreateInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "VkStructureType \fBsType\fP"
.br
.ti -1c
.RI "const void * \fBpNext\fP"
.br
.ti -1c
.RI "VkFormat \fBformat\fP"
.br
.ti -1c
.RI "VkSamplerYcbcrModelConversion \fBycbcrModel\fP"
.br
.ti -1c
.RI "VkSamplerYcbcrRange \fBycbcrRange\fP"
.br
.ti -1c
.RI "\fBVkComponentMapping\fP \fBcomponents\fP"
.br
.ti -1c
.RI "VkChromaLocation \fBxChromaOffset\fP"
.br
.ti -1c
.RI "VkChromaLocation \fByChromaOffset\fP"
.br
.ti -1c
.RI "VkFilter \fBchromaFilter\fP"
.br
.ti -1c
.RI "VkBool32 \fBforceExplicitReconstruction\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
