.TH "VkSamplerCreateInfo" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VkSamplerCreateInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "VkStructureType \fBsType\fP"
.br
.ti -1c
.RI "const void * \fBpNext\fP"
.br
.ti -1c
.RI "VkSamplerCreateFlags \fBflags\fP"
.br
.ti -1c
.RI "VkFilter \fBmagFilter\fP"
.br
.ti -1c
.RI "VkFilter \fBminFilter\fP"
.br
.ti -1c
.RI "VkSamplerMipmapMode \fBmipmapMode\fP"
.br
.ti -1c
.RI "VkSamplerAddressMode \fBaddressModeU\fP"
.br
.ti -1c
.RI "VkSamplerAddressMode \fBaddressModeV\fP"
.br
.ti -1c
.RI "VkSamplerAddressMode \fBaddressModeW\fP"
.br
.ti -1c
.RI "float \fBmipLodBias\fP"
.br
.ti -1c
.RI "VkBool32 \fBanisotropyEnable\fP"
.br
.ti -1c
.RI "float \fBmaxAnisotropy\fP"
.br
.ti -1c
.RI "VkBool32 \fBcompareEnable\fP"
.br
.ti -1c
.RI "VkCompareOp \fBcompareOp\fP"
.br
.ti -1c
.RI "float \fBminLod\fP"
.br
.ti -1c
.RI "float \fBmaxLod\fP"
.br
.ti -1c
.RI "VkBorderColor \fBborderColor\fP"
.br
.ti -1c
.RI "VkBool32 \fBunnormalizedCoordinates\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
