.TH "VkSurfaceCapabilitiesKHR" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VkSurfaceCapabilitiesKHR
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBminImageCount\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxImageCount\fP"
.br
.ti -1c
.RI "\fBVkExtent2D\fP \fBcurrentExtent\fP"
.br
.ti -1c
.RI "\fBVkExtent2D\fP \fBminImageExtent\fP"
.br
.ti -1c
.RI "\fBVkExtent2D\fP \fBmaxImageExtent\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxImageArrayLayers\fP"
.br
.ti -1c
.RI "VkSurfaceTransformFlagsKHR \fBsupportedTransforms\fP"
.br
.ti -1c
.RI "VkSurfaceTransformFlagBitsKHR \fBcurrentTransform\fP"
.br
.ti -1c
.RI "VkCompositeAlphaFlagsKHR \fBsupportedCompositeAlpha\fP"
.br
.ti -1c
.RI "VkImageUsageFlags \fBsupportedUsageFlags\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
