.TH "VkSubpassDescription" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VkSubpassDescription
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "VkSubpassDescriptionFlags \fBflags\fP"
.br
.ti -1c
.RI "VkPipelineBindPoint \fBpipelineBindPoint\fP"
.br
.ti -1c
.RI "uint32_t \fBinputAttachmentCount\fP"
.br
.ti -1c
.RI "const \fBVkAttachmentReference\fP * \fBpInputAttachments\fP"
.br
.ti -1c
.RI "uint32_t \fBcolorAttachmentCount\fP"
.br
.ti -1c
.RI "const \fBVkAttachmentReference\fP * \fBpColorAttachments\fP"
.br
.ti -1c
.RI "const \fBVkAttachmentReference\fP * \fBpResolveAttachments\fP"
.br
.ti -1c
.RI "const \fBVkAttachmentReference\fP * \fBpDepthStencilAttachment\fP"
.br
.ti -1c
.RI "uint32_t \fBpreserveAttachmentCount\fP"
.br
.ti -1c
.RI "const uint32_t * \fBpPreserveAttachments\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
