.TH "VkWriteDescriptorSet" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VkWriteDescriptorSet
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "VkStructureType \fBsType\fP"
.br
.ti -1c
.RI "const void * \fBpNext\fP"
.br
.ti -1c
.RI "VkDescriptorSet \fBdstSet\fP"
.br
.ti -1c
.RI "uint32_t \fBdstBinding\fP"
.br
.ti -1c
.RI "uint32_t \fBdstArrayElement\fP"
.br
.ti -1c
.RI "uint32_t \fBdescriptorCount\fP"
.br
.ti -1c
.RI "VkDescriptorType \fBdescriptorType\fP"
.br
.ti -1c
.RI "const \fBVkDescriptorImageInfo\fP * \fBpImageInfo\fP"
.br
.ti -1c
.RI "const \fBVkDescriptorBufferInfo\fP * \fBpBufferInfo\fP"
.br
.ti -1c
.RI "const VkBufferView * \fBpTexelBufferView\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
