.TH "wformat_args" 3 "Sat Jul 20 2019" "Version 0.1" "Typhoon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wformat_args
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbasic_format_args< wformat_context >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename \&.\&.\&. Args> \fBwformat_args\fP (Args &&\&.\&.\&. arg)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Typhoon Engine from the source code\&.
