#pragma once

#define TE_GAMEPAD_BUTTON_A               0
#define TE_GAMEPAD_BUTTON_B               1
#define TE_GAMEPAD_BUTTON_X               2
#define TE_GAMEPAD_BUTTON_Y               3
#define TE_GAMEPAD_BUTTON_LEFT_BUMPER     4
#define TE_GAMEPAD_BUTTON_RIGHT_BUMPER    5
#define TE_GAMEPAD_BUTTON_BACK            6
#define TE_GAMEPAD_BUTTON_START           7
#define TE_GAMEPAD_BUTTON_GUIDE           8
#define TE_GAMEPAD_BUTTON_LEFT_THUMB      9
#define TE_GAMEPAD_BUTTON_RIGHT_THUMB     10
#define TE_GAMEPAD_BUTTON_DPAD_UP         11
#define TE_GAMEPAD_BUTTON_DPAD_RIGHT      12
#define TE_GAMEPAD_BUTTON_DPAD_DOWN       13
#define TE_GAMEPAD_BUTTON_DPAD_LEFT       14
#define TE_GAMEPAD_BUTTON_LAST            TE_GAMEPAD_BUTTON_DPAD_LEFT

#define TE_GAMEPAD_BUTTON_CROSS       TE_GAMEPAD_BUTTON_A
#define TE_GAMEPAD_BUTTON_CIRCLE      TE_GAMEPAD_BUTTON_B
#define TE_GAMEPAD_BUTTON_SQUARE      TE_GAMEPAD_BUTTON_X
#define TE_GAMEPAD_BUTTON_TRIANGLE    TE_GAMEPAD_BUTTON_Y

#define TE_GAMEPAD_AXIS_LEFT_X        0
#define TE_GAMEPAD_AXIS_LEFT_Y        1
#define TE_GAMEPAD_AXIS_RIGHT_X       2
#define TE_GAMEPAD_AXIS_RIGHT_Y       3
#define TE_GAMEPAD_AXIS_LEFT_TRIGGER  4
#define TE_GAMEPAD_AXIS_RIGHT_TRIGGER 5
#define TE_GAMEPAD_AXIS_LAST          TE_GAMEPAD_AXIS_RIGHT_TRIGGER